### ISSUE TITLE
[Bug] Copied Picture

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageToolbox#100]
Hi

https://user-images.githubusercontent.com/23485114/227064757-9e0ba7c2-0c34-4a36-8bb1-cc3e07f6d16b.mp4

Why I can't open copied picture to this app?
```
android.intent.action.EDIT
```
```
content://org.mozilla.fenix.feature.downloads.fileprovider/mediaShareCache/629757759.webp
```
```
image/*
```
```
intent://org.mozilla.fenix.feature.downloads.fileprovider/mediaShareCache/629757759.webp#Intent;scheme=content;action=android.intent.action.EDIT;type=image/*;launchFlags=0x13108001;sourceBounds=304%20575%20892%201920;B.edit_source_clipboard=true;end
```

**Comment by T8RIN** [comment]
Idk, i've encountered this error with miui gallery and how no idea why some apps raising permission denial error... :(

**Comment by T8RIN** [comment]
Can you build the app and test it after fix? I can't reproduce it, because i have Android 10

**Comment by xmha97** [comment]
> Can you build the app and test it after fix? I can't reproduce it, because i have Android 10 

Thank you for trying to solve this problem.

Right now I'm traveling and can't build the app.

Please build the app yourself and zip the apk file and finally share it in this page. (app.apk.zip)

I will definitely test it.

**Comment by T8RIN** [comment]
Ok, will send it later, if it doesn't help, then i have no idea how to solve it, because there is no solution in the web, or i searched badly :(

**Comment by T8RIN** [comment]
[app-release.zip](https://github.com/T8RIN/ImageResizer/files/11058641/app-release.zip)

**Comment by xmha97** [comment]
Thanks, but the problem persists.

**Comment by xmha97** [comment]
Ok, you can close this issue.
I try to fix it next month.

**Comment by T8RIN** [comment]
Thanks!
