### ISSUE TITLE
Stick to image boundaries while cropping

### ISSUE THREAD

**Issue by mainrs** [T8RIN/ImageToolbox#1006]
**Is your feature request related to a problem? Please describe.**
Currently, when cropping an image, one can drag the cropping indicator out of the image bounds.

**Describe the solution you'd like**
Allow one to set an option to make the handles stick to the image boundary and not extend them.

**Describe alternatives you've considered**
For me at least it makes cropping some what harder. It just feels unnatural.

**Comment by T8RIN** [comment]
I'm using lib, but there was a feature idea to create a separate crop with another lib

**Comment by T8RIN** [comment]
If i sometime add other cropping method this will be added, there are some similar issues
