### ISSUE TITLE
v2.8.1 armeabi-v7a Not On F-Droid.

### ISSUE THREAD

**Issue by atikattar1104** [T8RIN/ImageToolbox#1013]
**Describe the bug**

Only arm64-v8a Available For This Version Via IzzySoft's Repo.

**To Reproduce**

Check `Versions` Section On F-Droid Page For App.

**Expected behavior**

armeabi-v7a Version Should Be Available.

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - OS: Android 12, MIUI 12.5

**Comment by T8RIN** [comment]
@licaon-kter how to resolve this?

**Comment by licaon-kter** [comment]
Let's take it step by step :)

Latest version in F-Droid is 2.8.0

Next version is built and awaits publishing.

F-Droid builds and hosts the "all arches version".

OP talks about IzzyDroid? Well, that repo gets only the armv7 version iirc, that's the procedure.

imho, not a bug :)

**Comment by T8RIN** [comment]
Thx for the explanation!👀
