### ISSUE TITLE
Video editor?

### ISSUE THREAD

**Issue by idontveapc** [T8RIN/ImageToolbox#1020]
**Is your feature request related to a problem? Please describe.**
Kind of, would want an image editor like Image Toolbox to also edit videos. Like some other video editors can.

**Describe the solution you'd like**
By the same edits that work for an image also to videos. Like cropping, resizing, adding effects, and the others.

**Describe alternatives you've considered**
Find other video editors??!

**Comment by T8RIN** [comment]
ImageToolbox is focused on images, video editing is for an separate app
