### ISSUE TITLE
Better Auto Remove Background feature

### ISSUE THREAD

**Issue by nyaasar** [T8RIN/ImageToolbox#1027]
Make it more user-friendly and user-reliant. 

From what I've experienced, the current auto remover is great for simple images, but not for complex image with multiple objects; and it relies too much on algorithm, which in turn gives users less control over it.

So here's some useful ~~suggestions~~ reference:

![Screenshot_20240503-171755](https://github.com/T8RIN/ImageToolbox/assets/54396528/f86fde87-c16b-4541-ac15-e6f7cb83c713)
Application link: [Background Eraser](https://play.google.com/store/apps/details?id=com.handycloset.android.eraser)

**Comment by T8RIN** [comment]
That app is not open source, and i'm using mlkit to perform background removal, so I can't do anything except change the lib, but i don't know any other

**Comment by nyaasar** [comment]
It's not open source, indeed. 
But I hope that can give you some inspirations for, perhaps, future update of the background remover feature. 😃

**Comment by T8RIN** [comment]
auto version can't be improved unless google do it

**Comment by T8RIN** [comment]
> hey [nyaasar](https://github.com/nyaasar), How can I achieve the repair functionality, do you have the open source code for the app inside your above image?

Which repair? This is already in my app while removing background
