### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by preethesh-ks** [T8RIN/ImageToolbox#1039]
Device: motorola edge 50 pro (motorola - eqe), SDK: 34 (14), App: 2.8.2-alpha01 (137)java.lang.NullPointerException: Attempt to read from field 'M0.P M0.H.V' on a null object reference in method 'void M0.H.J(M0.H)'at M0.H.J(SourceFile:1)at M0.H.P(SourceFile:20)at M0.x0.h(SourceFile:5)at c0.y.a(SourceFile:11)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.u0.o(SourceFile:188)at N0.Z.doFrame(SourceFile:34)at N0.X.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1341)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)at android.view.Choreographer.doCallbacks(Choreographer.java:952)at android.view.Choreographer.doFrame(Choreographer.java:878)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)at android.os.Handler.handleCallback(Handler.java:1000)at android.os.Handler.dispatchMessage(Handler.java:104)at android.os.Looper.loopOnce(Looper.java:242)at android.os.Looper.loop(Looper.java:362)at android.app.ActivityThread.main(ActivityThread.java:8448)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)Suppressed: S8.g: [N0.a0@16d13fa, N0.D0@4e3ddab, t0{Cancelling}@fd1ac08, Y@4e0dfa1]

**Comment by T8RIN** [comment]
Seems to be compose rleated issue

**Comment by T8RIN** [comment]
https://issuetracker.google.com/issues/338786470

**Comment by T8RIN** [comment]
Should be fixed now
