### ISSUE TITLE
[Bug] App Crash: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Squiggly-lines** [T8RIN/ImageToolbox#1047]
Device: SM-T976B (samsung - gts7xl), SDK: 33 (13), App: 2.8.2-alpha01 (137)java.lang.ArrayIndexOutOfBoundsException: src.length=16 srcPos=2 dst.length=16 dstPos=3 length=-1at java.lang.System.arraycopy(Native Method)at c7.m.i(SourceFile:12)at d0.d.a(SourceFile:16)at M0.H.y(SourceFile:73)at M0.x0.c(SourceFile:7)at c0.q.a(SourceFile:224)at c0.J.e(SourceFile:26)at c0.s.a(SourceFile:36)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.u0.o(SourceFile:188)at N0.Z.doFrame(SourceFile:34)at N0.X.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1329)at android.view.Choreographer.doCallbacks(Choreographer.java:930)at android.view.Choreographer.doFrame(Choreographer.java:854)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1303)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:226)at android.os.Looper.loop(Looper.java:313)at android.app.ActivityThread.main(ActivityThread.java:8810)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)Suppressed: S8.g: [N0.a0@965ac56, N0.D0@b50c4d7, t0{Cancelling}@2a781c4, Y@c7428ad]

**Comment by T8RIN** [comment]
Should be compose related

**Comment by T8RIN** [comment]
Should be fixed now
