### ISSUE TITLE
jpg to jxl convert does not work

### ISSUE THREAD

**Issue by BuZZ-dEE** [T8RIN/ImageToolbox#1048]
**Describe the bug**
Selected 2 jpg files to convert to jxl. Got an error message. 

**Screenshots**

![Screenshot_20240506-193814](https://github.com/T8RIN/ImageToolbox/assets/125954/ae1e7c00-ea1f-4a00-9e40-74085c812182)

**Smartphone (please complete the following information):**
 - Device: Fairphone 5
 - OS: Android 13

**Comment by T8RIN** [comment]
Which error?

**Comment by T8RIN** [comment]
#1047 #1039
