### ISSUE TITLE
Option to change "Image preview" with "editing tools"

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#1062]
I don't really use this application for previews but only editing. But it requires a bunch of extra steps, for example sharing image from file manager then choosing app from list & directly opening them open them in image preview mode so you have to click on image and choose editing seperatly. Maybe an option in settings to show up editing tools list directly would be much more convenient instead of preview.

**Comment by NikunjKhangwal** [comment]
> but editiong for opening could be added also

That would be nice

**Comment by T8RIN** [comment]
okay

**Comment by T8RIN** [comment]
added
