### ISSUE TITLE
Remove certain color in background by only touching

### ISSUE THREAD

**Issue by Gamer750** [T8RIN/ImageToolbox#1063]
Remove certain color in background by only touching.

**Comment by T8RIN** [comment]
> Remove certain color in background by only touching. 

👀👀

**Comment by Gamer750** [comment]
> > Remove certain color in background by only touching.
> 
> 👀👀

Like in pixel lab

**Comment by T8RIN** [comment]
you can use two filters to achieve that, replace color or crop to content with replace color
