### ISSUE TITLE
Crop to content

### ISSUE THREAD

**Issue by Raffael7777** [T8RIN/ImageToolbox#1066]
**Is your feature request related to a problem? Please describe.**
Many images often have large boundary areas, either filled with a solid color (usually white or black), or with transparency. Some people might consider them unsightly, unnecessary, or cause filesize bloat. Some apps do not let users zoom in on images posted, so removing unnecessary boundaries can also present these images better in those situations.

**Describe the solution you'd like**
A "crop to content" feature. The default boundary to ignore should probably be transparent edges, cropping automatically to the nearest non-transparent pixel from each edge. An option to select a background color to ignore by tapping on that color in the image would make this feature especially robust and useful. In that case it would crop to the nearest pixel from each edge that is not that color.

**Describe alternatives you've considered**
In searching for other apps that might do this, I found too many results for "background removal" to sort through, and this is not background removal. Most PC images editing software like PS, Gimp, etc offer this, but when away from your PC having the option in a mobile app would be useful.

**Comment by T8RIN** [comment]
Sounds like a possible option, should this be able to crop black frames from images, yes?

**Comment by T8RIN** [comment]
Almost added

**Comment by T8RIN** [comment]
Added this as a filter
