### ISSUE TITLE
[Bug] App Crash: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by catgangdev** [T8RIN/ImageToolbox#1071]
Device: M2101K6P (Xiaomi - sweetin), SDK: 33 (13), App: 2.8.2-alpha01 (137)java.lang.ArrayIndexOutOfBoundsException: src.length=16 srcPos=2 dst.length=16 dstPos=3 length=-1at java.lang.System.arraycopy(Native Method)at c7.m.i(SourceFile:12)at d0.d.a(SourceFile:16)at M0.H.y(SourceFile:73)at M0.x0.c(SourceFile:7)at c0.q.a(SourceFile:224)at c0.J.e(SourceFile:26)at c0.s.a(SourceFile:36)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.u0.o(SourceFile:188)at N0.Z.doFrame(SourceFile:34)at N0.X.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)at android.view.Choreographer.doCallbacks(Choreographer.java:899)at android.view.Choreographer.doFrame(Choreographer.java:827)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:201)at android.os.Looper.loop(Looper.java:288)at android.app.ActivityThread.main(ActivityThread.java:7934)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)Suppressed: S8.g: [N0.a0@cc1e945, N0.D0@401889a, t0{Cancelling}@d6245cb, Y@a1dc1a8]

**Comment by catgangdev** [comment]
Duplicate issue

**Comment by T8RIN** [comment]
Yup, waiting for google to fix this
