### ISSUE TITLE
Neverending preview loading

### ISSUE THREAD

**Issue by HaviOneEyedRaven** [T8RIN/ImageToolbox#1078]
**Describe the bug**

Often when I'm trying to add filters to my pictures the preview is loading forever, and nothing can change that. And yes, I'm sure it's not just loading the changes for 15 seconds, because I was waiting longer than that.

**To Reproduce**

Just try to add filters to many different pictures and maybe you'll be lucky to encounter it. I am probably a very lucky person, because it's happening somewhat often.

**Expected behavior**

Preview will actually load and show the picture affected by the latest changes.

**Screenshots**

Just a loading preview animation, in the editing menu "full filter" , so nothing fancy.

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 2a
 - OS: Nothing OS 2.5.5.a

**Comment by T8RIN** [comment]
is saving performs okay? Also which filters affected

**Comment by T8RIN** [comment]
Maybe this fix will help :)

**Comment by HaviOneEyedRaven** [comment]
Yes, saving works fine, and the issue was happening with different combinations of filters, or even with just one filter at the time. Nothing really specific.

**Comment by T8RIN** [comment]
Could you check the latest actions build?

**Comment by HaviOneEyedRaven** [comment]
Yeah, but I don't know how. Can you explain for a user on a Phone? I was only downloading things from releases on GitHub, never from "Actions".

**Comment by T8RIN** [comment]
Second

**Comment by T8RIN** [comment]
https://github.com/T8RIN/ImageToolbox/actions/runs/9120216212/artifacts/1511402584

**Comment by HaviOneEyedRaven** [comment]
![Screenshot_20240517-171739.png](https://github.com/T8RIN/ImageToolbox/assets/159295283/bd2dae31-7191-448f-9214-083e2acb0ecc)

**Comment by T8RIN** [comment]
https://github.com/T8RIN/ImageToolbox/actions/runs/9120216212/artifacts/1511402584 this too?

**Comment by T8RIN** [comment]
or scroll down here until you see artifacts section

https://github.com/T8RIN/ImageToolbox/actions/runs/9120216212

**Comment by HaviOneEyedRaven** [comment]
Also, sometimes the image itself won't load in the preview even without any alteration. It then splits itself (the preview) in 2 parts like 2 different pages in LibreOffice or Word.

![ResizedImage_2024-05-17_17-26-48_3072.png](https://github.com/T8RIN/ImageToolbox/assets/159295283/36633a2f-fa61-4eee-96ab-d4eacf4fd79c)

**Comment by HaviOneEyedRaven** [comment]
![Screenshot_20240517-172902.png](https://github.com/T8RIN/ImageToolbox/assets/159295283/ff4653f7-8a19-45c6-8660-0a09d2892311)

I can see it, but I can't download it (clicking on both does nothing)

**Comment by T8RIN** [comment]
is it fixed?

**Comment by HaviOneEyedRaven** [comment]
So, I don't know whether the usual neverending preview is gone, because it's a random thing and it's hard to tell, but the vertical stretch I told you about before is still there.

**Comment by HaviOneEyedRaven** [comment]
Okay, sorry, I'm dumb. I forgot you haven't updated it yet xD
