### ISSUE TITLE
Crop mask lock

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#1084]
**Is your feature request related to a problem? Please describe.**
Currently when you choose a crop mask and try to resize it using corners it can freely change the shape too not just size. For example you can change a circle into oval.

![IMG_20240517_210329](https://github.com/T8RIN/ImageToolbox/assets/99175083/7ec9942a-c040-48b6-be6f-32d2b08166ee)

**Describe the solution you'd like**
If possible add a "lock" functionality which only let the user change the size of mask with corner and keep the shape as it is.

**Comment by T8RIN** [comment]
You can lock the aspect ratio 👀

**Comment by NikunjKhangwal** [comment]
True but aspect ratio don't have these shapes.

**Comment by T8RIN** [comment]
You can select both shape and aspect ratio

**Comment by NikunjKhangwal** [comment]
:O
Cool, Didn't knew that. Thanks
