### ISSUE TITLE
internet permission 

### ISSUE THREAD

**Issue by Bertklq1** [T8RIN/ImageToolbox#1088]
Whay does this app require internet permission at all?

I have seen your responses where you state that it's for updates checking.

But do you really think that for checking updates require internet permission hard coded into the app? Since the app is on fdroid wouldn't it be possible to let fdroid notify users about new updates and make this photo editing app truly a privacy focused app?

**Comment by T8RIN** [comment]
You can download any image from the internet in the corresponding option

**Comment by Bertklq1** [comment]
> You can download any image from the internet in the corresponding option

But we can literally do that by downloading through the internet and adding it to the app right?

I really wish that this app was offline for privacy/security reasons.

**Comment by T8RIN** [comment]
You can create your own fork and strip up what's you don't want, anyway how you imagine disnloading images from net without internet permission

**Comment by Bertklq1** [comment]
> You can create your own fork and strip up what's you don't want, anyway how you imagine disnloading images from net without internet permission

If would happily fork it and mod it if only i was any good at that.

Any about loading images from internet.
Why do i need to do that specifically? I and i assume most users of foss want to edit their locally stored photos and not download photos from within the editing app for whatever purpose.

Anyway, I don't want to stretch this further.
I think this app has to be the best open source image editing app for android. Thank you for this .

It's just that many of the users including me, think that foss + offline will truely shine as a perfect privacy friendly app to use.

Cheers and good luck.

**Comment by Gamer750** [comment]
I would like to see this app without internet
