### ISSUE TITLE
On the crop screen, how can the crop frame fill the entire image?

### ISSUE THREAD

**Issue by TrinhVanManh** [T8RIN/ImageToolbox#1095]
As I said in the title, on the crop screen, how can the crop frame fill the entire image?. Currently when displayed it will display as follows
![Screenshot_20240522_101121_Image Toolbox](https://github.com/T8RIN/ImageToolbox/assets/118013004/b991bb60-40f6-4445-8ca4-412abac5f56a)
I want that the image will display like this 
![Screenshot_20240522_102234_Image Toolbox](https://github.com/T8RIN/ImageToolbox/assets/118013004/a019799e-417c-4273-9c73-eb04d52340ba)
Looking forward to your guidance, great project. Also, does this project have the function to add text or icons to images? Thank you, gentlemen

**Comment by T8RIN** [comment]
It has both text and images added, it's all behind the drawing option, not filling the full image is needed to outcome system gestures

**Comment by T8RIN** [comment]
In this case, just zoom out, and the frame will be just the image size
