### ISSUE TITLE
Template filter chain

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#1097]
**Is your feature request related to a problem? Please describe.**

The number of filters from ImageToolbox is very extensive. Conveniently, users can save filters as favorites and thus access them quickly. Occasionally, one wants to apply not only one filter, but several filters with defined parameters repeatedly.

**Describe the solution you'd like**

It would be nice if you could define several filters with their parameters, similar to the favorites. These filter chains should be given a name by the user. It would also be ideal if users could share their filter chains with others (e.g., as a QR code, as a hash, as a string …).

**Describe alternatives you've considered**

none

**Comment by devSJR** [comment]
I've just downloaded the latest version and I can tell it's starting to look great! :sparkles: 🥳

**Comment by devSJR** [comment]
I have tested the latest builds (https://github.com/T8RIN/ImageToolbox/actions/runs/9230793761). This is really developing well. The interface is good and intuitive for me. Honestly, I think you may consider adding this to a prominent position, too. Like the other tools here https://github.com/T8RIN/ImageToolbox/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/01.png

**Comment by T8RIN** [comment]
Hm, maybe in settings, idk, this is not a screen rather than option for filters👀

**Comment by devSJR** [comment]
Sounds good

**Comment by T8RIN** [comment]
You can check the latest build, it's almost finished 👀

**Comment by devSJR** [comment]
All seems to work as expected
