### ISSUE TITLE
Display crash during navigation

### ISSUE THREAD

**Issue by Efimj** [T8RIN/ImageToolbox#1101]
**Describe the bug**
Quickly switching between tabs in the navbar leads to list display problems. 

**To solve**
It's worth adding a delay or waiting for the animations to complete

**Screenshots**
![image](https://github.com/T8RIN/ImageToolbox/assets/87390257/107cf631-fdf9-4bc4-8415-a156d107b01e)

**Smartphone (please complete the following information):**
 - Device: mi a2
 - OS: A13 DerpFest

**Comment by T8RIN** [comment]
version?

**Comment by Efimj** [comment]
2.8.1 (136)

**Comment by T8RIN** [comment]
I think also google issue

**Comment by Efimj** [comment]
I think it's not critical

**Comment by Efimj** [comment]
I think it's not critical

**Comment by T8RIN** [comment]
Okay

**Comment by T8RIN** [comment]
navernoye fixed
