### ISSUE TITLE
QR Scanner and creation

### ISSUE THREAD

**Issue by T8RIN** [T8RIN/ImageToolbox#1103]

**Comment by Dhyfer1** [comment]
Thank you for this new function to scan QR code, I thought I could scan the QR code that I have in a screenshot with this new function, but that's not the case. Can you improve the scanner so that it can also scan QR codes on images?

Thanks in advance.

**Comment by Dhyfer1** [comment]
Thank you for this new function to scan QR code, I thought I could scan the QR code that I have in a screenshot with this new function, but that's not the case. Can you improve the scanner so that it can also scan QR codes on images?

Thanks in advance.

**Comment by T8RIN** [comment]
i can't do that easily beacause scanning delegated to separate library

**Comment by Dhyfer1** [comment]
Too bad :( I hope you can find a library that does what I ask, it would be very useful if the scanner can also scan QR screenshots.
