### ISSUE TITLE
Template filter

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#1105]
The template filter function is working great. Please consider to add the manual rearrangement like you have in other filters too. This would be useful if users need to change the order of the filters that are applied in the template.

**Comment by T8RIN** [comment]
Just long click, and rearrange sheet should appear

**Comment by devSJR** [comment]
@T8RIN didn't see that

**Comment by T8RIN** [comment]
![Screenshot_20240526-182055.png](https://github.com/T8RIN/ImageToolbox/assets/52178347/324ba6ed-1b6e-43b2-973c-b808352c10bf)

Long press on the filter you want to reorder
