### ISSUE TITLE
Colorblind mode

### ISSUE THREAD

**Issue by toddwc** [T8RIN/ImageToolbox#1120]
**Is your feature request related to a problem? Please describe.**

No. 

**Describe the solution you'd like**

A colorblind mode. 

**Describe alternatives you've considered**

**Comment by T8RIN** [comment]
not sure it can be added, but i know that this can be enabled in device settings

**Comment by T8RIN** [comment]
You can also use filters for that

i didn't get what do you want? I can create only color scheme adaption for some mode of colorblindness
