### ISSUE TITLE
[FR] append auto background effector (blur etc...)

### ISSUE THREAD

**Issue by mablue** [T8RIN/ImageToolbox#1121]

**Comment by T8RIN** [comment]
You can use mask filters with inverse mode

**Comment by mablue** [comment]
Yes but its not have autobackground detector.
But in background remover we have access to auto background detector and remover

**Comment by T8RIN** [comment]
I thought about that, so it can be added in the future

**Comment by mablue** [comment]
Thanks. I had "photo hacker app" with 3 levels of masks 1) red mask: background 
2) yellow mask(line): space(splitting line ) between background and object( blur effect or removing algorithm will effect 50% in this area)
3) blue or green mask: the object core

In this method we get a good mix around hairs and glasses of our object that have small pieces of background inside his area.
It can work better than autobackground detector.
We have colors in mask if we can set a spacial maskes with different effect( types and percentages) it can be helpfull.
For example:
Remove 100 background for red color
Remove 50% of background for orange color mask
Blur 100% for yellow line
Blur 50% for green line
Keep 100% for blue line just increase sharpness.

We can have an option to increase each color to object that them counting automaticly
And merge auto background remover to this option inside effects

**Comment by T8RIN** [comment]
You can achieve this behavior now with image stacking option also
