### ISSUE TITLE
[FR] fit to square option for use in insta without crpping.

### ISSUE THREAD

**Issue by mablue** [T8RIN/ImageToolbox#1122]

**Comment by T8RIN** [comment]
you can use crop resize mode

**Comment by T8RIN** [comment]
I can also create a filter for that or separate crop mode

**Comment by T8RIN** [comment]
I added ability to use AspectRatio preset, combine it with crop resize mode to achieve described result

**Comment by mablue** [comment]
Thank you.
Its such a hard method to create a square fitted instagram photo.
You know Instagram user are noob... :))
