### ISSUE TITLE
Ultra HDR photos support

### ISSUE THREAD

**Issue by gsdgethjfjj** [T8RIN/ImageToolbox#1124]
**Is your feature request related to a problem? Please describe.**

Android supports Ultra HDR photos. Photos doesn't look like they are HDR when opened. When I somehow edit pictures (crop, filters), all HDRness is gone and Google Photos doesn't show Ultra HDR label no more. 

**Describe the solution you'd like**

Please add support for viewing and editing Ultra HDR photos. These links might be helpful:
https://developer.android.com/media/platform/hdr-image-format
https://developer.android.com/media/grow/ultra-hdr/display
https://github.com/FossifyOrg/Gallery/issues/166
https://github.com/deckerst/aves/issues/838

**Describe alternatives you've considered**
Like I wrote above, Google Photos supports Ultra HDR photos but it's too bloated and too Google for me.

**Comment by T8RIN** [comment]
I will look, i think it's possible to display HDR Images, but not sure about saving with gainamap

**Comment by T8RIN** [comment]
I have pixel 8 on my own, so i can test it👀

**Comment by eddy-geek** [comment]
Thanks! In the end this does not yet cover modifying (eg cropping)  the gain map, right ? If all EXIF, MPF & multi-picture metadata is kept, in some case you could end up with an "out-of-sync" gain map ?

**Comment by T8RIN** [comment]
Gain map not preserved on cropping, but i can't be confident
