### ISSUE TITLE
Straightening

### ISSUE THREAD

**Issue by theamazing0** [T8RIN/ImageToolbox#1126]
**Is your feature request related to a problem? Please describe.**
This feature would allow you to rotate an image while keeping any thing inside the borders part of the final image. It is present in iOS and an example can be seen in this image: [https://images.macrumors.com/t/ZFaUJGMiM32fehA5GI5nwNcs9Yo=/800x0/article-new/2019/07/how-to-crop-rotate-straighten-photos-2.jpg?lossy](https://images.macrumors.com/t/ZFaUJGMiM32fehA5GI5nwNcs9Yo=/800x0/article-new/2019/07/how-to-crop-rotate-straighten-photos-2.jpg?lossy).

**Describe the solution you'd like**
A similar feature added to Image Toolbox.

**Describe alternatives you've considered**
Some other sort of rotation feature that could be combined with the crop feature?

**Comment by T8RIN** [comment]
Crop rotate?

**Comment by theamazing0** [comment]
Yes, something like that

**Comment by theamazing0** [comment]
Oh just saw #936
