### ISSUE TITLE
Precise trimming/cropping of images

### ISSUE THREAD

**Issue by bkosse** [T8RIN/ImageToolbox#1138]
Feature request: Precise image trimming/cropping 

It would be great to have a feature where you can specify an exact amount of pixels to be trimmed from either the top, bottom, left or right.
It would be very helpful if able so zoom in so you can be very precise.

Much like the attached image.

![Cropmarks17~2](https://github.com/T8RIN/ImageToolbox/assets/8471336/fe6aa68d-2fbc-4d53-91af-f1d5f6a383cc)

**Comment by T8RIN** [comment]
It's possible, use crop resize mode

**Comment by bkosse** [comment]
How can I specify on which side it should me trimmed?

**Comment by T8RIN** [comment]
For now there's no option, but I think i can add positioning

**Comment by bkosse** [comment]
👍🙏🙏

**Comment by bkosse** [comment]
Awesome!
