### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ngocanhtve** [T8RIN/ImageToolbox#1146]
**Is your feature request related to a problem? Please describe.**
Even though there's weblate, I don't feel comfortable having to click next hundreds of times instead of manipulating the xml file with the familiar Notepad++.

**Describe the solution you'd like**
Can i use Pull Require, strings.xml file?

**Comment by T8RIN** [comment]
Yup, of course

**Comment by ngocanhtve** [comment]
Great, thanks!

**Comment by ngocanhtve** [comment]
I have completed the PR, so i will close the issue.
