### ISSUE TITLE
Bulk Cropping support

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#1149]
Let me explain through example because i think that would be better. So i was watching a very old show which was made in 4:3 aspect ratio initially. I have this habit of taking a lot of screenshots of my favourite shows. Specially when the scene has a beautiful scenery or a memorable quote. Now i have to go through every pic one by one to crop the black borders. The same thing happens when i take screenshots from YouTube, i have to crop them in 16:9 ratio. In these scenarios i think a bulk cropping option would be super useful. Where you can just select multiple images, choose a aspect ratio and all the images will be cropped for respective setting.

**Comment by T8RIN** [comment]
I will try

**Comment by T8RIN** [comment]
I added ability to use AspectRatio preset, combine it with crop resize mode to achieve described result, for more info check  #1201 

but, threr was no cropping, so i will add option to not fit also

**Comment by T8RIN** [comment]
Added option to disable fit

**Comment by NikunjKhangwal** [comment]
Thanks a lot
