### ISSUE TITLE
[Draw] Moving drawn objects

### ISSUE THREAD

**Issue by idontveapc** [T8RIN/ImageToolbox#1181]
**Is your feature request related to a problem? Please describe.**
You cant move, what you draw after when you've draw something. Like lines you drew and you want move them to align. You can't move them.

**Describe the solution you'd like**
- First, you can move drawing
- and they(drawn objects) align (to centre, or each other. Like coordinates or something).

**Describe alternatives you've considered**
<p> </p>

**Comment by T8RIN** [comment]
You can't move something in ms paint, and i can't too, it's just by design, maybe i will do something in the future, but now it seems to be quite hard to achieve

**Comment by T8RIN** [comment]
Similar to #676 (will be a part of layers mode someday in future)
