### ISSUE TITLE
Add text to images

### ISSUE THREAD

**Issue by Violet-RM** [T8RIN/ImageToolbox#1183]
**Is your feature request related to a problem? Please describe.**
In the current state of the app it is very inconvenient to add text to images. It is technically possible through creating watermarks in a specific way, but this method is inconvenient and bothersome. In order to add text to images, I often must use a seperate app.

**Describe the solution you'd like**
Add an option to add text boxes to images in the app, whether in the single edit menu or another menu.

**Describe alternatives you've considered**
I can't think alternative to this beyond simply not implementing it.

**Comment by T8RIN** [comment]
You can already do that using draw option

**Comment by Violet-RM** [comment]
not really? whats missing is being able to place down a box for your text instead of having to draw its path out

**Comment by T8RIN** [comment]
For now it was a nice solution for text applying, I didn't see features like drawing text on path in android apps yet

**Comment by Violet-RM** [comment]
Respectfully, I could think of a thousand features that aren't in android
apps, but that doesn't make them practical or usable. Dedicated text boxes
wouldn't even have to replace drawing text on a path, they could both be
there. Drawing on a path is clunky and makes it difficult to make your text
look nice and visually appealing.

**Comment by deviantsemicolon** [comment]
> For now it was a nice solution for text applying, I didn't see features like drawing text on path in android apps yet

I would still very much like the ability to properly make a text box. Because there are points in time where I don't want text to be on one line, and doing that through drawing is clunky. Text boxes do this already because of text wrapping.
