### ISSUE TITLE
Google app store rating suggested even when app downloaded through another source.

### ISSUE THREAD

**Issue by vhuszaroakley** [T8RIN/ImageToolbox#1186]
**Describe the bug**
Ive downloaded the app through obtanium, but on saving my first image, the app asked me to provide a rating on the google app store

**To Reproduce**

**Expected behavior**
If app not installed through google play dont ask for rating.
Else link to f-droid or github

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: oppo find X 3 pro
 - OS: colorOS

**Comment by T8RIN** [comment]
That's intended, to have github rating link you should use foss version
