### ISSUE TITLE
[Bug] App Crash: IllegalStateException

### ISSUE THREAD

**Issue by Luispah** [T8RIN/ImageToolbox#1188]
Device: SM-F946B (samsung - q5q), SDK: 34 (14), App: 2.8.1 (136)java.lang.IllegalStateException: Offset is unspecifiedat b7.E.H(SourceFile:3)at q0.c.e(SourceFile:26)at r0.J.c(SourceFile:49)at J0.a1.i(SourceFile:31)at I0.g0.X0(SourceFile:74)at I0.g0.G(SourceFile:79)at J0.X.p(SourceFile:109)at J0.X.p(SourceFile:299)at J0.X.p(SourceFile:299)at J0.X.o(SourceFile:62)at J0.P.s(SourceFile:15)at J0.P.n(SourceFile:36)at J0.P.G(SourceFile:12)at J0.P.H(SourceFile:7)at J0.P.K(SourceFile:107)at J0.P.l(SourceFile:140)at J0.K.y(SourceFile:12)at M6.a.o(SourceFile:9)at p8.I.run(SourceFile:95)at J0.i0.X(SourceFile:7)at J0.h0.run(SourceFile:3)at android.os.Handler.handleCallback(Handler.java:958)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:230)at android.os.Looper.loop(Looper.java:319)at android.app.ActivityThread.main(ActivityThread.java:8919)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)Suppressed: u8.g: [J0.N0@cadd493, Y.i@97a7cd0, v0{Cancelling}@40eb4c9, i0@1ce67ce]

**Comment by T8RIN** [comment]
You should update to the latest 2.9.0 version
