### ISSUE TITLE
Requested features

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1192]
# Suggestions:
* Filters: option to set amount of the filter.
* Background Remover: fill transparent with selected color.
* Image stitching: option to set images quality + images sort: add manual sorting + option to set BOTH vertical & horizontal spaces in both vertical & horizontal grid (vertical grid has only vertical space).
* Watermarking: option to set image quality.
* Options: File Name > add option to save with original filename (in case of someone don't want to overwrite original file) instead of **ADDING** original filename (after disabling prefix and suffix .. The current filename is: date_time_number).
= Add object removal feature + background changer + change selected color on image.

**Comment by T8RIN** [comment]
1) available from beginning, this is possible only for complex filters
2) you can use color replacement (replace Transparent to any) filter after backgroud erasing
3) sort is available, or you can long press images to reorder
4) adding right now
5) will figure out if this possible with filenames
6) object removal feature - Cant (at least now)
7) background changer same as 8
8) change selected color on image same as 2

**Comment by T8RIN** [comment]
quality also available in image stitching already

**Comment by UserAccount123** [comment]
OK, thanks.

**Comment by UserAccount123** [comment]
OK, thanks.
