### ISSUE TITLE
Add option to disable/hide tool.

### ISSUE THREAD

**Issue by Entwineo** [T8RIN/ImageToolbox#1195]
Please add some features regarding customising Home screen/ui.

1. Ability to hid/disable some of tools 
2. Some of tools are redundant, can be combined into single one
3. I find list view hard to choose, card/gallery view with separated section will be easier to eyes.
4. OCR into PDFs

**Comment by T8RIN** [comment]
1. Why do you need this?
2. explained above
3. You can choose albums above grid, this way there is more inforamtion
4. Can't make it now, but you can extract frames using embedded tool
