### ISSUE TITLE
Path of OCR (Recognize Text) files + Issue.

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1196]
Image tab > OCR (Recognize Text): where is the path of downloaded language pack ? In case if I reinstalled the app, but don't want to download OCR files again, instead just copy the downloaded files to the path.
The files are not in (Android > data > ru.tech.imageresizershrinker) folder, it's empty.

ISSUE: when importing settings file, it didn't import the saved language that in the file.

Device: Xiaomi Redmi 9.
OS: Android.

Thanks.

**Comment by T8RIN** [comment]
It's not a bug

**Comment by T8RIN** [comment]
Files are stored in the internal app's storage, to save them on the deleting app, check the checkbox which says save app data in delete dialog

**Comment by UserAccount123** [comment]
> Files are stored in the internal app's storage, to save them on the deleting app, check the checkbox which says save app data in delete dialog

My phone doesn't support that.

**Comment by T8RIN** [comment]
Then it's impossible for now :( maybe i can create some kind of exporting/importing ocr models

**Comment by T8RIN** [comment]
Also i didn't get wdym by the saved language?

**Comment by UserAccount123** [comment]
> Also i didn't get wdym by the saved language?

The app's language when exporting settings is English language, but when importing the settings file .. the language I selected (English), it didn't selected, instead the app's language stay as my phone's language (Arabic language).

**Comment by T8RIN** [comment]
okay, got it, language don't saved because it has no sence on android upper than 12

**Comment by UserAccount123** [comment]
> okay, got it, language don't saved because it has no sence on android upper than 12

OK, thanks 🙂.
