### ISSUE TITLE
Fit to aspect ratio, fill space (no crop)

### ISSUE THREAD

**Issue by ggstrader** [T8RIN/ImageToolbox#1201]
Apologies if this is a duplicate, but other issues seem to be slightly different requests.

A helpful feature would be the ability to change aspect ratios without data loss, just adding blur/color background. E.g.
![Screenshot_20240713-113835.png](https://github.com/user-attachments/assets/d9ae7883-3e43-45d1-90c1-533a506be2d6)

Note that the image above was not cropped in any way.

Ideally, the input would be a w/h ratio rather than pixel dimensions

**Comment by T8RIN** [comment]
Doesn't crop resize fit your needs?

**Comment by T8RIN** [comment]
I think i could add an widget above dimensions selection to choose aspect based on width/height

**Comment by T8RIN** [comment]
I added ability to use AspectRatio preset, combine it with crop resize mode to achieve described result

**Comment by ggstrader** [comment]
> Doesn't crop resize fit your needs?

When I use that, it does not allow zooming out past the image bounds, and doesn't add a blurred version of the image as background to fill the negative space
![Screenshot_20240714-013850~2.png](https://github.com/user-attachments/assets/2eda8d97-deee-4bfe-b2cc-6ba0a2b13c95)

**Comment by ggstrader** [comment]
Oh, I see. For anyone else stumbling on this, you use the resize tool, set it to crop, and increase the pixel number

![Screenshot_20240714-014651.png](https://github.com/user-attachments/assets/e8d42f5c-8fca-4e05-93e8-6402408e3f28)
