### ISSUE TITLE
Bloated JXL Output/Final Output Size Not Matching Preview Estimate

### ISSUE THREAD

**Issue by OkyDooky** [T8RIN/ImageToolbox#1202]
**Describe the bug**
When converting to JXL, the preview estimate shown while adjusting settings will give several hundred kBs or lower (depending on quality and effort) for a lossy conversion, but then the resulting file is several MBs or larger when viewed in a file browser.

**To Reproduce**
Batch convert
Select large image (several MBs)
Select JXL
Choose Lossy
Lower Quality and raise Effort until preview estimate ~250kBs or less
Save
Check file in file manager

**Expected behavior**
Output size should match preview, or at least be smaller than input.

**Screenshots**
![Screenshot_20240713-170930_Amaze](https://github.com/user-attachments/assets/9d7b0134-a811-4900-a8f3-956c1ed9dde2)
![Stitch190ae930459](https://github.com/user-attachments/assets/16a34d08-be54-44d5-9f74-c78deb1a747f)
(Ignore the ghosting on the stitched long screenshot)

**Smartphone (please complete the following information):**
 - Device: Ocean (Moto G7 Power)
 - OS: Lineage 20 (Android 13)

**Comment by OkyDooky** [comment]
For comparison, I do not have this issue with this app: https://play.google.com/store/apps/details?id=ebusky.jpeg.xl.image.viewer.converter

**Comment by T8RIN** [comment]
i will check 😃

**Comment by OkyDooky** [comment]
Thanks! Also, the input file size is only 2.5MB! Not sure how it got so large, then. (12MP, if that has anything to do with it: 3024 x 4032)

**Comment by T8RIN** [comment]
Maybe that my fault, and i'm passing wrong args, but if not, that's may be related to libjxl or coder which i use

**Comment by OkyDooky** [comment]
Hopefully it's an easy fix. I found this, because I'm trying to help with getting JXL support into Fossify Gallery and I'm helping QuackDoc test his PR. It seems that all viewing apps suffer from the decoder (my guess), because all of them show a lower-resolution version than the actual file. The only one that seems to show it correctly is https://github.com/oupson/jxlviewer except it doesn't zoom in past 100% and isn't a gallery app.
So, there could be something funky with the libjxl implementation for Android, in general. Maybe something changed recently, because the PlayStore app I linked was last updated in Feb. of this year.

**Comment by T8RIN** [comment]
Try to open it in image preview screen

**Comment by OkyDooky** [comment]
Is that the +Magnifier button in the upper right (like in the second screenshot)?

**Comment by T8RIN** [comment]
It's in the third section

**Comment by OkyDooky** [comment]
Got it.
Well, that's weird. I imported the JXL of the flowers and the JPG original and the JXL looked crappier. But, after going back and forth, then it looked fine at some point? Hmmm.
But, weirdly, one other file that I converted twice with this app had one that looked just as bad as I described, while the first attempt now looked fine(ish).
...okay, hold up. I just imported the original for that other image just to see (since I couldn't remember if I did anything different with the settings between the two conversion attempts) and I didn't notice anything different between it (the original) and the first attempt. So, I  checked the second attempt and...it looked just as fine as the other two. It definitely looked way worse before. And this is all in one session (I didn't exit out of the Image Preview during making this post).
That seems like it might be the decoder, after all. 🤔

**Comment by T8RIN** [comment]
interesting indeed, i have no idea what's wrong 🧮

**Comment by OkyDooky** [comment]
Well, at least it's noted. But, I'll leave that aspect for the upstream parts, like Awxkee's coder and libjxl proper.
Thanks for bearing with me, regardless.

**Comment by T8RIN** [comment]
Theres update in libjxl and jxlcoder, maybe that will help

**Comment by OkyDooky** [comment]
Okay. I'm using Obtainium. So, as soon as the new binary releases for ImageTooolbox, I'll test it out and let you know if it's working for me.

**Comment by OkyDooky** [comment]
I think I need to either rename this issue or create a new one, because it isn't just JXL that's having this problem. I tested converting to MozJpeg, WebP, and Avif and all of them came out much larger than the preview file size claimed (I think it even low balls the input size, saying a 2.2MB PNG was 1.0MB). MozJoeg also came out massively bloated compared to what it should be. That 2.2MB PNG turned into a 597KB Jpeg when converting using Aves Gallery (which uses the system's built in libjpeg-turbo) at Q=93, while ImageToolbox output a 924KB Jpeg when using MozJpeg at Q=85! And the preview estimated it would be around 171KB.
Update: just tried converting that PNG to Jpeg (using the Jpg setting) in ImageToolbox using Q=93 and it output to 1MB (preview said 302KB), which is double what Aves output.

**Comment by OkyDooky** [comment]
@T8RIN 
Just updating to say that this issue is not resolved. I tested with the latest pre-release/alpha apk (FOSS version) and a 3MB Jpeg was turned into a 5MB JXL (Lossy at 80% quality and 7 Effort), while claiming the sample/preview size was ~97KB.

I also just tested it with Jpeg->Jpeg at 100% Quality and the result was it bumped it up from 3MB to 3.3MB...while claiming the preview size to be 579.6KB.

So, the preview estimate numbers seem to be broken across the board. And I've tested outputing to Jpeg, WebP, JXL, Avif, and MozJpeg, with only Jpeg and Avif not producing significantly bloated files.

(Just tested again with Avif and the numbers do seem to still be off, but not by nearly as much: 34.5KB for preview, 39.3KB for actual in one test)
(Tested that same image with JXL and got 66.4KB for preview, 610.6KB for actual...)

**Comment by OkyDooky** [comment]
I've been using another app I found before yours to handle JXL conversions ([this one](https://play.google.com/store/apps/details?id=ebusky.jpeg.xl.image.viewer.converter)) and I noticed similar bloating started happening with its outputs, as well. I realized that I had set it to RGBA, instead of the usual RGB. So, when I converted a file using one setting and then the other, I noticed the RGB one was really small and the RGBA one was larger (1.6MB) than the original PNG image (1.3MB).
I thought this must be what was going on in ImageToolbox, so I did the same test with the same image, but using this app. And...still quite large. It wasn't as big as the 1.3MB PNG, coming out at 842KB. The difference between RGB and RGBA from ImageToolbox was 0.3KB (842.2KB vs 842.5KB).
I'm not sure what the difference between the apps is, but your guess about the arguments being fed to the encoder might be it. I hope so, at least.

Again, this is using the Lossy mode only, not Lossless.

**Comment by OkyDooky** [comment]
Just wanted to post here to confirm that on the latest build (51 FOSS RC) MozJpeg, WebP, and JXL and no longer producing bloated files and the difference between the estimate and actual output is only a few kilobytes and is sometimes lower than the estimate!

I know it's been "closed" or a while, but I can now officially considered it resolved.

Thank you for whatever you did!

**Comment by T8RIN** [comment]
Thanks for using 👀
