### ISSUE TITLE
🔴 (#1206) NEW FEATURES

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1206]
# Suggestions:
- [ ] Drag handler: Create tab > Draw >> line width : while moving drag handler circle, I suggest viewing a circle sign shows the current real size (also add this feature when editing the number of line width (number of pt (points))) (add this feature to any other part of the app that has drag handler).

![2024-07-15_12-07-51_1867](https://github.com/user-attachments/assets/7d4b83af-dbd7-4fe9-8fad-e509c6b96ce6)

- [ ] Create tab > add numbers to images (bates numbering) (the 1st image takes number 1, the 2nd image takes number 2, and so on) + customize shapes around the number (shapes: circle, square or star + line's color + shape's fill color + line's width + shape's size + position [horizontal (left, center, right), vertical (up, middle, bottom), or in the image's center, or in specific position]), AND customizations for text (font type, size, color).
- [ ] Ability to add numbers in one image: if someone want to illustrate steps of something in an image .. touching in a place in the image puts number 1, touching in another place puts number 2, and so on).

- [x] Image tab > OCR (Recognize Text): ability to edit extracted text + ability to extract text from PDF file.

- [x] Edit tab > Resize and Convert: move to the next/previous image by swiping (that is faster).

- [x] Create tab > Filters > Full Filter: in (Favourite) tab: reorder items by drag & drop.

**Comment by T8RIN** [comment]
- [x] 4

**Comment by T8RIN** [comment]
Could you please split other request to different issues please? it's a bit hard to track

**Comment by T8RIN** [comment]
1 can't add, because PT is related to canvas size(not image size) and may change, but in controls i didn't know anything about it

**Comment by T8RIN** [comment]
- [ ] (2-1) Create tab > add numbers to images (bates numbering) (the 1st image takes number 1, the 2nd image takes number 2, and so on) + customize shapes around the number (shapes: circle, square or star + line's color + shape's fill color + line's width + shape's size + position [horizontal (left, center, right), vertical (up, middle, bottom), or in the image's center, or in specific position]), AND customizations for text (font type, size, color).
- [ ] (2-2) Ability to add numbers in one image: if someone want to illustrate steps of something in an image .. touching in a place in the image puts number 1, touching in another place puts number 2, and so on).

**Comment by UserAccount123** [comment]
> * [ ]  (2-1) Create tab > add numbers to images (bates numbering) (the 1st image takes number 1, the 2nd image takes number 2, and so on) + customize shapes around the number (shapes: circle, square or star + line's color + shape's fill color + line's width + shape's size + position [horizontal (left, center, right), vertical (up, middle, bottom), or in the image's center, or in specific position]), AND customizations for text (font type, size, color).
> * [ ]  (2-2) Ability to add numbers in one image: if someone want to illustrate steps of something in an image .. touching in a place in the image puts number 1, touching in another place puts number 2, and so on).

(2-1)
I explain this by an app called (iMarkup) in Google Play Store (link: https://play.google.com/store/apps/details?id=com.winterso.markup.annotable)
![iMarkup](https://github.com/user-attachments/assets/2404a8b6-454f-413a-ad5e-2ecfc7f839d0)

The video:

https://github.com/user-attachments/assets/0ee75557-ae6e-4f1a-be0a-3512db2127b8
 (2-2)

https://github.com/user-attachments/assets/c465d7c0-5a39-449c-9423-73b3d7f24338

**Comment by UserAccount123** [comment]
> * [ ]  (2-1) Create tab > add numbers to images (bates numbering) (the 1st image takes number 1, the 2nd image takes number 2, and so on) + customize shapes around the number (shapes: circle, square or star + line's color + shape's fill color + line's width + shape's size + position [horizontal (left, center, right), vertical (up, middle, bottom), or in the image's center, or in specific position]), AND customizations for text (font type, size, color).
> * [ ]  (2-2) Ability to add numbers in one image: if someone want to illustrate steps of something in an image .. touching in a place in the image puts number 1, touching in another place puts number 2, and so on).

(2-1)
I explain by an app called (iMarkup), in Google Play Store (https://play.google.com/store/apps/details?id=com.winterso.markup.annotable)

![iMarkup](https://github.com/user-attachments/assets/d2c49829-6e7b-4292-b720-a6a2014062ad)

The suggest feature is to add numbers to all images in one time, instead of opening each file every time.

https://github.com/user-attachments/assets/8f679d79-b301-4364-8aac-50cf1ab0fda2

(2-2)

https://github.com/user-attachments/assets/2c2ae608-6a12-4adc-a4ae-131d36285c88

**Comment by UserAccount123** [comment]
# Anothers suggestions to be added:
Move text object by arrows (up, down, right, left) .. I found this feature in an app called (Snap Markup: https://play.google.com/store/apps/details?id=com.snapmarkup)
![Snap Markup](https://github.com/user-attachments/assets/3da3957c-773e-484a-888c-034f1ecbc667)


https://github.com/user-attachments/assets/74ba0774-dc30-4140-ba22-7ac3d872c504

# Another feature .. In Google Snapseed app (https://play.google.com/store/apps/details?id=com.niksoftware.snapseed)
![Google Snapseed](https://github.com/user-attachments/assets/93158ad2-52a9-4b3e-b9ef-5abe3c37bf8b)

The feature is expanding image size .. But in this app expanding just allow small expanding, I hope you add this feature to your app with ability for bigger expanding.

https://github.com/user-attachments/assets/028fb640-4a86-4c7e-8add-fcdb75ef1821
