### ISSUE TITLE
[BUG][REQUEST] Image Preview Bug and Request for adding batch conversation from Image Preview section (Multi Select) and support for .txt format in format conversion tab.

### ISSUE THREAD

**Issue by sujitFYI** [T8RIN/ImageToolbox#1209]
**Describe the bug**
Image Preview Tab Issue:
You cannot preview [.txt](https://github.com/user-attachments/files/16273729/9b388a14-f65a-4ed0-b85d-cb5a06b9c9a7.txt) image if you choose is directly infact you can't even choose it. But its possible if you add a folder to preview all the image in the folder including .txt are previewable and also can perform conversion from their but limited to only one image that is getting preview. 

Format Conversion:
You cannot select . txt file in format conversion but format Conversion is possible by the method i mentioned above.

**To Reproduce**
Download the txt file put it into a folder. Go to Image Preview and uss folder icon button not pick an image. After you give use this folder button you can see the .txt image preview and also convert it using edit tab appear on top while previewing.

**Expected behavior**
Ability to select and convert txt format and batch tools implantation in image preview like multi select and edit. Yoi can perform action on Txt format using that trick.

**Screenshots**
[Ss1.txt](https://github.com/user-attachments/files/16273775/d77461ae-4bc6-46c6-87f0-ed15d8869fb2.txt)
[Ss2.txt](https://github.com/user-attachments/files/16273776/9b388a14-f65a-4ed0-b85d-cb5a06b9c9a7.txt)

**Smartphone (please complete the following information):**
 - Device: Vivo iQOO 7 Legend 
 - OS: Android 14 (Funtouch 14)

**Comment by T8RIN** [comment]
this will be available only through image preview option, because txt is not valid image format

**Comment by sujitFYI** [comment]
@T8RIN Got it. But atleast add ability to select txt format image preview or Batch Conversion from image preview.

**Comment by T8RIN** [comment]
i will

**Comment by T8RIN** [comment]
i checked this files, its just jpg's with txt extension

**Comment by T8RIN** [comment]
![d77461ae-4bc6-46c6-87f0-ed15d8869fb2](https://github.com/user-attachments/assets/619a59af-e7a4-4b22-8c56-d40068e82093)

**Comment by sujitFYI** [comment]
> i checked this files, its just jpg's with txt extension

Yes sir it is. In real time image generation images are in txt extension. Txt don't have image properties so ofcourse its extention doing.

**Comment by T8RIN** [comment]
Done

**Comment by OctoberNicole** [comment]
This seems like it's going to turn out to be an interesting option, thanks for adding this dev.👍
