### ISSUE TITLE
SOME BASIC AND EXTRA FEATURES FOR BACKGROUND REMOVER. 

### ISSUE THREAD

**Issue by sujitFYI** [T8RIN/ImageToolbox#1213]
**Is your feature request related to a problem? Please describe.**
I want to add some features in background remover 

1. Demonstration of Brush size and softness 

2. Auto Colour Remover 

3. Magic edge detection manual remover (self define name)

4. Edge smoothing using gaussian blur. sharp edges look dirty :-⁠X

**Describe the solution you'd like**
I've decided the solution in the telegram group here's link to [that message](https://t.me/t8rin_imagetoolbox/1/8028?single)

![Screenshot_20240720_144848](https://github.com/user-attachments/assets/10449cb2-1dfd-4eb5-a4fa-969706ea16be)

**Describe alternatives you've considered**
No alternatives but the features are combined of [PicsArt](https://play.google.com/store/apps/details?id=com.picsart.studio) and [Background Eraser](https://play.google.com/store/apps/details?id=com.handycloset.android.eraser) Application in Android.

**Comment by T8RIN** [comment]
Auto color removing is presented as a filter since long time ago

**Comment by sujitFYI** [comment]
The feature I'm asking and the filter you're saying are World apart. See the video in where i use auto colour option in which select colour from image And it'll automatically remove those colours.

**Comment by T8RIN** [comment]
You can use Pipette
