### ISSUE TITLE
🟤 (#1217) NEW FEATURES 

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1217]
# SUGGESTIONS:

- [ ] 1. NEW = Simple calculator for dimensions (*, +, ÷, -): in (Limits Resize) feature for example, if the image width is (250), and I want to increase it 5 times .. instead of opening calculator app, I can just type (250*5) in (Width) place to get the result directly (1250) (add this feature to any part of the app).

————————–————————–————————–

- [ ] 2. NEW = (Add text to image) feature:
- Text [font type, color, size + shadow color, shadow position, shadow opacity + text's outline color]
- Border around the text [(rectangle, square, circle, ...), border thickness, border line type (straight line, dotted line, zigzag line, ...), border color, border opacity].

————————–————————–————————–

- [ ] 3. NEW = insert image inside text: and the ability to move the image inside the text by freehand. And options to set image's opacity and brightness.

————————–————————–————————–

- [ ] 4. NEW = insert image on top of an image, & ability to change it's opacity, brightness and size.

————————–————————–————————–

- [ ] 5. NEW = Blend (mix) multiple colors together to get a new color (example: red + yellow = orange).

————————–————————–————————–

- [ ] 6. NEW = Convert between color codes to (HTML, Hex, RGB).

————————–————————–————————–

- [ ] 7. NEW suggested features from other apps:

(a) Annotium app (https://play.google.com/store/apps/details?id=app.ngockhanh.annotium) : shapes, measure, spotlight, magnify.
Shapes

https://github.com/user-attachments/assets/c5478f07-5f4c-4b35-bfc4-5a95fe7f5a41

Measure

https://github.com/user-attachments/assets/453c5875-d40a-4973-b8a4-848506181776

Spotlight

https://github.com/user-attachments/assets/b0fb06e4-7905-4418-85a0-77ec5ef4551f

Magnify

https://github.com/user-attachments/assets/5b4b7b3f-aaf9-40c2-9e1d-cb129641f988

(b) PicMarker app (https://play.google.com/store/apps/details?id=com.github.kolacbb.picmarker) : Blur: add these ⬇️ blur types + ability to blur by shape (square & circle) + ability to move & resize created blur shape.

https://github.com/user-attachments/assets/36aaf3b8-e1b0-42ec-a042-00bc8d926a6d

(c) Sketchbook app (https://play.google.com/store/apps/details?id=com.adsk.sketchbook): Transform, Fill, Guides, Symmetry and Perspective Guides.

![Sketchbook](https://github.com/user-attachments/assets/f739599e-242c-4c0b-9bb2-80617603dc0c)

————————–————————–————————–

- [ ] 8. Tools tab > PDF Tools:

(A) Preview PDF: add this feature: in current page number that appears beside scroll bar (example: 10/550) - tap on it to type the page number that you want to go.

(B) PDF to Images:
(B-1) Add option to specify page range by typing it (example: 1-250).
(B-2) Ability to extract multiple page ranges in one operation (example: first group (1-20), 2ed group (30-70)) and ability to put any range in their own folder.
(B-3) Specify custom pages (example: 1,13,244,430).

(C) Images to PDF:
(C-1) Option to specify paper size [Standard sizes: A0, A4, .., or specify custom size (width * hight) (in cm or inch)] + Ability to add margins + Crop the page to the image's border, other option is to not crop the page.
(C-2) Rotate images + images quality + add page numbering (left, center, right ... Top or bottom) & ability to add custom text beside numbering.
(C-3) Option to put two images side by side [put image number 1 into the right side, image number 2 into the left side .. Or the opposite .. Depending on language's text direction (left to right (LTR) or right to left (RTL))].

————————–————————–————————–

- [ ] 9. QR Code (in Tools tab): add ability to read & create BarCode.

————————–————————–————————–

- [ ] 10. Draw (in Create tab):

(A) Long press (Eraser) icon to remove all changes made by any tool (and make Undo icon to cancel the removing operation).
(B) Remove latest operation by long pressing (Undo) icon: in Draw (in Create tab): to explain this feature, say that you made two operations on an image: operation (1) is using (Pen) tool to draw multiple lines, operation (2) using (Text) tool to create multiple texts, .. The feature I suggest is to long press on (Undo) icon to remove ALL (all of them together) what you did with the LATEST TOOL you used (latest tool here is Text tool) + the same thing with (Redo) icon.
(C) Ability to move created shape (rectangle, circle, ...) + long press on drawn object to remove.

————————–————————–————————–

- [ ] 11. Suggestion: Image Stitching: add option to delete original images after stitching.

————————–————————–————————–

- [ ] 12. OCR (in create tab): add ability to add multiple images (and PDF files) at one time.

————————–————————–————————–

- [ ] 13. Add option to put a mark/star on any feature of app to as a favourite feature that I always use (to quickly find my favourite feature instead of looking at all features to find it).

————————–————————–————————–

- [ ] 14. Add option to exclude beta versions from update.

————————–————————–————————–

- [ ] 15. NEW features to save device's RAM and make the app faster:
(a) Option to disable all animations (examples: when opening tabs, icons shows with animations + when pressing settings icon (slide left animation) + when expanding & shrinking categories in settings).
(b) Ability to disable/hide features that someone is rarely usin (by disabling them the app will be faster) (JUST examples: Image Stacking, Delete EXIF (Create tab), JXL tools, Cipher, Zip (Tools tab) + Load image from internet (Image tab)).

=====================================

# Enhancements & Fixes:
- [ ] 1- Enhancement: in Edit tab .. The options of (Format Conversion) feature [Quality, Image Format and Compression Type] - all of them are included in (Resize and Convert) feature .. I suggest to remove (Format Conversion) feature.

- [ ] 2- Enhancement: in Edit tab .. (Crop) option is located among resize options, but it is not a resize option .. Please move it away .. move it to the last position.

- [ ] 3- Enhancement: In settings sidebar (better looking app + less file size of the app):
(a) Join (Updates + Contact me + About app + Firebase) in one new category named: (Help), and move the new category to the last position (and put (Options arrangement) category directly before it).
(b) Join (Customization + secondary customization + Night mode + Text + Screen + Emoji + Confetti ) in one new category named: (Appearance).
(c) Join (Output + Filename) in one new category named (Output), and separate between them. After joining them put (Image source) after it directly; because they are connected together.

- [ ] 4- FIX: in settings (sidebar) when shrinking (Contact me, customizations, About app) categories, they are expanded by itself every time I open the the settings .. Please fix that.

**Comment by T8RIN** [comment]
I have text on image in drawing

**Comment by T8RIN** [comment]
Image on top of image is already available by image stacking option

**Comment by T8RIN** [comment]
4 and 5 sounds like a good idea tho

**Comment by T8RIN** [comment]
Blur and pixelation are already available in drawing, also you can select any filter to use it as brush

**Comment by T8RIN** [comment]
There is undo redo and clear buttons in drawing already

**Comment by T8RIN** [comment]
12 exists, you can reorder screens
13 exists too

**Comment by T8RIN** [comment]
0 already exists, use presets

**Comment by T8RIN** [comment]
Hiding features will not make the app faster, i thought about animations, but it's too hard to do, because i need to rewrite the entire app

**Comment by T8RIN** [comment]
Format conversion as a separate option was requested by someone before, so i will not remove it

**Comment by T8RIN** [comment]
I will not move the crop, because it's the most needed function, and it fits in the change tab perfectly

**Comment by T8RIN** [comment]
3b i split these just for better understanding, and not cluttering all in one, anyways this will not reduce app size by any byte, moreover can increase it a bit, all the size comes from code, but all the code i wrote can fit into 7-8mb, all other weight is from native c++ code, that used for almost all features

**Comment by T8RIN** [comment]
4 is intended to be so, it will not expand/shrink on it's own till app closure, then it will be again at default values

**Comment by T8RIN** [comment]
Also, please, if you want something to be added/fixed, not make sooooo large issues, it's better to split them, so i can track easily, or you can add check boxes, so i can check what i've done, also if something can't be added, i can close separate issue as not planned, but not all of the other things (and this will be easier to find in future, if i will be able to do this then)

**Comment by UserAccount123** [comment]
> I will not move the crop, because it's the most needed function, and it fits in the change tab perfectly

I mean just reorder it, not removing it.

**Comment by T8RIN** [comment]
> > I will not move the crop, because it's the most needed function, and it fits in the change tab perfectly
> 
> I mean just reorder it, not removing it.

I knew, i mean that exactly 🐸

**Comment by UserAccount123** [comment]
OK, thanks alot 🙂.

**Comment by T8RIN** [comment]
I hope you got my thought that i will not change - it from the first page, also i think it will be a good setting to change the start tab

**Comment by UserAccount123** [comment]
👍
Thanks a lot.

**Comment by UserAccount123** [comment]
👉 How to change the label of issue from (Bug) to (Enhancement) ?
Is it possible to add more than one label on (Bug)?
