### ISSUE TITLE
Overwrite Files setting resets Image picker, but not the other way

### ISSUE THREAD

**Issue by k-dx** [T8RIN/ImageToolbox#1226]
**Describe the bug**
If I understand correctly, the _Overwrite Files_ setting only works if _Image source_ is set to _Gallery_. When I toggle _Overwrite Files_, it changes it _Image source_ to _Gallery_. However when I change _Image source_ to something other than _Gallery_ _Overwrite Files_ stays on, when it should get changed to off.

**To Reproduce**
1. Set _Overwrite Files_ to on.
2. When changing the _Image source_ setting the _Overwrite Files_ stays on.

**Expected behavior**
Changing _Image source_ should set _Overwrite Files_ to off if chosen settings are incompatible and **should tell user** that _Overwrite Files_ has been changed.

**Screenshots**
![obraz](https://github.com/user-attachments/assets/c596043f-e954-473a-afa8-8fb8cce8ff1d)
![obraz](https://github.com/user-attachments/assets/3f666292-17a7-40d1-84e7-76f73647f7c4)

**Smartphone (please complete the following information):**
 - Device: Samsung A52s 5G
 - OS: Android 14 with OneUI 6.1

**Comment by T8RIN** [comment]
It works for all except camera and photo picker

**Comment by T8RIN** [comment]
if you try to overwrite and it fails, then toast with message that you should repick and source are set to needed one

**Comment by T8RIN** [comment]
not a bug in my opinion

**Comment by k-dx** [comment]
Why not inform user settings were changed? It's confusing
