### ISSUE TITLE
Overwrite Files doesn't work with certain Image pickers

### ISSUE THREAD

**Issue by k-dx** [T8RIN/ImageToolbox#1227]
**Describe the bug**
_Overwrite Files_ is incompatible setting turned on I get error "Failed to save X image(s)." Tried both on SD card and internal storage.

**To Reproduce**
1. Set _Overwrite Files_ to on.
2. Set _Image source_ to _Gallery_
3. From _Edit_ tab choose _Resize and Convert_.
4. Pick a few images
5. Choose Preset 70
6. Save
7. "Failed to save X image(s)".

**Expected behavior**
Expected successful overwriting save.
Observation: If _Image source_ is set to _File explorer_ overwriting works.

**Screenshots**
![obraz](https://github.com/user-attachments/assets/f882ab1c-9f25-4b49-820c-4d30a66ea98c)

**Smartphone (please complete the following information):**
 - Device: Samsung A52s 5G
 - OS: Android 14 with OneUI 6.1

**Comment by T8RIN** [comment]
It's differs by device and app which is used as image provider, so on one it can overwrite using source, on other can't, only i can do is choose one which works
