### ISSUE TITLE
🟢 (#1229) NEW FEATURES

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1229]
# SUGGESTIONS:
- [x] 1. Create tab >> Background remover:
- When selecting (Auto erase background) option after first time installing the app .. The app start downloading the (Subject Segmentation) optional module .. I suggest to add an ability to export/import that module; in case if I reinstalled the app, I can just import it without downloading it again.
-  Ability to add multiple images at one time; so as to use (Auto erase background) feature on them.
- Add JPG in image format + Ability to change quality.

- [ ] 2. Create tab >> Watermarking: enable multiple lines in text box.

- [x] 3. Create tab >> (Watermarking + Gradient Overlay): Add (Quality) option to them.

- [ ] 4. NEW = ability to insert image (+ ability to modify its opacity and resize it by freehand) on top of other image/blank page AND ABILITY to MOVE it by FREEHAND to the DESIRED position [(Image Stacking) doesn't offer moving the image freely].

# FIXES:

- [x] 1- Image Stacking: when moving an image, BUT not changing its position, the stacking operation starts creating.

https://github.com/user-attachments/assets/5e6a28bc-89be-4694-8706-d6450589cb68

- [x] 2- In (Image Stitching): if the current value of (Row counts) is (2), when moving the slider to another value and directly put it back to (2), the app starts creating image while the initial value really didn't change (the same issue when just tapping on slider's grip (the circle)).

https://github.com/user-attachments/assets/ae0f1e54-3a1e-4d6f-9958-1e00abf2ba12

- [x] 3- Document Scanner: images are put in the center + When scrolling images, another image is selected be it self without touching it by the user + The language in the app is English, but here some text are not translated into English.

https://github.com/user-attachments/assets/ff32f8ce-014d-4a76-b8e0-a54b2f093928

**Comment by T8RIN** [comment]
> Add JPG in image format + Ability to change quality.

Jpg contains no alpha channel

**Comment by T8RIN** [comment]
> I suggest to add an ability to export/import that module; in case if I reinstalled the app, I can just import it without downloading it again

That's can't be done

**Comment by T8RIN** [comment]
Freely moving will not be done for now

**Comment by UserAccount123** [comment]
> > Add JPG in image format + Ability to change quality.
> 
> Jpg contains no alpha channel

OK, I got it.

**Comment by UserAccount123** [comment]
> Freely moving will not be done for now

OK.

**Comment by UserAccount123** [comment]
> > I suggest to add an ability to export/import that module; in case if I reinstalled the app, I can just import it without downloading it again
> 
> That's can't be done

Is it possible to embedd (put inside) that component inside the APK file ?
