### ISSUE TITLE
SETS OF SMALL BUT CRUCIAL FEATURES FOR DRAW, DOC SCANNER AND CROP MODE.

### ISSUE THREAD

**Issue by sujitFYI** [T8RIN/ImageToolbox#1230]
### 1.Add Page / Image Straightener Feature in Doc Scanner 
 •i know a method using skew for each side but AI help is also appreciated.

### 3. Draw Mode Lack some essentials
• Ability to use eraser as selected path mode too. 
• Ability To select and move Drawings afterwards and even resize them using 6 points.

https://github.com/user-attachments/assets/acc2d460-4555-42d7-b47f-5675a88fe5a0

### 4. Crop Mode Limited to Image Maximum height x Width
• my image is 1920x1080 but its content is 1920x864. But if i type this numbers in custom I won't get Desired results. Yikes
•Keep Image by default in 1x zoom mode and a Zoom resize button to change to 1x zoom quickly/precisely 
•Keep crop areas always in center i mean always. 

https://github.com/user-attachments/assets/40f4effb-5fcc-49df-a286-fcd32b8d2e22

**Comment by T8RIN** [comment]
4) this is not width and height rather ratio, to use precise trimming use Crop Resize Mode, not crop function

**Comment by T8RIN** [comment]
1 not now, 3 planned someday
