### ISSUE TITLE
🟣 (#1234) NEW FEATURES

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1234]
# SUGGESTIONS:
- [ ] 1. NEW = add (Collage) tool: its features: different type of grid shapes, curvature of the corners, add outline around the images or not.

![Collage](https://github.com/user-attachments/assets/b464974b-5a83-4cf7-b989-bbceec64319e)

- [ ] 2. NEW = add (Frame around images) tool [shapes of frame, color, thickness, line type (straight, dotted, ..)].

- [ ] 3. Add (Liquify) filter.

**Comment by T8RIN** [comment]
closed in favor of #881
