### ISSUE TITLE
Color Transfer Alternative Methods

### ISSUE THREAD

**Issue by Luminousquestor** [T8RIN/ImageToolbox#1235]
**Is your feature request related to a problem? Please describe.**  No, this is not related to a problem, just a recommendation. I recommend adding other methods of color transfer, as there are other more effective methods that could improve the current color transfer filter.

**Describe the solution you'd like** Add other methods of color transfer while keeping the current one, and maybe make it an option within the filter or make a separate filter.

**Describe alternatives you've considered**
If this is not possible, it would be fine to leave it as is.

**Comparison
This is what I mean when I say other effective methods for comparison. 
![Example 2](https://github.com/user-attachments/assets/ed84936a-dc76-46cc-980b-4cec4fc881c3)

![Example](https://github.com/user-attachments/assets/b1eff85e-f50a-46f0-9e6b-db8946378766)

![Original Fish Image](https://github.com/user-attachments/assets/8f032e5e-6981-4507-a376-b18b2c45d0ef)

**Comment by T8RIN** [comment]
Which other modes? I've seen only one really nice working algo

**Comment by T8RIN** [comment]
There are also was some hard to do one, but I didn't find how to make it, if you find you can share👀
