### ISSUE TITLE
⚪ (#1236) NEW FEATURES

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1236]
# SUGGESTIONS:
- [ ] 1. NEW = add (Color Curves) tool.

- [x] 2. NEW = (Dark & light tones of color) tool: the user puts a color, then the app generates its darker & lighter graduations [add ability to specify the number of colors to generate (when typing 5, the app generates 5 darker tones & 5 lighter tobes)] [add this tool inside (Generate palette) tool) (add it also in (Clipboard color) tool IF you create it (I mentioned it in issue: 🟠 #1232 (suggestion number 5)) by enabling saving a set of generated light and dark colors].

![Dark   light tones](https://github.com/user-attachments/assets/e66df149-fae1-40c4-983c-0f2c10ce2ced)

- [x] 3. NEW = (Image metadata editor) tool.
- [ ] 4. NEW = (Stamp) tool: put image's metadata in specific position in the image as a stamp with background color (upper/lower .. left, center, right) [Metadata: date taken (D/M/YYYY _ H:mm AM/PM), dimensions (px/cm, inch), GPS location, putting incremental numbers in multiple images) (ability to add any custom text before/after these info) [text size, text color, background color] (enable adding multiple images) [attached image].

![4  Stamp](https://github.com/user-attachments/assets/0c223014-9d78-4fec-b52b-cad2ef016e8b)

- [x] 5. NEW = Filename (in Settings): add this renaming method: (%Y year, %M month %D day, %a The abbreviated weekday name (Wed) .. image width, image hight, GPS location) or add any other method.

- [x] 6. OCR (in Image tab): in the box of extracted text, add these 2 buttons: Copy all, Export to text file (*.txt).

- [x] 7. Cipher (in Tools tab):
- Add ability to encrypt/decrypt multiple files.
- Add ability to add/remove encryption without creating new file.
- FIX: in (Decryption) section, remove (Random key generator) button (; its right place only in (Encryption) section).

![Remove (Random key) button](https://github.com/user-attachments/assets/931e079c-5cc8-4875-abcb-039f9adaa992)

- FIX: after typing the key (the typing box is still active) then pressing (Encrypt) button, the operation doesn't start until touching for the second time the key typing box .. The fix: make encryption starts when just tapping one time on the (Encrypt) button.

https://github.com/user-attachments/assets/b5ee72bc-91ab-4d07-84be-41c10a1ce9f7

- [x] 8. QR Code: allow importing image/images that has QR code.

- [x] 9. Clipboard button: add ability to save multiple copied images in the button .. Then selecting one image to take action on it.

- [ ] 10. When long pressing the (Save) button (one time save location) allow manually renaming [for single image].

- [ ] 11. Estimated output file size: when changing the value of (Quality) in these tools: [Image Stacking, Document Scanner, Images to GIF, GIF to images, Images to APNG, APNG to images] show output size in the top area.

- [ ] 12. Like in presets favourite values, also enable this feature for (Quality) (if someone uses a specific quality value every time) [attached image].

![Quality - Presets](https://github.com/user-attachments/assets/57011507-99cc-46ad-972d-2e10c53ad3cc)

- [ ] 13. GIF to images (in Tools tab):
- NEW = give incremental numbers (1, 2, 3, .. without adding (0) digit before the number) to the output images (skip (Filename) preferences in (Settings)).
- NEW = Add option to put output images in their own folder; so as not to be shuffled with other images in output folder (Make the app creates a folder & naming it with the GIF's filename).

- [ ] 14. NEW = (Spotlight) tool [add it inside the (Draw) tool]: description: everything around a circle is: blurred or hidden by black color (or any color).

- [ ] 15. Draw tool:
- Add square shape for the (Eraser) tool.
- Enable cloning drawn object & changing its color.
- Enable to view grids while drawing.
- Draw > Draw mode 👉 Image : add option to disable/enable (Repeat of image).
- ENHANCEMENT = (Pipette) tool that in Draw tool: move it to a new a new button beside (Paint color) tool + make (Pipette) tool gets color from image directly WITHOUT opening NEW WINDOW, then that color will be pasted automatically inside (Paint color).

![(Pipette) tool](https://github.com/user-attachments/assets/9631f032-4035-4d2a-8564-91fcc041f711)

- ENHANCEMENT = Draw tool: make color selector in the top corner by default; so as to show all colors in colors slider (instead of black).

![Color selector](https://github.com/user-attachments/assets/236166cf-6630-4131-a0b5-615621a53473)

- [ ] 16. NEW = PDF to images: put output images in their own folder; so as not to be shuffled with other images in output folder [Make the app creates a folder and naming it with Pages range (example: 1-15), or if selected few random pages, make folder's name by pages numbers (example: 1,5,23,50), BUT if selected too too many random pages, name the folder as: [(1 ... 430) 👉 (1) is the first selected page ... (430) last selected page]. 

- [ ] 17. Image splitting: add manual splitting feature (if user wants parts those are not equal in their sizes): add ability to manually add any number of splitting lines, horizontal ir vertical lines .. In any location he wants, by any angle.

- [ ] 18. NEW = IF you can create these 2 tools, AND make them WORK WITHOUT INTERNET (offline) that is would be excellent (if they need to download components then create a module to export/import the components of these 2 tools), BUT If not possible to make them work without internet just forget them. The tools are:
- (Restoration of old photos) tool: (remove tears, spots, dusts .. automatically adding colors to non colored photos).
- (Face) tools: reshape face items (eyes, eyebrows, eyelid, cheeck nose, mustache, beard, mouth, forhead, ears, blacken/coloring hair) + (remove: acne, blemish) + (whitening teeth, removing redeye).

- [ ] 19. Ability to save output files in the source folder of them.

# FIXES & ENHANCEMENTS:
- [ ] 1- ENHANCEMENT = Move (Quality) option above (Image Format) option (like in all other tools) in these tools: GIF to images, JXL to images.

- [x] 2- FIX = APNG to images: the first image that appears in the APNG preview is not extracted inspite of it is selected.

- [x] 3. FIX = Draw tool: arrow head disappears.

https://github.com/user-attachments/assets/0cb05594-79a8-4875-a159-fdf2985e61e3

**Comment by T8RIN** [comment]
for 7 use zip tool

**Comment by UserAccount123** [comment]
> for 7 use zip tool

OK 👍

**Comment by T8RIN** [comment]
> Add ability to encrypt/decrypt 👉 **MULTIPLE** files.

Create archive and you can achieve this

> Add ability to add/remove encryption 👉 **WITHOUT** creating new file.

Impossible
