### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by carkks** [T8RIN/ImageToolbox#1238]
In Options arrangement, there could be an option that allows you to favorite some options, which would be extremely useful for performing daily tasks (and would also allow my relative to stop downloading 300 apps for functions that already exist in your app... ). 
**Execution ideas**
- Only allow the addition of favorites through the settings, a star/heart in the function editing panel would pollute the application.
1. The “Group Options By Type” option, when disabled, lists all the functions in a single grouping. 
   - If this option is disabled, it would enable another option called (idea) “Favorite Single Group”, which describes “Separates favorites into a single group. (Note: This group will always be shown when running the app)”. The toolbar would then read “Favorites” and “Other”. 
   - If this option is activated, (idea) above the taskbar, you could fix (only) 4 options + the paste and search button (if the search button is deactivated, allow adding one more option), separating the taskbar and this function bar with a line.
     - You could also enable the favorite's slider, you know what I mean :)
2. If “Group Options By Type” is disabled, and the bookmarks are listed, you could give them a gallery view option, making the icons larger. (This is very useful for those with vision problems).

**Comment by T8RIN** [comment]
Added this
