### ISSUE TITLE
🟥 (#1246) NEW FEATURES

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1246]
# SUGGESTIONS:

- [x] 1. Add a tool in (Edit) tab to change the (Quality) ONLY .. for multiple images.

——————————————————————————

2. Draw:
- [ ] 2-1. NEW = Lock ratio: if changing one dimension (height or width) of the image/object, the other dimension will automatically change to maintain the shape and proportions of the object instead of stretching it out.
- [ ] 2-2. If I want to draw a rectangle exactly in the image's edge, that is very hard .. so I suggest to add ability to move image canvas freely (like in Crop tool), & ADD ability start drawing from outer of the canvas, then completing drawing the shape inside tge image + Add button to put the image in the center of screen.

![Move canvas](https://github.com/user-attachments/assets/e3e8389e-3849-4e1f-8fd5-117dc8e93b2e)

- [ ] 2-3. Text:
- Ability to add background (color, opacity, background space (up, down, left, right .. each separately).
- Add (Emphasis) feature: Bold, Italic, Underline, Stikethrough.

- [ ] 2-4. Add (Snap to 0°, 90°, 180°, 270°) (Snap to center/edge of image, make objects snaps to each other).

—————————————————————————— 

3. Filter (Full Filter):
- [x] 3-1. Add ability to reorder added filters.
- [x] 3-2. Add an option to set multiple filters as a profile (filters with specific values) [instead of adding filters with their values every time .. Here You just load a profile] + Ability to give it a name + Ability to embedd saved profiles in the settings backup file + Ability to remove filters from profiles.
- [ ] 3-3. Add (Grid view) mode: 4, 5, 6 columns per row (also when searching .. allow showing all filters in grid mode).

——————————————————————————

- [x] #1319

——————————————————————————

- [x] 5. Pipette (Copy & Paste): when closing (Pipette) tool, make color copied automatically, then when long pressing the (other colors) button 👉 make that color pasted.
This trick makes using the app faster, easier.
Add this trick in every other tools (Draw, Watermarking, many filters, ... etc).

![Pipette + Paste](https://github.com/user-attachments/assets/4c3495c6-8bd3-4845-920a-dd02ad024978)

—————————————————————————— 

- [x] #1321

![Stitching - Center 1](https://github.com/user-attachments/assets/62349929-a377-4dd9-91ad-3ca9d6df8846)

👇

![Stitching - Center 2](https://github.com/user-attachments/assets/c54b8dad-b234-478c-8e6a-673cdf7061b7)

——————————————————————————

- [x] 7. Enable (Order) for Favourite tab (when disabling grouping).

![Order - Favourite](https://github.com/user-attachments/assets/5ca88d9f-9edb-4364-9382-47bdb025146d)

- [x] #1318

https://github.com/user-attachments/assets/1e71049a-d5fa-4139-b6c4-74ae4512fc9e

- [ ] 9. Add (Grids) view mode in tabs (without description in these 2 modes): (Icon & Title, Icons only) 👉 3, 4 or 5 icons per row.
Make this feature active when (Grouping options by type) is DISABLED or NOT.

- [ ] 10. Add ability to REDUCE (& increase) the curvature of the corners (this is psychologically comfortable).

![Curvature 1](https://github.com/user-attachments/assets/c3746271-9b52-4ae7-b8e9-c51660f90a4d)
![Curvature 2](https://github.com/user-attachments/assets/58e7cfeb-dec3-4d53-96fe-e120a95dcc8c)
![Curvature 3](https://github.com/user-attachments/assets/c308768d-61b8-4338-8163-c9afb4cbf4c1)
![Curvature 4](https://github.com/user-attachments/assets/e8e3d5db-00ea-4c2a-a0cb-d432b55391d4)

——————————————————————————

- [ ] 11. Color Tools: make (Selected Color) always visible, even when scrolling down.

![Selected Color](https://github.com/user-attachments/assets/a88868f2-8a0e-4e1c-add3-74ec56d86b10)

——————————————————————————

- [x] #1320

![Cut out](https://github.com/user-attachments/assets/59270ee4-3092-4415-baef-c5f4ad425d21)

——————————————————————————

- [ ] 13. NEW = Correction tool for: perspective, backlight, red eye.

——————————————————————————

# ENHANCEMENT:
- [ ] Draw: hiding drawing tools .. Watch attached video. This problem also in: (Draw, Single edit > Draw, Crop, Background remover).
ONLY make hiding from the upper part.

https://github.com/user-attachments/assets/3cdf4764-2db2-4fcb-89ab-81b11b8ee699

And if I want to go up to other tools:

https://github.com/user-attachments/assets/645edbfd-986c-416f-ab64-12bad2cc8c1d

# FIXES:
- [ ] 1- Resize by weight: very very long time to complete resizing ONLY ONE IMAGE (by KB, or by presets).
- [ ] 2- After leaving the app for couple of minutes the app closes (fix that + add auto save feature (saving inside the app .. not in the storage)).

**Comment by T8RIN** [comment]
"fixes" 1 and 2 are inteded to be so
