### ISSUE TITLE
Choosing the defaults for the Draw feature and when sharing pictures to the app

### ISSUE THREAD

**Issue by EricMGVS** [T8RIN/ImageToolbox#1259]
Currently, we are able to select the default line width of the Draw feature through the settings, which already helps a lot, and I would love if it was possible to choose the default color and default shape as well, or even keep the last used color and shape in memory to use them for default in new editings.

And in relation to this, I would love if it was possible to select the default behavior when sharing a picture from the gallery to Image Toolbox. For example, the Draw feature is what I use 99% of the time when sharing a picture to the app, so it would be great if I could choose to open the pictures that I share to Image Toolbox in the Draw mode directly.

**Comment by T8RIN** [comment]
Thanks for suggestion!

**Comment by T8RIN** [comment]
As i implemented the half, this will be closed in favor of similar thing as second part of current issuse #1318
