### ISSUE TITLE
Improve gif creation

### ISSUE THREAD

**Issue by P0bo** [T8RIN/ImageToolbox#1265]
love using the Image Toolbox app, but I've been forced to use other tools like [EZGIF](https://ezgif.com/maker) even tho thay use bad compression just to get a few extra features. Right now, the app limits us to creating GIFs with each image only sticking around for a second max. It’d be awesome if we could have more control over how long each image stays and add some cool effects like crossfade.

### 1. Custom Frame Delay

- **What**: Let us set how long each image stays in the GIF.
- **Why**: Sometimes you want a particular image to be on the screen for more than a second to really let it shine or emphasize something important. Right now, I have to use EZGIF to do this, which isn’t ideal.

### 2. Adjust Frame Delay for a Range

- **What**: Allow changing the delay for multiple frames at once.
- **Example**:
  - **From**: Frame 1
  - **To**: Frame 5
  - **Delay**: 500 (milliseconds)
- **Why**: This would save a ton of time when making longer GIFs. It would be super handy to apply consistent timing across a bunch of frames quickly.

### 3. Global GIF Settings

- **Delay Time**: Set a default delay for all frames, with the option to tweak them individually later.
- **Loop Count**: Let us decide how many times the GIF loops (forever or a specific number).
- **Global Colormap**: Use the same colors across all frames to cut down on file size.
- **Why**: Having these options would make it way easier to make optimized GIFs that look just how we want.

### 4. Effects

- **Crossfade Between Frames**: Add a smooth transition effect between frames.
  - **Fader Delay**: Control how long the fade lasts.
  - **Frame Count**: Choose how many frames are used in the fade.
- **Fade from Last to First**: Allow the GIF to smoothly transition from the last frame back to the first.
- **No Fade from Last to First**: Option to prevent the GIF from looping awkwardly by not fading from the last back to the first frame.
- **Don’t Stack Frames**: Remove frames when displaying the next one, which is great for transparent images.
- **Transition Effect**: When using transition effects, the transition part must use a higher frame rate compared to other parts of the GIF for smoother transitions. To accommodate this, the current FPS selection must be improved to allow different frame rates in different sections.
- **Why**: These effects can make GIFs look smooth and engaging , and have a better transition effect instead of suddenly changing frame .

**Comment by T8RIN** [comment]
I haven't got such an opportunity unfortunately :( gif coder i use written in java 12 years ago, so👀

Maybe in future, thanks for ideas
