### ISSUE TITLE
Watermark: Text sizing doesn't match preview

### ISSUE THREAD

**Issue by Iizuki** [T8RIN/ImageToolbox#1276]
**Describe the bug**

In the watermark tool, when watermarking with text, `Size` setting doesn't behave as it should. The resulting image has differently sized watermark than in the preview view. Always significantly smaller in my tests.

**To Reproduce**

Apply text watermark to an image with increased size.
Compare the preview to the resulting image.

**Expected behavior**

The resulting image should look like the preview.

**Screenshots**

View from editor:

![Screenshot_20240814-120135_Image Toolbox](https://github.com/user-attachments/assets/0bcced5c-8dd9-4aa6-9169-832f75f5c09c)

The resulting image:

![ResizedImage_2024-08-14_12-01-42_1](https://github.com/user-attachments/assets/97656013-52d6-455b-9907-10ebdccc7872)

**Smartphone (please complete the following information):**
 - Device:  Fairphone 5
 - OS: /e/OS 2.2
 - ImageToolbox: 2.8.1

**Comment by T8RIN** [comment]
Maybe you should try a newer version first?

**Comment by Iizuki** [comment]
Sorry I missed your comment. 2.8.1 is just the latest version in F-Droid ATM.

Anyway thanks for taking a look!
