### ISSUE TITLE
JPEG2000 display/conversion issues

### ISSUE THREAD

**Issue by abdci** [T8RIN/ImageToolbox#1284]
**Describe the bug**
Color changes incorrectly when converting images to JPEG2000 format

**Expected behavior**
The color of the converted image should be the same as the original image

**Screenshots**
Original image
![ResizedImage_2024-08-15_20-17-43_1527](https://github.com/user-attachments/assets/a1faa51e-d4df-493e-9207-65001fc6bf27)
Converted image opens in xnview
![image](https://github.com/user-attachments/assets/8b661550-ab83-41ab-96c1-ae05d61b99a5)
Converted image opens in photoshop
![image](https://github.com/user-attachments/assets/91f02843-c018-477d-a402-37996a3f6142)
Image converted by other software open in imagetoolbox
![3cb61ed37b5275f51d6df039889101a](https://github.com/user-attachments/assets/ffb40c53-fcf9-4355-893b-57875cdec8a2)

**Smartphone (please complete the following information):**
 - Device: HONOR DIO-AN00
 - OS: Magic UI 6.1 / Android 12
 - ImageToolbox: 2.9.1-beta01-foss (148)

**Comment by T8RIN** [comment]
should be fixed now
