### ISSUE TITLE
Unable to remove image toolbox from notifications

### ISSUE THREAD

**Issue by Privateofcourse** [T8RIN/ImageToolbox#1295]
Taking a screenshot by tapping the SCREENSHOT button in the QUICK PANEL adds Image Toolbox to the notification area and the notification cannot be removed by swiping.

Tap SCREENSHOT button from pull down QUICK PANEL
After completion, open the notification area by swiping down
Try to clear Image Toolbox from notifications by swiping.... stuck.

It should be cleared on swipe.

 - Device: Samsung A12
 - OS: Android 12

**Comment by T8RIN** [comment]
And which notification is it showing? Could you expand

**Comment by T8RIN** [comment]
You can also disable showing i think

**Comment by Privateofcourse** [comment]
Hi

Thanks. Yes, Under notifications for Image Toolbox there is indeed a single choice for Screenshot. Sorry to bother you. Usually when you swipe something that appears in the notifications list it goes away and has some options or something.... so didn't think to look at notifications settings. So sorry, and thankyou.

And, the app is brilliant. It's good looking (I like nicely designed apps) has many very useful features, and is intuitively laid out. Superb.

**Comment by T8RIN** [comment]
Np, thanks for using!
