### ISSUE TITLE
[Feature Req] Add webp animation

### ISSUE THREAD

**Issue by Ero-gamer** [T8RIN/ImageToolbox#1297]
How come there are JXL animation but no webp animation? Webp animation feature was released in 2011 so I'm surprised to see JXL animation feature added before webp animation.

**Comment by T8RIN** [comment]
I just didn't know any lib to do webp animation creation

**Comment by T8RIN** [comment]
Just found it now 
https://github.com/penfeizhou/APNG4Android

**Comment by Ero-gamer** [comment]
> I just didn't know any lib to do webp animation creation

As I thought, it was a lack of compatible lib.

**Comment by Ero-gamer** [comment]
> Just found it now https://github.com/penfeizhou/APNG4Android

Haha, you work fast, I was actually gonna refer this lib to you but you already have it. Looking forward to your implemention of this feature. You are doing an amazing job, kudos to you :)

**Comment by T8RIN** [comment]
Added
