### ISSUE TITLE
Editing Multiple Images!

### ISSUE THREAD

**Issue by Maxitendo1** [T8RIN/ImageToolbox#1300]
Unfortunately you can only select one image to edit and not multiple. It would be nice to have something like in Pocket Paint, where you can import more images:![Screenshot_20240829-195714.png](https://github.com/user-attachments/assets/b3b74f94-d7aa-4a71-8af6-8cf40a1bcc14)

**Comment by T8RIN** [comment]
App repository?

**Comment by Maxitendo1** [comment]
https://github.com/Catrobat/Paintroid

**Comment by T8RIN** [comment]
Catrobat what is it?

**Comment by Maxitendo1** [comment]
They are a non-profit visual programming language with over 1,000 contributors. You can find more here:

https://catrobat.org/

**Comment by T8RIN** [comment]
I think it's similar to #676
