### ISSUE TITLE
Option to remove all suffixes from batch processing

### ISSUE THREAD

**Issue by OkyDooky** [T8RIN/ImageToolbox#1309]
**Is your feature request related to a problem? Please describe.**
I'd like to retain the original names of all the files I run through conversion as-is. Currently, I've turned off everything I'm allowed to in the File Output options:
Prefix: Empty
Suffix: Empty
Add file size: off
Add original filename: on
Replace number sequence: off
Overwrite files: off
Randomize filename: off

But, the replace number sequence option just seems to switch between adding the date&time and adding an incremental number count for batch processed files.

**Describe the solution you'd like**
Maybe divide the "Replace number sequence" option into two toggles? Or have it open a pop-up menu to select number/date/off?

**Describe alternatives you've considered**
I'd think putting those options actually in the batch processing screen would make sense, but that seems like it'd go against the design principles you set for the app.

Or maybe I've somehow missed something in the settings.

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by T8RIN** [comment]
I will think what can i do👀

**Comment by OkyDooky** [comment]
Thanks!
