### ISSUE TITLE
Option to preserve colour profile

### ISSUE THREAD

**Issue by Rafee-M** [T8RIN/ImageToolbox#1313]
**Is your feature request related to a problem? Please describe.**
Currently, if using a different compression method (such a MozJpeg for .jpg file) or resizing an image, the colour data gets lost (such as images taken by a phone camera)

**Describe the solution you'd like**
XnConvert has an option to preserve colour data.
![image](https://github.com/user-attachments/assets/acfe7b2d-7e05-480a-8d85-4ff83da0ea06)

**Describe alternatives you've considered**
Not resizing and using normal jpeg compression

**Comment by T8RIN** [comment]
And with normal jpeg option?

**Comment by Rafee-M** [comment]
With JPG and JPEG compression its's fine. With MozJpeg, Jpegli or resizing, the colour profile the phone camera processing puts goes away. Similar to putting the picture in a editing software like Lightroom Android

**Comment by Rafee-M** [comment]
Yes, but with a extra option/toggle to preserve the colour profile would be helpful for people who wish just to compress/resize the image

**Comment by T8RIN** [comment]
Idk how to strip it btw👀

**Comment by Rafee-M** [comment]
I did some digging and it's all in the metada. 

Image X with colour profile intact:
![image](https://github.com/user-attachments/assets/e42ee861-9ff2-459d-9a9d-c98e289cdd45)

Image X with colour profile stripped:
![image](https://github.com/user-attachments/assets/155106d1-45ba-4e7f-b3e8-773e21c06994)

**Comment by Rafee-M** [comment]
A list of missing metadata entries (25) on the converted image without colour profile: 

`BlueMatrixColumn, BlueTRC, CMMFlags, ChromaticAdaptation, ColorSpaceData, ConnectionSpaceIlluminant, DeviceAttributes, DeviceManufacturer, GreenMatrixColumn, GreenTRC, MediaWhitePoint, PrimaryPlatform, ProfileCMMType, ProfileClass, ProfileCOnnectionSpace, ProfileCopyright, ProfileCreator, ProfileDateTime, ProfileDescription, ProfileFileSignature, ProfileID, ProfileVersion, RedMatrixColumn, RedTRC, RenderingIntent, RenderingIntent`

<img src="https://github.com/user-attachments/assets/c8db80f9-07b5-46e4-a6c8-6566edd5d25f" width="273" height="900">

**Comment by T8RIN** [comment]
🤯 hard

**Comment by Rafee-M** [comment]
So, I believe if these metadata could be preserved with a toggle hopefully the colour profile would be preserved

<img src="https://github.com/user-attachments/assets/6da3c9a9-0bea-4ec9-971a-b8c18b0b1790">

**Comment by T8RIN** [comment]
idk how to handle this unfortunately 😢

**Comment by T8RIN** [comment]
If lightroom doesn't handle it, then i can't do it too, sorry i didn't find a possible way
