### ISSUE TITLE
Can't select my created images.

### ISSUE THREAD

**Issue by Nathanael-L** [T8RIN/ImageToolbox#1325]
I am not able to use created images for further editing. They don't appear in the explorer. Neither in the own importer nor in the android filesystem selector.

I merged 3 images vertically, saved it two times. Then I wanted to place them horizontally.
But I had the general problem, not to be able to select the pictures in the output folder. So I copied the pictures to the place, which I used for the import before. But the images don't appear in that folder.

The default export folder should appear in the import widget and created images should appear for import.

 - Device: Pixel 6
 - OS: Android 14

Ok, it seems it has sth to do with I wrote png.

**Comment by T8RIN** [comment]
App version? This should work, because i have pixel 8 and android 14 too

**Comment by Nathanael-L** [comment]
Am 08.09.2024 20:22 schrieb Malik Mukhametzyanov ***@***.***>:
App version? This should work, because i have pixel 8 and android 14 too

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Hi Malik,i found the images. It was just the case, that the preview/thumbnail didn't change. I merged three images vertically.So you can close the issue.Thanks for the application. It is a great tool!Bye bye

**Comment by T8RIN** [comment]
Okay 👀 thanks for using
