### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by ABDOULemul** [T8RIN/ImageToolbox#1339]
Device: POCO F2 Pro (POCO - lmi), SDK: 31 (12), App: 3.0.0 (152)java.lang.IllegalArgumentException: Key "1592001229" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.at n1.A.H(SourceFile:155)at g0.P.b(SourceFile:34)at e0.k.b(SourceFile:21)at e0.l.k(SourceFile:853)at Vc.f.k(SourceFile:2066)at n1.C.c(SourceFile:72)at p1.u.d(SourceFile:38)at X0.V.d(SourceFile:1)at p1.z.d(SourceFile:11)at W.N.d(SourceFile:34)at p1.z.d(SourceFile:11)at X0.V.d(SourceFile:1)at p1.z.d(SourceFile:11)at i1.b.a(SourceFile:67)at O0.s.e(SourceFile:114)at O0.t.a(SourceFile:52)at O0.u.c(SourceFile:131)at p1.h0.a(SourceFile:3)at p1.J.v0(SourceFile:131)at p1.E.M(SourceFile:17)at p1.E.N(SourceFile:18)at p1.Q.c(SourceFile:8)at p1.Q.m(SourceFile:138)at p1.Q.j(SourceFile:93)at q1.s.s(SourceFile:36)at q1.s.dispatchDraw(SourceFile:15)at android.view.View.draw(View.java:23021)at android.view.View.updateDisplayListIfDirty(View.java:21885)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21838)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21838)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21838)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21838)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21838)at android.view.View.draw(View.java:22743)at android.view.ViewGroup.drawChild(ViewGroup.java:4542)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)at android.view.View.draw(View.java:23021)at com.android.internal.policy.DecorView.draw(DecorView.java:891)at android.view.View.updateDisplayListIfDirty(View.java:21885)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4657)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4375)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3486)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2277)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9037)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)at android.view.Choreographer.doCallbacks(Choreographer.java:946)at android.view.Choreographer.doFrame(Choreographer.java:875)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:210)at android.os.Looper.loop(Looper.java:299)at android.app.ActivityThread.main(ActivityThread.java:8293)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by T8RIN** [comment]
How? and where
