### ISSUE TITLE
Image Stitching Failing Without Error [Device/Android Version Specific?]

### ISSUE THREAD

**Issue by OkyDooky** [T8RIN/ImageToolbox#1344]
**Describe the bug**
When attempting to save the stitched image, it will "succeed" and the toast message says "Saved to Documents/ResizedImages folder with name .jpg" (or .png or whatever I pick) and no file shows up when I switch to my gallery app.
This doesn't happen with every set of images, but there have been more than one set that this has happened on. Each set was a different type and number of images.

**To Reproduce**
I'm honestly not sure. It seems to do this on a lot of combinations, but I have had success before with this version of ImageToolbox (52 FOSS).

**Expected behavior**
It would output an actual file.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto G7 Supra (variant of Power)
 - OS: Android 9

Tested some images that failed on Supra and they worked on the Power (which is running Lineage 20/Android 13) and would give the same message, but an "_.png" would be the result when looking at my gallery app.

**Comment by T8RIN** [comment]
Can't reproduce it on my latest build, just no way

**Comment by OkyDooky** [comment]
That's unfortunate. I guess that means that, unless something miraculously changes, I'll have to only do stitching on my device that has Lineage on it. :/

**Comment by T8RIN** [comment]
This is suspicious

**Comment by OkyDooky** [comment]
After doing some more testing I discovered this is not specific to this app. For some reason, they were being ignored by the Gallery app because of not having a clear filename (I assume). But, they were visible in the file browser.
I don't think the Gallery app is having this problem still and the ability to manually decide the name when exporting has also solved this issue.

So, I think this can be considered fully closed and can be forgotten about. Thanks for being patent with me.
