### ISSUE TITLE
Inadequate consideration of image size when comparing images. 

### ISSUE THREAD

**Issue by Tseshongfeeshur** [T8RIN/ImageToolbox#1355]
**Describe the bug**
I have two images of different sizes, one of which is less than the width of my phone's screen. When I try to use the Compare Pictures feature in the software, the software doesn't handle the pictures with sufficient consideration for size, making one smaller and one larger. I've included those two images and the screen recording of the comparison as an attachment for your reference. Thank you for your efforts and contributions! I use DeepL to translate, so please forgive me if there may be inappropriate statements.

**To Reproduce**
Just use the two images I provided as attachments.

**Expected behavior**
Correct "comparison" behavior. That is, making two images equal in size.

**Screen Recording Video and Attachment**
[Click Here](https://drive.google.com/drive/folders/1_hxZcR3gXPorQzD87X90Zq9cZGefVUbk)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 12X
 - OS: Pixel Experience with Android 13

**Comment by T8RIN** [comment]
It's intended behavior

**Comment by T8RIN** [comment]
Just use different compare mode if this doesn't fit you, fe side by side is scaling up
