### ISSUE TITLE
JXL to JPEG isn't lossless

### ISSUE THREAD

**Issue by jonnyawsom3** [T8RIN/ImageToolbox#1363]
**Describe the bug**
JPEG transcoding should be bit-identical, but these additional EXIF tags are being added
```[File]          ExifByteOrder                   : Big-endian (Motorola, MM)
[IFD0]          ImageWidth                      : 1280
[IFD0]          ImageHeight                     : 960
[IFD0]          Orientation                     : Unknown (0)
[ExifIFD]       LightSource                     : Unknown
```

**To Reproduce**
Use JPEG to JXL, or cjxl on a JPEG
Use JXL to JPEG in ImageToolbox
Run djxl on the same JXL to JPEG
Compare filesize and hashes of JPEGs

**Expected behavior**
Same filesize and hash as the original file

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 10 Pro
 - OS: EMUI 12 (Android 10)

**Comment by T8RIN** [comment]
This better to address for libjxl or jxl-coder libs

**Comment by T8RIN** [comment]
I'm not controlling this

**Comment by jonnyawsom3** [comment]
Made an upstream issue https://github.com/awxkee/jxl-coder/issues/20
