### ISSUE TITLE
Some AVIF Images Require 'Share' Option for Viewing in Different Viewers

### ISSUE THREAD

**Issue by sojuo** [T8RIN/ImageToolbox#1374]
**Describe the bug**
Some AVIF images from ImageToobox display correctly in [Aves](https://github.com/deckerst/aves) and other viewers. However, some require selecting the “Share” option and then opening with Aves to view as a video with a 0-second duration.

**To Reproduce**

1. Generate AVIF images using ImageToobox.
2. Open the images in Aves.
3. For certain images, select “Share”.
4. Open with Aves.

**Expected behavior**
All AVIF images should be viewable directly in various image viewers, including Aves, without needing to use the 'Share' option.

**Files**
[files.zip](https://github.com/user-attachments/files/17212634/files.zip)

Previewing:
![Unedited1](https://web.archive.org/web/20240924134044im_/https://github.com/T8RIN/ImageToolbox/raw/master/fastlane/metadata/android/en-US/images/logo/logo.png)
![edited-aviflossess-abnormal1](https://files.catbox.moe/3uavs8.avif)
![edited-aviflossy-abnormal1](https://files.catbox.moe/d6nun4.avif)
![Unedited2](https://files.catbox.moe/wiibj0.png)
![edited-aviflossy-normal2](https://files.catbox.moe/5338ux.avif)
![Unedited4](https://files.catbox.moe/5g9ma6.jpg)
![edited-aviflossy-normal4](https://files.catbox.moe/gy463i.avif)
![edited-aviflossy-normal4](https://files.catbox.moe/gy463i.avif)

**Screenshots**
![Aves](https://files.catbox.moe/pmsh9q.avif)
![Forkgram](https://files.catbox.moe/agvk5e.avif)
**Smartphone (please complete the following information):**
 - Device: Redmi K40
 - OS:MIUI-V13.0.7.0.SKHCNXM

**Comment by T8RIN** [comment]
Maybe something wrong with aves?

**Comment by T8RIN** [comment]
I don't use that software, but any other gallery opens normally

**Comment by T8RIN** [comment]
Okay, i'm just tried aves, and all of your images showing normally

**Comment by sojuo** [comment]
> Okay, i'm just tried aves, and all of your images showing normally

Perhaps it's a problem with my phone's operating system? I'll try checking on another device.

**Comment by sojuo** [comment]
> Okay, i'm just tried aves, and all of your images showing normally

https://github.com/deckerst/aves/issues/895#issuecomment-1926415328

It seems that the limited support for AVIF in standard Android codecs is why some applications using these codecs cannot display all AVIF images correctly. However, you mentioned that your images display properly in Aves, which is somewhat confusing.

**Comment by sojuo** [comment]
> Idk 🐸 anyway i can close it right?

Did you get the software from F-Droid or from somewhere else? I got my Aves from F-Droid.

**Comment by T8RIN** [comment]
I downloaded it from the play store as i remember

**Comment by sojuo** [comment]
> I downloaded it from the play store as i remember

https://github.com/deckerst/aves/wiki/App-Versions
Maybe that's why your Aves view all AVIF images properly? If I have time, I'll see what the difference is between the Aves on the Play Store and the Aves on F-Droid. But I don't have time right now, I just want to go to sleep as soon as possible. Zzzzzzzzzzz(This user is trying his best to send the letter "Z" to indicate that it has fallen asleep.)
