### ISSUE TITLE
Shortcuts to homescreen

### ISSUE THREAD

**Issue by StioStudio** [T8RIN/ImageToolbox#1375]
**Is your feature request related to a problem? Please describe.**
The problem is that all the tools are only available in the app, and can't be found without navagating in the app. I really would like the qr-code reader!

**Describe the solution you'd like**
Home screen shortcuts.

**Describe alternatives you've considered**
Tried activities

**Comment by T8RIN** [comment]
Added

**Comment by StioStudio** [comment]
That was fast
