### ISSUE TITLE
Blurry Output and Preview Issues in Lossless Stitching

### ISSUE THREAD

**Issue by sojuo** [T8RIN/ImageToolbox#1379]
**Describe the bug**
A problem has been identified with the image stitching feature in Image Toolbox. Selecting the lossless option results in blurry stitched images that remain unclear even when zoomed in. Additionally, images viewed in Image Toolbox appear very blurry, and this issue also occurs in other image viewers such as [Aves](https://github.com/deckerst/aves), [Fossify Gallery](https://github.com/FossifyOrg/Gallery), and [Gallery](https://github.com/IacobIonut01/Gallery). However, when these images are uploaded to an image hosting service and viewed in a browser like [Mull](https://gitlab.com/divested-mobile/mull-fenix), they appear clear. This suggests an issue with how Image Toolbox processes or displays images compared to standard web browsers.

**To Reproduce**
Useing Image Stitching.
View the image.

**Expected behavior**
Expected Lossless Stitching to Produce Clear Output.
View it in Image Toolbox.

**Files**
[files.zip](https://github.com/user-attachments/files/17229254/files.zip)
![output](https://files.catbox.moe/0ov481.avif)

**Smartphone (please complete the following information):**
 - Device: Redmi k40
 - OS:MIUI-V13.0.7.0.SKHCNXM

**Comment by T8RIN** [comment]
I cannot open large images directly, it will cause crashes and OOM's so they downsampled

**Comment by T8RIN** [comment]
thats's limitation of android

**Comment by sojuo** [comment]
> thats's limitation of android

That is, it is difficult for me to view larger images locally on Android? Besides uploading the image to the image bed and opening it in the browser, is there any other convenient way, or is there any fully open source image viewer that can view larger size images on Android devices?

**Comment by T8RIN** [comment]
It can be achieved for several formats, but others just have no option to decode images by regions, so for now it's not achievable, at least in my app
