### ISSUE TITLE
Minor Misspelling

### ISSUE THREAD

**Issue by BurningButter** [T8RIN/ImageToolbox#1383]
**Describe the bug**
The *Cipher* option on the *Tools* tab includes a misspelling of the word algorithm as "algorythm" in five of the available languages: English, French, Arabic, Filipino, or Uighur.

**To Reproduce**
Open app on any platform and set your language to either English, French, Arabic, Filipino, or Uighur.
Navigate to the *Tools* tab to view the misspelling.

**Expected behavior**
The word is spelled correctly as "algorithm" in each these five languages' `strings.xml` file located at `core/resources/src/main/res/values-LANGUAGECODE/strings.xml`

**Screenshots**
![imagetoolbox-screenshot](https://github.com/user-attachments/assets/a4e339c5-6c93-4995-9e18-0bf1ecc95297)

**Smartphone (please complete the following information):**
 - Device: Galaxy A13 5G
 - OS: Android 13

**Comment by T8RIN** [comment]
Done

**Comment by T8RIN** [comment]
Also you can update to latest 3.0.0 version 😄
