### ISSUE TITLE
[Feature Request]: Remove inbuild animations & unnecessary graphics 

### ISSUE THREAD

**Issue by HusniMuhammad** [T8RIN/ImageToolbox#1388]
**Is your feature request related to a problem? Please describe.**

* To improve performance on low processing devices 
Looks very buggy on my device (not stable) even opening of this app

**Describe the solution you'd like**

Remove "animations & unnecessary graphics (shadows rendering of app UI" of this inbuild app as option to settings section of this disable or fully removing this 

**Describe alternatives you've considered**

NO

**Comment by T8RIN** [comment]
You can disable shadows in settings

**Comment by T8RIN** [comment]
Other options is not possible

**Comment by HusniMuhammad** [comment]
> You can disable shadows in settings

Ok thanks for your advice

**Comment by HusniMuhammad** [comment]
> You can disable shadows in settings

Is this normal?
Apk from latest releases & foss variant

![Screenshot_20241011-041853](https://github.com/user-attachments/assets/ba410179-8a93-45e4-b66e-c74b44c74419)

**Comment by HusniMuhammad** [comment]
1728601388.520 10010  6559  6559 W resizershrinke: Using default instruction set features for ARM CPU variant (generic) using conservative defaults
1728601388.529 10010  6559  6559 E resizershrinke: Not starting debugger since process cannot load the jdwp agent.
1728601392.270 10010  6559  6580 E OpenGLRenderer: reset ##### pid = 6580
1728601392.488 10010  6559  6559 E Dialog  : show dialog view=DecorView@50053fa[AppActivity]
1728601412.523 10010  6559  6559 E Dialog  : show dialog view=DecorView@877725[AppActivity]
1728601416.820 10010  6559  6967 E RenderScript: Failed loading RS driver: dlopen failed: library "" needed or dlopened by `"/apex/com.android.vndk.v30/lib/libRS_internal.so" is not accessible for the namespace "rs"
1728601416.820 10010  6559  6967 E RenderScript: Failed to load runtime , loading default
1728601417.741 10010  6559  6574 W System  : A resource failed to call destroy.
1728601417.742 10010  6559  6574 W System  : A resource failed to call destroy.
1728601422.378 10010  6559  6559 E Dialog  : show dialog view=DecorView@7bf19d7[AppActivity]
1728601422.959 10010  6559  6574 W System  : A resource failed to call destroy.
1728601422.960 10010  6559  6574 W System  : A resource failed to call destroy.
1728601424.128 10010  6559  6574 W System  : A resource failed to call release.
1728601431.560 10010  6559  6574 W System  : A resource failed to call release.
1728601416.820 10010  6559  6967 E linker  : library "" ("/apex/com.android.vndk.v30/lib") needed or dlopened by "/apex/com.android.vndk.v30/lib/libRS_internal.so" is not accessible for the namespace: [name="rs", ld_library_paths="", default_library_paths="/apex/com.android.vndk.v30/lib:/vendor/lib", permitted_paths="/odm/lib:/vendor/lib:/system/vendor/lib:/data"]
