### ISSUE TITLE
SVG to raster conversion improvement

### ISSUE THREAD

**Issue by l2nkxk8z** [T8RIN/ImageToolbox#1391]
**Is your feature request related to a problem? Please describe.**
I've tried converting an SVG image to PNG and got terrible results.

**Describe the solution you'd like**
Integrate librsvg or lunasvg library for conversations.

**Describe alternatives you've considered**

**Comment by T8RIN** [comment]
And what's wrong with conversion? Some examples maybe?

**Comment by l2nkxk8z** [comment]
Sorry. it comes out blurry. I think the problem may be resizing, by default it was 200x200 and I changed it but 200x200 didn't seem ideal either, not sure if some scaling mode fixes is this but I've head a very similar result with graphicsmagick. here's an example:

SVG
![cromite2](https://github.com/user-attachments/assets/31a275db-4baa-4bc0-9b98-cd71e8aaa320)

PNG imagetoolbox
![q5ejoEOMjb3L2ul68iRN2ELrGuG11rZC](https://github.com/user-attachments/assets/337b10d7-9eb4-4716-8c11-b53021b2b1f9)

PNG librsvg
![cromitersvg](https://github.com/user-attachments/assets/2a9a9526-e62d-4b02-873e-e610bfeef3ee)

**Comment by T8RIN** [comment]
You large image output, svg needs more space to draw normally

**Comment by T8RIN** [comment]
You need to set large image output, svg needs more space to draw normally

**Comment by l2nkxk8z** [comment]
Not sure what you mean by image output, I did change height and width to same one as rsvg. are you talking about something else?

**Comment by T8RIN** [comment]
I'm about size, try 1000*1000 i can't change the Library btw

**Comment by T8RIN** [comment]
I have troubles with compiling native libraries by ndk, but if there's pre compiled one with jni bindings, i can add this easily

**Comment by T8RIN** [comment]
😢

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by T8RIN** [comment]
Okay, there is no issue in tracer, and no issue at all, just image loads at original size, which is defined in svg itself, and then upscales, i think something can be done on my side to load svg immediately for requested size

**Comment by T8RIN** [comment]
should be ok now

**Comment by T8RIN** [comment]
a bit hacky, but works (just loading at higher resolution initially)
