### ISSUE TITLE
In Conversion Menu, Swap Places of "Quality" and "Image Format" Sections

### ISSUE THREAD

**Issue by OkyDooky** [T8RIN/ImageToolbox#1392]
**Is your feature request related to a problem? Please describe.**
Currently, I have to scroll back-and-forth (up and down) repeatedly whenever I convert something. Example being PNG to JPG using Jpegli or MozJpeg, I have to scroll down to select JPG and then again to select Jpegli or MozJpeg, then all the way back up to change the quality. Same with Jpeg XL lossy, because doing so changes the options in the "Quality" section and that moves the display back up a bit.

**Describe the solution you'd like**
Swap the order in which the "Quality" and "Image Format" sections are displayed. This will eliminate the back-and-forth scrolling during most conversions and will follow a more linear and logical flow, since the options in the "Quality" section are directly dependent on what is selected in the "Image Format" section (eg Jpeg XL) and subsection ("Compression Type", eg Lossless or Lossy). It would follow the hierarchy that's under the hood.

**Describe alternatives you've considered**
I've considered suggesting to make the display not move location when the options in the "Quality" section are changed by what I select in the "Image Format" section, but that might be more work on your end and wouldn't reduce  the amount of back-and-forth scrolling nearly as much.

![Stitch192643e06b9](https://github.com/user-attachments/assets/ee4d494d-237d-415b-8a2b-94ba9d2ee74c)

**Comment by OkyDooky** [comment]
Thanks!

**Comment by OkyDooky** [comment]
I tried it out and it works great. Feels much more intuitive. However, I noticed it's only changed for the Format Conversion section and nowhere else. Would it be better to swap it in the rest of the menus for consistency? Or do you prefer having it the original way in the other sections?

**Comment by T8RIN** [comment]
For now yes👀

**Comment by OkyDooky** [comment]
I see. Kind of doing a trial/test to see if would be better or not, in the long run?

**Comment by T8RIN** [comment]
Idk🐸
