### ISSUE TITLE
[Feature request]: Imaginary grid for better drawing 

### ISSUE THREAD

**Issue by HusniMuhammad** [T8RIN/ImageToolbox#1396]
**Is your feature request related to a problem? Please describe.**

For better drawing 

**Describe the solution you'd like**
Add imaginary gride 

![Screenshot_20241008-230638](https://github.com/user-attachments/assets/667fd763-2ee9-45ad-b86e-a1697cf166a6)

![Screenshot_20241008-230628](https://github.com/user-attachments/assets/99b4d2e9-6c41-437e-a360-2204a1fe9354)

**Describe alternatives you've considered**
No

**Comment by HusniMuhammad** [comment]
Is it anyway to install this updated apk

Or waiting for release?

**Comment by T8RIN** [comment]
You can download from actions, but it's really unstable

**Comment by HusniMuhammad** [comment]
> You can download from actions, but it's really unstable

![Screenshot_20241011-040124](https://github.com/user-attachments/assets/bc8c16ca-e65b-4430-a5ce-b4175d163d79)

Why all of them archivied? 
not separate apks to download

**Comment by T8RIN** [comment]
Cause that's the process 👀

**Comment by HusniMuhammad** [comment]
> Cause that's the process 👀

Is it possible to change workflow to show unarchived apks

![Screenshot_20241011-041110](https://github.com/user-attachments/assets/c5e7b1b7-3a2d-456f-906e-103a83f387ef)

Like this naming scheme

**Comment by HusniMuhammad** [comment]
> Nope, i need exactly archives for me it's useful

Ok
