### ISSUE TITLE
[Bug] Settings may not be clickable

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#140]
https://user-images.githubusercontent.com/51242302/231580591-6e1842ce-5998-4fca-a8ba-d718fe8977e3.mp4

Here is a video.

System:HarmonyOS 2.0（Android 10）
Version:1.9.8（F-Droid）

**Comment by T8RIN** [comment]
That is because you tapped too many times, and background tasks of changing your prefs started...

**Comment by Jesse205** [comment]
> That is because you tapped too many times, and background tasks of changing your prefs started...

@T8RIN
But there will be a lot of changes when adjusting the border, which can easily get stuck in the software

https://user-images.githubusercontent.com/51242302/231670066-bd596db4-688b-42a7-b91c-c3ff1aa5dff6.mp4

**Comment by T8RIN** [comment]
Oh, that's bad, i will check later if there is a solution...

**Comment by T8RIN** [comment]
I can't even reproduce it (

https://user-images.githubusercontent.com/52178347/231828934-079071aa-e513-4a16-8e6f-e5302d670beb.mp4

**Comment by Jesse205** [comment]
> I can't even reproduce it (
> 
> https://user-images.githubusercontent.com/52178347/231828934-079071aa-e513-4a16-8e6f-e5302d670beb.mp4
> 
> 

My Redmi Note 11, Android 12 also has this problem, this bug may require an older version of the android system, or a slightly slower processor processing speed

**Comment by T8RIN** [comment]
I'm also tested on sony Xperia zr, which has android 5, all works fine...

**Comment by Jesse205** [comment]
> I'm also tested on sony Xperia zr, which has android 5, all works fine... 

https://user-images.githubusercontent.com/51242302/233550174-7e77891a-fb50-4449-a04a-d3b238c6d9db.mp4

I just updated to the latest version and now the whole app is stuck

**Comment by T8RIN** [comment]
Maybe i know the possible solution, I will add this in the new version

**Comment by T8RIN** [comment]
Check the new release

**Comment by Jesse205** [comment]
> Check the new release 

The new version executes the task after the user has finished dragging. This approach alleviates this aspect, but I think there are still potential problems.

https://user-images.githubusercontent.com/51242302/233676667-741c342d-78ff-4999-a398-2677b699ccac.mp4

**Comment by T8RIN** [comment]
Weird... I have now idea now how to fix it, because your devices doesn't feel to be slow

**Comment by Jesse205** [comment]
Hello, I have made two new discoveries.

After 2.1.0, after multiple consecutive operations, the software will not freeze.

And versions 2.0.5 and earlier are more likely to reproduce this issue after clearing data.

https://github.com/T8RIN/ImageToolbox/assets/51242302/49eec9a6-e68c-4375-a4ac-9805a66e206f

This video is too large, so I did some resolution reduction and acceleration processing.

**Comment by T8RIN** [comment]
Maybe bumping libraries worked, cause i literally didn't change anything :)

**Comment by T8RIN** [comment]
So, that's fixed, i think?
