### ISSUE TITLE
how to Offline download auto erase subject segmentation  optional module 

### ISSUE THREAD

**Issue by avkiller** [T8RIN/ImageToolbox#1412]
**Is your feature request related to a problem? Please describe.**

use auto erase background  can not be 
![Screenshot_20241016_092258_ru tech imageresizershrinker](https://github.com/user-attachments/assets/2b1bdacf-14e8-4af3-96e3-8b017e202743)
download  segmentation optional module  

maybe huawei mobile user can not be use gms 
Download module requires gms？

**Describe the solution you'd like**
offline download and import by user

**Describe alternatives you've considered**

**Comment by T8RIN** [comment]
No way, also which version it is? I thought that i managed to use a worse embedded version while better one is both the downloaded
