### ISSUE TITLE
Edit metadata (EXIF) without re-encoding image

### ISSUE THREAD

**Issue by keturn** [T8RIN/ImageToolbox#1423]
Currently, it seems like metadata (EXIF/XMP) editing is offered only as part of the Resize & Convert tool. Saving it then re-encodes the image, with new encoder settings.

It'd be nice to be able to edit only the metadata without any change to the image data at all, especially for lossy formats where re-encoding would degrade the image.

(Ideally, I hope to edit or remove some metadata while leaving the [HDR gain map](https://developer.android.com/media/platform/hdr-image-format) intact, which is also stored in XMP.)

**Comment by T8RIN** [comment]
https://github.com/T8RIN/ImageToolbox/commit/71245562cad5bf073c3da4b8ca19e72b5f4dbdcf

**Comment by keturn** [comment]
Dang you're fast! Committed three days before I even asked!

**Comment by T8RIN** [comment]
Someone asked before you :)

**Comment by T8RIN** [comment]
shoul this be closed?

**Comment by T8RIN** [comment]
Okay, will close :)

**Comment by calculus-dbg** [comment]
With that commit, there is no re-encoding for deleting exif. Editing exif still re-encodes the image. Could this be changed, too? ❤️

**Comment by T8RIN** [comment]
No, there is no way to do that

**Comment by calculus-dbg** [comment]
> Only if there will be separate tool specifically to edit exif

which might be a good idea? :)
You could combine it with the existing deleting tool.

**Comment by T8RIN** [comment]
I will think, anyway you can create an issue about adding this tool, i can forget
