### ISSUE TITLE
''Bypass'' filter

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#1426]
Filter chains and imagetoolbox are quite powerful. However, when they are applied, sometimes it's useful to bypass one filter in the chain, to see the effect of a single filter in a chain. It would be nice to have a toggle that can bypass the filter temporarily without the need to delete it. A use case is for example that some filters have similar effects like exposure and Mobius. If the uses one filter is not needed it can be removed or kept muted (e.g. in templates) to achieve different results.

**Comment by T8RIN** [comment]
This can be transformed into controlling filter visibility, i think this will be added

**Comment by T8RIN** [comment]
Like toggle visible/invisible

**Comment by T8RIN** [comment]
But idk where to place this button

**Comment by devSJR** [comment]
@T8RIN just on the right side?

**Comment by T8RIN** [comment]
There is a button to expand/hide or value entering button

**Comment by devSJR** [comment]
@T8RIN True, I didn't keep this in mind. Maybe in the middle then?

**Comment by T8RIN** [comment]
Will look not usual in my opinion

**Comment by T8RIN** [comment]
I think about the left, with the remove button, or there dots, with hidden options to hide/show and remove
