### ISSUE TITLE
Auto BG Removing improvement!

### ISSUE THREAD

**Issue by debashishsahu9t8** [T8RIN/ImageToolbox#1431]
Hi I have tried using the background removing feature in the app, but the manual doing is quite difficult in a mobile, although you have provided the **auto bg removing** feature but sorry to say it's lacking very much, it's not good enough 😕! Please improve it 🙏

**Comment by T8RIN** [comment]
it better ask google to improve their subject segmenter

**Comment by T8RIN** [comment]
i cannot change anything in this case :(
