### ISSUE TITLE
High bitdepth RAW conversion

### ISSUE THREAD

**Issue by jonnyawsom3** [T8RIN/ImageToolbox#1439]
Not sure if it's possible, but being able to get the original bitdepth from RAW files would be nice inside of 8.

I know the compression is usually 16bit for this, which is fine, but there's also metadata with the real size inside for codecs that can handle specific depths to shave off some bytes.

**Comment by T8RIN** [comment]
Idk if it's possible, all in the app based in fact that bitmaps i use is 8 bit, or converted to it

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by jonnyawsom3** [comment]
Huh, well that was a first... Never seen a scam bot use a ReCaptcha as an attack. Anyway, no worries if it's not possible, just a thought I had

**Comment by T8RIN** [comment]
I think it's not possible, at least for now :(
