### ISSUE TITLE
Background remover 

### ISSUE THREAD

**Issue by harshkai** [T8RIN/ImageToolbox#1443]
****Describe the bug****
Photos background remover has a error like when I remove the background the the removed area are fully backed not removed 

**To Reproduce**

****Expected behavior****
See the IMG that some areas are removed but it's not removed it's blacked 

**Screenshots**
![Screenshot_20241029_063404](https://github.com/user-attachments/assets/57cbaaad-7b3f-4cff-9435-fb0ff695c4a6)

**Smartphone (please complete the following information):**
 - Device:   IQOO Z6 lite 
 - OS: android

**Comment by Skivling** [comment]
You need to make sure you're exporting to an image format that supports transparent-ification of backgrounds, like a PNG. If you're exporting to JPG that doesn't support transparent backgrounds so it defaults to black.
