### ISSUE TITLE
EXIF option to rename images with random names

### ISSUE THREAD

**Issue by quadratz** [T8RIN/ImageToolbox#1447]
Filenames can sometimes reveal the date and time a photo was taken, which can be a privacy concern. It would be great to have an option to rename all shared images with a random filename.

This could be similar to how [Scrambled Exif](https://gitlab.com/juanitobananas/scrambled-exif) renames files using the hash of each individual file.

**Comment by T8RIN** [comment]
You can enable random filenames in settings

**Comment by quadratz** [comment]
That could work, but since that feature is applied globally, including for image editing, it might be more convenient to have the option scoped. This way, we wouldn’t have to keep toggling it on and off while editing to maintain the original file name, or when clearing the EXIF, where we’d want to randomize the name.

**Comment by T8RIN** [comment]
Not globally thing is not possible :(
