### ISSUE TITLE
🟢 (#1454) NEW TOOLS

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1454]
Please add these new tools:
- [ ] 1. Tool to upscale images (2x, 4x, 8x, ...).
- [ ] 2. Tool to add a stroke (outline) around an object or multiple objects.
- [ ] 3. Extract Object by Color from Image: Quickly select any object in the image and extract it by its color.
- [x] 4. Tool to increase space around image (+ ability to change the color of that space).

**Comment by T8RIN** [comment]
4 already exists, use crop resize mode

**Comment by T8RIN** [comment]
1: no, there were issues about that, explained inside

**Comment by T8RIN** [comment]
2 and 3 same reason as first
