### ISSUE TITLE
Can't uninstall, "installer keeps stopping" error.  Broken app install.

### ISSUE THREAD

**Issue by Leif-W** [T8RIN/ImageToolbox#1456]
**Describe the bug**

Can't uninstall, "installer keeps stopping" error.  Broken app install.

**To Reproduce**

Install app (3.0.0 from F-Droid, 3.1.0-??? from GitHub).  Try to uninstall.  It won't uninstall.

**Expected behavior**

Uninstall when I click uninstall.  I've installed and uninstalled several other apps today without incident.  Restarted phone, same, no change.  Tried using F-Droid and Android Settings -> Apps, both fail.  F-Droid looks hung but Android Apps fails instantly saying `Package installer keeps stopping`.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: SM-N986U1
 - OS: Android / latest update for October 2024 / OneUI 5.1 / Android 13

**Comment by T8RIN** [comment]
I can't control the process of uninstalling, i think it's not really related to my app

**Comment by Leif-W** [comment]
Everything uninstalled normally until this app.  Now 2 other apps (Krita and Krira nightly) can't uninstall.  This app seems to have broken something.  Irresponsible to not even explore.  Maybe an interaction with this app and F-Droid that triggered it.  Who knows.  Doesn't gain any trust for app dev.

**Comment by T8RIN** [comment]
Investigating your firmware bugs is unrelated to my app at all
