### ISSUE TITLE
x86 minsdk21 not pass load screen

### ISSUE THREAD

**Issue by nalcwap** [T8RIN/ImageToolbox#1458]
**x86 minsdk21 not pass load screen**

**To Reproduce**

**app working**

**Screensh
![Screenshot 2024-11-06 111343](https://github.com/user-attachments/assets/e362265d-0d90-43ee-baed-e1ccc969d7e0)
ots**

**Smartphone (please complete the following information):**
 -lg devixe x86
 - 5.02
please fix app not work,you can test this bug in emulator to ldplayer 5.1 same bug not pass this screen

**Comment by T8RIN** [comment]
Supporting corner cases on android emulators with sdk 21 is very low priority, so this will not be fixed because idk what and why

**Comment by T8RIN** [comment]
Download newer emulator
