### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by ExidusGIT** [T8RIN/ImageToolbox#1465]
Device: SM-S908B (samsung - b0s), SDK: 34 (14), App: 3.1.0-beta02 (155)java.lang.NullPointerException: Expected to unbox a 'boolean' primitive type but was returned nullat $Proxy2.isVisible(Unknown Source)at Re.B.a(SourceFile:1)at wf.f.x(SourceFile:753)at wf.d.v(SourceFile:17)at ma.a.k(SourceFile:9)at Ub.B0.p(SourceFile:54)at Ub.a.k(SourceFile:23)at ma.a.k(SourceFile:32)at Ub.B0.p(SourceFile:54)at Ub.a.k(SourceFile:23)at ma.a.k(SourceFile:32)at Ub.H.run(SourceFile:107)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)at java.lang.Thread.run(Thread.java:1012)Suppressed: Zb.e: [r0{Cancelling}@669290a, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
Fixed already, will be in next beta
