### ISSUE TITLE
Croping doesn't work

### ISSUE THREAD

**Issue by Stzyxh** [T8RIN/ImageToolbox#1480]
**When I try to crop a image the image is not show/only a black picture**

**Reproduce**
Open image in Imagetoolbox and select tool "croping". 

**Expected behavior**
Black image is shown. 

**Screenshots**
![Screenshot_20241116-150148.png](https://github.com/user-attachments/assets/6f0173e9-733b-4c34-9955-097f3dd31e18)

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 13

**Comment by T8RIN** [comment]
app version?

**Comment by Stzyxh** [comment]
> app version?
> 

3.1 RC 1

**Comment by T8RIN** [comment]
also what if you choose crop shape mask, will it change?

**Comment by Stzyxh** [comment]
> Which image you are trying to crop?
> 

A png

**Comment by Stzyxh** [comment]
> also what if you choose crop shape mask, will it change?
> 
Oh yeah then it works

**Comment by T8RIN** [comment]
okay makes sense

will fix soon

**Comment by T8RIN** [comment]
Should work now, check the latest CI build

**Comment by Stzyxh** [comment]
> Should work now, check the latest CI build

How to download

**Comment by Stzyxh** [comment]
Oh wait i found it
