### ISSUE TITLE
F-Droid AF (disable GitHub connecting in FOSS version on start)

### ISSUE THREAD

**Issue by linsui** [T8RIN/ImageToolbox#1491]
**Describe the bug**

https://gitlab.com/fdroid/fdroiddata/-/jobs/8455700094 Reproduicble build failed because the embeded timestamp. Could you please fix it? See 
https://f-droid.org/docs/Reproducible_Builds/#aboutlibraries-gradle-plugin.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 
 - OS:

**Comment by T8RIN** [comment]
Okay

**Comment by T8RIN** [comment]
done, should i release next version then?

**Comment by linsui** [comment]
Yes, thanks!

**Comment by IzzySoft** [comment]
Thanks @linsui – to the point! The `M7.json` always rings a bell, right? :rofl: OK, so we then also just wait for the new release with our RB at IzzyonDroid. Thanks to both of you!

**Comment by T8RIN** [comment]
But, I haven't connected to GitHub for graphics for a long time, also beta updates disabled by default in foss version

**Comment by T8RIN** [comment]
Also, update checking is triggered by the user btw, so how can this be an anti feature?👀

**Comment by IzzySoft** [comment]
I can only guess: when those AF were added, your app checked for updates automatically and also downloaded graphics from Github. You might have changed that since, but didn't tell F-Droid or us – and those things cannot be checked automatically. So nobody knew to revisit this or to remove any AF.

To clarify:

* no graphics are loaded from Github anymore?
* update checks are strictly opt-in (and no self-updater is included)?

**Comment by T8RIN** [comment]
Yup, there is a description dialog on fisrt startup where the user can enable checking for updates

**Comment by linsui** [comment]
I just tested 3.0.0 and it still connects to github on start though checkupdate option is disabled by default.

**Comment by T8RIN** [comment]
Is it was foss version?

**Comment by T8RIN** [comment]
Maybe something is wrong here, so i will look

**Comment by T8RIN** [comment]
Okay, should be OK now :)

**Comment by linsui** [comment]
Thanks! Will check the next version and remove the AF.

**Comment by T8RIN** [comment]
3.1.1 is on the way

**Comment by linsui** [comment]
Now the checkupdate option is enabled by default and it still connects to github on start.

**Comment by T8RIN** [comment]
:/

**Comment by T8RIN** [comment]
I will look then

**Comment by T8RIN** [comment]
should be really ok now

**Comment by linsui** [comment]
Thanks, will test the next version. :)

**Comment by T8RIN** [comment]
After release? Or If you can, it's better to test first :)

**Comment by linsui** [comment]
It's fixed, thanks!

**Comment by T8RIN** [comment]
@linsui i asked if the trackers badge can be removed from the f-droid page, but it's still there :(

**Comment by linsui** [comment]
Ah, I didn't notice that the fixed version has been released. :) Do you remember when it stopped fetching graphics from GitHub? https://gitlab.com/fdroid/fdroiddata/-/merge_requests/18508

**Comment by T8RIN** [comment]
Idk for sure, but the version in f-droid should be fixed

**Comment by linsui** [comment]
OK, removed!

**Comment by T8RIN** [comment]
Thanks!
