### ISSUE TITLE
Suggestions + Errors

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1493]
# SUGGESTIONS:
- [x] 1. Add a tool to only change the quality (compress tool).
- [ ] 2. (Filter) tool: enable exporting/importing downloaded LUT filters.
- [x] 3. (Collage Maker) tool: Add button to restore the original position & zoom.
- [x] 4. (Pin tools to home screen as shortcuts):
(A) Add ability to change the color of the shortcut.
(B) ERROR: when opening the created shortcut (for example: (Single Edit) tool) it didn't open it, instead it just opens the main screen of the app.
- [ ] 5. Settings: add an option for (Back) key of navigation bar to choose between: (Closing App) or (Going back to the tools).

![(Back) key](https://github.com/user-attachments/assets/a1d06b16-f1e6-421b-99c2-e4469bdec608)

# ERRORS (latest version 3.1.0):
- [ ] 1. (Single Edit) tool: 4 tools not opening.

https://github.com/user-attachments/assets/b39f6711-f62d-4ebf-8c84-e2cd9b6c4d91

- [x] 2. (Background remover) tool: can't scroll down & view the (Draw Path Mode) tools.

https://github.com/user-attachments/assets/daceb123-39d2-403f-85c8-f8ee35fd8eba

**Comment by T8RIN** [comment]
could you check on another device? Also which phone are you using? because i can't reproduce first bug

**Comment by T8RIN** [comment]
didn't get the 5

**Comment by T8RIN** [comment]
2 didn't think it's neccessary as all luts laying in separate github repository and easy to access them

**Comment by T8RIN** [comment]
Which android version has a buggy device and device without issue?

**Comment by T8RIN** [comment]
> > 2 didn't think it's neccessary as all luts laying in separate github repository and easy to access them
> 
> Please send that link ..
> How to import all of them at once to inside the app ?
> If not possible to import them all at once, I think it would be nicer from you 🙂 to make this feature of export/import.

https://github.com/T8RIN/ImageToolboxRemoteResources/tree/main/cubelut

**Comment by T8RIN** [comment]
> > didn't get the 5
> 
> I attached an image for explanation.

It's not possible, it totally breaks navigation and leads to unexpected behavior

**Comment by T8RIN** [comment]
Download in the app👀

**Comment by T8RIN** [comment]
> > Which android version has a buggy device and device without issue?
> 
> Buggy device: Android 12
> Device without issue: Android 13

I'll take a look

**Comment by T8RIN** [comment]
I didn't get it unfortunately :(

**Comment by T8RIN** [comment]
Luts can be downloaded in the lut section, templates are not related

**Comment by T8RIN** [comment]
Download inside the app, there's a button

**Comment by T8RIN** [comment]
Good, you can also update to 3.1.1, there're new features and fixes
