### ISSUE TITLE
Feature request : Custom image splitter

### ISSUE THREAD

**Issue by czenon1** [T8RIN/ImageToolbox#1495]
Hi,

Firstly, thanks for this app ! It's a real powerhouse for mobile editing.

Would it be possible to add a custom image splitter, similar to the "collage" but to get separate images ?

It would be cool to get something customizable to put some cool cropped images in docs or making a grid on instagram profile.

Thanks,
C.

**Comment by T8RIN** [comment]
It's already available, use image splitter option
