### ISSUE TITLE
Unable to leave the Mask Filter screen

### ISSUE THREAD

**Issue by DZAladan** [T8RIN/ImageToolbox#1501]
**Describe the bug**
Leaving the Mask Filter screen is physically impossible

**To Reproduce**
Apply a mask on the image (4000 × 2250 first try, then 2000 × 1125), tap "Save". It reloads the preview, but never leaves the screen. Tapping the "Back" 
arrow then "Exit" also does nothing. If the app is processing something in background, it's giving no feedback.

**Expected behavior**
Mask Filter applied and return to the export screen.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Blackview BL8800
 - OS: Android 11 (Doke OS 2.0)

**Comment by T8RIN** [comment]
Yup, i know :( this is fixed in the latest ci build
