### ISSUE TITLE
Which version to Download?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [T8RIN/ImageToolbox#1511]
How can find out which app i have to download?

**Comment by T8RIN** [comment]
If you want to be 100% confident, download universal, but in most cases you need arm64

**Comment by Clemens-Ratte-Polle** [comment]
ImageToolbox should Show its version at about option

**Comment by T8RIN** [comment]
It's showing

**Comment by T8RIN** [comment]
The arch of the user's processor is the responsibility of user
