### ISSUE TITLE
Long screenshots are forced to scale

### ISSUE THREAD

**Issue by Pony-CW** [T8RIN/ImageToolbox#1515]
**Describe the bug**
Screenshots that are long enough to modify are scaled to an extremely blurry resolution
This bug appears in versions after 3.0.0, and ci builds don't fix it either
--DeepL translation

**To Reproduce**
Select a long enough screenshot, say 1080 x 18259, and when making changes it will somehow scale to 242 x 4096

**Expected behavior**
The resolution should be normal.

**Screenshots**
![Screenshot_2024-12-04-01-07-44-17_33b445981d13b98f91994c60df898715](https://github.com/user-attachments/assets/f97705ff-49f5-47d6-9e4b-02a937c87d92)
![Screenshot_2024-12-04-01-07-14-12_7c389b2ee94145b1ab3b976a49fd0291](https://github.com/user-attachments/assets/35a11345-4147-462d-8c0d-77069b3b82b0)

**Smartphone (please complete the following information):**
 - Device: OnePlus Ace Racing Edition
 - OS: ColorOS 14

**Comment by T8RIN** [comment]
It's not a bug, just defense from crashing, you can set normal resolution and it will be okay, anyway, which version are you used in the latest screenshot? It should load at least the size of the original

**Comment by Pony-CW** [comment]
Now is https://github.com/T8RIN/ImageToolbox/commit/027f6108bc2c57dc0849c8a81ef8914214c1e015, Still not loading the original size
> --- DeepL translation

**Comment by T8RIN** [comment]
![ResizedImage_2024-12-05_18-09-25_8058.png](https://github.com/user-attachments/assets/4a1418ea-54a7-4e7b-a73e-67c7f7b09375)

I think it's the key

**Comment by T8RIN** [comment]
Should be ok now

**Comment by Pony-CW** [comment]
It's OK now. Thanks.
