### ISSUE TITLE
Add "Privacy blur" option to obfuscate portions of images

### ISSUE THREAD

**Issue by Zeit08** [T8RIN/ImageToolbox#1519]
Your app is totally amazing and can replace many other apps - now I get why it is called _toolbox_ :)

I think a great addition many will appreciate is to add a function of apps like this: https://github.com/MATHEMA-GmbH/privacyblur into your _toolbox_

Basically it is for quickly drawing a circle or rectangle on an image to hide a face or a plate, but in this case the shape is blurred (or black color is also ok).

**Comment by T8RIN** [comment]
Its added already and exists almost a year👀

**Comment by T8RIN** [comment]
Also you can check in readme which features are present
