### ISSUE TITLE
Constant Popup "ImageToolbox in Telegram"

### ISSUE THREAD

**Issue by 85pando** [T8RIN/ImageToolbox#1526]
**Describe the bug**
There is a popup in the app, that is spawned
- on every interaction in the settings
- sometimes when editing images (harder to specify when exactly here)

**To Reproduce**
- change a setting in the settings
- use ImageToolbox to edit images

**Expected behavior**
Popup might be spawned once, but then either should not come again or have a checkbox to disable this popup.
I a person wants to join a Telegam chat, they can later do so via the button in the settings.
Also the popup does not have a "dismiss" or "cancel" button.

**Screenshots**
![image](https://github.com/user-attachments/assets/4af6e68d-db48-41e9-b046-d3fa7532b534)

**Smartphone (please complete the following information):**
 - Device: Pixel 7a
 - OS: GrapheneOS (Android 15)
 - ImageToolbox installed via F-Droid

**Comment by T8RIN** [comment]
It should disappear if you click buttons to redirect

**Comment by 85pando** [comment]
Yes, they dissappear, when
- clicking on of the redirect buttons
- clicking anywhere outside of the notification.
But the popup is spanwed again, when changing another (or the same) setting again. So any interaction in the settings and many regular actions in the APP will trigger the popup again and again and again.

**Comment by 85pando** [comment]
Also I can not reproduce on second device. So I guess we'll book this as once-off-strange behaviour.

**Comment by licaon-kter** [comment]
I can reproduce this, every second opening of the app this popup appears

Please reopen and remove it.

**Comment by T8RIN** [comment]
I will add a close button

**Comment by licaon-kter** [comment]
There's no button for me to tap, there's only "CI channel" and "Group" and I want to edit a file, I don't want to have anything to do with Telegram.

I did touch "outside" but... nothing happens, it disappears _now_ but popsup later...
