### ISSUE TITLE
Use as default editor

### ISSUE THREAD

**Issue by Tal-Gordon** [T8RIN/ImageToolbox#1532]
It would be nice if I could use this app as the system set editor for images. Like, if I click "edit" within a gallery, I want this app to present itself as a choice for editing. 

Using the "share" button also works I guess, but why, when there's a feature in Android that does exactly that?

**Comment by T8RIN** [comment]
I can't change something to add this, so it only relies on your system

**Comment by Tal-Gordon** [comment]
> I can't change something to add this, so it only relies on your system

From what I found online, it has something to do with intent filters. I think EDIT is a valid action type within that context. Are you sure this is not a change on your end?

**Comment by RenovAlgarve** [comment]
AndroidManifeat.xml

Application>Activity 

`            <intent-filter>
                <action
                    android:name="android.intent.action.EDIT" />
                <category
                    android:name="android.intent.category.DEFAULT" />
                <data
                    android:scheme="file" />
                <data
                    android:scheme="content" />
                <data
                    android:mimeType="image/*" />
            </intent-filter>`

**Comment by T8RIN** [comment]
> > I can't change something to add this, so it only relies on your system
> 
> From what I found online, it has something to do with intent filters. I think EDIT is a valid action type within that context. Are you sure this is not a change on your end?

It's already inside, because without it you will not be able to launch from edit in gallery
