### ISSUE TITLE
🟧 REQUESTS

### ISSUE THREAD

**Issue by UserAccount123** [T8RIN/ImageToolbox#1538]
1. (Markup Layers) tool:
- [x] Text: enable adding (Bold, Italic, Underline)
- [ ] Border around the text (line type, line thickness, line color)
- [x] Rotation angle (in layers menu)
- [x] Outline around the text
- [ ] Add arrow buttons (up, down, left, right) so as to move the object precisely.
- [ ] Image: enable adding border around the image (continuous line, dashed line, ..) + Adjusting the line color and width
- [ ] Add ability to insert multiple images.
- [ ] Enable selecting multiple objects.
- [x] Quick access:

![1](https://github.com/user-attachments/assets/cda67715-aeb7-4f82-8d74-2dbff6b10dbf)

- [x] 2. (Draw) tool: Helper grid: make it semi-transparent by default.
- [x] 3. Settings > Filename: add an option to save files with the original filenames.
- [x] 4. (Settings) & (Dismiss forever):

![2](https://github.com/user-attachments/assets/02080435-5929-4f2b-a71a-921385c892c9)

![3](https://github.com/user-attachments/assets/c2005b63-ce6b-4cb7-b84c-fcaf6505ff9d)

**Comment by T8RIN** [comment]
4 works that way, if you open the tg through these buttons at least 1 time

**Comment by T8RIN** [comment]
I will do 1 and 2 i think

**Comment by T8RIN** [comment]
> Add ability to insert multiple images.
Why is this needed? You can add images one by one, because if you do this immediately they will stack on each other

**Comment by T8RIN** [comment]
Next time please make more structurized checklists or separate issues :)
