### ISSUE TITLE
Add A Fill Bucket!

### ISSUE THREAD

**Issue by Maxitendo1** [T8RIN/ImageToolbox#1539]
I think that it's very important to have a fill bucket. If it's too hard to implement then this might be also achieved by selecting a color on the image and then being able to change this specific color. Here's more information for it:

The Fill Bucket tool is used for filling regions, layers, or selections with a specified color or image pattern. It’s a versatile tool with various settings and modes to achieve specific results.

https://docs.gimp.org/2.10/en/gimp-tool-bucket-fill.html

![](https://www.getpaint.net/doc/latest/images/tools/fill/ChangeColor.gif)

**Comment by T8RIN** [comment]
It's possible in the filters section 👀

**Comment by Maxitendo1** [comment]
Oh okay, thanks. I didn't know that, because I wouldn't have ever thought of having it there. After using it it I found out that it takes a lot of steps to change a specific color of the image:

The current steps (7): Pipette -> Click on a color in the image -> Copy color hex code -> Going back -> Going on all colors -> Pasting color hex code -> Clicking ok

The better steps (3): Placing the pipette also in the color replaced / target color besides the all colors button -> Click on a color in the image -> Automatically uses this color and goes back again
![grafik](https://github.com/user-attachments/assets/a9c4532c-8ae1-43da-b08b-71c7172a327a)

**Comment by T8RIN** [comment]
The main problem of this implementation, is that this color picking row used no only on this screen and may be confusing, but if i remember correctly , you can just hold the pallette button instead of opening sheet to paste copied color

**Comment by Maxitendo1** [comment]
Yeah, thanks. That's actually working, now it's taking me just 5 steps instead of 7.

**Comment by T8RIN** [comment]
I can close this right?

**Comment by Maxitendo1** [comment]
Yeah, we can close it.
