### ISSUE TITLE
Request: base64 encode/decode to image

### ISSUE THREAD

**Issue by preactive** [T8RIN/ImageToolbox#1545]
**Is your feature request related to a problem? Please describe.**
Problem use case is: people have access to text only services which still massive text but no media. If i need to send a picture of a map to my friend in the Philippines who is on freemode cellular network (text only over Facebook) then i can't help them as easily. 

**Describe the solution you'd like**
If i can take a screenshot like normal of a map. Then come to your app as me and my friend would both have your app installed going forward. I would base64 encode my map for them, send over text. They would base64 decode the picture on their text only network.

**Describe alternatives you've considered**
Base64 websites need Internet access which defeats the point.

**Comment by T8RIN** [comment]
Sounds good!

**Comment by T8RIN** [comment]
Added

**Comment by preactive** [comment]
Thank you so much 🙏🏻
