### ISSUE TITLE
Option to set the filename to the file checksum algorithm

### ISSUE THREAD

**Issue by Tarballwalf** [T8RIN/ImageToolbox#1555]
**Is your feature request related to a problem? Please describe.**
I usually save a lot of photos and covert them, later manually naming the file to one of the checksum algorithms (I myself use MD5) to avoid placing the same file within the same folder, or differentiating between slightly different photos that share the same filename/look.

**Describe the solution you'd like**
An option added to the `Filename` settings to save the files as the checksum name, this being different from fully randomized file names, as having the same image twice would result into having the same file name and images with slight variations having a different name.

The primary algorithms used could be MD5, SHA1, SHA256 and SHA521. As I think these are sufficient for people. 

People could find this useful for a lot more other stuff, this is just my use case.

**Describe alternatives you've considered**
I have considered using another app to calculate the checksum and rename the file manually, but it becomes tiring manually having to calculate the checksum of a file, the copying the hash, switching to the file manager and renaming the file, doing this over and over again for lots of files, sometimes even making mistakes and having to start all over. Having the option to just, select all the images, convert them and have them output with their checksum as the file name would be amazing.
I used to use a website in the past but they have recently shut down.

**Comment by T8RIN** [comment]
done
