### ISSUE TITLE
Sharpen filter slider has no effect

### ISSUE THREAD

**Issue by lgasp** [T8RIN/ImageToolbox#1556]
**Describe the bug**
The sharpen filter has a slider tha allows to apply the effect from -1 to 1. Changing this value does not affect the filter behaviour in any noticeable way. The sharpen filter is applied but the "strenght" doesn't change

**To Reproduce**
Singles edit -> add filter -> sharpen -> use the slider of the filter

**Expected behavior**
The strenght of the filter should be proportional to the value of the slider:
0: no effect
1: full effect, maximum sharpness
-1: unsharp the image? But there is an unsharp filter already. Not clear

**Screenshots**
Top left: original image
Others are the filter with the slider at 0, -1 and 1
![ResizedImage_2024-12-29_21-56-33_2312](https://github.com/user-attachments/assets/142ba884-cae1-466f-99f6-7be267352a29)

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: android 13
 - image toolbox version 3.1.1 foss

**Comment by T8RIN** [comment]
![Screenshot_20241230-001033.png](https://github.com/user-attachments/assets/f1bde33c-2d79-4668-8f0c-23e578140304)

Works normal for me

**Comment by T8RIN** [comment]
I didn't see that negative values differ from positive, so the value range should be 0..2 i think

**Comment by lgasp** [comment]
> ![Screenshot_20241230-001033.png](https://private-user-images.githubusercontent.com/52178347/399187318-f1bde33c-2d79-4668-8f0c-23e578140304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MDkxMzUsIm5iZiI6MTczNTUwODgzNSwicGF0aCI6Ii81MjE3ODM0Ny8zOTkxODczMTgtZjFiZGUzM2MtMmQ3OS00NjY4LThmMGMtMjNlNTc4MTQwMzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDIxNDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MzIwYzdhNmI4OGU1NDNlODUzMWFkY2VjZWZkYTM0NTYyZTg3YjVlMTVmNzEzZjIwYjhkZGExNDRhZWM2NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Oz-8DNgAIrdpg83kQcJe39rDp8q4A-Qrge6-nUihtg)
> 
> Works normal for me

The filter works. The issue is that the slider for the filtet has no effect. Try different values and check if you see any difference. In my example screenshot I tried -1, 0, 1 and the result was always the same
