### ISSUE TITLE
[Feature request] delete originals option

### ISSUE THREAD

**Issue by Lucky390163** [T8RIN/ImageToolbox#173]
Please add delete originals after the resize option for better.And please add show size.

**Comment by T8RIN** [comment]
What do you mean by saying "show size" ?

**Comment by Lucky390163** [comment]
Means the image we are compressing and how many of mb it takes and shows in
gallery like 3mb-4mb etc

**Comment by T8RIN** [comment]
![Screenshot_20230501-171656_Image Resizer.png](https://user-images.githubusercontent.com/52178347/235465671-4188c469-c974-4f3c-8a4f-e1b189707dd8.png)

This?

**Comment by Lucky390163** [comment]
Yes! I just cannot find or confused about it.

**Comment by T8RIN** [comment]
But this is on every screen where you choose an image

**Comment by Lucky390163** [comment]
Got it, thanks!

**Comment by T8RIN** [comment]
Unfortunately, that seems to be impossible, because of restrictions of android os or i just don't know how to avoid that :( maybe someone helps...

**Comment by Tanmandal** [comment]
https://github.com/deckerst
You can look into this project for help
There is a rotate option in this gallery app which when used it rotates the picture permanently for all apps
That means it most probably deletes the the original picture
The mirror option also does that

**Comment by T8RIN** [comment]
I'll check 👀

**Comment by Lucky390163** [comment]
Ok, thanks.

**Comment by mkf** [comment]
there's also the Atomize app that applies pngquant and removes original image. (I sometimes use it after ImageResizer. (Also, I sometimes use jpegoptim in Termux after ImageResizer, but that's an off-topic feature request kinda entirely) )

Also I would love that option because it would solve the need for apply-several-tools-one-after-another, because now if I want to crop and resize (that was one step before) I need to clutter storage in the meantime. Also I may then want to posterize, and that's also a separate step.

**Comment by T8RIN** [comment]
You can use the share button inside the app, that would gain you ability of chain editing with different options 🐸

**Comment by T8RIN** [comment]
Mb in the future i'll add the first one

**Comment by mkf** [comment]
> You can use the share button inside the app, that would gain you ability of chain editing with different options 🐸

oh if it doesn't indeed write an intermediate file persistently then… however, iirc i had sharing not work for me sometimes. I will however wait with recording this until the emoji-unbricking update, because I don't feel like clearing my settings.

**Comment by T8RIN** [comment]
It will be soon!

**Comment by Lucky390163** [comment]
I hope so too!
