### ISSUE TITLE
[Feature request] drag sides of crop to crop in only one direction

### ISSUE THREAD

**Issue by starchyunderscore** [T8RIN/ImageToolbox#202]
loving the app so far, but it would be great if you could drag the sides of the crop box to crop in just one direction, instead of needing to drag from the corners and do two directions at once.

current:

https://cdn.discordapp.com/attachments/1104898178085556384/1106619849834254386/screen-20230512-123146.mp4

wanted (simple gallery for demonstration):

https://cdn.discordapp.com/attachments/1104898178085556384/1106619869807521803/screen-20230512-123015.mp4

**Comment by T8RIN** [comment]
Thanks for the suggestion, at this moment i'm using the library to create this crop box, but i had the source, so i can try to implement your idea later :)

**Comment by ShoeUnited** [comment]
My request is an extension of this idea. Non-centered cropping.
