### ISSUE TITLE
feature req. in batch resize

### ISSUE THREAD

**Issue by Wjxfi** [T8RIN/ImageToolbox#23]
the ability to crop a photo for only one photo (the one I choose in the preview photo (#19))
Also, it should say that this will only work for 1 photo

**Comment by T8RIN** [comment]
Will think about it, but why you need this? Btw you can crop single image in other modes

**Comment by T8RIN** [comment]
Okay, will try to add

**Comment by T8RIN** [comment]
Sorry, i'm just discovered GitHub features 👀

**Comment by T8RIN** [comment]
Preview mode fixed this issue you now can select many images and crop them continiously
