### ISSUE TITLE
[Bug] Izzy and F-Droid Releases given same version number

### ISSUE THREAD

**Issue by fohfuu** [T8RIN/ImageToolbox#264]
The Izzy-on-droid and F-Droid releases should be given different versions (e.g. 2.0.5-Izzy and 2.0.5-Fdroid).

This might seem a petty feature request, but it actually seems to be the roor cause of some of the bugs that require complete fresh installs to fix.

It also seems to confuse the F-Droid client that sees them as identical versions. I can't actually tell you which version I have installed right now.

As a silver lining, this would also make bug triage easier in the future.

**Comment by T8RIN** [comment]
I understand you, but I'm not posting releases there, it's automatic and without my participation :)

**Comment by fohfuu** [comment]
What do you mean by "there"? F-Droid?

**Comment by T8RIN** [comment]
Yup

**Comment by fohfuu** [comment]
Does that mean you are posting to Izzy separately?

**Comment by T8RIN** [comment]
I'm not posting at all, that's going automatically when i push a new release on the github
