### ISSUE TITLE
[Bug] Wrong bottom application bar

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#285]
![Screenshot_20230609_022428_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/bc638450-65e7-4fe4-bb22-306e2c5d5f1c)

![Screenshot_20230609_022418_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/818a2648-232f-46ce-9263-e074f406e83d)

When I have not selected an image, a bottom bar with functions is displayed, and clicking the save button will keep loading.

But when I select an image, the bottom bar changes to "Pick Image" button, and the save button disappears, so I cannot save the image.

This issue only occurs in the first function: Single resize.

**Comment by T8RIN** [comment]
Thanks, I encountered this too, It is fixed already, i will release the changed version now
