### ISSUE TITLE
Lost ability to compare images

### ISSUE THREAD

**Issue by elesto** [T8RIN/ImageToolbox#287]
It seems that in the new release the option to compare images in the main screen has been removed. I used this to compare images that have not passed through this app. For example two images sent from a friend.

**Comment by T8RIN** [comment]
![Screenshot_20230610-075833_Image Toolbox (Resizer).png](https://github.com/T8RIN/ImageToolbox/assets/52178347/3886e934-88ae-4fc5-a6d0-5e50e45e54a5)

Everything is in place 👀

**Comment by elesto** [comment]
The option was definitely missing but a re-install has fixed it. Thanks
