### ISSUE TITLE
Custom location outside of /storage/emulated/0/ (/storage/0000-0000/(folder name)) save to /storage/emulated/0/(folder name) instead

### ISSUE THREAD

**Issue by theinsidersandrush** [T8RIN/ImageToolbox#290]
Whenever I saved a cropped image to my desired location (/storage/0000-0000/Resized images), but instead, it ends up in /storage/emulated/0/Resized images.

```
Device used: Xiaomi Redmi Note 5 Pro
Codename: whyred
Android version: 9 (Pie)
OS: MIUI 11.0.3
Rooted: No

```

**Comment by T8RIN** [comment]
Every image saving mode?

**Comment by theinsidersandrush** [comment]
Yes. Apparently, I choose to save all resized images to my external SD card, but it ended up in the internal storage ![Screenshot_2023-06-15-16-38-34-246_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/87752859/12bfc55b-5800-4a54-9cd7-a48b1f9ab8ab)

![Screenshot_2023-06-15-16-39-41-645_com.google.android.apps.nbu.files.jpg](https://github.com/T8RIN/ImageToolbox/assets/87752859/c0725477-b94f-4c2a-96a3-e0b721bc19cc)

I use this app on my Xiaomi Redmi Note 5 Pro, running on Android 9 version of MIUI (Version 11.0.3).

**Comment by theinsidersandrush** [comment]
How about adding Storage Access Framework (SAF) into the app might be resolving this?

**Comment by T8RIN** [comment]
> Yes. Apparently, I choose to save all resized images to my external SD card, but it ended up in the internal storage ![Screenshot_2023-06-15-16-38-34-246_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/87752859/12bfc55b-5800-4a54-9cd7-a48b1f9ab8ab)
> 
> ![Screenshot_2023-06-15-16-39-41-645_com.google.android.apps.nbu.files.jpg](https://github.com/T8RIN/ImageToolbox/assets/87752859/c0725477-b94f-4c2a-96a3-e0b721bc19cc)
> 
> I use this app on my Xiaomi Redmi Note 5 Pro, running on Android 9 version of MIUI (Version 11.0.3).

I can't check this, because I haven't got some device with sd card :(
