### ISSUE TITLE
I can't see the colors of the theme I set. 

### ISSUE THREAD

**Issue by J43git** [T8RIN/ImageToolbox#294]
If I want to check out the colors of a theme I made or saved, it ends up showing the colors of the theme I currently have on. For example, if I made a green theme and don't remember which colors I used, instead of seeing the colors of that theme, it's the colors of the theme that's been previously made. Also, every time I make a theme, if I use a color that is too close to another, for example, all the blues in a material design palette, all of them won't register because some will be replaced for being too close. 
![InCollage_20230615_153933155](https://github.com/T8RIN/ImageToolbox/assets/112982953/671375e7-ecd8-49de-9766-93bba5d46be4)
.

**Comment by T8RIN** [comment]
Thanks, i already fixed this, wait for the update :)

**Comment by J43git** [comment]
Okey dokey! Thank you!
