### ISSUE TITLE
Double crop

### ISSUE THREAD

**Issue by ShiftCtrlAltDel** [T8RIN/ImageToolbox#297]
Image Resizer v.2.0.5 (from F-Droid).

Crop image window: there are buttons "Crop" ("Обрезать") and "Save" (w/o label) at the bottom. After tapping "Crop", the image is being cropped, but not saved. After tapping "Save", the image is cropped _once again_ and then, saved. That's because after cropping, the image is enlarged to fit the window, and cropping frame remains in its place. I see no problem here, but:

Why only the part inside of the frame is saved, instead of the entire -- and already processed -- image???

**Comment by T8RIN** [comment]
Becausee this button just crops the image and does not save it, whereas save does it all. And of course every time cropped/saved only the frame selected area 👀

**Comment by ShiftCtrlAltDel** [comment]
o_O 
I thought I found a bug, but it turns out that it's not a bug, it's a feature... Too bad. This feature totally spoils a very interesting app. Please let me explain, shortly.

First of all, that's unhandy, because any duplication of functions is a problem for the user. Also, it's not obvious. Maybe it is "of course" for the author, but for a user like me, it's not "of course" at all. And the icon on the button (please see attached screenshot) doesn't mean "Crop&Save", it evidently means "Save" only. Actually, I spoiled several screenshots before I could discover the reason, because this is the very first time I see a menu like this (and I'm an active PC user since 1989).

Duplicate functions (just in case: I mean the buttons "**Crop**" and "**Crop**&Save") are an algorithmization error and must be avoided not only in code, but IRL, too.

Thank you for your attention.

![20230620_085105 14_7c389b2ee94145b1ab3b976a49fd0291](https://github.com/T8RIN/ImageToolbox/assets/137117538/5ff31774-64f0-47f1-94d6-6d46ba13c0ff)

**Comment by T8RIN** [comment]
Got it, i will rework it a bit 👀
