### ISSUE TITLE
Becausee this button just crops the image and does not save it, whereas save does it all. And of course every time cropped/saved only the frame selected area 👀

### ISSUE THREAD

**Issue by zzzzzzxXxzzzzzz** [T8RIN/ImageToolbox#302]
Becausee this button just crops the image and does not save it, whereas save does it all. And of course every time cropped/saved only the frame selected area 👀

_Originally posted by @T8RIN in https://github.com/T8RIN/ImageToolbox/issues/297#issuecomment-1598043752_

**Comment by T8RIN** [comment]
?
