### ISSUE TITLE
FEATURE Request for BMP image format 

### ISSUE THREAD

**Issue by YUDHPK** [T8RIN/ImageToolbox#308]
Please add an option to convert the image into bmp image format

**Comment by T8RIN** [comment]
Is it really needed?👀

**Comment by YUDHPK** [comment]
Yes it is needed since some government websites require bmp image with specific dimensions and size limits

**Comment by YUDHPK** [comment]
Your app is quite impressive and useful. Hence requesting you to implement BMP image format conversion if possible

**Comment by T8RIN** [comment]
> Yes it is needed since some government websites require bmp image with specific dimensions and size limits

Got it, also there is no built-in solution to convert the image into BMP , but I am early interested in this question, so i know the way 👀

**Comment by T8RIN** [comment]
Added this, wait in the 2.2
