### ISSUE TITLE
Feature Request: Improvements in colour picker

### ISSUE THREAD

**Issue by krishna8755** [T8RIN/ImageToolbox#316]
I have a very nice idea. Add colour picker to the quick panel. So what it does it when the user clicks it, the app clicks a screenshot of the Current page on which user is. It helps many people like designers to find hex code easily.

**Comment by T8RIN** [comment]
Nice idea, thanks!

**Comment by krishna8755** [comment]
> Nice idea, thanks!

Thankyou for your reply. I want to expand my idea. Here it is : After clicking screenshot the image toolbox app will open colour picker tab with the clicked screenshot to select part to find out its hex code

**Comment by T8RIN** [comment]
> > Nice idea, thanks!
> 
> Thankyou for your reply. I want to expand my idea. Here it is : After clicking screenshot the image toolbox app will open colour picker tab with the clicked screenshot to select part to find out its hex code

Unlike the first idea, this is not feasible without root :(
