### ISSUE TITLE
Some suggestions 

### ISSUE THREAD

**Issue by plum7x** [T8RIN/ImageToolbox#322]
The single/batch resize feature enhancement
The existing limits resize feature lack of compression level options.
Please add the limits resize as a resize type in the types of the existing single/batch resize feature, for limits resizing and compression in one conversion.

More filters
- Add a resize filter likes the above single/batch resize feature.
- Add a crop filter likes the existing crop feature.

For the multiple changing in one conversion, e.g. crop, resize, sharpen, compression in one conversion to get finished pictures that can avoid producing the extra temporary files.

**Comment by T8RIN** [comment]
What do you mean by filter? It just applies transformations to the image without changing it specs

**Comment by plum7x** [comment]
ffmpeg provide a resize filter named scale, I can add it in a filter chain for getting fenished output file in one conversion.

e.g. downsize 4k png to the high quality jpg and fit fullhd size: 
```
ffmpeg -i "input.png" -filters "scale='w=min(1920,trunc(1080*dar/2+0.5)*2):h=min(1080,trunc(1920/dar/2+0.5)*2)', any more filters..." -qscale:v 2 "output.jpg"
```

unfortunately ffmpeg is command-line interface, it not easy using in smart phone.

**Comment by T8RIN** [comment]
isnt it too much of crating special resize option?

**Comment by plum7x** [comment]
- The "Single resize" is same as that only one picture selected with the "Batch resize".
- The "Limits resize" Lack of some useful options.

So I suggest to merge the three resizings.

**Comment by T8RIN** [comment]
Which option do you lose in the limits resize? 👀

**Comment by plum7x** [comment]
Is the quality option, I need it to specify output quality for downsizing.

**Comment by T8RIN** [comment]
Can you explain more about skip and copy, what does it mean? "Skip" doesn't save smaller images, and "copy" is the ability to save as it is

**Comment by plum7x** [comment]
yes, that's it.
but only copy and recode options is actually necessary.
if we can filter images by size in image picker, then we don't need the skip option.

**Comment by T8RIN** [comment]
Already added both three options 🐸

**Comment by plum7x** [comment]
there is a problem, the force does not behave as my expected.
it should be converted only without resizing for the smaller images.
for example: below 2560x1440, jxl format
- 1.jpg (4000x3000) -> 1.jxl (2560x1920)
- 2.jpg (4000x2250) -> 2.jxl (2560x1440)
- 3.jpg (1920x1080) -> 3.jxl (1920x1080)
- 4.jpg (1440x1080) -> 4.jxl (1440x1080)

**Comment by T8RIN** [comment]
> there is a problem, the force does not behave as my expected.
> it should be converted only without resizing for the smaller images.
> for example: below 2560x1440, jpg format
> - 1.png (4000x3000) -> 1.jpg (1920x1440)
> - 2.png (4000x2250) -> 2.jpg (2560x1440)
> - 3.png (1920x1080) -> 3.jpg (1920x1080)
> - 4.png (1440x1080) -> 4.jpg (1440x1080)

Then you should use "skip" option 👀 it does that

**Comment by T8RIN** [comment]
> there is a problem, the force does not behave as my expected. it should be converted only without resizing for the smaller images. for example: below 2560x1440, jpg format
> 
> * 1.png (4000x3000) -> 1.jpg (1920x1440)
> * 2.png (4000x2250) -> 2.jpg (2560x1440)
> * 3.png (1920x1080) -> 3.jpg (1920x1080)
> * 4.png (1440x1080) -> 4.jpg (1440x1080)

Oh, i see, i replaced copy with recode option, in fact it does what you want :)
