### ISSUE TITLE
Please add a option to not change resolution.

### ISSUE THREAD

**Issue by JadenJSJ** [T8RIN/ImageToolbox#334]
I really like this tool, it is very good and is the best
Multi image format compressor for android that I know of.

However sometimes I may want to drop the quality of the image but keep the resolution unchanged. Unfortunately there is no option for that, and I'd have to manually check the resolution of the original image to keep it unchanged.

Please add a option to keep original resolution, thank you!

**Comment by T8RIN** [comment]
Hi, looks like you can just save the image without any changes except quality or smth else and image resolution will not be changed, also you can see label hint in text field, this determines original image dimensions (red one)->

![ResizedImage_2023-07-15_12-11-35_2647.jpg](https://github.com/T8RIN/ImageToolbox/assets/52178347/3ae44297-413e-44b5-acf0-2b23bf348295)

Also when you pick an image it's dimens are already inserted into the fileds, so there are no problems to you i think🐸

**Comment by JadenJSJ** [comment]
EDIT: I just realized a newer version of the app is available
I'll edit this message after I update, because if I switch tabs the tab usually gets discarded on my phone

The label did not display the correct image resolution, the compressed resolution still became smaller.

https://github.com/T8RIN/ImageToolbox/assets/44781632/3befb489-e1fc-4c64-9fe7-9af6b3fccdaa

This is the uncompressed file I tried to compress
![IMG_20230715_155357](https://github.com/T8RIN/ImageToolbox/assets/44781632/0f6b8fce-9ae3-414a-9633-17e8d20cfad4)

**Comment by T8RIN** [comment]
Check it on the 2.2.0-rc3 too

**Comment by JadenJSJ** [comment]
Ah yeah sorry, looks like I didn't update to a newer version (I was using f-droid stable version previously). It is fixed and uses the original resolution by default.
