### ISSUE TITLE
Support for newer image formats

### ISSUE THREAD

**Issue by JadenJSJ** [T8RIN/ImageToolbox#335]
Please consider adding support for avif, heic, jpegxl.

While avif is relatively new format, it is very efficient and excels in producing acceptable image quality in small file sizes. It is also supported by +90% of mobile browsers.

Avif is alot better in compressing to smaller file sizes.
https://www.reddit.com/r/AV1/comments/jp9w41/why_webdevelopers_should_use_avif_comparison/

Adding support for heic and jpegxl would be a plus as they are more efficient then jpeg especially at compressing images in high quality (in larger file size bracket), saving a significant amount of space.

It would be great if you removed one of the jpeg options as jpeg and jpg are the same codec/redundant, (they only differ in file extensions), and replace it with avif,heic,jpegxl(.jxl).

Thanks for reading this long request!

**Comment by T8RIN** [comment]
Someone might need this, (jpeg is this one which was requested the first), i will definitely add avif/heif but don't know about jxl
