### ISSUE TITLE
App icon seems to be missing in new release 2.2.0

### ISSUE THREAD

**Issue by quadroli** [T8RIN/ImageToolbox#340]
On my phone (vivo v25) the app is using the system's default icon upon updating it.

**Comment by quadroli** [comment]
![IMG_20230720_072944](https://github.com/T8RIN/ImageToolbox/assets/58091631/6e13b92f-7927-4399-813c-8fc77e3c98fc)

**Comment by T8RIN** [comment]
Could you please test the google play version? Because i literally didn't touch the app icon in this update (

**Comment by quadroli** [comment]
Hmm, its okay now 👍🏼, both google play and f-droid, after I re-installed

**Comment by T8RIN** [comment]
Maybe that's an install bug, It's good that it's fixed :)
