### ISSUE TITLE
Removing the emoji bricks the app

### ISSUE THREAD

**Issue by VistHJ** [T8RIN/ImageToolbox#341]
https://github.com/T8RIN/ImageToolbox/assets/86906143/6de52eaa-17b6-4fad-8c77-2d86c0dc1716

The only solution is to **wipe its data**.
Reopening, killing the task, clearing cache and restarting device is useless

**Comment by T8RIN** [comment]
Intersting, i will check it 🐸

**Comment by T8RIN** [comment]
Fixed
