### ISSUE TITLE
Lazy preview of resize-many

### ISSUE THREAD

**Issue by mkf** [T8RIN/ImageToolbox#344]
Resize many takes much more time when I want to resize a large image, than for one. Let's not wait with the preview for the images that are not yet being previewed.

(In general, the application seems to now take much more time to even WebP even a single 12MP image, after the new formats update)

**Comment by T8RIN** [comment]
Sorry, can you reexplain please, doesn't get it :(

Btw the second one sounds interesting, because I didn't change the compressor for another formats, but, maybe that's because of splitting to lossless and lossy webps
