### ISSUE TITLE
Getting blank screen on the app open.

### ISSUE THREAD

**Issue by Alfaizkhan** [T8RIN/ImageToolbox#345]
![Screenshot_20230722-230717.png](https://github.com/T8RIN/ImageToolbox/assets/33489180/1fbfaadb-a871-4148-8199-d1379c685f3c)

Device: Pixel 6
OS: Android 13

**Comment by T8RIN** [comment]
Can you try to clear app data?

**Comment by Alfaizkhan** [comment]
It's working now 😁

**Comment by T8RIN** [comment]
Nice to hear!

**Comment by T8RIN** [comment]
Wait for the patch, it'll fix those issues
