### ISSUE TITLE
[Bug] Problem with edge to edge display on the hole digging screen

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#347]
![Screenshot_2023-07-23-18-22-52-329_ru.tech.imageresizershrinker-edit.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/45bc4cdc-01fa-4a16-92bc-ab8fcb692348)
In landscape mode, the camera will block the setting items.
And there is an extra blank space on the left side of the setting items.

**Comment by Jesse205** [comment]
![Screenshot_2023-07-23-18-26-53-003_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/29e99a29-063a-43ef-a2af-b6bd8f03998b)
![Screenshot_2023-07-23-18-27-48-087_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/4eda4cfe-5e90-4afa-969a-71e3c69fe81f)

**Comment by T8RIN** [comment]
Thanks for reporting, i'll fix it soon !

**Comment by Jesse205** [comment]
Wait, this bug has not been fixed yet.
The camera on the left will still fill the settings menu on the right.

![Screenshot_2023-09-25-04-50-07-512_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/26315118-8ed1-4122-8fb8-01045472d276)
I'm very sorry, because my phone data was cleared, so I forgot about it.

**Comment by Jesse205** [comment]
Wait, this bug has not been fixed yet.
The camera on the left will still fill the settings menu on the right.

![Screenshot_2023-09-25-04-50-07-512_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/26315118-8ed1-4122-8fb8-01045472d276)
I'm very sorry, because my phone data was cleared, so I forgot about it.

**Comment by Jesse205** [comment]
You can launch an Android 9+ emulator to test this situation. More gap screen styles available in developer options.

**Comment by Jesse205** [comment]
![Screenshot_2023-09-25-04-59-16-472_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/05f73f0a-8fd0-40bd-bdcd-e287960dce01)
The layout has successfully avoided the camera on the right side

**Comment by T8RIN** [comment]
I think now it should work properly :)

**Comment by T8RIN** [comment]
Something else except that?

**Comment by Jesse205** [comment]
![Screenshot_2023-09-25-05-50-24-693_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/290a62b0-721c-4626-a04f-dd2bc017beda)
It's normal now.
I hope to restore the navigation bar to its original state, as there is no need to squeeze the screen space under the horizontal screen. There is sufficient space on the tablet to place the navigation bar, and the navigation bar on the phone will be displayed on the short edge of the screen.

**Comment by T8RIN** [comment]
i'll close it for now, wait for  the 2.3.3-alpha01 to check it this helped
