### ISSUE TITLE
Unit of "Presets"

### ISSUE THREAD

**Issue by uli-on** [T8RIN/ImageToolbox#348]
The Presets setting group needed any unit or descriptive subline to make it unequivocal, I never know is it about JPG quality or scaling percentage (or some third "quality"?)

Great job, BTW, to separate the app into tabs, make the setting groups foldable, and finally: Although I'm not a fan of animations in apps I've to say I love the new transition effects you've chosen, especially the tool headers and the explanatory icon animation of the edit tab.

**Comment by T8RIN** [comment]
Thanks!

And about presets, it is scaling percentage and jpg quality if it is less than 100 👀

I can add explanation info button like resize types has

**Comment by T8RIN** [comment]
Yes!

**Comment by uli-on** [comment]
Let's say my new phone creates huuuuge images and I don't reduce resolution 
each time, camera sided, when taking pictures. Now I need only 10 percent 
side length of existing images. Then - using presets - I'd get colour 
reduced, jaggy results. Shouldn't compression and quality be chosen 
independently to avoid that?

**Comment by T8RIN** [comment]
In this case you can just adjust quality, and nothing breaks then, saving should work using preset f.e. 40 and 100 quality

**Comment by uli-on** [comment]
> I can add explanation info button like resize types has

Yes, please. That might be useful not only for more scroll experts of my sort.
