### ISSUE TITLE
Keep original file name

### ISSUE THREAD

**Issue by valflrt** [T8RIN/ImageToolbox#352]
A button enabling keeping original file name could be added.

![Screenshot_20230726-233404.png](https://github.com/T8RIN/ImageToolbox/assets/49407769/9067f6f5-11af-46a5-a050-2d39a4b007f2)

**Comment by T8RIN** [comment]
Okay, but this will disable "add original filename" option  because or/or can be enabled

**Comment by T8RIN** [comment]
I see that you are using 2.1.3, why don't you update to 2.2.1?

**Comment by valflrt** [comment]
> Okay, but this will disable "add original filename" option  because or/or can be enabled 

yes it would, I think this option would be really important when you want to edit a file and quickly replace the old version with the new one without having to copy the old filename, rename the new file and so on...

**Comment by valflrt** [comment]
or maybe an button to replace automatically the old version(s) would be even better

**Comment by valflrt** [comment]
> I see that you are using 2.1.3, why don't you update to 2.2.1?

I've just done it 👍

**Comment by T8RIN** [comment]
> > Okay, but this will disable "add original filename" option  because or/or can be enabled 
> 
> yes it would but only when activated: when you want to keep the original file name, you just need to enable "keep original file name" and the other file naming options would appear grayed out.
> 
> I think this option would be really important when you want to edit a file and quickly replace the old version with the new one without having to copy the old filename, rename the new file and so on...
> 
> or maybe a button to replace automatically the old version(s) would be even better

There are some permission issues in these cases, the app needs high level permission to do that :( check

**Comment by valflrt** [comment]
> There are some permission issues in these cases, the app needs high level permission to do that :( check #173 i'm trying to find a way btw 

No problem the "keep original file name" would do the job !
Anyway thank you for making this app, it's very useful !

**Comment by T8RIN** [comment]
Thank you for using it!

**Comment by T8RIN** [comment]
I'll fix
