### ISSUE TITLE
Custom file saving directory works only in Single editing

### ISSUE THREAD

**Issue by VistHJ** [T8RIN/ImageToolbox#353]
https://media.discordapp.net/attachments/987384525493530624/1134580318830080080/cd2t7mMx.mp4

I couldn't find any solutions for this one. It immediatly forgets directory after using anything that's not Single editing

**Comment by T8RIN** [comment]
Это визуальный баг только или реально сохраняет не туда? Попробую исправить в ближайшее время

**Comment by T8RIN** [comment]
А если сначала поставить папку свою, и попробовать сохранить без перезапуска, то такое же поведение? А ещё бы версию андроид узнать бы 🐸

**Comment by VistHJ** [comment]
> Это визуальный баг только или реально сохраняет не туда? Попробую исправить в ближайшее время

Both. The first time it was just a glitch. But it actually forgot the directory after that and since saves in the default location

**Comment by VistHJ** [comment]
> А если сначала поставить папку свою, и попробовать сохранить без перезапуска, то такое же поведение? А ещё бы версию андроид узнать бы 🐸

Android 12 (RUI 3). The issue won't ever appear if you're using **only** Single editing

**Comment by T8RIN** [comment]
Okay, but why писать на инглиш, если я вижу, что язык русский стоит👀

**Comment by VistHJ** [comment]
> Okay, but why писать на инглиш, если я вижу, что язык русский стоит👀

Привычка. Просто со мной некоторые с запада разговаривали на русском через переводчик (это легко заметить) и приходилось их отгаваривать. Я в детстве учил англ чисто из-за игр без перевода (лучшее решение в моей жизни) поэтому он мне как родной

**Comment by T8RIN** [comment]
Полностью поддерживаю, игры это топ, тоже привык на английском отвечать, но иногда думаю мол нечего выпендриваться, можно и так, раз поймут

А через переводчик это да, ужас, лучше не надо

**Comment by T8RIN** [comment]
> > Okay, but why писать на инглиш, если я вижу, что язык русский стоит👀
> 
> Привычка. Просто со мной некоторые с запада разговаривали на русском через переводчик (это легко заметить) и приходилось их отгаваривать. Я в детстве учил англ чисто из-за игр без перевода (лучшее решение в моей жизни) поэтому он мне как родной
> 
> + мало кто поймёт о чём тут написано

Конспирация :)

**Comment by T8RIN** [comment]
починил)
