### ISSUE TITLE
Default preset values cannot be deleted

### ISSUE THREAD

**Issue by VistHJ** [T8RIN/ImageToolbox#358]
https://media.discordapp.net/attachments/987384525493530624/1135227657550843938/qaEZdL1p.mp4

Also if you enter something less than 10, even an empty field, it becomes 10 anyway (foolproof feature?)

**Comment by T8RIN** [comment]
Yes!

**Comment by T8RIN** [comment]
That's not a bug, but maybe i should just limit минимальное количество пресетов допустим четырьмя
