### ISSUE TITLE
Pic size changes via presets break below 70

### ISSUE THREAD

**Issue by VistHJ** [T8RIN/ImageToolbox#359]
https://media.discordapp.net/attachments/987384525493530624/1135232310388736151/kW5eiZxD.mp4

If it's below 70 it adds +15 to the preset value. For example, 50 = 65. It doesn't affect quality setting though

> на этот раз не фича а баг :)

**Comment by T8RIN** [comment]
Добавлял раньше, чтобы багов не было, уже убрано это, но пока не выпустил
