### ISSUE TITLE
Feature request: an Image Combiner tool

### ISSUE THREAD

**Issue by GrayLanterns** [T8RIN/ImageToolbox#364]
Hey,
Hope you're doing well.

I dropped a review in the morning today on your Play Store app page, where I spoke on this subject:

> if you could please introduce an Image Combiner tool inside this app it'll be of great help. And by image combiner I mean the ability to merge/stitch two images into one single image.

You asked me if I could share this idea with you on the issue tracker, so here I am.

### A few example use cases to support my idea:

1. You often click pictures of important information and interesting news stories to share around; for instance, let's take a few tweets from a Twitter thread. Now instead of combining them into a single image, you would send out each of these image separately. Not ideal, is it?
2. We all find joy in creating and sharing memes with our loved ones. Now, if you go searching for apps that can create well-rounded memes, they'll be plenty; but name one app that isn't cluttered with ads, can you.

### Problem with existing Image Combiner apps:

There aren't many options to begin with. A few options that I personally tried but didn't like include: [PhotoLayers](https://play.google.com/store/apps/details?id=com.handycloset.android.photolayers&hl=en&gl=US), [Adobe Mix](https://play.google.com/store/search?q=adobe%20mix&c=apps&hl=en&gl=US), [Stitch](https://github.com/ekibun/Stitch/releases/tag/v1.1.11), [Image Combiner](https://play.google.com/store/search?q=image%20combiner&c=apps&hl=en&gl=US) and [Inshot](https://play.google.com/store/search?q=inshot&c=apps&hl=en&gl=US). While Stitch happens to be the only open source among the lot, it still isn't the most efficient. Image Combiner comes out as a decent alternative, but with a heavy paywall on its [premium clone](https://play.google.com/store/apps/details?id=com.zombodroid.imagecombinerpaid&hl=en&gl=US), it effectively makes it a dull choice. While Inshot solves the purpose, it is primarily a photo and video editor app - which will not be your first choice, if what you're looking for is just an image combiner.

I see hope in Image Toolbox. Firstly because it is open source, but also because of how the developer came out responding to my review in just a few hours, thanking me for giving the idea then generously asking me to raise an alert through this medium. It looks like they genuinely want to build this app with the best of intentions - while keeping their users' feasibility in check.

**Comment by T8RIN** [comment]
Thank you very much for posting such a good explanation, it looks quite interesting!

I will try to add this, and also thanks for giving references to other apps

**Comment by GrayLanterns** [comment]
> @GrayLanterns have you tried Screenmaster?

Not until now. This one's quite practical. Does more than just image stitching and the UI is presentable too. Ads aren't scattered like most other apps in the segment, and the one-off payment is what most users are comfortable with. Thanks for this crack of a suggestion! @kcryptonian :)

Though I'd still wish for the dev to consider the idea, if they please, as the feature we're talking about not only gives justice to the title "Image Toolbox" resulting in a more fulfilling app - especially advancing with features that are much lesser known in other apps in this segment, but also because the Image Toolbox is an open source app with zero ads. This would likely be a great leverage for new users to try out the app, and eventually become paid users in the future, hopefully. I am surely sticking by.

**Comment by kcryptonian** [comment]
You're very welcome. That's just one of the many useful apps I hoard ;)

**Comment by GrayLanterns** [comment]
_Only if I could take a sneak peek_ hahaha

**Comment by T8RIN** [comment]
Sorry for such a long feature maintenance I don't have much time right now, but I hope to be able to tackle this request in the near future

**Comment by T8RIN** [comment]
I've been working on this for 3 days now 🐸 expect it to be done soon!! Sorry for the wait :(

**Comment by kcryptonian** [comment]
No worries, thanks for the update!

**Comment by GrayLanterns** [comment]
> I've been working on this for 3 days now 🐸 expect it to be done soon!! Sorry for the wait :(

Take your time brother! Thanks for keeping us informed. :)

**Comment by GrayLanterns** [comment]
Thankyou once again for accepting and working on my request. ❤️ I appreciate the time and efforts you put into this. Loving the new update!

**Comment by GrayLanterns** [comment]
I will continue to raise feedback and feature requests that can help your users in the future.

**Comment by T8RIN** [comment]
You are welcome :)
