### ISSUE TITLE
Fdroid showing latest version as 2.1.3

### ISSUE THREAD

**Issue by tEctutoRIt** [T8RIN/ImageToolbox#366]

**Comment by T8RIN** [comment]
I don't publish any versions to platforms except GitHub and GooglePlay, they performed automatically

**Comment by shuvashish76** [comment]
Because it's Disabled.
related  #151

**Comment by T8RIN** [comment]
How to turn it on (

**Comment by shuvashish76** [comment]
Sorry I'm not a F-Droid maintainer ask in that discussion for help :(

**Comment by T8RIN** [comment]
It Will be uploaded soon, wait for 2.3.2 and check #151
