### ISSUE TITLE
A Reborted bug & 2 features Request

### ISSUE THREAD

**Issue by kcryptonian** [T8RIN/ImageToolbox#367]
The Bug:

My v2.2.1 of the app I'm using takes forever to process (even for more than 10 mins) when I use the reduce ''weight reduce'' feature/tool. 
And it's irreespective of the output or input picture format/extention. 
The issue has started since I updated to 2.2.1 and even after I updated to v2.2.2 it's still there.

I downgraded by installing the final release of  v2.2.0 but the problem still persisted

But when I installed the v2.2.0-beta3(69) that I was initially using before updating to v2.2.1 in the first place, the weight resize option starts working back.

*Please correct the bug in the next release. And try to shorten the time the picture use to process if possible (even the app version that works for me takes at least between 9-15 seconds to process).

Requested Features:

1. Option to 'backup' and restore the app user-settings.
2. Under the crop tool, make it possible to crop the Image in a freestyle manner (being able to drag the four edges of cropping not just in X and Y direction but also diagonally to any angle like in CamScanner app) and the image will auto-adjusts afterwards to maintain a standard aspect ratio. (I really anticipate this feature)

**Comment by T8RIN** [comment]
Please can you split this into separate issues? I use that as todos and close them on completion 👀

**Comment by kcryptonian** [comment]
> Please can you split this into separate issues? I use that as todos and close them on completion 👀

Done boss.
