### ISSUE TITLE
Feature Request: Omni-direction cropping.

### ISSUE THREAD

**Issue by kcryptonian** [T8RIN/ImageToolbox#384]
Under the crop tool, make it possible to crop the Image in a freestyle manner (being able to drag the four edges of cropping not just in X and Y direction but also diagonally to any angle like in CamScanner app) and the image will auto-adjusts afterwards to maintain a standard aspect ratio. (I really anticipate this feature)

**Comment by Dr-John-Early** [comment]
Not an exact solution, but a template that might help if you're willing to use opencv. This should take a polygon defined by any four points inside the image, and map/resize/transform the selection up to the original size of the image. You could also crop at this point, or resize to the longest edge of the selected polygon to avoid too much upscaling.

1. Define Source Points: Specify four points from the source image. These are the coordinates the user selects for the transformation.

pts_src = np.array([[x1, y1], [x2, y2], [x3, y3], [x4, y4]], dtype=float)

2. Define Destination Points: Set the points to the corners of the original image dimensions.

pts_dst = np.array([[0, 0], [width-1, 0], [width-1, height-1], [0, height-1]], dtype=float)

3. Calculate Transformation Matrix: Use the getPerspectiveTransform function with the source and destination points.

matrix = cv2.getPerspectiveTransform(pts_src, pts_dst)

4. Apply Transformation: Transform the image using the warpPerspective function.

transformed_image = cv2.warpPerspective(image, matrix, (width, height))
