### ISSUE TITLE
¿ Need to fix it

### ISSUE THREAD

**Issue by xventivs1** [T8RIN/ImageToolbox#389]
![image](https://github.com/T8RIN/ImageToolbox/assets/130994216/467e73d8-9234-4223-815d-32fafe961ffb)

**Comment by T8RIN** [comment]
What i need to fix?👀

**Comment by xventivs1** [comment]
> What i need to fix?👀

This stuff is jumping , please fix it , boss 🛐😔

**Comment by T8RIN** [comment]
> > What i need to fix?👀
> 
> This stuff is jumping , please fix it , boss 🛐😔

Will do
