### ISSUE TITLE
donate link on fdroid metadata

### ISSUE THREAD

**Issue by ghost** [T8RIN/ImageToolbox#392]
@T8RIN 
* **without your explicit consent** donate link ```https://qiwi.com/n/T8RIN``` given in https://github.com/T8RIN/ImageToolbox#-buy-me-a-coffee was added by me in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/ru.tech.imageresizershrinker.yml)
* donate link updated in fdroid metadata will create link on fdroid client
* should i remove it?

**Comment by T8RIN** [comment]
What > donate link updated in fdroid metadata will create link on fdroid client
means?

**Comment by T8RIN** [comment]
thanks!

**Comment by T8RIN** [comment]
> @T8RIN 
> > thanks!
> 
> i am assuming **its ok or yes** to keep donate link
> 
> 
> 

It's ok 🐸
