### ISSUE TITLE
Join multiple pictures 

### ISSUE THREAD

**Issue by iJahangard** [T8RIN/ImageToolbox#402]
Sometimes I need to join multiple photos together in a single photo, vertical and horizontal
And i think it is a good feature to be shown in image toolbox app

**Comment by T8RIN** [comment]
Possible duplicate of #364

**Comment by T8RIN** [comment]
I will add this, but firstly i'll drop 2.3.0 with new background remover and other fixes

**Comment by iJahangard** [comment]
Thank you so much

**Comment by T8RIN** [comment]
I will close it in favor of #364 (I don't have much time right now, but I hope to be able to tackle this request in the near future)
