### ISSUE TITLE
[Bug]Abnormal screen rotation when selecting font size

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#405]
https://github.com/T8RIN/ImageToolbox/assets/51242302/138e3bd0-c751-4af3-a619-bbf16ff48abd

I have turned off automatic screen rotation and my phone is always in vertical screen mode.

This bug also exists when selecting languages and fonts.

**Comment by T8RIN** [comment]
You can say that I thought so, to update the size of the system font, because simple recreation won't help, I don't like this approach either. I'll try to find a solution, it was temporary 🐸

**Comment by T8RIN** [comment]
> https://github.com/T8RIN/ImageToolbox/assets/51242302/138e3bd0-c751-4af3-a619-bbf16ff48abd
> 
> I have turned off automatic screen rotation and my phone is always in vertical screen mode.
> 
> This bug also exists when selecting languages and fonts.

When selecting a language? This shouldn't be here...

**Comment by Jesse205** [comment]
https://github.com/T8RIN/ImageToolbox/assets/51242302/fa3eb381-71b7-4ff1-a898-69e0d4cbd3e4
This is a screen recording.
