### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by Alexandru51** [T8RIN/ImageToolbox#419]
Hi, i'm that guy who translated in romanian.

I have one quick question: i saw that when changing the emoji from settings, i see there's a "emotions" option. And i was thinking... It is supposed to be a mispelling of "Emoticons"?

**Comment by T8RIN** [comment]
Hi, now, emoticons are usually this -> :D
But i have emojis that are illustrating emotions 👀

**Comment by Alexandru51** [comment]
Oh, i understand now :)

**Comment by T8RIN** [comment]
How problems!
