### ISSUE TITLE
Editing an image loaded from net releases confetti

### ISSUE THREAD

**Issue by v1s7** [T8RIN/ImageToolbox#421]
2.3.1
Android 13

https://github.com/T8RIN/ImageToolbox/assets/86906143/64a5dbf6-357f-472f-820d-dde52323d372

**Comment by T8RIN** [comment]
Конечно я так задумывал вроде как, не помню сейчас, но наверное лучше убрать, оно на сохранение и поделиться выглядит более логично :)

**Comment by T8RIN** [comment]
Добавил
