### ISSUE TITLE
[Bug] App Crash: OutOfMemoryError

### ISSUE THREAD

**Issue by yossijaki** [T8RIN/ImageToolbox#426]
I accidentally enter a big number on the resize field and it broke, this on the resize interface, hope it helps!

Device: M2102J20SG (POCO - vayu), SDK: 33 (13), App: 2.3.1 (85)java.lang.OutOfMemoryErrorat android.graphics.Bitmap.nativeCreate(Native Method)at android.graphics.Bitmap.createBitmap(Bitmap.java:1120)at android.graphics.Bitmap.createBitmap(Bitmap.java:950)at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:805)at fc.l.n(SourceFile:322)at fc.l.d0(SourceFile:13)at h6.w.p(SourceFile:5)at h6.a0.w(SourceFile:74)at fc.s.k(SourceFile:15)at fc.c.n(SourceFile:72)at fc.c.d0(SourceFile:13)at h6.w.p(SourceFile:5)at h6.a0.w(SourceFile:74)at i6.i0.h(SourceFile:15)at fc.d.n(SourceFile:144)at fc.d.d0(SourceFile:13)at h6.w.p(SourceFile:5)at h6.a0.w(SourceFile:74)at fc.s.e(SourceFile:16)at nf.j.n(SourceFile:75)at ja.a.m(SourceFile:1)at db.d0.run(SourceFile:1)at h8.n.run(SourceFile:176)at jb.i.run(SourceFile:1)at jb.a.run(SourceFile:94)Suppressed: ib.f: [o1{Cancelling}@79610b6, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
When this happened?

**Comment by T8RIN** [comment]
> I accidentally enter a big number on the resize field and it broke, this on the resize interface, hope it helps!

How large was it?

**Comment by yossijaki** [comment]
It happened when I entered to "Single edit" option, then picked a image from my gallery > scroll down and select 'Ratio' option on the 'Resize type' section > scroll up and enter different big sizes, I don't remember why I was changing the number many times, but I was able to repeat the bug entering many large numbers randomly on the Height field

**Comment by T8RIN** [comment]
> It happened when I entered to "Single edit" option, then picked a image from my gallery > scroll down and select 'Ratio' option on the 'Resize type' section > scroll up and enter different big sizes, I don't remember why I was changing the number many times, but I was able to repeat the bug entering many large numbers randomly on the Height field

Okay, thx for the info :)
