### ISSUE TITLE
FOSS version asking for update 

### ISSUE THREAD

**Issue by catgangdev** [T8RIN/ImageToolbox#427]
I am on latest foss version v2.3.1 arm64 v8. App still asking for update again and again 
![Screenshot_20230908-151746_Image Toolbox (Resizer)](https://github.com/T8RIN/ImageToolbox/assets/62982051/dace0b10-d571-4f63-8d53-4d1057fdac1f)

**Comment by T8RIN** [comment]
Yup, know that problem, i'll fix it :(

**Comment by catgangdev** [comment]
> Yup, know that problem, i'll fix it :(

Oh great. Sorry haven't found in issues tracker so thought to report it

**Comment by T8RIN** [comment]
> > Yup, know that problem, i'll fix it :(
> 
> Oh great. Sorry haven't found in issues tracker so thought to report it

Because people just said to me, thanks for the issue, i almost forget about it :)

**Comment by T8RIN** [comment]
> > Yup, know that problem, i'll fix it :(
> 
> Oh great. Sorry haven't found in issues tracker so thought to report it

Better open duplicate issue rather than miss one 👀
