### ISSUE TITLE
app doesn't pick big jpeg images

### ISSUE THREAD

**Issue by 5wHN28Dg** [T8RIN/ImageToolbox#433]
So I have this very big jpeg image 59308 x 11650 (690.9MP) that's 14.3 MB in size and the app refuses to pick it no matter what `Image source` I use, the app doesn't crash, the `Image source` just closes upon choosing it. 

I don't know if this issue applies to other image formats too.

**Comment by T8RIN** [comment]
Where did you get this image?... can you send it to me?

**Comment by T8RIN** [comment]
Maybe the android system just can't provide it to me then? Btw, even if it will be passed to my app, after saving attempt OOM will be thrown, because that's too large image

**Comment by 5wHN28Dg** [comment]
> Where did you get this image?... can you send it to me?

It is a family tree image that I created using MyHeritage hence the very high resolution, I tried blurring it using Screen Master so I wouldn't mind sending it but it downgraded its resolution significantly and PrivacyBlur closed the image picker then through a toast message 'image not selected' when I selected it😆

**Comment by T8RIN** [comment]
> > Where did you get this image?... can you send it to me?
> 
> It is a family tree image that I created using MyHeritage hence the very high resolution, I tried blurring it using Screen Master so I wouldn't mind sending it but it downgraded its resolution significantly and PrivacyBlur closed the image picker then through a toast message 'image not selected' when I selected it😆
> 
> > Btw, even if it will be passed to my app, after saving attempt OOM will be thrown, because that's too large image
> 
> What's OOM?

Of course it closed it, lol🐸🐸🐸 that's too large for phones :( not my fault...

OOM - Out Of Memory error 👀

**Comment by T8RIN** [comment]
> > Where did you get this image?... can you send it to me?
> 
> It is a family tree image that I created using MyHeritage hence the very high resolution, I tried blurring it using Screen Master so I wouldn't mind sending it but it downgraded its resolution significantly and PrivacyBlur closed the image picker then through a toast message 'image not selected' when I selected it😆
> 
> > Btw, even if it will be passed to my app, after saving attempt OOM will be thrown, because that's too large image
> 
> What's OOM?

Of course it closed it, lol🐸🐸🐸 that's too large for phones :( not my fault...

OOM - Out Of Memory error 👀

**Comment by 5wHN28Dg** [comment]
Understood but then how/why gallery and file managing apps like Simple Gallery and Material Files can open and view the image with ease? I guess image editing apps work differently, right? Anyway, I'll try to find a way to blur it without changing the resolution (maybe using a PC if necessary) and then send it.

**Comment by T8RIN** [comment]
> Understood but then how/why gallery and file managing apps like Simple Gallery and Material Files can open and view the image with ease? I guess image editing apps work differently, right? Anyway, I'll try to find a way to blur it without changing the resolution (maybe using a PC if necessary) and then send it.

Because they have full file access i think, or my app just has an internal crash , btw, even if it can view this image, you won't be able to save that because of oom :(

**Comment by 5wHN28Dg** [comment]
Simple Gallery advanced editor was able to blur it without downgrading the resolution and it got a little bit bigger in file size! Anyway here it is and btw why would it throw an OOM message?! What does 'out of memory' really mean? You mean out of RAM?! Why simple gallery editor didn't throw OOM message?

The image is too big even GitHub ends the uploading process so here it is on my GDrive, [link](https://drive.google.com/file/d/1k_ZkfKW0QIsMDWl1ZUDgXsiwyXfrlzUS/view?usp=drivesdk)

**Comment by T8RIN** [comment]
> Simple Gallery advanced editor was able to blur it without downgrading the resolution and it got a little bit bigger in file size! Anyway here it is and btw why would it throw an OOM message?! What does 'out of memory' really mean? You mean out of RAM?! Why simple gallery editor didn't throw OOM message?
> 
> The image is so big even GitHub ends the uploading process so here it is on my GDrive, [link](https://drive.google.com/file/d/1k_ZkfKW0QIsMDWl1ZUDgXsiwyXfrlzUS/view?usp=drivesdk) 

Hmm, maybe i should dive into its code, and my app will be able to do the same 👀

**Comment by T8RIN** [comment]
Which editor did you use? I didn't find "advanced editor" at simple mobile tools GitHub page

**Comment by 5wHN28Dg** [comment]
It is the built-in advanced editor in [Simple Gallery app](https://github.com/SimpleMobileTools/Simple-Gallery)

**Comment by T8RIN** [comment]
> It is the built-in advanced editor in [Simple Gallery app](https://github.com/SimpleMobileTools/Simple-Gallery) 

But there is no blur option, or i misunderstood something?

**Comment by T8RIN** [comment]
> It is the built-in advanced editor in [Simple Gallery app](https://github.com/SimpleMobileTools/Simple-Gallery) 

Where should i tap to view it? I cannot find it for some reason :(

Because it shows to me only 3 options

![Screenshot_20230914-073000_Галерея.png](https://github.com/T8RIN/ImageToolbox/assets/52178347/120c03ac-b712-45cc-9232-6aa91ebffe9a)

**Comment by 5wHN28Dg** [comment]
![ZomboDroid_14092023073808](https://github.com/T8RIN/ImageToolbox/assets/109148083/3cd02c94-5f53-41b1-bf19-c5c15b85afe6)

**Comment by T8RIN** [comment]
Lol, i just don't have it 🐸, i'll try to update

**Comment by 5wHN28Dg** [comment]
I'm using version `6.27.2`

**Comment by 5wHN28Dg** [comment]
- Just found out that the app was able to pick the image using the `Resize by weight` option but it fails to export the image even though it reports that it succeeded and switching to the `presets` mode from within the `Resize by weight` option and selecting different presets doesn't change anything (the app doesn't respond the changes I make).
- the app seems to load forever wehn selecting the image to draw on it or remove the background using the `background remover` although it is worth noting that it was able to encrypt and decrypt it
![Screenshot_20230916-121142_Image Toolbox (Resizer)](https://github.com/T8RIN/ImageToolbox/assets/109148083/1f7919f8-115f-42be-979f-7777ba9cfd07)
![Screenshot_20230916-122003_Image Toolbox (Resizer)](https://github.com/T8RIN/ImageToolbox/assets/109148083/0e4836a6-86db-4b30-8065-c40a88edc543)
![Screenshot_20230916-122022_Image Toolbox (Resizer)](https://github.com/T8RIN/ImageToolbox/assets/109148083/a1e2d0b6-1bb8-4790-8969-4685f6573297)

**Comment by T8RIN** [comment]
> - Just found out that the app was able to pick the image using the `Resize by weight` option but it fails to export the image even though it reports that it succeeded and switching to the `presets` mode from within the `Resize by weight` option and selecting different presets doesn't change anything (the app doesn't respond the changes I make).
> - the app seems to load forever when selecting the image to draw on it or remove the background using the `background remover` although it is worth noting that it was able to encrypt and decrypt it
> ![Screenshot_20230916-121142_Image Toolbox (Resizer)](https://github.com/T8RIN/ImageToolbox/assets/109148083/1f7919f8-115f-42be-979f-7777ba9cfd07)
> ![Screenshot_20230916-122003_Image Toolbox (Resizer)](https://github.com/T8RIN/ImageToolbox/assets/109148083/0e4836a6-86db-4b30-8065-c40a88edc543)
> ![Screenshot_20230916-122022_Image Toolbox (Resizer)](https://github.com/T8RIN/ImageToolbox/assets/109148083/a1e2d0b6-1bb8-4790-8969-4685f6573297)
> 
> 

Maybe it uses some other image method like async image, besides that i will check, but I can almost certainly promise that this will not be fixed...
