### ISSUE TITLE
[feature request] add ability to appear as a gallery.

### ISSUE THREAD

**Issue by not-programmer98** [T8RIN/ImageToolbox#441]
It would be a great feature.
When I'm trying to put a photo in browser like what I'm trying now I would click on photo icon, then from file manager which will appear click the 3 dots then your app should be there where I can open it and choose a photo maybe resize it and delete metadata the it's ready to be on GitHub.
Like this
![Imagepipe_0](https://github.com/T8RIN/ImageToolbox/assets/126913926/f8a6dfe3-c747-42ba-952f-f27e13afc39f)
Your app is perfect for this use case. I hope you consider adding this functionality

**Comment by not-programmer98** [comment]
Imagepip has that functionality and it's open source you could take a look at there code but it's old app didn't get updates and his crop functionality is painful and unusable

**Comment by T8RIN** [comment]
I'll take a look:)

**Comment by not-programmer98** [comment]
> I'll take a look:)

I hope you do it's a perfect feature for a perfect app.

**Comment by T8RIN** [comment]
Added this

**Comment by NikunjKhangwal** [comment]
How can i perform operations like resize & delete metadata?
