### ISSUE TITLE
Emoji list lag 

### ISSUE THREAD

**Issue by fedikhatib** [T8RIN/ImageToolbox#443]
When scrolling the emoji list it feels slow and lagging.

**Comment by T8RIN** [comment]
> When scrolling the emoji list it feels slow and lagging.

I think that's one of Jetpack Compose issue, but i'll check :(

**Comment by T8RIN** [comment]
Maybe now it will lag less, I've tried to optimise as i can, but nothing helped much.. waiting for the compose updates then(
