### ISSUE TITLE
Allow image zoom in colour picker 

### ISSUE THREAD

**Issue by catgangdev** [T8RIN/ImageToolbox#450]
Can you add zoom option in colour picker mode so we can pick colour from smaller areas too. Right now it's very difficult to pick colour from tiny areas.

**Comment by T8RIN** [comment]
It's already here, just tap tge switch at the start bottom corner

**Comment by catgangdev** [comment]
Oh how could I miss that. Didn't noticed it's a toggle switch not a button 🥲

**Comment by T8RIN** [comment]
> Oh how could I miss that. Didn't noticed it's a toggle switch not a button 🥲

No problems, at least you know now :)
