### ISSUE TITLE
[Bug] App Crash: RuntimeException

### ISSUE THREAD

**Issue by ShoeUnited** [T8RIN/ImageToolbox#451]
I had previewed an image that somebody uploaded on Discord. I viewed it I wanted to crop it.  When I chose the app from the share sheet I got this crash.

---

> Device: Pixel 5 (google - redfin), SDK: 34 (14), App: 2.3.2_foss (87)java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.tech.imageresizershrinker/ru.tech.imageresizershrinker.presentation.main_screen.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object referenceat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)at android.os.Handler.dispatchMessage(Handler.java:106)at android.os.Looper.loopOnce(Looper.java:205)at android.os.Looper.loop(Looper.java:294)at android.app.ActivityThread.main(ActivityThread.java:8177)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object referenceat ru.tech.imageresizershrinker.presentation.main_screen.MainActivity.H(SourceFile:155)at ru.tech.imageresizershrinker.presentation.main_screen.MainActivity.onCreate(SourceFile:36)at android.app.Activity.performCreate(Activity.java:8595)at android.app.Activity.performCreate(Activity.java:8573)at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)... 12 more

**Comment by T8RIN** [comment]
> I had previewed an image that somebody uploaded on Discord. I viewed it I wanted to crop it.  When I chose the app from the share sheet I got this crash.
> 
> ---
> 
> > Device: Pixel 5 (google - redfin), SDK: 34 (14), App: 2.3.2_foss (87)java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.tech.imageresizershrinker/ru.tech.imageresizershrinker.presentation.main_screen.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object referenceat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)at android.os.Handler.dispatchMessage(Handler.java:106)at android.os.Looper.loopOnce(Looper.java:205)at android.os.Looper.loop(Looper.java:294)at android.app.ActivityThread.main(ActivityThread.java:8177)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object referenceat ru.tech.imageresizershrinker.presentation.main_screen.MainActivity.H(SourceFile:155)at ru.tech.imageresizershrinker.presentation.main_screen.MainActivity.onCreate(SourceFile:36)at android.app.Activity.performCreate(Activity.java:8595)at android.app.Activity.performCreate(Activity.java:8573)at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)... 12 more
> 

Looks interesting, i will try to reproduce this one, because i saw this in crashes...

**Comment by ShoeUnited** [comment]
Second crash for you as promised
---
[Bug] App Crash: NullPointerException

Device: Pixel 5 (google - redfin), SDK: 34 (14), App: 2.3.2_foss (87)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
	at ru.tech.imageresizershrinker.presentation.main_screen.MainActivity.H(SourceFile:155)
	at ru.tech.imageresizershrinker.presentation.main_screen.MainActivity.onNewIntent(Unknown Source:3)
	at android.app.Activity.performNewIntent(Activity.java:8613)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1556)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1569)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3962)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3969)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by T8RIN** [comment]
i think i fixed this
