### ISSUE TITLE
Privacy blur feature

### ISSUE THREAD

**Issue by idontveapc** [T8RIN/ImageToolbox#454]
> ### option: Create>Draw

setting alpha either makes images just transparent or opaque lines. it should be like this:
![IMG_20230925_191721_641](https://github.com/T8RIN/ImageToolbox/assets/122597295/79a65490-26e9-47a2-a437-483392d29ee7)

**Comment by T8RIN** [comment]
> > ### option: Create>Draw
> 
> setting alpha either makes images just transparent or opaque lines. it should be like this:
> ![IMG_20230925_191721_641](https://github.com/T8RIN/ImageToolbox/assets/122597295/79a65490-26e9-47a2-a437-483392d29ee7)
> 

But this can be done i think 🤔
