### ISSUE TITLE
Permissions enhancement

### ISSUE THREAD

**Issue by serrq** [T8RIN/ImageToolbox#456]
An image resizing app cannot having "full internet access" permission. In my humble opinion. Unistalled (until this aspect will be fixed).

![1000041895](https://github.com/T8RIN/ImageToolbox/assets/113377431/1326bd2d-6fab-4df2-bd0e-8f374612c4a2)

**Comment by T8RIN** [comment]
Check #245

**Comment by T8RIN** [comment]
I'm using it to check updates only
