### ISSUE TITLE
Donation suggestion

### ISSUE THREAD

**Issue by xventivs** [T8RIN/ImageToolbox#459]
"Only the first time you run the app.  Not like you're begging. Like if I open the settings the first time you just move the category to the top and once you collapse it remembers your settings like always. 

Not have it uncollapsed every time, just the first." - provided from the Telegram.

**Comment by ameaninglessname** [comment]
Could you please enable GitHub sponsor?

**Comment by T8RIN** [comment]
It's not available in my country
