### ISSUE TITLE
Add text 😁

### ISSUE THREAD

**Issue by xventivs** [T8RIN/ImageToolbox#461]
I'm waiting for the opportunity to add text to the image

**Comment by vukasin-nikodijevic-kb** [comment]
I was surprised that this level of app doesn't have a text. 

It would be nice to have as well bubbled text - something like rounded subtitle box with the background.

**Comment by T8RIN** [comment]
It will have, but now i work on pdf tools 🐸

**Comment by T8RIN** [comment]
Closed in prior of #568
