### ISSUE TITLE
[feature] upload an image to generate link

### ISSUE THREAD

**Issue by fallsdevil** [T8RIN/ImageToolbox#463]
I'm loving this app! The functions are rich and incredible, including viewing an image from the URL/link. With that, I had an idea that it would be great if we could improve this function with the possibility of sharing one (or more) images via a link, something similar to hosting sites like Imgur for simple sharing on posts that do not allow insertion media attachments, and if possible, to make it simpler, allow the configuration of how long this link will remain active (e.g. 24 hours, or X days) to self-delete.

**Comment by T8RIN** [comment]
> I'm loving this app! The functions are rich and incredible, including viewing an image from the URL/link. With that, I had an idea that it would be great if we could improve this function with the possibility of sharing one (or more) images via a link, something similar to hosting sites like Imgur for simple sharing on posts that do not allow insertion media attachments, and if possible, to make it simpler, allow the configuration of how long this link will remain active (e.g. 24 hours, or X days) to self-delete.

Hello! Thanks for using, unfortunately I can't add this, because it needs a backend :(

**Comment by fallsdevil** [comment]
> > I'm loving this app! The functions are rich and incredible, including viewing an image from the URL/link. With that, I had an idea that it would be great if we could improve this function with the possibility of sharing one (or more) images via a link, something similar to hosting sites like Imgur for simple sharing on posts that do not allow insertion media attachments, and if possible, to make it simpler, allow the configuration of how long this link will remain active (e.g. 24 hours, or X days) to self-delete.
> 
> Hello! Thanks for using, unfortunately I can't add this, because it needs a backend :(

It's ok then, thanks!
