### ISSUE TITLE
[Bug] App Crash: RuntimeException 

### ISSUE THREAD

**Issue by ShoeUnited** [T8RIN/ImageToolbox#469]
Tried using the screenshot tile and if there isn't an instance running it activates the screencast for a second but doesn't do anything.

![Screenshot_20231005-041306](https://github.com/T8RIN/ImageToolbox/assets/221434/8e1a9def-e99e-4728-846c-266f222458da)

![Screenshot_20231005-041311](https://github.com/T8RIN/ImageToolbox/assets/221434/7121d57f-9bb7-46c3-a252-3c3b4d6f2ccb)
And then doesn't do anything.

If I have an instance running already I get this crash.
![Screenshot_20231005-041635](https://github.com/T8RIN/ImageToolbox/assets/221434/0b84d7d0-e4be-4ee4-9042-819eb9d469e4)
``
Sorry, can't record a video of it  due to it taking over the screen capturing.

Device: Pixel 5 (google - redfin), SDK: 34 (14), App: 2.3.3-alpha03 (90)java.lang.RuntimeException: Unable to start service ru.tech.imageresizershrinker.presentation.pick_color_from_image_screen.components.ScreenshotService@67788eb with Intent { cmp=ru.tech.imageresizershrinker/.presentation.pick_color_from_image_screen.components.ScreenshotService (has extras) }: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{ae88d33 30162:ru.tech.imageresizershrinker/u0a453} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media] at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4839)at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)at android.os.Handler.dispatchMessage(Handler.java:106)at android.os.Looper.loopOnce(Looper.java:205)at android.os.Looper.loop(Looper.java:294)at android.app.ActivityThread.main(ActivityThread.java:8177)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)Caused by: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{ae88d33 30162:ru.tech.imageresizershrinker/u0a453} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media] at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)at android.os.Parcel.createException(Parcel.java:3041)at android.os.Parcel.readException(Parcel.java:3024)at android.os.Parcel.readException(Parcel.java:2966)at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)at android.app.Service.startForeground(Service.java:862)at q1.f.j(SourceFile:1)at ru.tech.imageresizershrinker.presentation.pick_color_from_image_screen.components.ScreenshotService.onStartCommand(SourceFile:115)at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)... 9 more

**Comment by T8RIN** [comment]
I'll see what I can do, since there are already a lot of complaints about this :(

**Comment by ShoeUnited** [comment]
Crash log for video provided here: https://t.me/t8rin_imagetoolbox/1511/1514


[Bug] App Crash: RuntimeException

Device: Pixel 5 (google - redfin), SDK: 34 (14), App: 2.3.3-beta01 (91)

java.lang.RuntimeException: Unable to start service ru.tech.imageresizershrinker.presentation.pick_color_from_image_screen.components.ScreenshotService@a412d18 with Intent { cmp=ru.tech.imageresizershrinker/.presentation.pick_color_from_image_screen.components.ScreenshotService (has extras) }: java.lang.IllegalStateException: Must register a callback before starting capture, to manage resources in response to MediaProjection states.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4839)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.IllegalStateException: Must register a callback before starting capture, to manage resources in response to MediaProjection states.
	at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:206)
	at ru.tech.imageresizershrinker.presentation.pick_color_from_image_screen.components.ScreenshotService.onStartCommand(SourceFile:197)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)
	... 9 more

**Comment by T8RIN** [comment]
Yaaay, fixed this 👀
