### ISSUE TITLE
[Bug] App Crash: IllegalStateException

### ISSUE THREAD

**Issue by ShoeUnited** [T8RIN/ImageToolbox#470]
Added a hue filter and removed it and then left the current image without saving and in a crashed.

Device: Pixel 5 (google - redfin), SDK: 34 (14), App: 2.3.3-alpha03 (90)java.lang.IllegalStateException: item can't be savedat y0.k.e(SourceFile:1)at n.n.a(SourceFile:38)at p0.i0.a(SourceFile:1)at p0.u.b(SourceFile:49)at p0.v.k(SourceFile:58)at p0.v.j(SourceFile:6)at p0.c2.g0(SourceFile:173)at androidx.compose.ui.platform.a1.doFrame(Unknown Source:6)at androidx.compose.ui.platform.y0.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)at android.view.Choreographer.doCallbacks(Choreographer.java:952)at android.view.Choreographer.doFrame(Choreographer.java:878)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)at android.os.Handler.handleCallback(Handler.java:958)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:205)at android.os.Looper.loop(Looper.java:294)at android.app.ActivityThread.main(ActivityThread.java:8177)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)Suppressed: sb.h: [p0.k1@7605bae, androidx.compose.ui.platform.x1@68a3d4f, r1{Cancelling}@1a45cdc, z0@56ec1e5]

**Comment by T8RIN** [comment]
Left it and closed the app?

**Comment by ShoeUnited** [comment]
> Left it and closed the app?
Yes, I exited out of editing the image without saving and the app crashed. I'll try to recreate this issue with the new version.  But I believe that's all I did.

**Comment by T8RIN** [comment]
> > Left it and closed the app?
> 
> Yes, I exited out of editing the image without saving and the app crashed. I'll try to recreate this issue with the new version.  But I believe that's all I did.
> 
> *now to see if it depends on what image. I'll update this comment if I do it again.*
> 
> ### Cannot replicate in **2.3.3-beta01 (91)**
> Suggest closing ticket.

I think this is some kind of rare library glitch, I'll close it for now and then we'll see
