### ISSUE TITLE
[Bug] App Crash: OutOfMemoryError

### ISSUE THREAD

**Issue by ShoeUnited** [T8RIN/ImageToolbox#475]
Yeah this is mostly PEBCAK but I was trying to resize an image by ratio and it refused to scale either side downwards . Now maybe I didn't understand how it's supposed to work but I was trying to make one side smaller stuff the other side would resize in proportion. So it wouldn't let me change numbers. It kept refilling and changing them. As is tradition of software users, I did nothing but pound in zeros until it broke. Instead of asking for help or doing anything that may have actually worked.  I'll get a video up for you shortly.

######  Feature request: let me delete all the numbers when changing resolution of one side window for ratio. Instead of the changing it because it has a blank space at least not so fast a little too strict on that one but it was PEBCAK. what can ya do?

Device: Pixel 5 (google - redfin), SDK: 34 (14), App: 2.3.3-alpha03 (90)java.lang.OutOfMemoryErrorat android.graphics.Bitmap.nativeCreate(Native Method)at android.graphics.Bitmap.createBitmap(Bitmap.java:1206)at android.graphics.Bitmap.createBitmap(Bitmap.java:979)atandroid.graphics.Bitmap.createScaledBitmap(Bitmap.java:831)at pc.l.l(SourceFile:325)at pc.l.V(SourceFile:13)at k6.r5.A(SourceFile:5)at la.i.I(SourceFile:74)at pc.s.l(SourceFile:15)at pc.c.l(SourceFile:72)at pc.c.V(SourceFile:13)at k6.r5.A(SourceFile:5)at la.i.I(SourceFile:74)at k6.y4.s(SourceFile:15)at pc.d.l(SourceFile:138)at pc.d.V(SourceFile:13)at k6.r5.A(SourceFile:5)at la.i.I(SourceFile:74)at pc.s.f(SourceFile:16)at ag.j.l(SourceFile:75)at ra.a.n(SourceFile:1)at nb.e0.run(SourceFile:1)at n8.m.run(SourceFile:176)at tb.i.run(SourceFile:1)at tb.a.run(SourceFile:94)Suppressed: sb.h: [r1{Cancelling}@8137ccd, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
It seems to have been fixed, but what you are saying is that it allows you to enter other values, then not allowing this is a feature of the ratio mode, if you want so, then use flexible resize mode 🐸
