### ISSUE TITLE
[feature] background option for cropped images

### ISSUE THREAD

**Issue by fallsdevil** [T8RIN/ImageToolbox#480]
would like to make a suggestion of an interesting function that I miss, when the image can not be cut in 1:1 for example, and we have to adapt it on a smaller background that it causing edges on the sides, leaving these edges with Blur effect.

To be clearer I will leave this image that I made a screenshot in the app "PicsArt" to demonstrate this feature:
![Screenshot_20231010-214824](https://github.com/T8RIN/ImageToolbox/assets/142761950/a53e1071-af02-4d1c-a0ff-082e50347ee5)

would be a useful and interesting resource for these simple and basic cut/adapt edits.

**Comment by T8RIN** [comment]
Hm, would canvas extending fit you? Because I've added this but with background color, maybe blurred background will be also useful, also Maybe I should add different Aspect ratios to crop available, if you are using canvas extending, thanks for the request :)

**Comment by fallsdevil** [comment]
Yes, it would be cool some aspects image cropping ratio! and sorry but did not know this option that already exists in the app, so I did not notice with color background 😅

**Comment by T8RIN** [comment]
> Yes, it would be cool some aspects image cropping ratio! and sorry but did not know this option that already exists in the app, so I did not notice with color background 😅

This resizing mode presented in latest beta 👀
