### ISSUE TITLE
[BUG] Draw tools cause slowdown.

### ISSUE THREAD

**Issue by ShoeUnited** [T8RIN/ImageToolbox#482]
Using the paint brushes causes significant lag when applied after a few layers. 

Pixel 5 (Redfin) Running Android 14

#####  *Report will be updated shortly with link to video.*

https://t.me/t8rin_imagetoolbox/1511/1516

**Comment by T8RIN** [comment]
> Using the paint brushes causes significant lag when applied after a few layers. 
> 
> Pixel 5 (Redfin) Running Android 14
> 
> #####  *Report will be updated shortly with link to video.*

I encountered this problem, i hope i'll find a solution, because i don't know how to fix it right now :(

**Comment by ShoeUnited** [comment]
> > Using the paint brushes causes significant lag when applied after a few layers.
> > Pixel 5 (Redfin) Running Android 14
> > ##### _Report will be updated shortly with link to video._
> 
> I encountered this problem, i hope i'll find a solution, because i don't know how to fix it right now :(

Sorry boss. I don't suppose it's a matter of off-loading onto swap is it?

**Comment by T8RIN** [comment]
I hope i found solution, we will see if it works :)
