### ISSUE TITLE
app always opens in camera instead of gallery

### ISSUE THREAD

**Issue by mxKeaton** [T8RIN/ImageToolbox#484]
No matter what settings I choose or even after I reset/reinstall the app, it always opens up after clicking on the gallery button on the camera app. I don't see any option to disable that behaviour nor did I give it any special access to allow that. I might be blind and missed something, but then it would need to get more accessible.

**Comment by T8RIN** [comment]
Hmm

**Comment by T8RIN** [comment]
Can you show it?

**Comment by T8RIN** [comment]
Can you show it?

**Comment by mxKeaton** [comment]
https://drive.google.com/file/d/17IThy3-jqNepy8fi-fQgJOjWdNYHXFzG/view?usp=drivesdk

**Comment by T8RIN** [comment]
> https://drive.google.com/file/d/17IThy3-jqNepy8fi-fQgJOjWdNYHXFzG/view?usp=drivesdk

Hmm, it looks like it's not my app's fault, but what kind of icon set do you have, by the way?👀

**Comment by T8RIN** [comment]
> https://drive.google.com/file/d/17IThy3-jqNepy8fi-fQgJOjWdNYHXFzG/view?usp=drivesdk

Hmm, it looks like it's not my app's fault, but what kind of icon set do you have, by the way?👀

**Comment by mxKeaton** [comment]
Customised "Pix Material You" is the icon pack. You like it?

If it is not your apps fault then where should I look? I use pixel experience maybe that is the issue. Sadly I can not keep the app installed with that issue occurring everytime I take a picture. Throws me off completely every time

**Comment by tttooommmeeekkk** [comment]
> Customised "Pix Material You" is the icon pack. You like it?
> 
> If it is not your apps fault then where should I look? I use pixel experience maybe that is the issue. Sadly I can not keep the app installed with that issue occurring everytime I take a picture. Throws me off completely every time

Did you already found a solution for your problem switching directly to the image gallery by pressing the button inside the camera app?
I have the same issue using standard camera app from e/OS (murena OS) on an fairphone5.
Would be a pity if the only way is uninstalling the image toolbox.

**Comment by pbiering** [comment]
Can one please reopen this issue as it still persist

OS: iode 6.6 (Android 15) / App: Open Camera 1.54.1

ImageToolbox deinstalled -> Open Camera asks for which app should used for image display, "Gallery" selected and confirmed for "always"

ImageToolbox reinstalled -> Open Camera is automatically using "ImageToolbox" again.

Would be very nice to have either in ImageToolbox or in OpenCamera an option about such default behavior
