### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by plum7x** [T8RIN/ImageToolbox#485]
The app crash when opening image link from shared.
To avoid that I only can copy image link to "Load image from net" manually.

Another question
The force option in limits resize, it not only convert image, also zoom in image to fit limit. But this is different from my expectation (just force recode).
https://github.com/T8RIN/ImageToolbox/issues/322#issuecomment-1763425750

**Comment by T8RIN** [comment]
Is it persists in latest beta?

**Comment by plum7x** [comment]
No crash, bat i got an error message "something went wrong", it is still working abnormally.

**Comment by T8RIN** [comment]
At least not a crash 🐸 I'll investigate

**Comment by T8RIN** [comment]
Fixed!
