### ISSUE TITLE
blur in draw on

### ISSUE THREAD

**Issue by idontveapc** [T8RIN/ImageToolbox#490]
option is added great!

but we got one option to set lines’ width. we'd also want customisable **`blur radius`**, as if how much we want to hide the image data. also **`transparency`**, to control how much background colour must blur expand or mix. and if possible **`saturation`** to make certion clours achieve its true colours after or before blurring.

**Comment by T8RIN** [comment]
Blur radius will be added , but I'm not sure about the rest 👀

**Comment by T8RIN** [comment]
In general, there are plans to apply filters based on the mask drawn, I think there will be a lot of things there
