### ISSUE TITLE
Add Monero (XMR) donation address

### ISSUE THREAD

**Issue by nahuhh** [T8RIN/ImageToolbox#492]
Can use Feather Wallet or Monero GUI to manage funds on desktop. Cake Wallet or monerujo on mobile. 

tldr: Monero isn't an altcoin, it's heavily used digital cash.

BTC is expensive, slow and transparent.
At this time, I'd accept XMR-only, or XMR + BTC + LTC, since LTC functions much better than BTC as well.

Thanks

**Comment by T8RIN** [comment]
> Can use Feather Wallet or Monero GUI to manage funds on desktop. Cake Wallet or monerujo on mobile. 
> 
> tldr: Monero isn't an altcoin, it's heavily used digital cash.
> 
> BTC is expensive, slow and transparent.
> At this time, I'd accept XMR-only, or XMR + BTC + LTC, since LTC functions much better than BTC as well.
> 
> Thanks
> 
> 

What is XMR + BTC + LTC ?👀

**Comment by T8RIN** [comment]
Created wallet in Cake, thanks for the advice :)

```48sgrSJFQfLQcZeCCG2GfGeAoSfFRVR14c1wsWyNGLU1KpEi2SYhNfiY7SYK7SsfvJcumq7dkd2BRM6f6xVSC6nK1u4z5T4```

**Comment by T8RIN** [comment]
> Created wallet in Cake, thanks for the advice :)
> 
>
I hope it at least correct 🐸

```48sgrSJFQfLQcZeCCG2GfGeAoSfFRVR14c1wsWyNGLU1KpEi2SYhNfiY7SYK7SsfvJcumq7dkd2BRM6f6xVSC6nK1u4z5T4```

**Comment by nahuhh** [comment]
> Created wallet in Cake, thanks for the advice :)
> 
> I hope it at least correct 🐸
> 
> ```48sgrSJFQfLQcZeCCG2GfGeAoSfFRVR14c1wsWyNGLU1KpEi2SYhNfiY7SYK7SsfvJcumq7dkd2BRM6f6xVSC6nK1u4z5T4```

Perfect 👌, thanks

**Comment by Alexandru51** [comment]
I think you forgot to add in your "readme.md"

**Comment by T8RIN** [comment]
in my opinion it doesn't work, at least I don't really like how, I added TON, it's better i thought

**Comment by nahuhh** [comment]
What doesn't work? XMR? ...
https://twitter.com/was_not_here/status/1684664142056095744

also, should add here:
![lq12woxfg68y8505.jpg](https://github.com/T8RIN/ImageToolbox/assets/50635951/f98dd289-8148-40ab-8f13-0c247a2af901)

**Comment by T8RIN** [comment]
This wallet

**Comment by T8RIN** [comment]
I added ton

**Comment by nahuhh** [comment]
Cake wallet doesn't work? 
That doesnt make sense. 

feel free to contact me at @ofrnxmr:monero.social on matrix or on [simplex](https://simplex.chat/contact#/?v=1-2&smp=smp%3A%2F%2F6iIcWT_dF2zN_w5xzZEY7HI2Prbh3ldP07YTyDexPjE%3D%40smp10.simplex.im%2FP1JDEeJuEimENIJY8W-ZtPjx0uG6dVaj%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEAx1AIMuCtyoxOxVPgOBchc9ub8bw-cc4AS5Zs8nZSPAk%253D%26srv%3Drb2pbttocvnbrngnwziclp2f4ckjq65kebafws6g4hy22cdaiv5dwjqd.onion)

(What in the world is a TON?... thats 100m market cap pump and dump?)

not interested in coins nobody uses, gimmicks, or whatever a TON is. 

The only coins you need to accept are xmr and btc. 
Even usdt is a waste of your time.

**Comment by T8RIN** [comment]
> Cake wallet doesn't work? 
> That doesnt make sense. 
> 
> feel free to contact me at @ofrnxmr:monero.social on matrix or on [simplex](https://simplex.chat/contact#/?v=1-2&smp=smp%3A%2F%2F6iIcWT_dF2zN_w5xzZEY7HI2Prbh3ldP07YTyDexPjE%3D%40smp10.simplex.im%2FP1JDEeJuEimENIJY8W-ZtPjx0uG6dVaj%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEAx1AIMuCtyoxOxVPgOBchc9ub8bw-cc4AS5Zs8nZSPAk%253D%26srv%3Drb2pbttocvnbrngnwziclp2f4ckjq65kebafws6g4hy22cdaiv5dwjqd.onion)
> 
> (What in the world is a TON?... thats 100m market cap pump and dump?)
> 
> not interested in coins nobody uses, gimmicks, or whatever a TON is. 
> 
> The only coins you need to accept are xmr and btc. 
> Even usdt is a waste of your time.
> 
> 

I transfer to btc anyway, cake wallet works, but i don't know if it can receive anything, just saying sync everytime

**Comment by nahuhh** [comment]
Cake should show (at the top):
"connecting > attempting sync > synchronizing (blocks remaining) > synchronized"
