### ISSUE TITLE
[Bug] App Crash: IllegalStateException

### ISSUE THREAD

**Issue by niks255** [T8RIN/ImageToolbox#495]
Device: Mi 9 Lite (Xiaomi - pyxis), SDK: 30 (11), App: 2.4.1 (94)java.lang.IllegalStateException: LayoutNode should be attached to an ownerat m0.c.v(SourceFile:14)at z1.e0.p0(SourceFile:20)at z1.e0.X(SourceFile:71)at x1.z0.b(SourceFile:30)at v.t.a(SourceFile:96)at v.t.s(SourceFile:17)at x1.o0.k(SourceFile:37)at x1.c0.k(SourceFile:15)at q.k0.a(SourceFile:103)at q.k0.c(SourceFile:79)at l2.h0.H(SourceFile:59)at c1.x.a(SourceFile:48)at c1.y.c(SourceFile:162)at z1.g1.a(SourceFile:1)at z1.e0.f(SourceFile:132)at n.o.s(SourceFile:1280)at z1.e0.x(SourceFile:24)at z1.a.g(SourceFile:1)at z1.e0.f(SourceFile:170)at z1.e0.o0(SourceFile:131)at z1.e0.p0(SourceFile:63)at z1.e0.X(SourceFile:71)at x1.z0.f(SourceFile:66)at p0.s0.s(SourceFile:152)at x1.o0.k(SourceFile:37)at q.k0.a(SourceFile:103)at q.k0.c(SourceFile:79)at l2.h0.H(SourceFile:59)at c1.x.a(SourceFile:48)at c1.y.c(SourceFile:162)at z1.g1.a(SourceFile:1)at z1.e0.f(SourceFile:132)at z1.e0.o0(SourceFile:131)at z1.p.X(SourceFile:18)at x1.z0.i(SourceFile:29)at x1.z0.j(SourceFile:1)at r.s.d(SourceFile:330)at r.s.s(SourceFile:171)at x1.o0.k(SourceFile:37)at z1.u.X(SourceFile:42)at x1.z0.b(SourceFile:30)at v.q0.a(SourceFile:44)at v.q0.s(SourceFile:17)at x1.o0.k(SourceFile:37)at z1.u.X(SourceFile:42)at x1.z0.d(SourceFile:26)at r.y0.a(SourceFile:268)at r.y0.c(SourceFile:215)at l2.h0.H(SourceFile:59)at c1.x.a(SourceFile:48)at c1.y.c(SourceFile:162)at z1.g1.a(SourceFile:1)at z1.e0.p0(SourceFile:88)at androidx.compose.ui.node.a.M(SourceFile:32)at z1.j0.j(SourceFile:273)at z1.j0.g(SourceFile:67)at androidx.compose.ui.platform.AndroidComposeView.onLayout(Unknown Source:4)at android.view.View.layout(View.java:22844)at android.view.ViewGroup.layout(ViewGroup.java:6389)at androidx.compose.ui.platform.a.f(SourceFile:1)at androidx.compose.ui.platform.a.onLayout(Unknown Source:6)at android.view.View.layout(View.java:22844)at android.view.ViewGroup.layout(ViewGroup.java:6389)at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)at android.widget.FrameLayout.onLayout(FrameLayout.java:270)at android.view.View.layout(View.java:22844)at android.view.ViewGroup.layout(ViewGroup.java:6389)at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)at android.view.View.layout(View.java:22844)at android.view.ViewGroup.layout(ViewGroup.java:6389)at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)at android.widget.FrameLayout.onLayout(FrameLayout.java:270)at android.view.View.layout(View.java:22844)at android.view.ViewGroup.layout(ViewGroup.java:6389)at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)at android.view.View.layout(View.java:22844)at android.view.ViewGroup.layout(ViewGroup.java:6389)at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)at android.widget.FrameLayout.onLayout(FrameLayout.java:270)at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)at android.view.View.layout(View.java:22844)at android.view.ViewGroup.layout(ViewGroup.java:6389)at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3475)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)at android.view.Choreographer.doCallbacks(Choreographer.java:796)at android.view.Choreographer.doFrame(Choreographer.java:731)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loop(Looper.java:223)at android.app.ActivityThread.main(ActivityThread.java:7664)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Image: 
![4174_double_1_1080x2340](https://github.com/T8RIN/ImageToolbox/assets/4942241/65dfff25-28d8-4ce4-bfe4-5caa42ef61c6)

**Comment by T8RIN** [comment]
Which steps should I do to reproduce it?

**Comment by niks255** [comment]
> Which steps should I do to reproduce it?

Edit the imagine, add the stack blur filter and change the values. It crashes on preview consistently.

**Comment by T8RIN** [comment]
fixed
