### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by foobsr1** [T8RIN/ImageToolbox#498]
Device: Armor 17 Pro (Ulefone - Armor_17_Pro), SDK: 31 (12), App: 2.4.1 (94)java.lang.IllegalArgumentException: Lookahead pass was never done for target content.at p.s.d(SourceFile:99)at z1.p.a(SourceFile:38)at p.k1.h(SourceFile:1)at z1.u.a(SourceFile:11)at k1.r0.h(SourceFile:1)at z1.u.a(SourceFile:11)at p.z.a(SourceFile:88)at p.z.o(SourceFile:15)at x1.y.h(SourceFile:8)at z1.u.a(SourceFile:11)at q.k0.a(SourceFile:34)at q.k0.c(SourceFile:75)at l2.h0.H(SourceFile:59)at c1.x.a(SourceFile:48)at c1.y.c(SourceFile:162)at z1.g1.a(SourceFile:1)at z1.e0.q0(SourceFile:107)at z1.e0.a(SourceFile:106)at p.n0.q(SourceFile:78)at x1.d0.d(SourceFile:49)at z1.p.a(SourceFile:38)at k1.r0.h(SourceFile:1)at z1.u.a(SourceFile:11)at q.k0.a(SourceFile:34)at q.k0.c(SourceFile:75)at l2.h0.H(SourceFile:59)at c1.x.a(SourceFile:48)at c1.y.c(SourceFile:162)at z1.g1.a(SourceFile:1)at z1.e0.q0(SourceFile:107)at z1.j0.c(SourceFile:55)at z1.j0.j(SourceFile:146)at z1.j0.g(SourceFile:67)at androidx.compose.ui.platform.AndroidComposeView.w(SourceFile:32)at z1.c1.a(SourceFile:4)at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)at android.view.View.draw(View.java:22792)at android.view.View.updateDisplayListIfDirty(View.java:21620)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4572)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4545)at android.view.View.updateDisplayListIfDirty(View.java:21564)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4572)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4545)at android.view.View.updateDisplayListIfDirty(View.java:21564)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4572)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4545)at android.view.View.updateDisplayListIfDirty(View.java:21564)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4572)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4545)at android.view.View.updateDisplayListIfDirty(View.java:21564)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4572)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4545)at android.view.View.updateDisplayListIfDirty(View.java:21564)at android.view.View.draw(View.java:22502)at android.view.ViewGroup.drawChild(ViewGroup.java:4588)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4349)at android.view.View.draw(View.java:22792)at com.android.internal.policy.DecorView.draw(DecorView.java:1015)at android.view.View.updateDisplayListIfDirty(View.java:21620)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4647)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4363)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3494)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2248)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9045)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1105)at android.view.Choreographer.doCallbacks(Choreographer.java:896)at android.view.Choreographer.doFrame(Choreographer.java:815)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1090)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:201)at android.os.Looper.loop(Looper.java:288)at android.app.ActivityThread.main(ActivityThread.java:7924)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by foobsr1** [comment]
Happens after the new version notification notorioudly refuses to go away

**Comment by T8RIN** [comment]
Try last beta, i fixed Maybe
