### ISSUE TITLE
Update dialoge makes app unusable

### ISSUE THREAD

**Issue by NobodyForNothing** [T8RIN/ImageToolbox#499]
After installing version 2.4.1 from fdroid and granting the directory permission the update dialogue for version 2.4.2-alpha pops up. 

Pulling the dialoge sheet down causes it to reappear after half a second.

This bug makes the app unusable.

![Screenshot_2023-10-22-15-39-16-442_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageToolbox/assets/82763757/a5d84fc9-524c-46a8-b604-1ec76cfe7a62)

**Comment by T8RIN** [comment]
Fixed already bu #496

**Comment by T8RIN** [comment]
You can also tap OK and all will be fine

**Comment by MrScreemi** [comment]
> You can also tap OK and all will be fine

There is no ok button. 

https://youtube.com/shorts/xiL20Ut11Q0?si=_8RUS1eTyO65p60K

**Comment by T8RIN** [comment]
I will try to fix this in 2.4.2, it might be not a big but important update
