### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by orsopedro** [T8RIN/ImageToolbox#500]
Device: RMX3241 (realme - RE513CL1), SDK: 33 (13), App: 2.4.1 (94)java.lang.NullPointerExceptionat h9.d.w(SourceFile:56)at g7.a.u(SourceFile:1)at b8.c0.run(SourceFile:1)at k.j.run(SourceFile:253)at h8.i.run(SourceFile:1)at h8.a.run(SourceFile:94)Suppressed: g8.e: [m1{Cancelling}@e4acad, Dispatchers.Main]

**Comment by T8RIN** [comment]
Steps to reproduce?

**Comment by orsopedro** [comment]
Hi.
  

  
This happens when I start the application.    just clicking on the icon.

**Comment by T8RIN** [comment]
Latest beta also?

**Comment by orsopedro** [comment]
I installed using f-droid.    I'll try on github

**Comment by orsopedro** [comment]
2.4.2-alpha1 running ok.
  
Thanks a lot.
  
I'll try it

**Comment by T8RIN** [comment]
Good :)
