### ISSUE TITLE
Library?

### ISSUE THREAD

**Issue by opk12** [T8RIN/ImageToolbox#501]
What is the state of things in regards to embedding as a library into a third-party gallery app? Perhaps a trimmed version with few dependencies, as the apk is 25 MB.

Context is that the gallery app Aves Libre ([GitHub](https://github.com/deckerst/aves), [F-droid](https://f-droid.org/en/packages/deckers.thibault.aves.libre/)) has a [feature request](https://github.com/deckerst/aves/issues/17) for a basic editor, and I was thinking about this app.

**Comment by T8RIN** [comment]
25 is for all apk architectures, for a specific device, it will weigh approximately 10 MB

**Comment by T8RIN** [comment]
> What is the state of things in regards to embedding as a library into a third-party gallery app? Perhaps a trimmed version with few dependencies, as the apk is 25 MB.
> 
> Context is that the gallery app Aves Libre ([GitHub](https://github.com/deckerst/aves), [F-droid](https://f-droid.org/en/packages/deckers.thibault.aves.libre/)) has a [feature request](https://github.com/deckerst/aves/issues/17) for a basic editor, and I was thinking about this app.

It's possible, but I don't really understand why if it doesn't have an interface

**Comment by opk12** [comment]
Perfect, thank you for the quick reply!

> It's possible, but I don't really understand why if it doesn't have an interface

I just mean as an embedded editor that pops up when pressing a button in the main "gallery" app (sorry for the terminology, I am a user but not an Android dev).
