### ISSUE TITLE
I have a question/suggestion

### ISSUE THREAD

**Issue by fallsdevil** [T8RIN/ImageToolbox#504]
This is basically just another question, but it would be an interesting suggestion too.

This app is amazing, and my question would be is there any chance of this app (or a variant of it) having the ability to edit simple videos? because I miss this type of editing simple, for example video cuts (split, trim) crop aspect ratio, etc. with few resources to make it a lightweight app, such as simple text or a blur effect to hide content of sensitive data or irrelevant.

So far I haven't been able to find an open source like this and it would be useful.
The suggestion would basically be to create a specific app for this instead of including it in the Image ToolBox, or if you know of any app with these features I would be happy to know.

**Comment by T8RIN** [comment]
**Image**Toolbox 👀

**Comment by fallsdevil** [comment]
> **Image**Toolbox 👀

fact 😅, one of the reasons I said about a different app. but thanks!

**Comment by T8RIN** [comment]
> > **Image**Toolbox 👀
> 
> fact 😅, one of the reasons I said about a different app. but thanks!

I don't know about such apps, but maybe in the future there will be **Video**Toolbox 🐸
