### ISSUE TITLE
App closes while editing image 

### ISSUE THREAD

**Issue by catgangdev** [T8RIN/ImageToolbox#506]
I am trying to remove background from an image using mannual brush but when I start to erase app closes. No errors just app closes itself... Let me know if need more information 🙂

**Comment by T8RIN** [comment]
Version and android? It definetly can't close by no reason 🐸

**Comment by catgangdev** [comment]
> Version and android? It definetly can't close by no reason 🐸

2.4.1 foss (94)
Android 13

**Comment by T8RIN** [comment]
> > Version and android? It definetly can't close by no reason 🐸
> 
> 2.4.1 foss (94)
> Android 13 
> Tried to erase background from different images but it still closes. I am opening image from Create tab > background remover 

Hmm, can you record a video please?

**Comment by catgangdev** [comment]
Trying to upload here but it's failing. Let me upload somewhere else and share the link

**Comment by catgangdev** [comment]
> > > Version and android? It definetly can't close by no reason 🐸
> > 
> > 
> > 2.4.1 foss (94)
> > Android 13
> > Tried to erase background from different images but it still closes. I am opening image from Create tab > background remover
> 
> Hmm, can you record a video please?

https://filetransfer.io/data-package/DC3I6Lvf#link

**Comment by T8RIN** [comment]
Weird :( I'll take a look

**Comment by catgangdev** [comment]
> Weird :( I'll take a look

Do you need Dropbox log ?

**Comment by T8RIN** [comment]
> > Weird :( I'll take a look
> 
> Do you need Dropbox log ? Not sure there would be something in log as it's not a crash.

Come on, because this is very strange behavior (

**Comment by catgangdev** [comment]
> > > Weird :( I'll take a look
> > 
> > 
> > Do you need Dropbox log ? Not sure there would be something in log as it's not a crash.
> 
> Okay, because this is very strange behavior (

Using latest alpha and somehow it's not closing app while removing background. So far working good 👍

**Comment by T8RIN** [comment]
Okay, that's good 👀
