### ISSUE TITLE
[Bug] App Crash: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by manishji749** [T8RIN/ImageToolbox#507]
Device: Redmi Note 9 Pro (Redmi - curtana), SDK: 31 (12), App: 2.4.2-alpha01 (95)java.lang.IndexOutOfBoundsException: Index 2, size 2at x.z0.b(SourceFile:31)at x.z0.c(SourceFile:1)at v6.e7.c(SourceFile:5)at v.o.b(SourceFile:1)at v.u.a(SourceFile:7)at v.v.o(SourceFile:1279)at r.v0.o(SourceFile:359)at w1.f0.e(SourceFile:74)at y1.p.a(SourceFile:51)at q.m.h(SourceFile:44)at q.m.n(SourceFile:476)at w1.z.f(SourceFile:8)at y1.p.a(SourceFile:83)at q.m.h(SourceFile:10)at q.m.n(SourceFile:489)at w1.z.f(SourceFile:8)at y1.p.a(SourceFile:83)at j1.r0.f(SourceFile:1)at y1.p.a(SourceFile:83)at j1.r0.f(SourceFile:1)at y1.p.a(SourceFile:83)at y1.e0.d(SourceFile:26)at l8.d.e(SourceFile:59)at b1.y.b(SourceFile:48)at b1.z.c(SourceFile:162)at y1.g1.a(SourceFile:1)at y1.c0.o0(SourceFile:139)at y1.k0.b(SourceFile:44)at y1.k0.j(SourceFile:139)at y1.k0.g(SourceFile:67)at androidx.compose.ui.platform.AndroidComposeView.q(SourceFile:32)at y1.c1.a(SourceFile:4)at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)at android.view.View.draw(View.java:23005)at android.view.View.updateDisplayListIfDirty(View.java:21869)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21822)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21822)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21822)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21822)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21822)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)at android.view.View.updateDisplayListIfDirty(View.java:21822)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4652)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4370)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3481)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2272)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1160)at android.view.Choreographer.doCallbacks(Choreographer.java:950)at android.view.Choreographer.doFrame(Choreographer.java:879)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1142)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:210)at android.os.Looper.loop(Looper.java:299)at android.app.ActivityThread.main(ActivityThread.java:8319)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by T8RIN** [comment]
When happened, steps to reproduce?

**Comment by jont4** [comment]
> When happened, steps to reproduce?

same crash log here.
This happened when I was fiddling with the scroll button in the Resize Size option page:

![Screenshot_20231025-205524_Image Toolbox (Resizer)_1_1](https://github.com/T8RIN/ImageToolbox/assets/31804298/72ee0f68-49f2-47d5-8352-569937629658)

**Comment by T8RIN** [comment]
It seems to be a Comppse library bug (

**Comment by T8RIN** [comment]
https://github.com/zed-alpha/shadow-gadgets/issues/1 here it explained a bit

**Comment by mecuricat** [comment]
I also encountered the same issue. I could only reproduce it 2 out of 5 times. In my case, it occurred when I shared 10 photos to this app and started stitching.

**Comment by T8RIN** [comment]
Info in #529
