### ISSUE TITLE
[Bug] App Crash: RuntimeException (Image too large ;-;)

### ISSUE THREAD

**Issue by Applewubs** [T8RIN/ImageToolbox#509]
Device: 23049PCD8G (POCO - marble), SDK: 33 (13), App: 2.4.2 (97)java.lang.RuntimeException: Canvas: trying to draw too large(531069896bytes) bitmap.at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:145)at j1.c.v(SourceFile:102)at l1.c.c0(SourceFile:34)at y1.b0.c0(SourceFile:1)at l1.e.c(SourceFile:120)at m1.a.i(SourceFile:1)at m1.b.g(SourceFile:99)at q4.o.i(SourceFile:52)at m1.b.g(SourceFile:99)at q4.t.i(SourceFile:95)at y1.d.i(SourceFile:1)at y1.b0.b(SourceFile:32)at y1.v0.x0(SourceFile:50)at y1.v0.w0(SourceFile:25)at y1.v.Q0(SourceFile:6)at y1.v0.x0(SourceFile:8)at q.z0.a(SourceFile:229)at q.z0.d(SourceFile:211)at m8.d.e(SourceFile:59)at b1.y.b(SourceFile:48)at b1.z.c(SourceFile:162)at y1.h1.a(SourceFile:1)at y1.r0.s(SourceFile:603)at androidx.compose.ui.platform.d2.w(SourceFile:24)at androidx.compose.ui.platform.f2.e(SourceFile:40)at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:69)at android.view.View.draw(View.java:23414)at android.view.View.updateDisplayListIfDirty(View.java:22246)at android.view.View.draw(View.java:23123)at android.view.ViewGroup.drawChild(ViewGroup.java:4582)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4340)at android.view.View.updateDisplayListIfDirty(View.java:22235)at android.view.View.draw(View.java:23123)at android.view.ViewGroup.drawChild(ViewGroup.java:4582)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4340)at android.view.View.updateDisplayListIfDirty(View.java:22235)at android.view.View.draw(View.java:23123)at android.view.ViewGroup.drawChild(ViewGroup.java:4582)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4340)at android.view.View.updateDisplayListIfDirty(View.java:22235)at android.view.View.draw(View.java:23123)at android.view.ViewGroup.drawChild(ViewGroup.java:4582)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4340)at android.view.View.updateDisplayListIfDirty(View.java:22235)at android.view.View.draw(View.java:23123)at android.view.ViewGroup.drawChild(ViewGroup.java:4582)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4340)at android.view.View.updateDisplayListIfDirty(View.java:22235)at android.view.View.draw(View.java:23123)at android.view.ViewGroup.drawChild(ViewGroup.java:4582)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4340)at android.view.View.draw(View.java:23414)at com.android.internal.policy.DecorView.draw(DecorView.java:896)at android.view.View.updateDisplayListIfDirty(View.java:22246)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4927)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4628)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3816)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2546)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9498)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1467)at android.view.Choreographer.doCallbacks(Choreographer.java:1089)at android.view.Choreographer.doFrame(Choreographer.java:1003)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1435)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:211)at android.os.Looper.loop(Looper.java:300)at android.app.ActivityThread.main(ActivityThread.java:8395)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by T8RIN** [comment]
When and how?👀

**Comment by Applewubs** [comment]
> When and how?👀

When trying to open a pretty large picture with any option, in resizers it just doesn't shows and on IMG preview it'll crash. (The picture in question is 16387*8102, size is 142.69MB)

**Comment by T8RIN** [comment]
> > When and how?👀
> 
> When trying to open a pretty large picture with any option, in resizers it just doesn't shows and on IMG preview it'll crash. (The picture in question is 16387*8102, size is 142.69MB)
> 
> [Gotta add, the picture is correctly previewed in any other editor or gallery (I use Aves gallery and Xiaomi default editor)

Well, I know how it could be opened without crashes, in fact, in the preview option it should open normally, the problem here is that I won’t be able to save it, since I’m using a  Bitmap object for all operations and at one moment it can't be placed in the memory (

**Comment by Applewubs** [comment]
> > > When and how?👀
> > 
> > 
> > When trying to open a pretty large picture with any option, in resizers it just doesn't shows and on IMG preview it'll crash. (The picture in question is 16387*8102, size is 142.69MB)
> > [Gotta add, the picture is correctly previewed in any other editor or gallery (I use Aves gallery and Xiaomi default editor)
> 
> Well, I know how it could be opened without crashes, in fact, in the preview option it should open normally, the problem here is that I won’t be able to save it, since I’m using a Bitmap object for all operations and at one moment it can't be placed in the memory (


https://github.com/T8RIN/ImageToolbox/assets/59571080/49fb738d-941b-4cb0-8793-68329082c2c6

I mean, it pretty much just straight up crashes, I guess this is sadly am unrepairable bug.

**Comment by T8RIN** [comment]
Did you try the image preview screen? It's under the tools section

**Comment by Applewubs** [comment]
> Did you try the image preview screen? It's under the tools section

It's the one I try second on the video
