### ISSUE TITLE
[Feature Request] stitching enhancement

### ISSUE THREAD

**Issue by plum7x** [T8RIN/ImageToolbox#513]
The long screenshot on Android is not works in some cases. for that we must take each part manually then combine them.

But we will get some redundancy part on one of the screenshot, so we need a way to eliminate it.

The following is my suggestion, add specified image to a layer, then use negative value in pixels for spacing to overlap same parts.

![stitching](https://github.com/T8RIN/ImageToolbox/assets/106440424/b4ed074a-3f51-462b-a487-6e08adf83306)

**Comment by T8RIN** [comment]
Nice idea, i also thought to add this, so i'll 🐸🐸

**Comment by T8RIN** [comment]
Done, wait in next update :)
