### ISSUE TITLE
[Bug] App Crash: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by HemanthJabalpuri** [T8RIN/ImageToolbox#514]
Device: moto g52 (motorola - rhode), SDK: 31 (12), App: 2.4.2

> (97)java.lang.IndexOutOfBoundsException: Index 2, size 2at x.z0.b(SourceFile:31)at x.z0.c(SourceFile:1)at w6.b7.c(SourceFile:5)at v.o.b(SourceFile:1)at v.u.a(SourceFile:7)at v.v.p(SourceFile:1279)at r.v0.p(SourceFile:359)at w1.f0.e(SourceFile:74)at y1.p.a(SourceFile:51)at q.m.i(SourceFile:44)at q.m.n(SourceFile:476)at w1.z.f(SourceFile:8)at y1.p.a(SourceFile:83)at q.m.i(SourceFile:10)at q.m.n(SourceFile:489)at w1.z.f(SourceFile:8)at y1.p.a(SourceFile:83)at j1.r0.f(SourceFile:1)at y1.p.a(SourceFile:83)at j1.r0.f(SourceFile:1)at y1.p.a(SourceFile:83)at y1.e0.d(SourceFile:26)at m8.d.e(SourceFile:59)at b1.y.b(SourceFile:48)at b1.z.c(SourceFile:162)at y1.h1.a(SourceFile:1)at y1.c0.o0(SourceFile:139)at y1.k0.b(SourceFile:44)at y1.k0.j(SourceFile:139)at y1.k0.g(SourceFile:67)at androidx.compose.ui.platform.AndroidComposeView.t(SourceFile:32)at y1.d1.a(SourceFile:4)at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)at android.view.View.draw(View.java:22768)at android.view.View.updateDisplayListIfDirty(View.java:21640)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21596)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21596)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21596)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21596)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21596)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21596)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4635)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4363)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3480)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2271)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8982)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)at android.view.Choreographer.doCallbacks(Choreographer.java:845)at android.view.Choreographer.doFrame(Choreographer.java:780)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)at android.os.Handler.handleCallback(Handler.java:978)at android.os.Handler.dispatchMessage(Handler.java:104)at android.os.Looper.loopOnce(Looper.java:238)at android.os.Looper.loop(Looper.java:357)at android.app.ActivityThread.main(ActivityThread.java:8089)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

I am new to this app and experimenting various options and I got this crash by doing this

Create -> Image Stitching -> Select 2 images -> Click on lock icon

now click the unlock icon

I don't even know what that lock does and these is no toast like help when long pressing it.

**Comment by T8RIN** [comment]
Yup, i know( check #507 i can't do anything for now😭

**Comment by T8RIN** [comment]
You can also enter our telegram group
