### ISSUE TITLE
Incorrect file extension when using shelter.

### ISSUE THREAD

**Issue by shift18** [T8RIN/ImageToolbox#524]
Reproduce

- Open Image toolbox
- You need to Select an Output folder inside your [Shelter](https://gitea.angry.im/PeterCxy/Shelter/src/branch/master/CHANGELOG.md)  work profile (your selecting a location inside your work profile while image toolbox runs inside your main profile) for the bug to appear.
- Select Resize and convert from main screen
- Keep file extension as .jpg
- Save file
- Get ResizedImage_2023-10-28_00-37-44_2.jpg.null

 * If instead if .jpg you select .jpeg you get 
ResizedImage_2023-10-28_00-35-20_1.jpeg.jpg
* If you use file format heic instead of jpg then file extension is correct.

**Comment by T8RIN** [comment]
Android?

**Comment by shift18** [comment]
Yes
 i was not aware the app was available on another OS, sorry.

**Comment by T8RIN** [comment]
> Yes
>  i was not aware the app was available on another OS, sorry.
> 
> 
> Edit: well if you want to be specific I'm running GrapheneOS which is based on AOSP so i suppose technically not android
> My current version is based on android 14
> 
> Image Toolbox
> version 2.4.2 foss
> ru.tech.imageresizershrinker

Hmm, i will look into 👀
