### ISSUE TITLE
[Bug] App Crash: RuntimeException

### ISSUE THREAD

**Issue by Krys600** [T8RIN/ImageToolbox#525]
Hello, 

This bug happening while I'm trying to open several times a huge photo (9000x12000:108mp) because the app never showing the photo and at the end it's crash. 

Device: SM-S908B (samsung - b0s), SDK: 33 (13), App: 2.4.2-alpha01 (95)java.lang.RuntimeException: Canvas: trying to draw too large(432000000bytes) bitmap.at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:98)at k1.c.q(SourceFile:100)at m1.c.l0(SourceFile:34)at z1.c0.l0(SourceFile:1)at m1.e.c(SourceFile:108)at n1.a.i(SourceFile:1)at n1.b.g(SourceFile:99)at n4.o.i(SourceFile:52)at n1.b.g(SourceFile:99)at n4.t.c(SourceFile:95)at z1.d.c(SourceFile:1)at z1.c0.b(SourceFile:32)at z1.v0.x0(SourceFile:50)at z1.v0.w0(SourceFile:25)at z1.v.Q0(SourceFile:6)at z1.v0.x0(SourceFile:8)at r.z0.a(SourceFile:229)at r.z0.c(SourceFile:211)at l2.h0.I(SourceFile:59)at c1.y.b(SourceFile:48)at c1.z.c(SourceFile:162)at z1.h1.a(SourceFile:1)at n.t.t(SourceFile:1445)at androidx.compose.ui.platform.g2.K(SourceFile:24)at androidx.compose.ui.platform.i2.e(SourceFile:40)at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:100)at android.view.View.draw(View.java:24409)at android.view.View.updateDisplayListIfDirty(View.java:23267)at android.view.View.draw(View.java:24136)at android.view.ViewGroup.drawChild(ViewGroup.java:4748)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)at android.view.View.updateDisplayListIfDirty(View.java:23253)at android.view.View.draw(View.java:24136)at android.view.ViewGroup.drawChild(ViewGroup.java:4748)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1544)at android.view.View.draw(View.java:24409)at com.android.internal.policy.DecorView.draw(DecorView.java:1517)at android.view.View.updateDisplayListIfDirty(View.java:23267)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:777)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:783)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:881)at android.view.ViewRootImpl.draw(ViewRootImpl.java:5647)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5330)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4486)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)at android.view.Choreographer.doCallbacks(Choreographer.java:923)at android.view.Choreographer.doFrame(Choreographer.java:852)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:226)at android.os.Looper.loop(Looper.java:313)at android.app.ActivityThread.main(ActivityThread.java:8762)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by T8RIN** [comment]
Hi, which screen is affected?

**Comment by Krys600** [comment]
Single edit

**Comment by T8RIN** [comment]
I think i somewhat improved this moment
