### ISSUE TITLE
Status bar is always dark in 2.4.3-α01

### ISSUE THREAD

**Issue by v1s7** [T8RIN/ImageToolbox#526]
(Android 13)
Before α01:
https://github.com/T8RIN/ImageToolbox/assets/86906143/f3eacfe5-147f-47bc-a46e-c277abb20afc

In α01:
https://github.com/T8RIN/ImageToolbox/assets/86906143/37a313d6-adbf-49ed-b0e1-cb86257de139

**Comment by T8RIN** [comment]
> (Android 13)
> Before α01:
> https://github.com/T8RIN/ImageToolbox/assets/86906143/f3eacfe5-147f-47bc-a46e-c277abb20afc
> 
> In α01:
> https://github.com/T8RIN/ImageToolbox/assets/86906143/37a313d6-adbf-49ed-b0e1-cb86257de139

Pocheny
