### ISSUE TITLE
[Feature Request] Limits resize enhancement

### ISSUE THREAD

**Issue by plum7x** [T8RIN/ImageToolbox#529]
An option to rotate the limit box depending on original image orientation.

For example the both side lengths of the limit box are 3840 and 2560 then 

resize below 3840x2560 for the landscape images
4000x3000 -> 3414x2560
4000x2250 -> 3840x2160
1920x1440 -> 1920x1440
1920x1080 -> 1920x1080
...

and resize below 2560x3840 for the portrait images
3000x4000 -> 2560x3414
2250x4000 -> 2160x3840
1440x1920 -> 1440x1920
1080x1920 -> 1080x1920
...

**Comment by T8RIN** [comment]
Didn't get it, is it not work the same now?

**Comment by plum7x** [comment]
The orientation of the limit box is fixed, but I hope it will can rotate automatically. Then I don't have to resize twice separately for different the orientation of original images.

**Comment by plum7x** [comment]
the following powershell script did what I wanted.

```powershell 
[void] [System.Reflection.Assembly]::LoadWithPartialName('System.Drawing')
[void] [System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms')
$image = [System.Drawing.Image]::FromFile($imageFilePath)

$imageAspectRatio = $image.Width / $image.Height

if ($imageAspectRatio -ge 1)
{    
    # Set limit box as landscape 
    $limitWidth     = ($limitSideLength1, $limitSideLength2 | Measure-Object  -Maximum).Maximum
    $limitHeight    = ($limitSideLength1, $limitSideLength2 | Measure-Object  -Minimum).Minimum    
}
else
{
    # Set limit box as portrait 
    $limitWidth     = ($limitSideLength1, $limitSideLength2 | Measure-Object  -Minimum).Minimum
    $limitHeight    = ($limitSideLength1, $limitSideLength2 | Measure-Object  -Maximum).Maximum
}

$limitBoxAspectRatio = $limitWidth / $limitHeight

$isOverTheLimit = ($image.Width -gt $limitWidth) -or ($image.Height -gt $limitHeight)

if ($isOverTheLimit)
{
    if ($imageAspectRatio -ge $limitBoxAspectRatio)
    {
        # Resize by width and keep the ratio
        $scaleWidth     = $limitWidth
        $scaleHeight    = ($limitHeight * $imageAspectRatio) -as [int]
    }
    else
    {
        # Resize by Height and keep the ratio
        $scaleWidth     = ($limitWidth / $imageAspectRatio) -as [int]
        $scaleHeight    = $limitHeight
    }
}
else
{
    # Keep original size
    $scaleWidth = $image.Width
    $scaleWidth = $image.Height
}
```

**Comment by T8RIN** [comment]
thanks 👀

**Comment by plum7x** [comment]
Another problem, no save button in the latest version.

**Comment by T8RIN** [comment]
> Another problem, no save button in the latest version.

Where?

**Comment by plum7x** [comment]
limits resize
![ResizedImage_2023-10-31_19-10-41_1330.png](https://github.com/T8RIN/ImageToolbox/assets/106440424/0aa690a2-5e70-487a-87b8-6eb6796f3a6c)

**Comment by T8RIN** [comment]
You need to select preset or limit box to appear

**Comment by plum7x** [comment]
i see, thanks. both width and height must be set. i originally thought that it will use the maximum value.
