### ISSUE TITLE
[Bug] App Crash: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by rahulamreshp** [T8RIN/ImageToolbox#530]
I get this error often due to which the app crashes!

SDK: 30 (11), App: 2.4.2 (97)java.lang.IndexOutOfBoundsException: Index 2, size 2at x.z0.b(SourceFile:31)at x.z0.c(SourceFile:1)at w6.b7.c(SourceFile:5)at v.o.b(SourceFile:1)at v.u.a(SourceFile:7)at v.v.p(SourceFile:1279)at r.v0.p(SourceFile:359)at w1.f0.e(SourceFile:74)at y1.p.a(SourceFile:51)at j1.r0.f(SourceFile:1)at y1.p.a(SourceFile:83)at j1.r0.f(SourceFile:1)at y1.p.a(SourceFile:83)at y1.e0.d(SourceFile:26)at m8.d.e(SourceFile:59)at b1.y.b(SourceFile:48)at b1.z.c(SourceFile:162)at y1.h1.a(SourceFile:1)at y1.c0.o0(SourceFile:139)at y1.k0.b(SourceFile:44)at y1.k0.j(SourceFile:139)at y1.k0.g(SourceFile:67)at androidx.compose.ui.platform.AndroidComposeView.t(SourceFile:32)at y1.d1.a(SourceFile:4)at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)at android.view.View.draw(View.java:22538)at android.view.View.updateDisplayListIfDirty(View.java:21389)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)at android.view.View.updateDisplayListIfDirty(View.java:21349)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)at android.view.View.updateDisplayListIfDirty(View.java:21349)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)at android.view.View.updateDisplayListIfDirty(View.java:21349)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)at android.view.View.updateDisplayListIfDirty(View.java:21349)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)at android.view.View.updateDisplayListIfDirty(View.java:21349)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)at android.view.View.updateDisplayListIfDirty(View.java:21349)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4417)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4144)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3391)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2182)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8730)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)at android.view.Choreographer.doCallbacks(Choreographer.java:1149)at android.view.Choreographer.doFrame(Choreographer.java:1049)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loop(Looper.java:233)at android.app.ActivityThread.main(ActivityThread.java:8010)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by rahulamreshp** [comment]
No worries! Appreciate your work. Work on an update and try to resolve it soon. Keep up.✌🏻

**Comment by T8RIN** [comment]
Waiting for google updates 😭

**Comment by rahulamreshp** [comment]
Okay 🤞🏻

**Comment by jcperil** [comment]
> This is due to compose library bug, sorry, i can't do anything for now 😭😭😭

Can you revert it back to an older version? AFAIK, this was not an issue a few weeks back.
