### ISSUE TITLE
Extract text from image

### ISSUE THREAD

**Issue by mecuricat** [T8RIN/ImageToolbox#539]
As an image toolbox, a tool like "Extract text from image" would be a pretty nice feature.

I usually have to go online to extract text from an image. For example, [Brandfolder](https://brandfolder.com/workbench/extract-text-from-image) allows up to 5 free images everyday. It has higher accuracy than many similar online tools, as I found.

Perhaps someone here can help out with a better way of extracting text from images.

**Comment by T8RIN** [comment]
I also thought about this, but it will need many extra memory, so i won't add this in the near future :) btw thanks for the suggestion 👀

**Comment by Turhvjbufv** [comment]
@mecuricat maybe [universal copy](https://play.google.com/store/apps/details?id=com.camel.corp.universalcopy) can help you with that
