### ISSUE TITLE
[Bug] Image stitch: For right order, must add photo #1 + extra photo, then photo #2, but "Remove" extra photos = "App Crash: IndexOutOfBoundsException"

### ISSUE THREAD

**Issue by AmericaPacific42** [T8RIN/ImageToolbox#540]
Device: Pixel 6a (google - bluejay), SDK: 34 (14), App: 2.4.2 (97)java.lang.IndexOutOfBoundsException: Index 3, size 3at y.z0.b(SourceFile:31)at y.z0.c(SourceFile:1)at m0.d.K0(SourceFile:5)at w.o.b(SourceFile:1)at w.u.a(SourceFile:7)at w.v.p(SourceFile:1262)at s.w0.p(SourceFile:359)at x1.f0.d(SourceFile:74)at z1.p.a(SourceFile:51)at r.m.f(SourceFile:44)at r.m.o(SourceFile:476)at x1.z.h(SourceFile:8)at z1.p.a(SourceFile:83)at r.m.f(SourceFile:10)at r.m.o(SourceFile:489)at x1.z.h(SourceFile:8)at z1.p.a(SourceFile:83)at k1.r0.h(SourceFile:1)at z1.p.a(SourceFile:83)at p.h1.h(SourceFile:12)at z1.p.a(SourceFile:83)at k1.r0.h(SourceFile:1)at z1.p.a(SourceFile:83)at z1.e0.c(SourceFile:26)at l2.h0.K(SourceFile:59)at c1.y.b(SourceFile:48)at c1.z.c(SourceFile:162)at z1.h1.a(SourceFile:1)at z1.c0.o0(SourceFile:139)at z1.k0.b(SourceFile:44)at z1.k0.j(SourceFile:139)at z1.k0.g(SourceFile:67)at androidx.compose.ui.platform.AndroidComposeView.w(SourceFile:32)at z1.d1.a(SourceFile:4)at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)at android.view.View.draw(View.java:23892)at android.view.View.updateDisplayListIfDirty(View.java:22756)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)at android.view.View.updateDisplayListIfDirty(View.java:22712)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)at android.view.View.updateDisplayListIfDirty(View.java:22712)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)at android.view.View.updateDisplayListIfDirty(View.java:22712)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)at android.view.View.updateDisplayListIfDirty(View.java:22712)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)at android.view.View.updateDisplayListIfDirty(View.java:22712)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)at android.view.View.updateDisplayListIfDirty(View.java:22712)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)at android.view.Choreographer.doCallbacks(Choreographer.java:952)at android.view.Choreographer.doFrame(Choreographer.java:882)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)at android.os.Handler.handleCallback(Handler.java:958)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:205)at android.os.Looper.loop(Looper.java:294)at android.app.ActivityThread.main(ActivityThread.java:8177)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by AmericaPacific42** [comment]
Should goto GIMP for such simple image manipulations?
GIMP loads slow on phons...

**Comment by T8RIN** [comment]
It works correctly for reordering, i've checked, IndexOutOfBoundsException is not my fault, check #530 👀

**Comment by AmericaPacific42** [comment]
> It works correctly for reordering, i've checked,

How? It loses the selected order of photos,
and has no "Reorder" options.
It doesn't matter what order you add photos,
it always makes the most old photo "#1,"
unless you add your preferred "photo #1" plus extra photo,
and then manual add "photo #2" and remove extras.
You can not just add "photo #1" first and then add "photo #2",
or it complains that you "Did not select at least 2 photos."
Can not remove a photo unless you add at least 3 photos,
so how to reorder photos?

**Comment by T8RIN** [comment]
Hold photos and reorder after picking 👀

**Comment by AmericaPacific42** [comment]
> Hold photos and reorder after picking 👀

Works gud.
Awsum editor!
