### ISSUE TITLE
[Feature request] Watermark remover

### ISSUE THREAD

**Issue by Alexandru51** [T8RIN/ImageToolbox#549]
Add a watermark remover for images if possible 😅

Also, i updated the romanian translation!

**Comment by Alexandru51** [comment]
Like how this [app](https://play.google.com/store/apps/details?id=com.bongasoft.addremovewatermark) has

**Comment by T8RIN** [comment]
Not sure about deleting, but I'm planning to add applying watermark after I add some cool stuff👀

**Comment by Alexandru51** [comment]
👍🏻

**Comment by Alexandru51** [comment]
Oh, and one more thing

If you add a "applying watermark" feature, please also include a button to select our icon.

**Comment by T8RIN** [comment]
#363
