### ISSUE TITLE
FAB in PDF tools ignores position defined in settings 

### ISSUE THREAD

**Issue by HotarunIchijou** [T8RIN/ImageToolbox#550]
![](https://github.com/T8RIN/ImageToolbox/assets/113282550/b757fea7-79d7-4317-ae67-23787f6136e3)
![](https://github.com/T8RIN/ImageToolbox/assets/113282550/e52f38cb-7f70-4595-af24-7e966a0a6764)

**Comment by T8RIN** [comment]
that's intended behavior, because it's laying in bottom bar, position applied only on non containered FABs👀

**Comment by T8RIN** [comment]
Btw, how pdf tools are going? No bugs?

**Comment by HotarunIchijou** [comment]
Tbh I don't use it, so I can't definitely say if there's any bugs
