### ISSUE TITLE
The border width and number of emoticons cannot be dragged smoothly as before

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#557]
https://github.com/T8RIN/ImageToolbox/assets/51242302/cc15edcb-432d-425f-8eff-5613d58f46f7

**Comment by T8RIN** [comment]
Latest version?

**Comment by Jesse205** [comment]
> Latest version?

Yes, this is the alpha version just released!
[Screenshot_20231116_064347_com.android.settings.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/136107ee-51ec-4301-b8c0-84724673add8)

**Comment by T8RIN** [comment]
Okay, i'll look tomorrow morning 🐸
