### ISSUE TITLE
Emoticons cannot be completely turned off

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#558]
![Screenshot_20231116_064154.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/caed5111-63cc-4fbb-9997-0ba24fb64dab)

After turning off emoticons, the emoticon icon on the homepage has disappeared, but once you enter the tool and exit, a blank emoticon box will appear.

This problem has been around for a long time. I always thought this bug was obvious enough to be fixed in the next version, but it didn't.

**Comment by T8RIN** [comment]
Just not noticed that😅 thanks
