### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by J43git** [T8RIN/ImageToolbox#559]
Device: moto e (motorola - ginna), SDK: 29 (10), App: 2.4.3-alpha03 (100)java.lang.IllegalArgumentException: Lookahead pass was never done for target content.at o.t.b(SourceFile:99)at z1.s.a(SourceFile:38)at o.a0.a(SourceFile:88)at o.a0.i(SourceFile:15)at x1.w.h(SourceFile:8)at z1.x.a(SourceFile:11)at p.k0.b(SourceFile:34)at p.k0.c(SourceFile:17)at i7.j9.g(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.q0(SourceFile:109)at androidx.compose.ui.node.a.K(SourceFile:17)at androidx.compose.ui.node.a.L(SourceFile:18)at z1.g0.o(SourceFile:46)at z1.g0.o0(SourceFile:131)at z1.s.Z(SourceFile:18)at x1.b1.j(SourceFile:29)at x1.b1.k(SourceFile:1)at q.s.f(SourceFile:382)at q.s.o(SourceFile:1506)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.b1.g(SourceFile:68)at a.h.k(SourceFile:75)at a.h.o(SourceFile:1184)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.b1.g(SourceFile:68)at u.n.a(SourceFile:166)at u.n.o(SourceFile:95)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.b1.e(SourceFile:26)at q.z0.a(SourceFile:202)at q.z0.c(SourceFile:203)at i7.j9.g(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.p0(SourceFile:88)at z1.g0.Z(SourceFile:90)at x1.b1.e(SourceFile:26)at u.s.b(SourceFile:45)at u.t.a(SourceFile:36)at u.t.o(SourceFile:23)at z1.k0.k(SourceFile:7)at p.k0.b(SourceFile:103)at p.k0.c(SourceFile:21)at i7.j9.g(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.o(SourceFile:100)at z1.g0.o0(SourceFile:131)at z1.s.Z(SourceFile:18)at x1.b1.j(SourceFile:29)at x1.b1.k(SourceFile:1)at q.s.f(SourceFile:382)at q.s.o(SourceFile:1506)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.b1.g(SourceFile:68)at a.h.k(SourceFile:75)at a.h.o(SourceFile:1184)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.b1.j(SourceFile:29)at x1.b1.k(SourceFile:1)at q.s.f(SourceFile:382)at q.s.o(SourceFile:1506)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.b1.g(SourceFile:68)at u.n.a(SourceFile:170)at u.n.o(SourceFile:101)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at q.z0.a(SourceFile:241)at q.z0.c(SourceFile:203)at i7.j9.g(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.p0(SourceFile:88)at z1.g0.Z(SourceFile:90)at x1.b1.l(SourceFile:37)at w.b0.f(SourceFile:565)at w.b0.o(SourceFile:259)at x1.z.k(SourceFile:25)at w.c0.k(SourceFile:1)at x1.b0.k(SourceFile:43)at p.k0.b(SourceFile:103)at p.k0.c(SourceFile:21)at i7.j9.g(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.o(SourceFile:100)at z1.g0.o0(SourceFile:131)at z1.s.Z(SourceFile:18)at x1.b1.j(SourceFile:29)at x1.b1.k(SourceFile:1)at q.s.f(SourceFile:382)at q.s.o(SourceFile:1506)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.b1.e(SourceFile:26)at q.z0.a(SourceFile:202)at q.z0.c(SourceFile:203)at i7.j9.g(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.p0(SourceFile:88)at androidx.compose.ui.node.a.O(SourceFile:32)at z1.o0.i(SourceFile:97)at androidx.compose.ui.platform.AndroidComposeView.v(SourceFile:8)at androidx.compose.ui.node.a.j(SourceFile:41)at m.x.a(SourceFile:627)at m.x.o(SourceFile:163)at r.z.a(SourceFile:17)at q.c3.o(SourceFile:310)at q.k.c(SourceFile:387)at r.x2.a(SourceFile:46)at r.y1.b(SourceFile:1)at r.h.w(SourceFile:118)at vb.a.j(SourceFile:1)at rc.e0.run(SourceFile:1)at androidx.compose.ui.platform.z0.R(SourceFile:7)at androidx.compose.ui.platform.y0.doFrame(SourceFile:10)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)at android.view.Choreographer.doCallbacks(Choreographer.java:790)at android.view.Choreographer.doFrame(Choreographer.java:721)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)at android.os.Handler.handleCallback(Handler.java:883)at android.os.Handler.dispatchMessage(Handler.java:100)at android.os.Looper.loop(Looper.java:241)at android.app.ActivityThread.main(ActivityThread.java:7604)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)Suppressed: wc.f: [androidx.compose.ui.platform.a2@d44dd64, s0.g@11eebcd, p1{Cancelling}@3910c82, z0@51e1f93]

**Comment by T8RIN** [comment]
Looks like it's continue of #530

**Comment by J43git** [comment]
Yep. In this new version whenever I scroll through my color palettes too quickly or save a stitched image with more than two files (in this case 8) I get greeted with a crash screen.

**Comment by T8RIN** [comment]
Eh( waiting for next alpha :(

**Comment by T8RIN** [comment]
it should be fixed now, so i'll close the issue until new possible occurencies
