### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by meiMingle** [T8RIN/ImageToolbox#561]
Device: RMX3370 (realme - RE5473), SDK: 30 (11), App: 2.4.3-alpha03-jxl (100)java.lang.NullPointerExceptionat ff.r.x(SourceFile:277)at gd.a.j(SourceFile:1)at he.v.u(SourceFile:1)at ce.a.j(SourceFile:23)at gd.a.j(SourceFile:1)at ce.f0.run(SourceFile:1)at wa.j.run(SourceFile:274)at ie.i.run(SourceFile:1)at ie.a.run(SourceFile:94)Suppressed: he.h: [s1{Cancelling}@58f31ac, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
Which screen?
