### ISSUE TITLE
[Feature Request] Provides backward compatibility for language change.

### ISSUE THREAD

**Issue by hushenghao** [T8RIN/ImageToolbox#562]
Use [AppCompatDelegate.setApplicationLocales(LocaleListCompat)](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#setApplicationLocales(androidx.core.os.LocaleListCompat)). Provides backward compatibility for the new per-language preferences API available in Android 13.

Support to Android N, For API<24 the application does not have a localeList instead it has a single locale.

Like this: 
Source code, [LanguagePref.kt](https://github.com/hushenghao/AndroidEasterEggs/blob/main/app/src/main/java/com/dede/android_eggs/views/settings/prefs/LanguagePref.kt)
![1000001215](https://github.com/T8RIN/ImageToolbox/assets/28776451/52799e12-3cfb-414e-adfc-f4addd241a37)

**Comment by hushenghao** [comment]
If you think it's a good idea, I can contribute to make it happen

**Comment by T8RIN** [comment]
It's already presented, isn't it?

**Comment by hushenghao** [comment]
It is my mistake. I chose the language on the device of Android13, but it jumped to the system Settings. I thought this function was not implemented.
I just read the source code and found that it only opens on Android13 and below and MIUI, but everything is perfect

**Comment by T8RIN** [comment]
:)
