### ISSUE TITLE
[Bug] App Crash: OutOfMemoryError

### ISSUE THREAD

**Issue by dumascon** [T8RIN/ImageToolbox#566]
Device: NOH-NX9 (HUAWEI - HWNOH), SDK: 31 (12), App: 2.4.3-alpha01 (98)java.lang.OutOfMemoryErrorat android.graphics.Bitmap.nativeCreate(Native Method)at android.graphics.Bitmap.createBitmap(Bitmap.java:1257)at android.graphics.Bitmap.createBitmap(Bitmap.java:1192)at b3.a.b(SourceFile:1)at m0.d.r0(SourceFile:1)at k9.u.u(SourceFile:330)at k9.u.p(SourceFile:13)at l0.b.v(SourceFile:5)at j7.w.W1(SourceFile:74)at k9.e0.o(SourceFile:15)at k9.f.u(SourceFile:84)at k9.f.p(SourceFile:13)at l0.b.v(SourceFile:5)at j7.w.W1(SourceFile:74)at j8.w.G0(SourceFile:37)at k9.k.u(SourceFile:95)at o7.a.n(SourceFile:1)at j8.c0.run(SourceFile:1)at k.j.run(SourceFile:253)at p8.i.run(SourceFile:1)at p8.a.run(SourceFile:94)Suppressed: o8.e: [m1{Cancelling}@42f3c58, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
Large image?

**Comment by dumascon** [comment]
After selecting image
Using Resize 'Type' / 'Ratio' / manually setting Height to '800'
Repeated 3x & crashed 3x.

**Comment by T8RIN** [comment]
Ratio is quite buggy, i will remove it i think, it's just the copy of flexible but working bad
