### ISSUE TITLE
adding text and/or emojis on images

### ISSUE THREAD

**Issue by idontveapc** [T8RIN/ImageToolbox#568]
app has a fair amount of options that an image editor would have, except one i mentioned as the title!

**Comment by T8RIN** [comment]
Yup, thanks for the suggestion, this planned and mentioned in #468 :)

**Comment by hushenghao** [comment]
Consider switching from SVG emoji to emoji text in Android 13 and above, as you can use the CORL feature to display clearer emojis.

**Comment by T8RIN** [comment]
> Consider switching from SVG emoji to emoji text in Android 13 and above, as you can use the [COLR](https://developer.android.google.cn/about/versions/13/features#color-vector-fonts) feature to display clearer emojis.
> 
> I can provide some help on whether the system fonts support the COLR feature, because OEMs may negatively optimize emoji fonts on Android13 devices. (Such as : Meizu)
> [COLRv1.kt](https://github.com/hushenghao/AndroidEasterEggs/blob/main/eggs/T/src/com/android_t/egg/COLRv1.kt)

Initially i used emojis as text, that worked great, but on each device that looked different, so i considered switching for svg, so on all devices it'll look the same :)

**Comment by T8RIN** [comment]
But they will be still different depending on device isn't it? Also didn't the app size will be increased of storing all entire available emojis?

**Comment by T8RIN** [comment]
Also i have some svgs that are not from emojis👀

**Comment by hushenghao** [comment]
> But they will be still different depending on device isn't it? Also didn't the app size will be increased of storing all entire available emojis?

If using SVG emoji, it definitely cannot support all emojis, so only enable more emoji support or allow users to customize input on Android 13 or above.

**Comment by hushenghao** [comment]
You can consider allowing users to customize emoji input on Android 13 devices, which will minimally intrude on existing functions.

**Comment by T8RIN** [comment]
> You can consider allowing users to customize emoji input on Android 13 devices, which will minimally intrude on existing functions.

Maybe, but it seems to be tricky, maybe when adding text to images I'll add this, but now i'll need to rewrite all emoji parts to achieve using colr

**Comment by T8RIN** [comment]
So maybe in the future, not now :)

**Comment by hushenghao** [comment]
I don't quite understand why assets svg should be copied to the local directory and then loaded. 
Are there any advantages to doing this?
```kotlin
private fun Context.getFileFromAssets(cat: String, filename: String): Uri =
    "file:///android_asset/svg/${cat}/${filename}".toUri()
```

**Comment by T8RIN** [comment]
> I don't quite understand why assets svg should be copied to the local directory and then loaded. 
> Are there any advantages to doing this?
> ```kotlin
> private fun Context.getFileFromAssets(cat: String, filename: String): Uri =
>     "file:///android_asset/svg/${cat}/${filename}".toUri()
> ```

how can I load image without it? Can coil load that directly? If you know, I'll be glad :)

**Comment by hushenghao** [comment]
> > I don't quite understand why assets svg should be copied to the local directory and then loaded.
> > Are there any advantages to doing this?
> > ```kotlin
> > private fun Context.getFileFromAssets(cat: String, filename: String): Uri =
> >     "file:///android_asset/svg/${cat}/${filename}".toUri()
> > ```
> 
> how can I load image without it? Can coil load that directly? If you know, I'll be glad :)

I will submit a PR to implement this optimization https://github.com/T8RIN/ImageToolbox/pull/581

**Comment by T8RIN** [comment]
thanks!

**Comment by T8RIN** [comment]
now you can use watermark feature to achieve this, hope it fits :)
