### ISSUE TITLE
[Bug Report?/Feature Request] The 'Resize By Weight' Feature Is Lowering The Resolution Of Images

### ISSUE THREAD

**Issue by MadZiontist** [T8RIN/ImageToolbox#574]
Please allow 'Resize By Weight' to shrink the file size, without changing the resolution of the image.

**Comment by T8RIN** [comment]
how do you imagine this? even if the reduction in quality did not help achieve the desired weight, you will have to reduce the sizes anyway, they still change proportionally

**Comment by MadZiontist** [comment]
@T8RIN I'm not sure if we understand each other. Many apps and websites will compress images without changing the dimension/pixel size of the image. I really like your app, in general, and was hoping you would implement this ability. However, I don't use it very much, because I don't want the resolution of the image changed. I just want the file size reduced. Here's a website, for example, that does what I'm looking for:

https://compresspng.com

**Comment by T8RIN** [comment]
> @T8RIN I'm not sure if we understand each other. Many apps and websites will compress images without changing the dimension/pixel size of the image. I really like your app, in general, and was hoping you would implement this ability. However, I don't use it very much, because I don't want the resolution of the image changed. I just want the file size reduced. Here's a website, for example, that does what I'm looking for:
> 
> https://compresspng.com

Just change image quality, resize by weight reduces quality then dimensions, you need to use single edit or resize and convert

**Comment by MadZiontist** [comment]
@T8RIN 

Got it, thanks. 'Resize and Convert' seems to work well for me, for this purpose. However, I had an issue with 'Single Edit', when I attempted to pick an 18.74MB PNG image. After I selected the pic, Image Toolbox just immediately returned to the home page. I'll open a new issue for that though. I appreciate your help.

**Comment by T8RIN** [comment]
> @T8RIN 
> 
> Got it, thanks. 'Resize and Convert' seems to work well for me, for this purpose. However, I had an issue with 'Single Edit', when I attempted to pick an 18.74MB PNG image. After I selected the pic, Image Toolbox just immediately returned to the home page. I'll open a new issue for that though. I appreciate your help. 

Maybe a large image, can you send it here?
