### ISSUE TITLE
[Bug] 'Single Edit' Mode Isn't Opening PNG Files

### ISSUE THREAD

**Issue by MadZiontist** [T8RIN/ImageToolbox#575]
I tried to open both larger (18MB and 25MB) images, as well as smaller ones (1MB), with the 'Single Edit' feature. After the image is selected, no editing options are opened. The app just loops right back to the home page.

**Comment by T8RIN** [comment]
Can you show a video and provide some test files please?

**Comment by T8RIN** [comment]
Did you tried to wait some time? It's seems to be visual loading bug

**Comment by T8RIN** [comment]
kinda fixed

**Comment by MadZiontist** [comment]
I'm sorry for the late response. I'll test it, and let you know if I have any more issues. Thank you.
