### ISSUE TITLE
Option to Overwrite existing file

### ISSUE THREAD

**Issue by meichthys** [T8RIN/ImageToolbox#578]
Issue #352 seems to indicate that it should be possible to overwrite the existing file (or keep the existing file name) when trying to save the edits that have been made.

Currently this doesn't seem to be possible however in v2.5.0-rc1-jxl (101)

I'm able to toggle  the "Add original filename" option, but I cannot remove the "Prefix" option, so the file is always saved with the prefix without overwriting or removing the original:

![ResizedImage_Screenshot_20231129-093913 png_2023-11-29_09-39-32_1115](https://github.com/T8RIN/ImageToolbox/assets/10717998/541d90c0-0a9d-49f2-bad0-c09f347ec01e)

**Comment by T8RIN** [comment]
Add original filename just adds it, because i can't delete either overwrite the original file, this requires high permissions, for that reason it will be hard to be published on google play, but I'll remove superfluous underscore if the prefix is empty

**Comment by T8RIN** [comment]
Thanks, i ll wait, i know some ways, but it anyway requires some extra actions from user, especially on higher android

**Comment by T8RIN** [comment]
Added this !
