### ISSUE TITLE
Partial rotate feature

### ISSUE THREAD

**Issue by meichthys** [T8RIN/ImageToolbox#584]
Currently it seems like we can only rotate in increments of 90 degrees. It would be nice if we could partially rotate an image to help level it. This would obviously change the size of the photo since the aspect ratio would need to be maintained. An example UI for this could be the iOS implementation shown here: https://media.idownloadblog.com/wp-content/uploads/2015/02/rotate-photos-on-iPhone.png

**Comment by T8RIN** [comment]
closed in favor of #936
