### ISSUE TITLE
Feature Request: HDR Filters & Effects

### ISSUE THREAD

**Issue by Pantyhose-X** [T8RIN/ImageToolbox#596]
- [ ] Polarizing filters
- [ ] ND filter
- [ ] Neutral density (ND) filter
- [ ] graduated ND filter
- [ ] Cold/warm filter
- [ ] Color filter
- [ ] CC filters
- [ ] Black and white filter
- [ ] Hard GND filter
- [ ] RGND filter
- [ ] Blur filter
- [ ] Retro Film filter
- [ ] [Comic/Paint filter
- [ ] Sketch filter
### More Filter
https://docs.blender.org/manual/en/latest/compositing/types/filter/index.html
https://docs.gimp.org/en/filters.html

Filter effects: https://www.bhphotovideo.com/explora/photography/buying-guide/a-guide-to-filters-for-lenses
Filter effects: https://www.kentfaith.com/blog/11-photography-filters-guide-and-use

**Comment by T8RIN** [comment]
Mostly all of this filters already presented in the app
