### ISSUE TITLE
Limits resize has no save option

### ISSUE THREAD

**Issue by Djfe** [T8RIN/ImageToolbox#600]
When choosing the last Edit option "Limits resize" then I cannot save the image.

**Comment by T8RIN** [comment]
It has, you need to specify both dimensions

**Comment by Djfe** [comment]
thanks, that wasn't obvious to me. The second input already says "Height 3072".
just my two cents: limiting one dimension should be enough. I won't open another issue since I don't require it to be this way.

For good user interaction it might be helpful to always display a save button and show a dialogue box to explain which input option is missing.

**Comment by T8RIN** [comment]
> thanks, that wasn't obvious to me. The second input already says "Height 3072".
> just my two cents: limiting one dimension should be enough. I won't open another issue since I don't require it to be this way.
> 
> For good user interaction it might be helpful to always display a save button and show a dialogue box to explain which input option is missing.

Maybe that will be helpful, yes :)
