### ISSUE TITLE
Save to clipboard

### ISSUE THREAD

**Issue by thibaultmol** [T8RIN/ImageToolbox#602]
It would be nice to save the edited image to clipboard when it saves. (samsung's image editing tool does it) and it's quite nice. Because keyboards like gboard will automatically give you a button to add an image in your computers to a conversation

**Comment by T8RIN** [comment]
Maybe i'll add this as an option , thx for the suggestion

**Comment by T8RIN** [comment]
Added :) wait 2.5.1
