### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by alabotski** [T8RIN/ImageToolbox#603]
Device: Pixel 7 Pro (google - cheetah), SDK: 34 (14), App: 2.5.0 (104)java.lang.IllegalArgumentException: Lookahead pass was never done for target content.at o.t.b(SourceFile:99)at z1.s.a(SourceFile:38)at o.a0.a(SourceFile:88)at o.a0.i(SourceFile:15)at x1.x.h(SourceFile:8)at z1.x.a(SourceFile:11)at p.k0.b(SourceFile:35)at p.k0.c(SourceFile:17)at i7.j9.h(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.q0(SourceFile:114)at androidx.compose.ui.node.a.K(SourceFile:17)at androidx.compose.ui.node.a.L(SourceFile:18)at z1.g0.o(SourceFile:46)at z1.g0.o0(SourceFile:131)at z1.s.Z(SourceFile:18)at x1.c1.g(SourceFile:68)at a.h.k(SourceFile:75)at a.h.o(SourceFile:1184)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.c1.e(SourceFile:26)at q.y0.a(SourceFile:202)at q.y0.c(SourceFile:203)at i7.j9.h(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.p0(SourceFile:95)at z1.g0.Z(SourceFile:90)at x1.c1.c(SourceFile:30)at u.h1.b(SourceFile:88)at a.h.k(SourceFile:287)at a.h.o(SourceFile:1172)at z1.k0.k(SourceFile:7)at p.k0.b(SourceFile:103)at p.k0.c(SourceFile:21)at i7.j9.h(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.o(SourceFile:100)at z1.g0.o0(SourceFile:131)at z1.s.Z(SourceFile:18)at x1.c1.e(SourceFile:26)at q.y0.a(SourceFile:202)at q.y0.c(SourceFile:203)at i7.j9.h(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.p0(SourceFile:95)at z1.g0.Z(SourceFile:90)at x1.c1.e(SourceFile:26)at u.s.b(SourceFile:45)at u.t.a(SourceFile:36)at u.t.o(SourceFile:23)at z1.k0.k(SourceFile:7)at p.k0.b(SourceFile:103)at p.k0.c(SourceFile:21)at i7.j9.h(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.o(SourceFile:100)at z1.g0.o0(SourceFile:131)at z1.s.Z(SourceFile:18)at x1.c1.j(SourceFile:29)at x1.c1.k(SourceFile:1)at q.s.f(SourceFile:382)at q.s.o(SourceFile:1506)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.c1.j(SourceFile:29)at x1.c1.k(SourceFile:1)at q.s.f(SourceFile:382)at q.s.o(SourceFile:1506)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.c1.j(SourceFile:29)at x1.c1.k(SourceFile:1)at q.s.f(SourceFile:382)at q.s.o(SourceFile:1506)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.c1.j(SourceFile:29)at x1.c1.k(SourceFile:1)at q.s.f(SourceFile:27)at q.s.o(SourceFile:1514)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.c1.g(SourceFile:68)at u.n.a(SourceFile:178)at u.n.o(SourceFile:101)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at q.y0.a(SourceFile:241)at q.y0.c(SourceFile:203)at i7.j9.h(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.p0(SourceFile:95)at z1.g0.Z(SourceFile:90)at x1.c1.i(SourceFile:71)at q.s.f(SourceFile:287)at q.s.o(SourceFile:1624)at x1.a0.k(SourceFile:25)at y.u.k(SourceFile:1)at x1.c0.k(SourceFile:43)at p.k0.b(SourceFile:103)at p.k0.c(SourceFile:21)at i7.j9.h(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.o(SourceFile:100)at z1.g0.o0(SourceFile:131)at z1.s.Z(SourceFile:18)at x1.c1.c(SourceFile:30)at q.l.a(SourceFile:27)at q.l.o(SourceFile:17)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.c1.j(SourceFile:29)at x1.c1.k(SourceFile:1)at q.l.a(SourceFile:60)at q.l.o(SourceFile:23)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.c1.j(SourceFile:29)at x1.c1.k(SourceFile:1)at q.s.f(SourceFile:382)at q.s.o(SourceFile:1506)at z1.k0.k(SourceFile:7)at z1.x.Z(SourceFile:16)at x1.c1.e(SourceFile:26)at q.y0.a(SourceFile:202)at q.y0.c(SourceFile:203)at i7.j9.h(SourceFile:59)at c1.z.b(SourceFile:48)at c1.a0.c(SourceFile:162)at z1.m1.a(SourceFile:1)at z1.g0.p0(SourceFile:95)at androidx.compose.ui.node.a.O(SourceFile:32)at z1.o0.i(SourceFile:97)at androidx.compose.ui.platform.AndroidComposeView.v(SourceFile:8)at androidx.compose.ui.node.a.j(SourceFile:41)at m.x.a(SourceFile:216)at m.x.o(SourceFile:130)at r.z.a(SourceFile:17)at q.a3.o(SourceFile:310)at q.k.c(SourceFile:387)at r.x2.a(SourceFile:46)at r.y1.b(SourceFile:1)at r.h.w(SourceFile:118)at vb.a.j(SourceFile:1)at rc.e0.run(SourceFile:1)at androidx.compose.ui.platform.a1.R(SourceFile:7)at androidx.compose.ui.platform.z0.doFrame(SourceFile:10)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1341)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)at android.view.Choreographer.doCallbacks(Choreographer.java:952)at android.view.Choreographer.doFrame(Choreographer.java:878)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)at android.os.Handler.handleCallback(Handler.java:958)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:205)at android.os.Looper.loop(Looper.java:294)at android.app.ActivityThread.main(ActivityThread.java:8194)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)Suppressed: wc.f: [androidx.compose.ui.platform.b2@87aaaed, s0.g@c9d2d22, p1{Cancelling}@cf8c3b3, a1@fe0d70]

**Comment by T8RIN** [comment]
Related to #559
