### ISSUE TITLE
Image stitching: Can't add image

### ISSUE THREAD

**Issue by GitAritron** [T8RIN/ImageToolbox#605]
Device: Xiaomi Redmi Note 8 Pro
Image Stitching. 
When I click "add an image to start" it opens automatically some integrated image picker which, although not very comfortable, works. (although it lets you pick just ONE picture)
The problem is when you choose a picture a pop-up appears "Choose at least two photos".

tldr:
The image picker lets me pick no more than one and I have to pick at least two... 

![Screenshot_2023-12-12-01-53-31-462_ru tech imageresizershrinker](https://github.com/T8RIN/ImageToolbox/assets/103900385/a86af9be-b0e7-4b45-bf65-d5b428b6de14)

**Comment by T8RIN** [comment]
It's android system embedded picker, and you need to hold if you want more images

**Comment by T8RIN** [comment]
Also you can change image source in the settings

**Comment by GitAritron** [comment]
I forgot to mention that, but I did try every possible way that I could think of to select multiple ones. (click and hold, swipe, pinch...)

Thank you for the settings tip tho, changing settings to the other two works fine.

**Comment by T8RIN** [comment]
Nice :)
