### ISSUE TITLE
Share menu cause another crop

### ISSUE THREAD

**Issue by thibaultmol** [T8RIN/ImageToolbox#606]
If you edit the image using the single edit mode, crop it, then use the share menu to share the image:
it will crop the image again but incorrectly and instead create a warped image.
![image](https://github.com/T8RIN/ImageToolbox/assets/1010226/b3be5d74-790b-4fd8-9640-8e7a0446d9b3)

note from dev to include:
> cropper have some issue with changing free/original, it locks by some reason when switching between them

**Comment by T8RIN** [comment]
Thanks, when i have free time i'll fix this firstly!

**Comment by thibaultmol** [comment]
Can indeed confirm it's fixed! Thx
