### ISSUE TITLE
[Bug] Limits Resize not limited by causality 

### ISSUE THREAD

**Issue by Shoe64** [T8RIN/ImageToolbox#607]
https://github.com/T8RIN/ImageToolbox/assets/153294160/8ee3f99b-71ea-4764-9687-e3fb7ee2e042
I'm impressed by the 4th dimensional compression.

That folder did exist but i seem to have deleted it recently. I haven't tested all the different modes but I did notice that single edit does throw an error as so:

![Screenshot_20231216-172022](https://github.com/T8RIN/ImageToolbox/assets/153294160/a08cb6be-bf74-4a95-ae3b-c393d3a474cf)

If it wasn't the users, eh? lol

Anyway, I hope you two are doing well and I love all the stuff in the updates. I hope to see you again sometime.

Don't forget to have fun.
хорошо

-Shoe

**Comment by T8RIN** [comment]
Hi bro, nice to hear you again❤️ That's not a bug, rather than intended behavior, because the folder doesn't exist anymore, and you need yo create it again, because as i remember I can't do that myself :(

**Comment by T8RIN** [comment]
Btw, we are fine 🐸

**Comment by Shoe64** [comment]
Dude did you watch the video? The "Limits Resize" doesn't throw an error. It shows success.

The user wouldn't know the folders missing without using other functions. There's a chance of losing work and not knowing until the work is gone.

P.S.  I looked and I finally got something I saw. The best thing in my life is to find something unique and wonderful.  A unicorn.

I found a flavor I cannot describe for the first time in years and it's wonderful.

![Uploading IMG_20231218_141208837.jpg…]()

**Comment by T8RIN** [comment]
> Dude did you watch the video? The "Limits Resize" doesn't throw an error. It shows success. Gotta quit assuming answers without all the information my friend.
> 
> The user wouldn't know the folders missing without using other functions. There's a chance of losing work and not knowing until the work is gone.
> 
> P.S.  I looked and I finally got something I saw. The best thing in my life is to find something unique and wonderful.  A unicorn.
> 
> I found a flavor I cannot describe for the first time in years and it's wonderful.
> 
> ![IMG_20231218_141208837](https://github.com/T8RIN/ImageToolbox/assets/153294160/50ae6ff3-64f1-4aa2-b6e9-221d69e2f807)
> 
> 

Oh, thanks, I'll try to do something when i have free time...
