### ISSUE TITLE
[Feature Request]: Add Regex and Batch Renaming, and Batch Date Modification for Photos

### ISSUE THREAD

**Issue by bropines** [T8RIN/ImageToolbox#615]
### Feature Description
I would like to suggest a couple of features that could enhance the utility of the app. These are based on my recent experience and a comparison with existing applications in the market.

- [ ] 1. **Regex and Batch Renaming**: Is there a possibility to add functionality for regex-based renaming of files and folders? This feature would greatly help in organizing and managing files more efficiently, especially when dealing with a large number of items.

- [ ] 2. **Batch Renaming with Multiple Parameters**: Alongside regex renaming, it would be beneficial to have an option for batch renaming with multiple parameters. This would allow users to quickly rename an entire folder based on set criteria, streamlining the organization process.

- [ ] 3. **Batch Date Modification for Photos**: Another useful feature would be the ability to modify the creation or update dates of photos in a batch. This is especially helpful for organizing and sorting photos. An example of this functionality can be found in the Image Date Fixer app ([Google Play Store Link](https://play.google.com/store/apps/details?id=eu.duong.imagedatefixer)).

---

**Additional Details on Feature Implementation**

### 1. Regex and Batch Renaming Functionality
- **User Interface**: A dedicated section in the app's menu for 'File Renaming'.
- **Function**: Users can input regex patterns for renaming. There should be a preview option to see the potential changes before applying them.
- **Use Case Example**: If a user wants to rename all files with the format "Vacation2022_(number)" to "Holiday2022_(number)", they could use a regex pattern to make this change in bulk.

### 2. Batch Renaming with Multiple Parameters
- **User Interface**: An extension of the renaming section with advanced options.
- **Function**: Allows users to select multiple criteria for renaming, such as date, file type, or custom text patterns. 
- **Use Case Example**: Renaming all .jpg files in a folder to include the date of creation in the file name, like "YYYYMMDD_Filename.jpg".

### 3. Batch Date Modification for Photos
- **User Interface**: A new feature in the photo management section of the app.
- **Function**: Users can select a group of photos and set a new creation or modification date. The app could offer a calendar view for easy date selection.
- **Use Case Example**: If a user discovers that the dates on their vacation photos are incorrect, they could select all these photos and set them to the correct date in one action.

**Additional Considerations**
- **Safety Measures**: To prevent accidental mass changes, a confirmation step should be included before applying any batch operations.
- **Undo Function**: After applying changes, an option to undo the last operation could be helpful in case of mistakes.
- **Help Section**: Including a tutorial or help section within the app explaining how to use these new features would be beneficial for users unfamiliar with regex or batch operations.

---
PS.
This issue was written by chatGPT (he is stupidly smarter).

**Comment by JackDropHammer** [comment]
Tbh I've actually NEVER seen an undo function in any of the application I've ever used so if this was implemented, it would be really interesting!

**Comment by T8RIN** [comment]
Which undo?

**Comment by bropines** [comment]
> Which undo?

In general, GPT wrote this for fun, but as a trick it would be convenient that after you renamed or did something with the images, they were still stored in the application buffer, and as soon as you saved the result, they were replaced, and it's better that the application just reads the final result, and then applies it.

**Comment by JackDropHammer** [comment]
> Which undo?

basically, you performed mass rename on a bunch of files and when you press undo, the app will automatically rename those files to what they were originally.

**Comment by T8RIN** [comment]
Playmarket restrics usage of MANAGE_EXTERNAL_STORAGE permission, and because this is not the main app feature they will just not publish me, i recently tried to use it for new option, bu they rejected my proposals 5 times, so i will not add this unfortunately :(
