### ISSUE TITLE
[Bug] App Crash: OutOfMemoryError //>4gb free

### ISSUE THREAD

**Issue by AmericaPacific42** [T8RIN/ImageToolbox#617]
Device: Pixel 6a (google - bluejay), SDK: 34 (14), App: 2.5.0 (104)java.lang.OutOfMemoryErrorat android.graphics.Bitmap.nativeCreate(Native Method)at android.graphics.Bitmap.createBitmap(Bitmap.java:1206)at android.graphics.Bitmap.createBitmap(Bitmap.java:979)at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:831)at u9.k0.l(SourceFile:1)at u9.k0.a(SourceFile:23)at u9.e.y(SourceFile:212)at x7.a.m(SourceFile:1)at s8.v1.u(SourceFile:54)at s8.a.m(SourceFile:23)at x7.a.m(SourceFile:1)at x8.q.u(SourceFile:1)at s8.a.m(SourceFile:23)at x7.a.m(SourceFile:1)at s8.c0.run(SourceFile:1)at k.j.run(SourceFile:253)at y8.j.run(SourceFile:1)at y8.a.run(SourceFile:94)Suppressed: x8.e: [m1{Cancelling}@3bc99b4, Dispatchers.Main.immediate]

**Comment by AmericaPacific42** [comment]
Had >4GB RAM free for use, but could not load 4 photos.

**Comment by T8RIN** [comment]
What resolution do they have?
