### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by thibaultmol** [T8RIN/ImageToolbox#618]
I'll be honest, I don't know how useful this bug report is going to be because I don't really know what I did different than usual. I was watching a YouTube video and took a screenshot and then I click on edit which opens the app.

Device: FP4 (Fairphone - FP4), SDK: 33 (13), App: 2.5.0 (104)java.lang.IllegalArgumentException: width(-80) must be >= 0at m2.r.B(SourceFile:31)at z.r.a(SourceFile:69)at f8.j.T0(SourceFile:18)at z.t.p(SourceFile:516)at s.w0.f(SourceFile:59)at s.w0.p(SourceFile:350)at y1.d0.d(SourceFile:74)at a2.s.a(SourceFile:38)at r.m.i(SourceFile:44)at r.m.o(SourceFile:476)at y1.x.d(SourceFile:8)at a2.x.a(SourceFile:11)at r.m.i(SourceFile:10)at r.m.o(SourceFile:489)at y1.x.d(SourceFile:8)at a2.x.a(SourceFile:11)at l1.q0.d(SourceFile:1)at a2.x.a(SourceFile:11)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at a2.g0.a(SourceFile:101)at v.v.d(SourceFile:83)at a2.s.a(SourceFile:38)at v.g0.d(SourceFile:99)at a2.x.a(SourceFile:11)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at a2.g0.a(SourceFile:101)at v.i1.a(SourceFile:111)at v.h1.d(SourceFile:32)at a2.s.a(SourceFile:38)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at a2.g0.a(SourceFile:101)at v.i1.a(SourceFile:389)at v.h1.d(SourceFile:32)at a2.s.a(SourceFile:38)at f1.o.d(SourceFile:1)at a2.x.a(SourceFile:11)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at a2.g0.a(SourceFile:101)at v.i1.a(SourceFile:111)at v.h1.d(SourceFile:32)at a2.s.a(SourceFile:38)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at a2.g0.a(SourceFile:101)at v.v.d(SourceFile:83)at a2.s.a(SourceFile:38)at l1.q0.d(SourceFile:1)at a2.x.a(SourceFile:11)at p.k1.d(SourceFile:25)at a2.x.a(SourceFile:11)at l1.q0.d(SourceFile:1)at a2.x.a(SourceFile:11)at v.z0.d(SourceFile:1)at a2.x.a(SourceFile:11)at v.q0.d(SourceFile:59)at a2.d.d(SourceFile:1)at a2.x.a(SourceFile:11)at c7.d0.d(SourceFile:66)at a2.d.d(SourceFile:1)at a2.x.a(SourceFile:11)at v.a1.d(SourceFile:1)at a2.x.a(SourceFile:11)at v.g0.d(SourceFile:99)at a2.x.a(SourceFile:11)at v.n1.d(SourceFile:117)at a2.x.a(SourceFile:11)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at a2.g0.a(SourceFile:101)at v.v.d(SourceFile:214)at s.w0.f(SourceFile:40)at s.w0.p(SourceFile:373)at y1.d0.d(SourceFile:74)at a2.s.a(SourceFile:38)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at a2.g0.a(SourceFile:101)at v.v.d(SourceFile:83)at a2.s.a(SourceFile:38)at v.g0.d(SourceFile:99)at a2.x.a(SourceFile:11)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at a2.g0.a(SourceFile:101)at v.v.d(SourceFile:83)at a2.s.a(SourceFile:38)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at a2.g0.a(SourceFile:101)at y1.h1.d(SourceFile:34)at a2.s.a(SourceFile:38)at q.k0.b(SourceFile:35)at q.k0.d(SourceFile:17)at m2.r.W(SourceFile:59)at d1.z.b(SourceFile:48)at d1.a0.c(SourceFile:162)at a2.m1.a(SourceFile:1)at a2.g0.q0(SourceFile:114)at androidx.compose.ui.node.a.J(SourceFile:17)at a2.o0.c(SourceFile:3)at a2.o0.m(SourceFile:1)at a2.o0.j(SourceFile:55)at androidx.compose.ui.platform.AndroidComposeView.onMeasure(SourceFile:79)at android.view.View.measure(View.java:26368)at androidx.compose.ui.platform.a.g(SourceFile:1)at androidx.compose.ui.platform.a.onMeasure(Unknown Source:3)at android.view.View.measure(View.java:26368)at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)at android.view.View.measure(View.java:26368)at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3929)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3303)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2331)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9090)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)at android.view.Choreographer.doCallbacks(Choreographer.java:985)at android.view.Choreographer.doFrame(Choreographer.java:916)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:201)at android.os.Looper.loop(Looper.java:288)at android.app.ActivityThread.main(ActivityThread.java:7932)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by T8RIN** [comment]
#559
