### ISSUE TITLE
[Bug] App Crash: j

### ISSUE THREAD

**Issue by Unacceptium** [T8RIN/ImageToolbox#625]
Device: RKY-LX1 (HONOR - HNRKY-M1), SDK: 31 (12), App: 2.5.1 (105)t0.j: Compose Runtime internal error. Unexpected or incorrect use of the Compose internal runtime API (Start/end imbalance). Please report to Google or use https://goo.gle/compose-feedbackat n0.c.K(SourceFile:11)at t0.o.y(SourceFile:77)at t0.o.q(SourceFile:157)at t0.o.J(SourceFile:31)at t0.u.y(SourceFile:34)at t0.e2.w(SourceFile:127)at t0.c2.s(SourceFile:435)at androidx.compose.ui.platform.c1.doFrame(Unknown Source:6)at androidx.compose.ui.platform.a1.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1621)at android.view.Choreographer.doCallbacks(Choreographer.java:1141)at android.view.Choreographer.doFrame(Choreographer.java:1007)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1585)at android.os.Handler.handleCallback(Handler.java:955)at android.os.Handler.dispatchMessage(Handler.java:102)at android.os.Looper.loopOnce(Looper.java:206)at android.os.Looper.loop(Looper.java:296)at android.app.ActivityThread.main(ActivityThread.java:8971)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)Suppressed: w8.e: [t0.m1@7d3d68, androidx.compose.ui.platform.c2@4790581, m1{Cancelling}@9fad626, b1@470f267]

thats the output
app is from the update list, universal one.
what happened is i just started drawing on an empty background
edit:my work is done :(

**Comment by T8RIN** [comment]
Compose library bug, just waiting for the new alpha
