### ISSUE TITLE
app rotates and resets

### ISSUE THREAD

**Issue by thibaultmol** [T8RIN/ImageToolbox#626]
When i do single edit, crop, confirm, then try to draw
The app switches to landscape, then switches to portrait (and loses the crop). I also noticed the app colors reset during that.
I'm holding my phone in portait and the rotation of my phone is locked. So i'm confused why the app switches to landscape somehow.

https://github.com/T8RIN/ImageToolbox/assets/1010226/455dc720-17cd-420c-a076-c26fc4fe1549

2.5.1 foss

**Comment by T8RIN** [comment]
Losing crop is definitely a bug , but this rotation in draw mode can be disabled in the settings

**Comment by thibaultmol** [comment]
so , is draw mode always going landscape? or what do you mean?
I feel like i've used draw mode in portait before.

again, i'm not holding my phone in landscape, I on purpose made sure to really hold it vertically so it would always detect portait. Plus my phone's rotation is locked anyway

**Comment by T8RIN** [comment]
Enter the standalone draw mode and u will see the setting if you not find it in settings sheet

**Comment by thibaultmol** [comment]
the app settings were set to stay locked though: 
![image](https://github.com/T8RIN/ImageToolbox/assets/1010226/3167f381-8e44-4fc4-a0e9-fe5e45873bb4)

**Comment by T8RIN** [comment]
Description is unclear, switch this off and all be ok

**Comment by thibaultmol** [comment]
that does fix it. But it is confusing yeah.

I guess it's confusing if you have this set to on, I would have expected it to never do any kind of ui rotation unlike what you saw in the video

**Comment by T8RIN** [comment]
When i created this i thought that landscape images will be locked to landscape, and portrait to portrait, preventing auto rotate

**Comment by thibaultmol** [comment]
hmm, but in my case it's a portait image, so it should never rotate either way I guess

**Comment by T8RIN** [comment]
You cropped it to be non portrait

**Comment by thibaultmol** [comment]
Oooh ok yeah

Guess I'll see how it behaves when the crop removal bug is fixed.
Thx 👍
