### ISSUE TITLE
Share to Clipboard

### ISSUE THREAD

**Issue by meichthys** [T8RIN/ImageToolbox#630]
Similar to #602, but without the need to save the photo first. 

Often i like to make a quick drawing and send it without first saving it to the device. It would be nice if the 'Share' action gave an option to share the image/drawing to the clipboard.

As a workaround it is possible to install a separate app that the image can be shared to and then re-directed to the clipboard: https://www.youtube.com/watch?v=bSMAixGHsik

It would be nice if this additional app wasn't needed.

**Comment by T8RIN** [comment]
Okay, i will add an additional toggle

**Comment by T8RIN** [comment]
But this might work bad for batch modes
