### ISSUE TITLE
'PDF to images' the exported images are very low res

### ISSUE THREAD

**Issue by 5wHN28Dg** [T8RIN/ImageToolbox#631]
No way to up/control the resolution?

**Comment by T8RIN** [comment]
It's not presented yet?

**Comment by T8RIN** [comment]
It's presented, i've checked now, you can use presets above 100 to make images larger

**Comment by 5wHN28Dg** [comment]
![Screenshot_20240104-071115_Image Toolbox (Resizer)](https://github.com/T8RIN/ImageToolbox/assets/109148083/32458965-6649-45c6-9f7b-086329d03273)
![Screenshot_20240104-071414_Image Toolbox (Resizer)](https://github.com/T8RIN/ImageToolbox/assets/109148083/ab8ccee3-a0ac-4050-929e-0bc3891dbb4b)
 I just tried entering a larger preset value it didn't work the output image is still very low res, here below an image wtih the quality manually set to 125% no change in resolution

![ResizedImage_2024-01-04_07-24-22_1](https://github.com/T8RIN/ImageToolbox/assets/109148083/04e3abaf-d659-46ff-bfa9-cd6cd992e340)

**Comment by T8RIN** [comment]
Quality are not preset

**Comment by 5wHN28Dg** [comment]
There is no option to get a higher quality o/p above what's available that's the problem

**Comment by T8RIN** [comment]
Use "presets"![ResizedImage_2024-01-05_10-03-54_6359.png](https://github.com/T8RIN/ImageToolbox/assets/52178347/e491bd0a-0759-44ff-95b9-558cd069d6e3)

Swipe right or long click on it to add higher preset

**Comment by 5wHN28Dg** [comment]
It worked, thank you so much!
