### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#634]
This tool has a lot of filters. I was wondering if there are presets of filter chains like in imagepipe or snapseed.
If this is not present in imagetoolbox it might be a nice addition in the future. ![](https://i.imgur.com/vrlY5Xr.jpg)

**Comment by T8RIN** [comment]
I can add this, vut i don't know which filters i should yse to achieve effects on the picture, you can provide it, if you can

**Comment by devSJR** [comment]
Thanks for the fast response. I made a mistake. Imagepipe is not able to apply filters. I confused it with another tool.
Photo Editor (MIT licence) has filters. Here is a link to the code likely invoking the filters.
https://github.com/burhanrashid52/PhotoEditor/blob/master/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/ImageFilterView.kt

**Comment by T8RIN** [comment]
No, i don't need such libraries, i just want you to combine my app existing filters to create some presets :) if i add that i would also add ability to create custom presets

**Comment by devSJR** [comment]
Yes, that is of course correct. It was my assumption that you can do exactly that with the existing ~ 60 filters.
I had searched online for cookbooks that describe something like this, but unfortunately, it was not very successful.
That's why the question came up whether you can use existing libraries to do something like this with fast presets. In the end, the filters could still be processed with the existing filters.
I have tried different things, but the creation of the vignette effect, for example, actually from everything else, I have not been able to do it.
In the end, this is exactly what happened to my initial request.

**Comment by T8RIN** [comment]
Vignette works pretty well, can you then tell some names of presets you want to exist initially?

**Comment by devSJR** [comment]
Sorry, for the confusion. I didn't mean that the Vignette effect in ImageToolbox does not work. It works very well. My apologies. I need to be more precise with comments.
What I want to say is that I cannot tell you how others do that. It appears that there are typical image processing workflows to get filters like “oil painting”, “Fine art”, “Accentuate”, “Posh”, “Grunsh”, “Vintage”, “Faded Glow”, “Silhouette” … “Morning”. For example, “Morning” from Snapseed seems to add a gradient of a yellowish tone (bottom) to transparent (top) as double exposure. I looked on the internet and there are just numerous apps doing that. But they don't disclose how they do it exactly.
Maybe in future, somebody with more artistic insight will be able to answer this.
Thanks for considering it!

**Comment by T8RIN** [comment]
Okay thanks for the idea

**Comment by devSJR** [comment]
The latest commits (entering 2.6.1 alpha) exceed by far my enhancement request. Well done!

**Comment by T8RIN** [comment]
I also added a small preview at the start of each filter to easily understand the approximate effect👀

**Comment by T8RIN** [comment]
Alpha 02 will contain more than 44 predefined filters with no arguments

**Comment by T8RIN** [comment]
So, i think this can be closed

**Comment by devSJR** [comment]
The previews are great and very useful.
This is definitely closed!

**Comment by devSJR** [comment]
The previews are great and very useful.
This is definitely closed!
