### ISSUE TITLE
User Defined Centers for Filter Effects 

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#641]
This app has many useful filters. However, it appears that most filters assume that the center of the static or endpoint is in the middle of an image.
It would be great if users could define manually the x and y position for the center of effects.
For example, if a user has taken an image with an object that's on the left side or on the right side or on the top or the bottom of an image, it would be good if he could highlight this particular area by designing the XY position to this. In particular, it would be possible to use the vignette or blur effect on a certain area more intensively or to focus the vignette area on the object.

**Comment by T8RIN** [comment]
Vignette has xy controls, and also you can use the mask filter option, to filter only particular area

**Comment by devSJR** [comment]
Hi. Sorry. But is start and end x and y?

Maybe I should not compare the UI it to snapseed.

This is what I see in ImageToolBox.

![Screenshot_20240106-190333_Image_Toolbox_(Resizer)](https://github.com/T8RIN/ImageToolbox/assets/5408324/93fbaf32-0d05-407c-9b9d-fefc07e06c94)

**Comment by T8RIN** [comment]
Yes it is as i remember 👀

**Comment by devSJR** [comment]
OK. Please, don't get me wrong. I am not intending to say B is better than A. Next I will just describe how snapseed is doing it, to illustrate were my misconception is coming from. The blue dot can be used to adjust the "new" center. Outer and Inner Brightness can be used to change the vignette appearance. I assumed that Start and End are the equivalent to Outer and Inner Brightness.

![Screenshot_20240106-195331_Snapseed](https://github.com/T8RIN/ImageToolbox/assets/5408324/76941fcb-2fdd-41ee-8bf9-6c1e682945ed)

**Comment by T8RIN** [comment]
Thanks, that will be tough task in toolbox because there are many filters and all of them use single value changing mechanism

**Comment by devSJR** [comment]
OK
