### ISSUE TITLE
Pick Image/File from Camera

### ISSUE THREAD

**Issue by meichthys** [T8RIN/ImageToolbox#643]
Currently we can choose an image from the phone's gallery, but it would be nice if there was an option to just take a photo and directly perform actions on that photo. This would be helpful for various workflows, but one example is to use this as a document scanning app. Take photo, convert to pdf and save to Nextcloud.

I'm thinking there could be another button at the bottom of the screen here instead of just "pick file", there could be "camera" or something similar:

![Screenshot_20240106-165034](https://github.com/T8RIN/ImageToolbox/assets/10717998/ef23e17d-8413-4bcc-a52e-c17d20995082)

**Comment by T8RIN** [comment]
I thought about that as image source setting, i'll try to implement

**Comment by T8RIN** [comment]
Added this
