### ISSUE TITLE
Draw on image looks pixelated when zoomed in

### ISSUE THREAD

**Issue by NastyFlytrap** [T8RIN/ImageToolbox#649]
Im using an image with a resolution of 2113 by 2248 and it looks absolutely unreadable when i zoom in.
Issue doesnt exist anywhere else outside this app. 

Also, the zoom isnt using the screen's center as the point to zoom but the image's center, so when i try to zoom in it moves 'my view' of the image closer to the center of the image.

Also also, the app lags really bad. Its running at like 15-20 FPS.

**Comment by T8RIN** [comment]
> the zoom isnt using the screen's center as the point to zoom but the image's center
I know about this one, and cant easily fix because zooming leads to an library

> Draw on image looks pixelated when zoomed in
Ofc because you are drawing on raster image, which consists of pixels

> Also also, the app lags really bad. Its running at like 15-20 FPS.
Everywhere or just in drawing? As possible solution you can disable shadows in app settings

**Comment by T8RIN** [comment]
You are drawing on it, pixels visible, i see no problem, if pixelation occurs somewhere else, this is due to optimisation

**Comment by NastyFlytrap** [comment]
> You are drawing on it, pixels visible, i see no problem, if pixelation occurs somewhere else, this is due to optimisation

Just because the end result doesnt come up overly pixelated doesnt mean that it should look like this while its being edited.
What if someone needs the precision its taking away from them? In fact, i do, because i need to be able to read the damn text to know what im drawing over......

**Comment by T8RIN** [comment]
More zoom more pixels visible, isn't it?
