### ISSUE TITLE
Improved it's ui design

### ISSUE THREAD

**Issue by iBabu007** [T8RIN/ImageToolbox#652]
It is too good and powerful app but don't  
you throughout that it's present ui is not for this app.
If possible then change its design
View image/pdf form file (not open in edit space.)

Swipe up to open Edit tools with 
two section image and pdf
__________________________________

                   Image Toolbox       ⚙️ 

                + Pick image/pdf
 

_________________________________ ^                          
                           Image

filter | adjust | crop | compress | BG remover | blur/vintage | collage | stretch | draw | text | sticker | overly | compare | set-as | info | encrypt/decrypt | Remove EXIF | share |

__________________________________
                             PDF

img-pdf | pdf-img | rearrange | compress | draw | sticker | img/sign | lock/unlock | info | encrypt/decrypt | Remove EXIF | share |
_________________________________

![Screenshot_20240111-131452](https://github.com/T8RIN/ImageToolbox/assets/65340361/e356afeb-8111-4550-9050-83fb2ac7cb41)

![Screenshot_20240111-162244](https://github.com/T8RIN/ImageToolbox/assets/65340361/8d03f412-a325-46b9-9aff-4e13dace0d64)

**Comment by T8RIN** [comment]
Hi, this an improvement to single edit mode i think, thanks for suggestion, but this can't be done :( only if living in single edit option, could you rewrite it to be possible for this thing?👀

**Comment by rsuu** [comment]
@T8RIN 
How about this?

![a](https://github.com/T8RIN/ImageToolbox/assets/38876461/efd6dbf8-abe6-488d-b453-5ca28dfe5511)

**Comment by T8RIN** [comment]
Hm, looks like current filters but without sheet, also filters have additional params, like extension and so on

**Comment by rsuu** [comment]
And hope we can show the image view only once when changing tools.
Like this
![a](https://github.com/T8RIN/ImageToolbox/assets/38876461/84717aee-9692-4f4c-9a5b-369a1f976276)

**Comment by T8RIN** [comment]
Looks better, thanks, i will implement this sometime i hope, but i added some suggestions to filters already, it will be a part of 2.6.1 👀
