### ISSUE TITLE
GPS / Geo-Location data lost on edit

### ISSUE THREAD

**Issue by foss-** [T8RIN/ImageToolbox#654]
**Reproduce**

1. select `Draw` for an image with GPS data
2.  enable `Keep EXIF` option so that metadata is kept
3. draw on image
4. tap disc icon to save image
5. see confirmation dialog

**Currently**

When looking at the edited image, the GPS data is gone.

**Expected**

All metadata should be kept.

**Comment by foss-** [comment]
Thanks for the response. When I open `Settings > Image source` I see Photo picker selected. Since that option mentions `Has issues receiving EXIF metadata` I switched to `Gallery` and repeated above steps but saved image still has no GPS data.

**Comment by T8RIN** [comment]
Hm, even with get content?

**Comment by foss-** [comment]
Third option works and keeps the GPS metadata 🎉
This is very helpful, been wondering about this for a long time.

Would it make sense to remember the EXIF setting last used? My personal use-case requires this to be on, but it is always off when I go into editing.

**Comment by T8RIN** [comment]
Hm, i can add an additional setting if you want :)

**Comment by foss-** [comment]
Not sure how this is best handled. Follow last used state avoids an additional settings option and my be sufficient. Certainly a setting is also possible - not sure which section would fit and adding yet another section to settings would make them even more crowded so not a fan. But if you have an existing category in mind sure.

**Comment by T8RIN** [comment]
In the additional exif category, i prefer this way because it's much easier to implement 👀

**Comment by foss-** [comment]
Sure, you're the boss and since I can't code happy either way 🚀

Do you want a separate issue for that feature request?

**Comment by T8RIN** [comment]
Yup, that's would be great 💯

**Comment by foss-** [comment]
Persisting in 2.6.0a3. Could you re-open this issue? Sadly none of the three image source options allows to keep the GPS information in the image when saving a draw edit. The timestamp was kept with all three options.

This feels like a problem in Android behavior.

Found a similar issue filed against Nextcloud and fm-sys pointed out that `Stripping EXIF data is part of the android Q privacy feature set. Starting with Android 10 (or 11?), apps need to explicitly specify that they want to receive Metadata.`.

If you'd be willing to take a look how to specifically request to receive EXIF data when opening an image, that might solve this issue.

In comment https://github.com/nextcloud/android/issues/6248#issuecomment-1147167524 there are also three links about the behavior which are:

* https://stackoverflow.com/questions/68442139/exif-location-data-removed-when-sharing-photo-via-intent
* https://developer.android.com/reference/android/provider/MediaStore#EXTRA_ACCEPT_ORIGINAL_MEDIA_FORMAT
* https://issuetracker.google.com/issues/128675076

**Comment by T8RIN** [comment]
Thanks, i will check

**Comment by T8RIN** [comment]
I did this i think, checked with latest image source and location not lost on android 14 😄
