### ISSUE TITLE
[Feature] add setting to keep EXIF data on edit

### ISSUE THREAD

**Issue by foss-** [T8RIN/ImageToolbox#655]
Use-cases vary and there may be users who want the option to keep EXIF data enabled.

**Currently**

Always defaults to off without an option to change it.

**Expected**

Either remember last used state or, if easier to implement, add a settings option to set the default to keep EXIF data. Don't care about the default state, but being able to change the default would be very useful. Thanks for considering.

**Comment by T8RIN** [comment]
Added :)
