### ISSUE TITLE
Draw view cannot be closed

### ISSUE THREAD

**Issue by foss-** [T8RIN/ImageToolbox#663]
**Describe the bug**

The preview image does not show edits made to the image.

**To Reproduce**

1. from Aves Libre select Edit and open ImageToolbox
2. select Draw to edit the image (Image Toolbox switches to landscape view)
3. set Keep EXIF (probably not relevant) and do some drawing on the image
4. tap disk icon to store image
5. see confetti animation and info box about stored image
6. try to leave draw view by tapping top left back arrow
7. confirm dialog `Saving - All unsaved changes will be lost if you exit now` with `Close`

**Currently**

see spinner / loading animation for a second and user is back in draw view.

**Expected behavior**

Leave draw view.

**Smartphone:**
 - Device: Xiaomi Lisa
 - OS: ArrrowOS 13.1
 - ImageToolbox 2.6.0-alpha01 (21 foss)

**Comment by T8RIN** [comment]
Hmm, thanks for the report

**Comment by foss-** [comment]
This is resolved in 2.6.0a2 foss (108).
Another thing that is fixed is that for draw view, the app kept switching to landscape view, which was annoying. This is also resolved.

**Comment by T8RIN** [comment]
Switching for landscape is an additional setting 👀

**Comment by foss-** [comment]
I did not alter any other setting than the new EXIF option. Curiously I now found that option in `Draw > Lock draw orientation`. That setting its off for me and yet the app no longer rotates.

I would find non-rotation the better default, but besides that, there seems to be a mismatch with the shown setting state and app behavior.
