### ISSUE TITLE
Delete function in compare mode

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#664]
I have started to use the compare mode very intensively. In particular, I used this mode to compare images that were taken with different exposure times. So they show the same scene but with different brightness.
It would be great if the compare mode could be enhanced by a file operation, in this case by a delete functionality, because I want to discard one of the two compared images that I do not use. So I would preferably use the image with the most details or the best appearance or whatever counts. I guess this would be useful for many other users too.

**Comment by T8RIN** [comment]
Delete something is hard but can be done i think, i will look 👀

**Comment by devSJR** [comment]
Thanks

**Comment by T8RIN** [comment]
Playmarket doesn't publish 3.0.0 because of MANAGE_EXTERNAL_STORAGE permission, so this will not be added :(

**Comment by devSJR** [comment]
Thanks for trying!

**Comment by T8RIN** [comment]
Too much effort to split up these features too :(

**Comment by devSJR** [comment]
Ok. Thanks for considering.
