### ISSUE TITLE
Romanian translation

### ISSUE THREAD

**Issue by Alexandru51** [T8RIN/ImageToolbox#67]
Hello, i translated this app in romanian from weblate. So, can you add it in the next update if posibile?

**Comment by T8RIN** [comment]
Hi, yup, it already merged, as you can see :)

**Comment by T8RIN** [comment]
And thanks for your work!👀

**Comment by Alexandru51** [comment]
Thank you, and you're welcome 😄

**Comment by Alexandru51** [comment]
Hello, i updated the romanian translation, so can you apply it on the next update please? @T8RIN

**Comment by T8RIN** [comment]
Of course, but 2.3.1 is an experiment without changes, wait for it in 2.3.2 👀

**Comment by T8RIN** [comment]
Also i added some new strings recently

**Comment by Alexandru51** [comment]
Lol, already? :)

**Comment by T8RIN** [comment]
> Lol, already? :)

Yup :) I'll push the changes now, wait 👀

**Comment by Alexandru51** [comment]
And translated the string that you added

**Comment by T8RIN** [comment]
Thanks!
