### ISSUE TITLE
Unable to save: "...not called Looper.prepare()"

### ISSUE THREAD

**Issue by uahim** [T8RIN/ImageToolbox#673]
**Describe the bug**
(Sorry if this is a duplicate; I did search both closed and open issues)
When trying to save any format (jpg, png, etc), the following error pops up:
`Something went wrong: Can't create handler inside thread that has not called Looper.prepare()`

**To Reproduce**
Tap the save button

**Expected behavior**
One would expect the image to be saved

**Screenshots**
![Untitled](https://github.com/T8RIN/ImageToolbox/assets/6866794/857c6990-aa45-4641-bada-c9efa3184280)

**Smartphone (please complete the following information):**
 - Device: Samsung J5
 - OS: Android 7.1.1 unrooted

**Comment by T8RIN** [comment]
Which saving settings did you use?

**Comment by uahim** [comment]
I did not change any settings in the app (save for theme/appearance later on)

**Comment by T8RIN** [comment]
Okay, i will look

**Comment by T8RIN** [comment]
looked through the code, there no handlers at all, is it happens on latest beta? Also which screens are affected

**Comment by uahim** [comment]
thank you for checking

the version is 2.5.1 (105) installed via F-Droid app

define screen please, it happens whenever I try, e.g. edit/single edit, create/draw etc

**Comment by T8RIN** [comment]
Could you check on the lastest beta please?

**Comment by uahim** [comment]
yes, beta works fine

thanks!

**Comment by T8RIN** [comment]
Nice 🐸
