### ISSUE TITLE
Option for maximum screen brightness

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#674]
It is quite possible that I have overseen this function under the vast amount of option available in this app. However, I would like to suggest to add an option that enables the user to increase the screen brightness to maximum intensity while editing images or comparing images.

**Comment by T8RIN** [comment]
Okay, i will add something like that :) Maybe option for enabling for all screens or for choosen ones

**Comment by devSJR** [comment]
I would recommended any screen that shows an image (filter, compare …).
Browsing through the menu, selecting an image may not need the brightest screen.

**Comment by T8RIN** [comment]
This would be customizeable in the settings ofc

**Comment by T8RIN** [comment]
Added

**Comment by devSJR** [comment]
Works perfectly!
