### ISSUE TITLE
Compare function with transparency could also be a good method to get a kind of double exposure

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#675]
I just noticed that the new compare function with transparency could also be a good method to get a kind of double exposure to a picture. I often take two pictures from the same scene at different brightness levels, and then I choose the best colors with the most details. One now could use the slider to find a good middle between the two. Currently, of course, a function is missing to save.
You could also use this function to take a scene and then move a small object in the same scene and then take another picture and then put the overlap of the two pictures together as a final picture. A concrete example would be, you stand in front of an object or a scene as a person. Then you take the first photo, move to the left or right, take the second photo. So the person would be with his digital twin.
So I would like to suggest that you use this function as a basis and to improve it. For example, it could be useful to better map/correlate significant points of the images, i.e. based on landmarks.

**Comment by T8RIN** [comment]
That was asked a long ago, so will be added sometime👀

**Comment by devSJR** [comment]
Oh, I am sorry. I didn't check for such a suggestion from other users. It is nothing with high priority, I would say. The level of features for an open-source image processing software is incredible. There is nothing else like that.

**Comment by T8RIN** [comment]
Thanks for using 🐸

**Comment by T8RIN** [comment]
Now you can use the watermark feature as a double exposure mode
