### ISSUE TITLE
Stitch images free-handed (Layers Mode)

### ISSUE THREAD

**Issue by DrStrangeloovee** [T8RIN/ImageToolbox#676]
**Currently the image stitching only allows three modes to merge two or more images. A free-handed mode is missing.**

**I would like to have the functionality to merge multiple images together. It should be possible to place images anywhere, create overlaps between images, adjust the size and orientation of each image additionally being able to define the layers and their order would be great.**

**Comment by T8RIN** [comment]
I will think but now definitely no, too hard, this might be a part of layers mode

**Comment by T8RIN** [comment]
You can use the new draw image on the path option in the drawing screen

**Comment by Ashtaavakra** [comment]
I tried very hard to find this function. Now it confirms that it is not available in the App.
