### ISSUE TITLE
Combine color gradients and images

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#686]
If I understand all the commits correctly, version 2.6 will give the possibility to create color gradients. This is a great thing.
This gives users an interesting opportunity to edit images.
However, a requirement is that it should be possible to overlay images, similar to the suggestion with the double exposure.
The whole thing is based on creating a color gradient as the background or foreground in a transparent form to an existing image.
For example, a color gradient can be applied on a relatively “boring” target image, which would not occur in this way. An application is that you start with a slightly orange-yellow tone on the ground and let the color gradient run up into the blue. If you lay this over a landscape (target image), you can create the impression of a warm summer day. 
Another application would be to put such a gradient over a portrait so that you can create very artistic, stylistic images.
However, I have to admit that this is not a trivial feature request. On the one hand, the software would need to be developed in such a way that the function for creating the gradient recognizes how large an existing image is. Then all this should be possible to edit the gradient in real-time on the target image so that the user can make the appropriate settings. 
Moreover, one needs an algorithm that offers the possibility to combine the color gradient with the target image very efficiently.
I think it's more of an idea that might come up in the future. But in the present, it seems like a huge and complicated job.

**Comment by T8RIN** [comment]
Hm, i can add it not as an separate option or overlaying images rather than Integrate this to the existing gradient maker screen, i mean you will can select, whether you want create gradient, or overlay image with it

**Comment by devSJR** [comment]
Yes, this sounds quite reasonable to me. And I wonder if this wouldn't be also the best approach to implement this double exposure thingy. Because at the end of the day, it shouldn't matter whether the user decides to use a gradient or another image. Am I wrong here?
Oh, let me think. I guess I might be wrong here because I guess that double exposure might require an algorithm to align two differently exposed images to landmarks.
My fault could be that the images in the double exposure in question still have to be adjusted to each other in their positioning. This would not be important with the gradient.
What I mean by that is, if people take pictures twice and want to put them on top of each other, it can happen that these pictures move slightly in their position so that you would have to use landmarks to position them correctly. In this respect, I think there are two different applications. Gradient is an application and double exposure is an application. Double exposure is indeed much more complicated.

**Comment by devSJR** [comment]
I just installed the current beta version. 💡 The funny thing is that you could even put a fake planet (or fake start (sun)) in the image if you used the radial as a gradient type.

**Comment by T8RIN** [comment]
> I just installed the current beta version. 💡 The funny thing is that one could even put a fake planet (or fake start (sun)) in the image if you used the radial as a gradient type. 

Sounds interesting, i will add the ability to choose an option, like in the draw screen

**Comment by devSJR** [comment]
> Yup, but overlaying two images with transparency or blend modes will be added too, without layers for now, it's quite hard, so i will implement easy features first, watermarks waiting me for half a year 🐸

I thought to myself that this is not a trivial question because one really has to consider and implement a lot. Watermarks are indeed something that is very practical, especially nowadays, where you sometimes want to make sure that you have created the picture or that it is really original.

**Comment by T8RIN** [comment]
Working at night to make the best app :)

**Comment by devSJR** [comment]
> Working at night to make the best app :)

I had the impression that you work full time on the project.  It is really a great app with great functions. I hope that there will be more people who use the software and that some developers will participate in it in the future.

**Comment by T8RIN** [comment]
Also this is just my hobby, during the day I have work on other projects waiting for me 👀

**Comment by T8RIN** [comment]
Added this 😄

**Comment by devSJR** [comment]
If you make a new beta, I can test it.

**Comment by T8RIN** [comment]
I released the last alpha yesterday, so the next beta will be until the end of this week, but you can download the compiled apk from actions section

**Comment by devSJR** [comment]
😲 Each commit triggers a build? That's really crazy. So GitHub has to have a decent power bill.

**Comment by T8RIN** [comment]
And it's free :))

**Comment by devSJR** [comment]
Works as expected.
Could you add the compare feature to the interface like we have it for the filter?

**Comment by T8RIN** [comment]
Okay, can you start a separate issue for this please?

**Comment by devSJR** [comment]
OK
