### ISSUE TITLE
Add options to preprocess images for OCR

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#687]
Please add options to preprocess images for OCR. Typically following preprocessors are used:

- Enhance Contrast: Adaptively attempts to expand the contrast to the full dynamic range  (guess that is already used, but not an option)
- Un-Sharp Masking: Performs unsharp masking (edge enhancement) of image (guess that is already used, but not an option)
- OTSU Threshold: Performs locally-adaptive Otsu threshold *binarization* of image (guess that is already used, but not an option)
- Deskew Image: Find the Skew and Deskew the Image  (not present in ImageToolBox)
- Rotate image (only 90° rotation present in ImageToolBox)
- Crop image (present in ImageToolBox)

**Comment by T8RIN** [comment]
Okay, i'll look what i can add using existing filters api :)

**Comment by devSJR** [comment]
Adjusting the perspective is a non-trivial task as far as I can see. I've looked what is available and there seems to be one open source package based on OpenCL that is capable of doing that. So I think it's not really an option currently to be consider for implementation in imagetoolbox.

https://github.com/danopdev/Perspective

**Comment by T8RIN** [comment]
Yup, this needs opencv or smth else and quite tricky to implement

**Comment by T8RIN** [comment]
added
