### ISSUE TITLE
Compare feature to the gradient interface

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#688]
From version 2.6, a color gradient can be placed over an existing image. In order for the user to set the optimal properties, it would make sense to integrate the comparison function, as it is also available in the filters, into this interface. This allows the user to create the optimal properties very finely in their images and achieve optimal results. 
In addition, such a function could be used to compare two gradients with each other. 
However, I see practically no cases of application for this, so the focus should probably only be on the first case.

**Comment by T8RIN** [comment]
I just realized that the gradient overlay feature can be applied on a batch of images easily, so i need to add multiple image picking now

**Comment by devSJR** [comment]
It is still baking on GitHub. Will test ASAP.

**Comment by devSJR** [comment]
> added 😄

It is still baking on GitHub. Will test ASAP.

**Comment by T8RIN** [comment]
also added batch processing
