### ISSUE TITLE
Center indicator for filters with xy position parameters 

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#694]
Some filters have an option to set the xy position. Some filters would benefit from a position indicator (e.g. red cross) to indicate the position of the center.
Usecase: if the blur size is low it is hard to see its center. Having an toggleable indicator or an indicator that is only shown while the position is altered users could faster adjust the parameters.

**Comment by T8RIN** [comment]
It's really hard to do with current filters implementation, so for now i just can't add it :(
