### ISSUE TITLE
Histogram for RGB

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#695]
It would be great to have a histogram like Aves libre in images. This might be useful to adjust images.

**Comment by T8RIN** [comment]
Thx for the suggestion, i'll look :)

**Comment by T8RIN** [comment]
I almost added this to embedded picker image preview and separate image preview option, i think it's also handy for filters screen, but idk where to place it

**Comment by devSJR** [comment]
Thanks
