### ISSUE TITLE
The gradient maker crashes after only having 2 colors.

### ISSUE THREAD

**Issue by J43git** [T8RIN/ImageToolbox#704]
Device: moto e (motorola - ginna), SDK: 29 (10), App: 2.6.0-beta01 (111)java.lang.IllegalArgumentException: needs >= 2 number of colorsat android.graphics.Shader.convertColors(Shader.java:190)at android.graphics.LinearGradient.<init>(LinearGradient.java:70)at o1.f0.b(SourceFile:130)at o1.r0.a(SourceFile:27)at q1.c.b(SourceFile:11)at q1.c.d(SourceFile:14)at q1.c.P(SourceFile:44)at d2.i0.P(SourceFile:1)at q1.g.i(SourceFile:65)at ef.p.m(SourceFile:194)at l1.e.g(SourceFile:1)at d2.i0.b(SourceFile:32)at d2.h1.D0(SourceFile:52)at s.b1.a(SourceFile:319)at s.b1.c(SourceFile:178)at j8.g9.g(SourceFile:60)at f1.u.a(SourceFile:48)at f1.v.c(SourceFile:153)at d2.t1.a(SourceFile:1)at o1.u0.m(SourceFile:475)at e2.w2.B(SourceFile:24)at e2.y2.i(SourceFile:40)at e2.a0.dispatchDraw(SourceFile:69)at android.view.View.draw(View.java:21485)at android.view.View.updateDisplayListIfDirty(View.java:20359)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)at android.view.View.updateDisplayListIfDirty(View.java:20319)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)at android.view.View.updateDisplayListIfDirty(View.java:20319)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)at android.view.View.updateDisplayListIfDirty(View.java:20319)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)at android.view.View.updateDisplayListIfDirty(View.java:20319)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)at android.view.View.updateDisplayListIfDirty(View.java:20319)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)at android.view.View.updateDisplayListIfDirty(View.java:20319)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)at android.view.ViewRootImpl.draw(ViewRootImpl.java:3699)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3507)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2837)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1797)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7748)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)at android.view.Choreographer.doCallbacks(Choreographer.java:790)at android.view.Choreographer.doFrame(Choreographer.java:725)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)at android.os.Handler.handleCallback(Handler.java:883)at android.os.Handler.dispatchMessage(Handler.java:100)at android.os.Looper.loop(Looper.java:241)at android.app.ActivityThread.main(ActivityThread.java:7604)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by J43git** [comment]
Now I really love this feature, but it crashes if you don't have at least 3 colors, which isn't a problem unless I'm looking to do a specific 2 color palette, like the colors of Alpha Kappa Alpha for example. Save me!

**Comment by T8RIN** [comment]
I'll fix, thanks :)
