### ISSUE TITLE
Crop and rotate everywhere 

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#707]
Crop and rotate are things that I frequently do with images. I would greatly appreciate it if it would also be available in filter chain and other tools.

**Comment by T8RIN** [comment]
Cropping is impossible at the moment for batch  modes, so if you need to filter and crop at the same time then take a look at a single edit screen, it has all the most used features :)

**Comment by devSJR** [comment]
Thanks you. I was not aware of this.

Too many features ;)

**Comment by devSJR** [comment]
Thank you. I was not aware of this.

Too many features ;)

**Comment by T8RIN** [comment]
:)
