### ISSUE TITLE
App showing up for unrelated Android intents

### ISSUE THREAD

**Issue by Terrance** [T8RIN/ImageToolbox#720]
#### Describe the bug

As of 2.6.0, Image Toolbox is now being shown as a target for Android intents it probably doesn't belong to, including "add new contact" and "add calendar event" intents.

Choosing it in either case seems to just start the app as if from the launcher, so I'm assuming there's no special behaviour here and the app is incorrectly registered for those intents.

#### To reproduce

So far I've found these two using [FairEmail](https://email.faircode.eu)'s add/edit contact options and [Todo Agenda](https://f-droid.org/packages/org.andstatus.todoagenda/)'s widget's add event button.

#### Expected behavior

Image Toolbox to not be presenting itself as an option.

#### Screenshots

From the resulting prompts to select capable apps to handle the contact and calendar intents:

<img src="https://github.com/T8RIN/ImageToolbox/assets/4025899/6e2a9c03-3fdb-4901-aadf-2958b104caa9" width="300">
<img src="https://github.com/T8RIN/ImageToolbox/assets/4025899/a5da4a67-77f1-4f87-914f-2dba80c094e1" width="300">

#### Smartphone

 - Device: OnePlus Nord CE
 - OS: Android 13

**Comment by T8RIN** [comment]
Looks quite interesting

**Comment by T8RIN** [comment]
It will be useful if you can catch those intents through app manager and show their values

**Comment by Terrance** [comment]
Copying from App Manager's interceptor (so hopefully in a useful format for you):

```
URI	intent://com.android.contacts/contacts/lookup/1291e91d45dcc-15ea-23fa-1383-91f097a9494b..vcf/1533#Intent;scheme=content;action=android.intent.action.EDIT;type=vnd.android.cursor.item/contact;launchFlags=0x3000000;S.email=notifications%40github.com;end

VERSION	1
ACTION	android.intent.action.EDIT
DATA	content://com.android.contacts/contacts/lookup/1291e91d45dcc-15ea-23fa-1383-91f097a9494b..vcf/1533
TYPE	vnd.android.cursor.item/contact
FLAGS	0x3000000
EXTRA	email	12	notifications@github.com

MATCHING ACTIVITIES	3
0	LABEL  	Contacts
 	NAME   	com.android.contacts.activities.ContactEditorSpringBoardActivity
 	PACKAGE	com.android.contacts
1	LABEL  	Interceptor
 	NAME   	io.github.muntashirakon.AppManager.intercept.ActivityInterceptor
 	PACKAGE	io.github.muntashirakon.AppManager
2	LABEL  	Image Toolbox (Resizer)
 	NAME   	ru.tech.imageresizershrinker.presentation.AppActivity
 	PACKAGE	ru.tech.imageresizershrinker
```

```
URI	intent://com.android.calendar/events#Intent;scheme=content;action=android.intent.action.INSERT;launchFlags=0x17200000;l.endTime=1706734800000;l.beginTime=1706731200000;end

VERSION	1
ACTION	android.intent.action.INSERT
DATA	content://com.android.calendar/events
FLAGS	0x17200000
EXTRA	endTime	8	1706734800000
EXTRA	beginTime	8	1706731200000

MATCHING ACTIVITIES	3
0	LABEL  	Interceptor
 	NAME   	io.github.muntashirakon.AppManager.intercept.ActivityInterceptor
 	PACKAGE	io.github.muntashirakon.AppManager
1	LABEL  	Image Toolbox (Resizer)
 	NAME   	ru.tech.imageresizershrinker.presentation.AppActivity
 	PACKAGE	ru.tech.imageresizershrinker
2	LABEL  	Etar
 	NAME   	com.android.calendar.EditEventActivity
 	PACKAGE	ws.xsoh.etar
```

**Comment by T8RIN** [comment]
Is it persited on 2.5.1 ?

**Comment by Terrance** [comment]
Downgraded to 2.5.1, doesn't happen there.

**Comment by T8RIN** [comment]
Not a fix, broken everything

**Comment by T8RIN** [comment]
This should help 😄
