### ISSUE TITLE
Add Image Splitter for carousels

### ISSUE THREAD

**Issue by KittyBloo** [T8RIN/ImageToolbox#724]
## Is your feature request related to a problem? Please describe.
I've been searching for a tool that can cut long images into smaller images so that I can post them in carousels on platforms like instagram.

## Describe the solution you'd like
An image splitter that can split images into equally sized smaller images on either the X-axis Y-axis or both.

## Describe alternatives you've considered
_There's no alternative i could find that outputs the images with full resolution and no glitches._

**Comment by T8RIN** [comment]
Sounds like an great idea, but may be quite complicated to implement, so i will look if i can add this 😄

**Comment by T8RIN** [comment]
Added hopefully
