### ISSUE TITLE
Auto privacy blur background

### ISSUE THREAD

**Issue by Toiletmason** [T8RIN/ImageToolbox#728]
It would be nice to have it autodetect that background and give then the options to what degree you want it blurred without having to do it manually. 

If this is already in there and I couldn't find it I apologize for being a moron.

**Comment by T8RIN** [comment]
It can't be done automatically , only of you use mask filters you can select which areas will be filtered

**Comment by T8RIN** [comment]
Closed in favor of #1121, but it's possible now using image stacking option, just make blurred one, one with erased bg and stack them together
