### ISSUE TITLE
Get rid of unnecessary permissions

### ISSUE THREAD

**Issue by uhyf3** [T8RIN/ImageToolbox#730]
Installing from Google Play includes risky permissions, including "run foreground service" and "have full network access," without the ability to opt out. Editing files doesn't require these.

It would help security to eliminate these permissions.

**Comment by T8RIN** [comment]
You have options like tedt recognition which downloads trainedpdels, loading image from network, and also 4 quick tiles to capture the screen and edit it on the go

**Comment by uhyf3** [comment]
How about a fork without the network access or without any "Other" category
permissions?

**Comment by T8RIN** [comment]
It's impossible, i have features which are needing it

**Comment by uhyf3** [comment]
On Saturday, February 3, 2024, Malik Mukhametzyanov <
***@***.***> wrote:

> It's impossible, i have features which are needing it
>
Can you put some compile-time "if statements" in to be able to compile
without those features?

**Comment by T8RIN** [comment]
I have the foss version already, i will not create another one which doesn't have "dangerous" permissions with stripped features, this foss version following all standards, it built by f-droid, they know about all of that, and you can look through the code if app really needs those permissions or not

If you didn't allow these ones you can just not use the app anyway 👀

**Comment by T8RIN** [comment]
On the play store there are tons of trash closed source apps with ads and tracking, which are quite similar to mine in some aspects, but none of them are collecting all the tools in one place with small app size and sources that everyone can look into

**Comment by uhyf3** [comment]
There aren't many apps with good features and good permission security on Google Play; you could do some real good by having a concurrent version using compile-time "if statements" with 1 code base for both, and having them both on Google Play.

**Comment by T8RIN** [comment]
Sorry, but i will not do this :(
