### ISSUE TITLE
Wrong colors when coverting

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#737]
**Describe the bug**
Converting to heif and jxl leads to unexpected and bad color conversion

**To Reproduce**
Do the above

**Expected behavior**
Colors looking the same.
Maybe add options for color space?

**Screenshots**
<img width="990" alt="Untitled" src="https://github.com/T8RIN/ImageToolbox/assets/87526638/022f4181-909e-4f34-b70a-1df8c5724213">

HEIF looks bland, while JXL looks like bleach

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A33
 - OS: OneUI 6.0

**Comment by T8RIN** [comment]
This related to awxkee/jxl-coder

**Comment by kremzli** [comment]
Does it not have any color related options? Should i make issues to awxkee/jxl-coder and awxkee/avif-coder (for heif) ? Or will you handle that, cuz i dont really know how to work with that stuff

**Comment by T8RIN** [comment]
I have contact with dev, he said that will fix jxl, but avif is okay

**Comment by kremzli** [comment]
Heres a good example of that jxl color issue:

![image](https://github.com/T8RIN/ImageToolbox/assets/87526638/a1f77fd7-ec91-4a1c-820a-e86a18282450)

Follow bar straight up gone

**Comment by kremzli** [comment]
> I have contact with dev, he said that will fix jxl, but avif is okay

I meant the heif looking bland, that avif library handles heif too, or is it just the container?

**Comment by T8RIN** [comment]
Yup, just container

**Comment by T8RIN** [comment]
Fixed for jxl
