### ISSUE TITLE
Dont use JXL with max effort by default

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#738]
**Describe the bug**
Max effort is quite exhaustive, on lower end devices that is too slow and will cause crashes

**To Reproduce**
Input image, select a JXL option, you get effort 9

**Expected behavior**
Maybe use effort 7 by default, ive seen that as default in every other JXL capable image converter / editor

**Screenshots**
Not needed

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A33 
 - OS: OneUI 6.0

**Comment by T8RIN** [comment]
I Set this as 7, thanks :)
