### ISSUE TITLE
Quality slider for JXL Lossy and effort slider for AVIF

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#739]
**Is your feature request related to a problem? Please describe.**
While the defaults are good (idk about AVIF effort), sometimes those options would be nice. Like when converting in bulk or when you want it to try even harder. Or you want to compress (with JXL) harder

**Describe the solution you'd like**
Adding an a quality option for JXL Lossy (i would prefer using "distance", but doesnt really matter) and effort slider for AVIF

**Describe alternatives you've considered**
None?

**Comment by T8RIN** [comment]
Can't say about avif because it relies on Library, but added for jxl some additional params

**Comment by T8RIN** [comment]
about effort better ping the avif-coder

**Comment by kremzli** [comment]
https://github.com/awxkee/avif-coder/issues/16
