### ISSUE TITLE
Equalize images

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#740]
The following description might be applied in many places of imagetoolbox, for example in stitching or even in batch processing.

When users take images in a short time frame, they might appear very similar but still differ a bit in their brightness or other properties.

It would be nice to have a function that enables the user to equalize the image. For example, to make them all have the same brightness, to make them have the same exposure or contrast or something that is a combination thereof.

In that situation, the user could select a bunch of images and then use the preview that is already implemented in image toolbox to look for acceptable adjustments.

If I'm not totally wrong, one task of imagetoolbox would be to get the values of each image and then calculate the average of these and then calculate the differences of these images, which then are the foundation to adjust the images to each other. An alternative would be that the users do not adjust their values themselves, but ImageToolbox tries to find the optimum.

**Comment by T8RIN** [comment]
Sounds interesting, but i have no idea how to implement it

**Comment by devSJR** [comment]
You are a smart developer. Eventually you will come up with a good idea. If not it's also fine.

**Comment by T8RIN** [comment]
I ll close it as not planned for now, but maybe came back in the future 😄
