### ISSUE TITLE
Missing jxl-coder in readme

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#742]
**Describe the bug**
jxl-coder library is missing from the readme

**To Reproduce**
Scroll here https://github.com/T8RIN/ImageToolbox?tab=readme-ov-file#-tech-stack--open-source-libraries

**Expected behavior**
See jxl-coder ( https://github.com/awxkee/jxl-coder )

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 
 - OS:

**Comment by T8RIN** [comment]
Added
