### ISSUE TITLE
Is there JXL lossless JPEG transcoding?

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#743]
**Is your feature request related to a problem? Please describe.**
One of JXL's main features is lossless JPEG transcoding, completely converting optimised JPEG is many times only going to be bigger. This lossless transcoding is also reversible

**Describe the solution you'd like**
Add lossless JPEG transcoding. Maybe add a function to reverse it too? Like when converting JXL to JPEG it could maybe detect that it can be reversed and do that by default

**Comment by T8RIN** [comment]
you should better write it to the jxl-coder, because it doesn't have this feature yet

**Comment by kremzli** [comment]
This is now a feature in [jxl-coder](https://github.com/awxkee/jxl-coder/releases/tag/2.0.0). (losslessly) Transcoding jpeg into jxl is almost always better, but there should be an option to not transcode too (transcoding should be on by default as is with libjxl)

**Comment by T8RIN** [comment]
Thanks

**Comment by T8RIN** [comment]
I will add separate jxl tools for it, because it uses some different mechanism

**Comment by kremzli** [comment]
Where is it? Im on alpha 3 and using jxl lossless doesnt seem to transcode. Jpegli also doesnt do that (and its not what would do it anyway, but i really like that its there now)

**Comment by T8RIN** [comment]
Use jxl tools option, transcoding requires usage of raw files
