### ISSUE TITLE
More default settings

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#744]
**Is your feature request related to a problem? Please describe.**
I always change the extention, resize type and clear exif.

**Describe the solution you'd like**
I would like for those to have default options in settings

**Comment by kremzli** [comment]
It would also slightly save a bit of battery since i dont have to change those options while the image gets reprocessed with every option change

**Comment by T8RIN** [comment]
Extension came from the selected image, so it can't be overridden, but for resize type it's possible

**Comment by T8RIN** [comment]
Also clear exif is also default setting, and you can change it to always on in settings 👀

**Comment by kremzli** [comment]
Then i think it should be named "Always clear" and have a clearer description. It doesnt sound like it clears it

**Comment by T8RIN** [comment]
I have save exif selector, and setting controls default value, if checked, then exif will be saved

**Comment by kremzli** [comment]
Yes but the name and description require already knowing about how that option inside the editor works, changing it to "Always clear" and describing it as "Clears exif by default" would be much easier to understand

**Comment by kremzli** [comment]
Progress? Heres the summary of this issue: The default extension selection based on the file is fine, the resize type should have a default setting (for people who want to always keep aspect ratio or crop by default), and the exif option is definitely not clear: "Force initial value" (and its description) doesnt say anything about what will be done to exif, so i suggest changing it to changing it to "Always clear" and describing it as "Clears exif by default"

**Comment by T8RIN** [comment]
Patience, all will be done
