### ISSUE TITLE
See original size when compressing

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#747]
**Is your feature request related to a problem? Please describe.**
Seeing the original size of the source image would be nice to compare.

**Describe the solution you'd like**
Show the original size of the source image probably at the top in smaller text under the converted size (idk maybe you can do better). Maybe also add a % of difference between them (EX: -20% would show in green or +10% would show in red because you wouldnt want it to be bigger)

**Describe alternatives you've considered**
None

**Comment by kremzli** [comment]
I just realized ive been comparing to the first size i see, which is the size of a recompression instead of the original file size. So for already optimised images that would usually always be bigger than the original and theres nothing telling you that

**Comment by T8RIN** [comment]
this is the size, which image would take if you save it right now

**Comment by kremzli** [comment]
Yes but im proposing to see the original size too in a way that makes comparing easy, so that people dont do what i did in my 2nd comment

**Comment by T8RIN** [comment]
Ofc, i will investigate for possible solution
