### ISSUE TITLE
Filter mask shapes (whole area)

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#756]
Filter masks are great for working with specific filters in certain areas in pictures. However, sometimes I also want to cover, additional to selected areas, the picture with a global filter mask (no area selected). So far, I have not been able to do this manually. I often cannot capture the entire area. Therefore, I would like to have a button that can be used for the whole picture area is covered with the filter mask.
To be precise, I want to apply filter masks on a picture and then apply an additional filter globally to the whole picture.
Another example would be that you have specific shapes, such as rectangles, circles, or hearts (regrettable example), as it is already available with the crop tool. I would truly appreciate it if you could use such masks to create specific areas on which filter masks can be applied.

**Comment by T8RIN** [comment]
shapes already available in masks

**Comment by T8RIN** [comment]
Draw screen also has arrows on top of this 6 options

**Comment by devSJR** [comment]
True, I have seen the different Draw Path modes. However, I am not able to mark the whole picture as a mask with the filled square. There is always something left at the edges that I do not reach at the best of my ability when using the tool.

**Comment by T8RIN** [comment]
You can drag the painting out of the picture, it will not be cancelled and processed as expected 👀

**Comment by T8RIN** [comment]
![Screenshot_20240208-154924.png](https://github.com/T8RIN/ImageToolbox/assets/52178347/c4d4557a-8ef8-4488-8904-5ee7ced34e29)

**Comment by devSJR** [comment]
OK, I will try/practice that.  
Adding an option “Fill whole area” would not be something worth considering?
Anyways, consider this as closed please.

**Comment by T8RIN** [comment]
> Adding an option “Fill whole area” would not be something worth considering?

It will be confusing i think if you can draw and select qhole area at the same time
