### ISSUE TITLE
Filter option appears twice

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#759]
**Describe the bug**
Filter option appears twice when pressing edit on an image in the image preview, the 2nd option is for Mask filter, but it just says Filter with the same description

**To Reproduce**
1. Open image with Image Preview
2. Press on edit icon
3. See Filter option twice

**Expected behavior**
Seeing full filter option, and seeing mask filter option. Or maybe seeing filter just once and then selecting which to use

**Screenshots**
![Screenshot_20240208_201554_Image Toolbox](https://github.com/T8RIN/ImageToolbox/assets/87526638/e6224a85-88df-480b-80a3-d882b9f50b30)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A33
 - OS: OneUI 6.0

**Comment by T8RIN** [comment]
Thanks, i'll fix
