### ISSUE TITLE
Favorite tab

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#765]
It's really pleasant to see that the number of filters in imagetoolbox is growing and growing. As of now, 148 filters are available for the users, even with a useful search function.

Basically, finding a filter that's suitable for the task is not a problem. However, I recommend to consider an additional tab that allows the user to define a limited number of favorite filters.

However, implementing this appears not simple to me. One idea that I would have is to add another button besides the filter previews that is called Favorites, that adds the filter to a corresponding list.

**Comment by T8RIN** [comment]
Thanks for the idea, i'll add this :smile:
