### ISSUE TITLE
[Feature Request/Enhancement] Batch File Convert/Operation

### ISSUE THREAD

**Issue by Ero-gamer** [T8RIN/ImageToolbox#767]
Add batch file convert as independent/native tab with option to disable before/after previews while converting for low end devices and if possible the option to apply filters directly before converting files (Just like Photo Edit or app on Google play store. Package name: com.iudesk.android.photo.editor)

**Comment by T8RIN** [comment]
It's already available, just pick multiple files in corresponding options
