### ISSUE TITLE
Crop resize buggy

### ISSUE THREAD

**Issue by T8RIN** [T8RIN/ImageToolbox#768]

**Comment by photoalex** [comment]
Is this concerning the image allways loosing much more resolution than the amount you actually crop? Because thats what i would like to report.. also missing 4/5 aspect ratio.

**Comment by T8RIN** [comment]
Cropping tool currently uses screen dimensions as max image size, so it's true, but the issue is about crop resize mode in single edit

**Comment by T8RIN** [comment]
> Is this concerning the image allways loosing much more resolution than the amount you actually crop? Because thats what i would like to report.. also missing 4/5 aspect ratio.

I will add 4/5, thanks :)

**Comment by photoalex** [comment]
Neat.. is it difficult to implement? Cropping to full resolution that is.. 

I just tried out a simple app called LLCrop on fdroid.. there you can simply fill in whatever aspect ratio you want to lock to.. I think Ill be using that for my cropping needs for now as it does full resolution cropping. Thx in any case!

**Comment by T8RIN** [comment]
I ll look, thanks 👀
