### ISSUE TITLE
Missing Chinese (Traditional/Simplified) option after 2.6.0/2.6.0后缺失中文（繁体/简体）选项

### ISSUE THREAD

**Issue by RejectVanity** [T8RIN/ImageToolbox#775]
2.6.0 to 2.6.1alpha03 Missing Chinese (Traditional/Simplified) Option
Issue:
The Chinese (Traditional/Simplified) language option is missing in the following areas:
 * Language setting: The option is not available in the "Settings" menu under "Set Language."
 * OCR (Text Recognition): The option is not available under the "OCR" function.

（This issue was translated from Chinese to English using Google AI Gemini.）

2.6.0版本至2.6.1alpha03缺失中文（繁体/简体）选项。
1.在设置中的设置语言时没有“中文（繁体/简体）选项”；
2.在“OCR（文本识别）”功能中也没有“中文（繁体/简体）选项”。

**Comment by T8RIN** [comment]
Interesting, I'll look why this could happen, does this appear on lower versions?

**Comment by RejectVanity** [comment]
> Interesting, I'll look why this could happen, does this appear on lower versions?

The issue does not exist in 2.5.1. I think it started in 2.6.0 and may have been caused by the introduction of the "OCR" function.

**Comment by RejectVanity** [comment]
> Could you check alphas before 2.6.0 please? OCR didn't rely on that, there is some bug in locale retrieval

This problem already exists in 2.6.0-alpha01.

**Comment by T8RIN** [comment]
Okay, thanks for investigation

**Comment by RejectVanity** [comment]
> Okay, thanks for investigation

Thank you for your selfless dedication.
