### ISSUE TITLE
Batch resize-by-weight takes a very long time

### ISSUE THREAD

**Issue by pt8o** [T8RIN/ImageToolbox#778]
**Describe the bug**
I'm not sure if I'd call this a bug, just a strange behaviour.

I tried using the `resize by weight` a couple of times on a batch of 6 photos and it just hung on the loading spinner, and I thought it was frozen. But recently I tried it again and just let it run for as long as it needed to. It succeeded, but it took a very long time, like 2-3 minutes per photo. Other features of this app only take a few seconds to convert images so I don't think it's a hardware/CPU issue.

**To Reproduce**
- select `resize by weight`
- select 6 photos
- resize to a custom KB limit
- processing takes a very long time

**Expected behavior**
- I don't see why resize by weight should take longer than other forms of image resize/conversion?

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: CalyxOS (Android)

**Comment by T8RIN** [comment]
If you are using image formats like PNG BMP, who doesn't have compression quality params then you cannot get desired weight at all, and execution fails or takes a really long time

**Comment by T8RIN** [comment]
It can take a long time, because I'm trying to compress the image while it's size will be <= than given size

**Comment by pt8o** [comment]
The original files were JPG and they were not being converted, just saved as JPG again. However I was reducing the size by a lot (12MB -> 100KB), could that have caused this?

**Comment by T8RIN** [comment]
Yup it's intended for that size scaling

**Comment by T8RIN** [comment]
But maybe i can create a better algorithm

**Comment by T8RIN** [comment]
Okay, this should be much faster now :)
