### ISSUE TITLE
Allow breaking up the executable into 3 .APK's

### ISSUE THREAD

**Issue by uhyf3** [T8RIN/ImageToolbox#780]
For permission security, it would be an improvement to break up the output of making the executable into 3 .apk files: a screen capture utility, a picture downloader [maybe with online sharing features], and a main app that would share back & forth with the other .apk components, read files, edit files, save files, be the main interface, and, preferably, have included the optional content so that that would not have to be specially downloaded anymore.

**Comment by T8RIN** [comment]
I will not do this, sorry
If you want this, just take the code and create this type of apk👀
