### ISSUE TITLE
Regarding the issue of converting images to GIFs.

### ISSUE THREAD

**Issue by dragonjay-lyj** [T8RIN/ImageToolbox#782]
**Describe the bug**

When using the GIF tool to convert images to GIFs, there is a frame delay setting, with a range of 0 to 4000. However, no matter which value I input, the playback speed of the generated GIF remains the same.

**To Reproduce**

No matter which value I input, the playback speed of the generated GIF remains the same.

**Expected behavior**

If the frame delay is set to 1000, then the playback speed of this GIF is one image per second.

**Screenshots**

![5a2a06383c8254bf9417ec8dffcbcf2](https://github.com/T8RIN/ImageToolbox/assets/111476039/60f85930-4848-4de8-a1af-bca76dee989b)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Readmi K60 pro
 - OS:Android 14

**Comment by T8RIN** [comment]
Okay, this should be removed, because fps sets delay too
