### ISSUE TITLE
Phone restart needed

### ISSUE THREAD

**Issue by rons4** [T8RIN/ImageToolbox#784]
**Describe the bug**
The app does start fine once. When stopping it and starting it again it shows Oops .. IllegalStateException.
App data clearing or reinstall do not help. Only a phone restart helps.

**To Reproduce**
Stop the app and start it again.

**Expected behavior**
Be able to start the app without phone restart.

**Screenshots**
![Screenshot_20240217-165812](https://github.com/T8RIN/ImageToolbox/assets/43244104/0f2b07a6-c5fe-42e4-a229-665c0f68839a)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 14

**Comment by T8RIN** [comment]
Can you provide a full exception description?

**Comment by T8RIN** [comment]
Also app version

**Comment by rons4** [comment]
Unfortunately, I cannot get the exception text. The screen is flickering, seems the app restarts over and over again.

App version is 2.6.0 (116) from the Google Play Store. Same result with the F-Droid version.

https://github.com/T8RIN/ImageToolbox/assets/43244104/e8c43f57-3dde-43de-ab8e-d9bc7eae737e

On a Pixel 5 device and on a Samsung tablet all is fine.

Last but not least, thank you for the great app.

**Comment by rons4** [comment]
Now I was fast enough and got the exception test:


Device: Pixel 7 Pro (google - cheetah), SDK: 34 (14), App: 2.6.0 (116)java.lang.IllegalStateException: scroll observation scope does not existat a.l.run(SourceFile:2999)at android.os.Handler.handleCallback(Handler.java:959)at android.os.Handler.dispatchMessage(Handler.java:100)at android.os.Looper.loopOnce(Looper.java:232)at android.os.Looper.loop(Looper.java:317)at android.app.ActivityThread.main(ActivityThread.java:8516)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by T8RIN** [comment]
Thanks! This seems to be a compose library issue (again, many such issues was before)

I'll look at what i can do to prevent this, or if i cannot solve this we can wait until next Thursday, there will be a new alpha release, and this might be fixed

**Comment by T8RIN** [comment]
https://github.com/google/accompanist/issues/1752

**Comment by T8RIN** [comment]
![image](https://github.com/T8RIN/ImageToolbox/assets/52178347/584233e3-9b1f-4e6b-b34e-30b023a3b4e6)
 ahhhhhhhhhhh, google 💢

**Comment by T8RIN** [comment]
https://issuetracker.google.com/issues/325667060

**Comment by rons4** [comment]
Oh no. No rush for me, but I hope Google will be able to fix the issue quickly. Thanks a lot.

**Comment by nightfury05** [comment]
pixel 6a user here exact same issue

**Comment by T8RIN** [comment]
I noticed, that it happens only on google devices, at least for now there are no crashes on other devices, but on my pixel 8 there is no issue, weird

**Comment by nightfury05** [comment]
it happens only on google devices


yeah probably google messed up somthing again

**Comment by T8RIN** [comment]
> it happens only on google devices
> 
> 
> yeah probably google messed up somthing again
> 
> 

:smile:

**Comment by T8RIN** [comment]
![image](https://github.com/T8RIN/ImageToolbox/assets/52178347/4d1f0af8-6542-4a36-bbf9-7115d412dbb8)

**Comment by T8RIN** [comment]
They fixed this :) https://issuetracker.google.com/issues/322402917

**Comment by T8RIN** [comment]
check latest beta, this should be fixed

**Comment by rons4** [comment]
Yes, I can confirm, this seems to be fixed. Thanks a lot.
