### ISSUE TITLE
Incorrect Toast When Using Replace File

### ISSUE THREAD

**Issue by locuturus** [T8RIN/ImageToolbox#788]
**Describe the bug**
When replacing a file the newly modified file overwrites the original. However, the toast says 'saved to Documents/ResizedImages folder' instead of wherever it really is saved.

**To Reproduce**
Set the filename option to replace the source file. Then edit and replace some file not already in /Documents/ResizedImages. In case it matters, I was using the resize and convert tool.

**Expected behavior**
I expect the toast to accurately reflect the actual save directory.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xperia 1 V 
 - OS: Android 14

**Comment by T8RIN** [comment]
It cannot reflect the directory, but should say that it's saved to its original destination, I'll look, thanks :)

**Comment by T8RIN** [comment]
Tested right now, it's working for me, could you record a video for it please?

**Comment by locuturus** [comment]
I confirm the update changed the toast. If you're curious I attached a video showing what the previous version did.

Oh, and I suspect you can get the actual path in many circumstances. Action getcontent returns a URI you can parse if it's coming from com.android.externalstorage. But if it's coming from some other provider, like mediastore, then maybe not. Unless you can read the data column with the media permissions?

I don't know, I'm spitballing. What you chose to do is probably the best option.

https://github.com/T8RIN/ImageToolbox/assets/19397973/6427beaf-58de-4e61-8a0d-7a91392df0a3

**Comment by T8RIN** [comment]
I've tried it before, but it has not worked at all, i m using mediastore btw
