### ISSUE TITLE
File Extension Is Not Updated

### ISSUE THREAD

**Issue by locuturus** [T8RIN/ImageToolbox#789]
**Describe the bug**
When using both Settings > Filename > Overwrite; and Resize and Convert, and when also converting to a different format (webp lossless in this case) the new file copies the original filename (good) but also the extension (bad). So for example the new webp image will have a jpg or png extension.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xperia 1 V 
 - OS: Android 14

**Comment by T8RIN** [comment]
As I remember, I just can't change the file extension while using overwrite, it's impossible without some permissions which are using file managers
