### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by crashlyrics** [T8RIN/ImageToolbox#81]
Sorry, but German translation of "Resize by weight" (Größenänderung nach Gewichtung") doesn't make much sense. Of course, it's not colloquial in German to speak of the "weight" of a file in terms of size. So the related term "Gewichtung" is a bit misleading, as it's more linked to "evaluation", "ranking" than to the sought meaning. Obviously, as a repetition of the word "size" should be avoided, you could use "Volumen" ("volume", "amount"). So the whole item would be: "Größenänderung nach Volumen".

Otherwise, nice app (also nice UI). Thank you!

**Comment by T8RIN** [comment]
You can easily change translations on weblate, can you do it please?
