### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by mizu-048** [T8RIN/ImageToolbox#811]
**Is your feature request related to a problem? Please describe.**
Right you can only copy an image to the clipboard if you have clipboard-only or auto pin enabled.
In clipboard only you can't save images to the device
and in Auto pin you need to the save image to your device to copy it to clipboard

**Describe the solution you'd like**

Add a button next to save to copy the edited image to just the clipboard

**Describe alternatives you've considered**

none

**Comment by T8RIN** [comment]
Why is this needed?

**Comment by mizu-048** [comment]
quick edit and send, instead of having every small edit like circling some element from a  screenshot be saved to the gallery

**Comment by T8RIN** [comment]
Then why the share button didn't fit your needs?

**Comment by mizu-048** [comment]
copy to clipboard has its own ease of use, i would personally rather use the save to gallery then the share

**Comment by T8RIN** [comment]
Okay, i will add dialogue on the share button to share or copy into a clipboard, If the second is not available on the device just share then

**Comment by mizu-048** [comment]
thank you very much.
