### ISSUE TITLE
Hope to add the function of importing pictures from the clipboard

### ISSUE THREAD

**Issue by tch123** [T8RIN/ImageToolbox#812]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When adding pictures, in addition to using the file selector, I would like to add a function to import clipboard pictures.
In this way, you can copy a picture when browsing in other applications, and then import it directly from the clipboard when you return to ImageToolbox. The operation will be more convenient.

**Describe alternatives you've considered**

**Comment by T8RIN** [comment]
added
