### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by jont4** [T8RIN/ImageToolbox#817]
Device: Lenovo L78032 (Lenovo - heart), SDK: 33 (13), App: 2.6.1-alpha01 (118)

`java.lang.IllegalArgumentException: Callable expects 2 arguments, but 1 were provided.at ca.h.r0(SourceFile:42)at xa.j.c(SourceFile:13)at wa.s.b(SourceFile:439)at ru.tech.imageresizershrinker.core.filters.presentation.model.UiFilter.a(SourceFile:94)at mh.b.n(SourceFile:135)at d2.k0.a(SourceFile:20)at d2.k0.d(SourceFile:8)at o.d0.n(SourceFile:275)at t.c3.z(SourceFile:134)at ea.a.k(SourceFile:1)at rc.c.n1(SourceFile:1)at gd.g.q(SourceFile:100)at gd.g.F(SourceFile:33)at gd.g.k(SourceFile:17)at y1.p0.C0(SourceFile:51)at y1.p0.m0(SourceFile:1)at s.k.m0(SourceFile:117)at y1.i.f(SourceFile:157)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.e.b(SourceFile:30)at y1.y.a(SourceFile:122)at e2.a0.G(SourceFile:79)at e2.a0.m(SourceFile:214)at e2.a0.dispatchTouchEvent(SourceFile:76)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)at android.app.Activity.dispatchTouchEvent(Activity.java:4299)at g.f0.dispatchTouchEvent(SourceFile:3)at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)at android.view.View.dispatchPointerEvent(View.java:15309)at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778)at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329)at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)at android.os.MessageQueue.nativePollOnce(Native Method)at android.os.MessageQueue.next(MessageQueue.java:335)at android.os.Looper.loopOnce(Looper.java:161)at android.os.Looper.loop(Looper.java:288)at android.app.ActivityThread.main(ActivityThread.java:7924)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)Suppressed: ld.f: [e2.k2@654061, v0.h@c02786, p1{Cancelling}@57fd847, h1@93ee874]`

**Comment by T8RIN** [comment]
Which filter did you use?

**Comment by jont4** [comment]
Light -> Brightness

I updated to last beta, beta02-foss, and now it crashed when I just select a filter tab, like Simple effect, Light, Color and so on.

**Comment by T8RIN** [comment]
It might be so, yes, here is the answer https://t.me/t8rin_imagetoolbox/1992/4927

**Comment by T8RIN** [comment]
Is problem solved?

**Comment by jont4** [comment]
yeah, solved
