### ISSUE TITLE
Bigger hitbox on cropping

### ISSUE THREAD

**Issue by candroid-man** [T8RIN/ImageToolbox#829]
![ResizedImage_2024-02-28_14-40-36_2361.png](https://github.com/T8RIN/ImageToolbox/assets/51019003/3dfd2be6-baf4-4960-bfcc-6fd5b9e84ed3)

Trying to crop an image is really difficult and a little frustrating at times because it is really hard to touch the corners of the cropping box. I end up accidentally moving the entire box instead of resizing it. I think this would be fixed by a larger "hitbox" on the corners and edges.

Love the app so far, keep it up!

**Comment by T8RIN** [comment]
Thanks! I'm using this lib, so i can't easily increase it https://github.com/SmartToolFactory/Compose-Cropper/tree/master

**Comment by candroid-man** [comment]
Is there a better lib to use for this? It appears this repo hasn't had a release in nearly a year and issues aren't being responded to

**Comment by T8RIN** [comment]
No :(

**Comment by JackDropHammer** [comment]
@T8RIN Try searching "Android image cropper" on github or just pick up this lib instead https://github.com/CanHub/Android-Image-Cropper , although this one seems to be having issues with Android 13 lately.

**Comment by T8RIN** [comment]
This lib is worse than current in my opinon, i wanted to add separte crop with roatation for different lib, but didn't find any, so i will try to modify current one

**Comment by JackDropHammer** [comment]
@T8RINr8 I see, thank you for continuing to develop this awesome app

**Comment by T8RIN** [comment]
https://github.com/T8RIN/ImageToolboxLibs/commit/279f8a3f99b308fce91b6ef490a27f244804ee5e added
