### ISSUE TITLE
Re adding the preview of modified pictures

### ISSUE THREAD

**Issue by MarkovType** [T8RIN/ImageToolbox#840]
**Is your feature request related to a problem? Please describe.**

I recently upgraded to 2.6.0. I'm not a fan of the new UI placements, which I find less intuitive than before.

However my problem isn't here. Before, when I wanted to rescale a photo, I could see live what the modified photo would look like, as a preview.
It doesn't seem to work anymore.
Also it looks like the button to enable "Ratio keeping" for rescaling a picture isn't even there anymore.

**The solution?**

Enable again live preview of modified pictures.

**Comment by T8RIN** [comment]
Live preview is here, isn't it? Could you check on the latest pre release please?

**Comment by T8RIN** [comment]
Ratio keeping is flexible resize
