### ISSUE TITLE
Some colors don't display

### ISSUE THREAD

**Issue by remaker17** [T8RIN/ImageToolbox#847]
**Describe the bug**
Some surface colors aren't displayed when creating a Material you color scheme (**Surface Bright,** **Surface Dim**, maybe others).

**To Reproduce**
Create color scheme

**Expected behavior**
These specified colors must be displayed on the screen as all colors.

**Screenshots**
![Screenshot_20240304-181634.jpg](https://github.com/T8RIN/ImageToolbox/assets/95296093/475b6371-4919-4b7f-b3d8-7dff9ae91b50)

**Smartphone (please complete the following information):**
 - Device: TECNO SPARK 8C
 - OS: Android 11

**Comment by T8RIN** [comment]
Why do you need them?👀 material theme builder does not provide event surface-* colors, this will be included in the output scheme anyway

**Comment by remaker17** [comment]
> Why do you need them?👀 material theme builder does not provide event surface-* colors, this will be included in the output scheme anyway

I need to generate several color schemes for my project. Do I need to export the colors every time and look at these colors from there?

**Comment by T8RIN** [comment]
added
