### ISSUE TITLE
Rotation of Individual Images in PDF

### ISSUE THREAD

**Issue by GhoulBoii** [T8RIN/ImageToolbox#850]
**Is your feature request related to a problem? Please describe.**
I would like to rotate my images as some of images come rotated. 

**Describe the solution you'd like**
A feature on the images to pdf page where I can individually rotate each image.

**Describe alternatives you've considered**
Manually rotating each image in my photos app but this is too time consuming and annoying.

**Comment by T8RIN** [comment]
After some investigations i can say that for now there is only a way just rotating needed pictures manually
