### ISSUE TITLE
PDF compression

### ISSUE THREAD

**Issue by GhoulBoii** [T8RIN/ImageToolbox#852]
**Is your feature request related to a problem? Please describe.**
The size of pdf's come to around 100MB size when I am only attaching 5-6 images. 

**Describe the solution you'd like**
A compression option would be appreciated to compress the size of the pdf's to a lesser size.

**Describe alternatives you've considered**
Using an external compressor but it would be better if an in-built feature is provided in the app.

**Comment by T8RIN** [comment]
added as preset option
