### ISSUE TITLE
App running out of memory

### ISSUE THREAD

**Issue by JackDropHammer** [T8RIN/ImageToolbox#863]
**Describe the bug**
First, when you try to stitch too many images and/or multiple images that are big in file size, the app would run out of memory while trying to generate a preview. Secondly, it would take a lot of time to generate a preview.

**To Reproduce**
The same as above

**Expected behavior**
For the first one, there are various ways to implement it;

  1) Put a memory cap on the app based on current available memory, though, it should also measure the current available memory constantly (while processing images) so that it can handle it even if user starts a new activity. If the available memory is not enough to generate a preview, you should put an error stating "couldn't generate preview because of low memory" instead of just letting the app crash.

  2) I would like an option to generate the stitched image even if the preview has not been generated, this would atleast serve as a "hacky" solution in case the generation of preview takes too long/no preview gets generated. Also add an option to turn off previews to avoid the problem of program running out of memory *while* generating the end product.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: Redmi note 10 pro max
 - OS: Android 10, Miui 12.5.10

Log from the app: [Bug] App Crash: OutOfMemoryError

Device: M2101K6I (Redmi - sweetin), SDK: 30 (11), App: 2.7.0 (124)

java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1122)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
	at ei.d.A(SourceFile:497)
	at ei.c.y(SourceFile:16)
	at da.a.j(SourceFile:1)
	at fd.z1.w(SourceFile:54)
	at fd.a.j(SourceFile:23)
	at da.a.j(SourceFile:1)
	at kd.r.w(SourceFile:1)
	at fd.a.j(SourceFile:23)
	at da.a.j(SourceFile:1)
	at fd.g0.run(SourceFile:1)
	at l.j.run(SourceFile:14)
	at ld.j.run(SourceFile:1)
	at ld.a.run(SourceFile:96)
	Suppressed: kd.f: [q1{Cancelling}@644a3cd, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
That's jvm restriction, i can't create too large images by design

**Comment by T8RIN** [comment]
Preview disabling sounds like a possible improvement

**Comment by JackDropHammer** [comment]
> That's jvm restriction, i can't create too large images by design

Does that imply that an image simply can't be generated or that a preview cannot be generated?

**Comment by T8RIN** [comment]
Added, also ability to skip initial picking
