### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by tidyboythfc** [T8RIN/ImageToolbox#873]
Device: SM-S908B (samsung - b0s), SDK: 34 (14), App: 2.7.0 (124)java.lang.IllegalArgumentException: Can't represent a width of 962880 and height of 472 in Constraintsat ne.k.B(SourceFile:109)at i2.g.g(SourceFile:1)at w.p.b(SourceFile:213)at d2.d0.a(SourceFile:38)at d2.p0.b(SourceFile:32)at d2.p0.e(SourceFile:587)at g8.za.c(SourceFile:60)at f1.v.a(SourceFile:52)at f1.w.c(SourceFile:153)at d2.u1.a(SourceFile:1)at d2.n0.t0(SourceFile:112)at d2.n0.a(SourceFile:91)at w.w.e(SourceFile:114)at d2.x.a(SourceFile:49)at w.s1.b(SourceFile:33)at d2.d0.a(SourceFile:38)at w.s1.b(SourceFile:33)at d2.d0.a(SourceFile:38)at o1.u0.b(SourceFile:1)at d2.d0.a(SourceFile:38)at o1.n.b(SourceFile:1)at d2.d0.a(SourceFile:38)at d2.p0.b(SourceFile:32)at d2.p0.e(SourceFile:587)at g8.za.c(SourceFile:60)at f1.v.a(SourceFile:52)at f1.w.c(SourceFile:153)at d2.u1.a(SourceFile:1)at d2.n0.t0(SourceFile:112)at d2.n0.a(SourceFile:91)at w.w.e(SourceFile:114)at d2.x.a(SourceFile:49)at d2.p0.b(SourceFile:32)at d2.p0.e(SourceFile:587)at g8.za.c(SourceFile:60)at f1.v.a(SourceFile:52)at f1.w.c(SourceFile:153)at d2.u1.a(SourceFile:1)at d2.n0.t0(SourceFile:112)at d2.n0.a(SourceFile:91)at w.w.e(SourceFile:114)at d2.x.a(SourceFile:49)at d2.p0.b(SourceFile:32)at d2.p0.e(SourceFile:587)at g8.za.c(SourceFile:60)at f1.v.a(SourceFile:52)at f1.w.c(SourceFile:153)at d2.u1.a(SourceFile:1)at d2.n0.t0(SourceFile:112)at d2.n0.a(SourceFile:91)at q.a.c(SourceFile:1)at q.a0.e(SourceFile:27)at d2.x.a(SourceFile:49)at q.b1.b(SourceFile:222)at d2.d0.a(SourceFile:38)at o1.u0.b(SourceFile:1)at d2.d0.a(SourceFile:38)at q.i.h(SourceFile:126)at q.i.k(SourceFile:1281)at b2.e0.b(SourceFile:8)at d2.d0.a(SourceFile:38)at d2.p0.b(SourceFile:32)at d2.p0.e(SourceFile:587)at g8.za.c(SourceFile:60)at f1.v.a(SourceFile:52)at f1.w.c(SourceFile:153)at d2.u1.a(SourceFile:1)at d2.n0.t0(SourceFile:112)at d2.n0.a(SourceFile:91)at q.r.e(SourceFile:40)at d2.x.a(SourceFile:49)at q.x.b(SourceFile:1)at d2.d.b(SourceFile:1)at d2.d0.a(SourceFile:38)at w.m0.b(SourceFile:99)at d2.d0.a(SourceFile:38)at d2.p0.b(SourceFile:32)at d2.p0.e(SourceFile:587)at g8.za.c(SourceFile:60)at f1.v.a(SourceFile:52)at f1.w.c(SourceFile:153)at d2.u1.a(SourceFile:1)at d2.n0.t0(SourceFile:112)at androidx.compose.ui.node.a.K(SourceFile:17)at androidx.compose.ui.node.a.L(SourceFile:18)at d2.w0.c(SourceFile:8)at d2.w0.k(SourceFile:124)at d2.w0.h(SourceFile:78)at e2.a0.v(SourceFile:34)at d2.q1.a(SourceFile:4)at e2.a0.dispatchDraw(SourceFile:14)at android.view.View.draw(View.java:25151)at android.view.View.updateDisplayListIfDirty(View.java:24007)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)at android.view.View.updateDisplayListIfDirty(View.java:23953)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)at android.view.View.updateDisplayListIfDirty(View.java:23953)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)at android.view.View.updateDisplayListIfDirty(View.java:23953)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)at android.view.View.updateDisplayListIfDirty(View.java:23953)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)at android.view.View.updateDisplayListIfDirty(View.java:23953)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)at android.view.View.updateDisplayListIfDirty(View.java:23953)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:764)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:770)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:868)at android.view.ViewRootImpl.draw(ViewRootImpl.java:5945)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5614)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4734)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3239)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11197)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)at android.view.Choreographer.doCallbacks(Choreographer.java:1129)at android.view.Choreographer.doFrame(Choreographer.java:1055)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)at android.os.Handler.handleCallback(Handler.java:958)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:230)at android.os.Looper.loop(Looper.java:319)at android.app.ActivityThread.main(ActivityThread.java:8893)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

Kept crashing (roughly 4 or 5 times) when I loaded and tried to change image size. This isn't the first time. It's happened everytime I've tried in previous attempts but i kept trying and eventually after 7 attempts it did converted 1 out of 3 different sessions

**Comment by T8RIN** [comment]
Fixed in alpha02 👀
