### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by Krishna-G-OP** [T8RIN/ImageToolbox#874]
Hey,

I am a web developer, I'd be happy to contribute to your project and its continued development. I've reviewed the project  and believe my skills in web development could be valuable. I see that the project currently don't have a website, I think i can contribute to the process of web development as I'm interested in exploring contribution opportunities.

Please let me know how I can best get involved based on the project's current needs.

**Comment by T8RIN** [comment]
Hi! Do you want to create a landing page or a working web site?

**Comment by Krishna-G-OP** [comment]
I can create a static site of the project

**Comment by T8RIN** [comment]
Okay, that would be great, i can create repo, and then you can contribute to it, thus website can be hosted on GitHub pages

**Comment by Krishna-G-OP** [comment]
Sure

**Comment by Krishna-G-OP** [comment]
Invite me as contributor

**Comment by T8RIN** [comment]
sure

**Comment by Krishna-G-OP** [comment]
I have accepted

**Comment by Krishna-G-OP** [comment]
Now I am going to start the development

**Comment by T8RIN** [comment]
Good 👀
