### ISSUE TITLE
Auto updates disable themselves on restart (foss)

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#875]
**Describe the bug**
Auto updates disable themselves on restart with the foss version. I guess this is for fdroid, but theres also people who arent using that, so maybe the fix should be a info panel popping up to say it shouldnt be enabled if you are using a store to update it with

**To Reproduce**
1. Enable "Check for updates" 
2. Restart the app
3. The option turns itself off

**Expected behavior**
Keep itself on

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsuck A33 5G
 - OS: OneUI 6.0 (Android 14)

**Comment by T8RIN** [comment]
interesting, this should be disabled only for fist launch on foss version, thanks, i will take a look
