### ISSUE TITLE
"Image Toolbox pasted from your clipboard" on app start

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#879]
**Describe the bug**
Image Toolbox checks clipboard for some reason on app start

**To Reproduce**
1. Turn on setting to be notified of apps using your clipboard
2. Start Image Toolbox
3. Get your clipboard inspected

**Expected behavior**
No unnecessary clipboard inspection

**Screenshots**

https://github.com/T8RIN/ImageToolbox/assets/87526638/8faa6f0c-94c2-49d1-8f78-5e53df717116

**Smartphone (please complete the following information):**
 - Device: Samsuck A33 5G
 - OS: OneUI 6.0 (Android 14)

**Comment by kremzli** [comment]
Maybe have it off by default? That kind of notification raises suspicion (im not accusing) when people dont know about it

**Comment by T8RIN** [comment]
This was requested from user, but i can disable it by default
