### ISSUE TITLE
Collages

### ISSUE THREAD

**Issue by GhoulBoii** [T8RIN/ImageToolbox#881]
**Is your feature request related to a problem? Please describe.**
There is no good open source collage solution and having one integrated to this app would be appreciated.

**Describe the solution you'd like**
A collage feature to be added which allows for multiple pictures to be stitched together with different borders and orientations.

**Describe alternatives you've considered**
I have tried using image stitching but that is only good for one continuous image and not collages with different image placements and orientations.

**Comment by T8RIN** [comment]
I also thought about this, but delayed this feature in cause of not obvious implementation
