### ISSUE TITLE
Image stich for shared images to the app

### ISSUE THREAD

**Issue by Devaprasad-reddy** [T8RIN/ImageToolbox#886]
**when I share a screenshot to this app it doesn't show me the image stich button.**

**the image stich button should show up when any image is shared so that I can add the 2nd image later in the app**

**I've to open image tool box app and then select the tool and select the images to stich which is a long process, especially when you are stiching a lot of images everyday**

**Comment by T8RIN** [comment]
Okay

**Comment by Devaprasad-reddy** [comment]
Wow super fast...

**Comment by T8RIN** [comment]
😄 👀

**Comment by Devaprasad-reddy** [comment]
Is it possible for you to make this system-wide
Like this
Example: I can directly choose anki image occlusion from the global share
menu
Is it possible to make image stich icon appear here...?

**Comment by T8RIN** [comment]
I think it's possible, but tricky and may have boilerplate

**Comment by Devaprasad-reddy** [comment]
Haha, thanks!
