### ISSUE TITLE
Imagemagick integration 

### ISSUE THREAD

**Issue by JackDropHammer** [T8RIN/ImageToolbox#888]
**Is your feature request related to a problem? Please describe.**
I would love the ability to convert an image between different formats and things like #880 would also be possible and much much more.

**Describe the solution you'd like**
If possible, implement imagemagick in your project. Imagemagick is an open-source tool for Linux, windows, mac, etc but there are no official executables for handheld devices but can be used on Android through the command line emulator called "termux", I cannot use termux because of certain technical issues on MY specific device but that's unrelated to this thread. 

Imagemagick:- https://imagemagick.org/

Links/Libraries related to that:- 
 • https://github.com/paulasiimwe/Android-ImageMagick
 • https://github.com/lilac/Android-ImageMagick
 • https://github.com/puelocesar/android-lib-magick
 • https://stackoverflow.com/questions/9460764/android-image-magick

**Describe alternatives you've considered**
There's also an unmaintained library; https://github.com/MolotovCherry/Android-ImageMagick7 which I don't think you'd consider using because it's not maintained anymore. 

Alternatively, you can implement your own solution.

**Comment by T8RIN** [comment]
Okay, i will look if this is possible but now there are also many formats you can convert between

**Comment by JackDropHammer** [comment]
> Okay, i will look if this is possible but now there are also many formats you can convert between

I think that #881 might be looking for montage feature on image magick https://imagemagick.org/script/montage.php

**Comment by T8RIN** [comment]
It's for collages like Instagram, stitching is already available in the app 👀

**Comment by T8RIN** [comment]
https://github.com/puelocesar/android-lib-magick 
looks interesting

**Comment by T8RIN** [comment]
i wanted to use this one https://github.com/paulasiimwe/Android-ImageMagick
but any built .so native package of image magick weights around 5mb, idk is it costs the revenue of small amount of filters

**Comment by T8RIN** [comment]
Power of image magick not achievable using this jni wrappers, also it costs MB, and gives a very small amount of new features
