### ISSUE TITLE
Remove objects from the photo 

### ISSUE THREAD

**Issue by Uranusek** [T8RIN/ImageToolbox#889]
**Is your feature request related to a problem? Please describe.**
No, it would just be nice to have this feature. 

**Describe the solution you'd like**
Select elements in a photo, for example birds, and then remove them. 

**Describe alternatives you've considered**
Using other apps, but I don't think there is any open source app that has this feature.

**Comment by T8RIN** [comment]
If you have such an open source library, tag me, for now it's impossible 👀
