### ISSUE TITLE
[Bug] App Crash: Exception

### ISSUE THREAD

**Issue by srVJT0** [T8RIN/ImageToolbox#890]
Device: Redmi 8 (Xiaomi - olive), SDK: 29 (10), App: 2.7.1-alpha03 (127)java.lang.Exception: Currently support encoding only RGBA_8888, RGBA_F16, RGBA_1010102, RBR_565 images pixel formatat com.awxkee.aire.pipeline.ScalePipelinesImpl.scaleImpl(Native Method)at com.awxkee.aire.pipeline.ScalePipelinesImpl.a(SourceFile:18)at com.awxkee.aire.Aire.scale(SourceFile:18)at U6.v.y(SourceFile:128)at U6.v.n(SourceFile:13)at U5.c.V0(SourceFile:16)at U5.c.k1(SourceFile:74)at U6.A.c(SourceFile:18)at U6.y.y(SourceFile:116)at H4.a.l(SourceFile:9)at k6.H.run(SourceFile:97)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)at java.lang.Thread.run(Thread.java:919)Suppressed: p6.g: [s0{Cancelling}@b3312e5, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
fixed
