### ISSUE TITLE
AVIF 100% quality looks worse than 99%

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#891]
**Describe the bug**
AVIF 100% quality looks worse than 99%, technically it cant even do "100%" quality. AVIF is quite not good at lossless

**To Reproduce**
1. Convert an image to 100% quality AVIF
2. Convert an image to 99% quality AVIF
3. Compare

**Expected behavior**
AVIF 100% to look better than 99%. You could remove 100% option because that would mean lossless and it isnt

**Screenshots**
Here are 2 AVIF images converted to PNG because github forgot to update their file picker supported extentions

99% quality (217KB):
![IMG_2024-03-17_20-48-10_7515](https://github.com/T8RIN/ImageToolbox/assets/87526638/03caa920-899e-4d66-b0c8-c2a79401af8a)

100% quality (45KB):
![IMG_2024-03-17_20-47-53_1090](https://github.com/T8RIN/ImageToolbox/assets/87526638/0a1d6223-c8ec-4ce5-9783-2e8132c1bfb5)

This is a simple example to show that its bad even on simple stuff, its worse in more complex images. Also look at the size differences (not the PNG's)

**Smartphone (please complete the following information):**
 - Device: Samsuck A33 5G
 - OS: OneUI 6.0 (Android 14)

**Comment by T8RIN** [comment]
Hm, i think this question is better to ask here -> https://github.com/awxkee/avif-coder

**Comment by kremzli** [comment]
https://github.com/awxkee/avif-coder/issues/18

**Comment by kremzli** [comment]
Fixed in https://github.com/awxkee/avif-coder/releases/tag/1.7.2

**Comment by T8RIN** [comment]
Thanks! I will update and add this decoding variants
