### ISSUE TITLE
jxl problems

### ISSUE THREAD

**Issue by JackDropHammer** [T8RIN/ImageToolbox#893]
**Describe the bug**
So, it seems like the jxl decoder is brokern, not the encoder but the *decoder*. If you convert an image to jxl (lossy/lossless) it comes out correct(*checked by using a browser*) but the preview is simply incorrect (horrible quality with tons of artifact). 
If you try viewing the image in the app the same problem occurs. Comparison here; 
[![Screenshot-2024-03-18-21-08-24-090-ru-tech-imageresizershrinker-1.jpg](https://i.postimg.cc/Yq5VppPb/Screenshot-2024-03-18-21-08-24-090-ru-tech-imageresizershrinker-1.jpg)](https://postimg.cc/1fKMBZsq)
(full size image:- https://postimg.cc/1fKMBZsq)

It doesn't end there because if you convert from jxl to any other format, the image will look the same as in preview. So the image will become horrible.

This same problem seems to present in avif. (full size image :- https://postimg.cc/5jzsHR0Z)
[![Screenshot-2024-03-18-21-20-08-568-ru-tech-imageresizershrinker-1.jpg](https://i.postimg.cc/kM1zHrdX/Screenshot-2024-03-18-21-20-08-568-ru-tech-imageresizershrinker-1.jpg)](https://postimg.cc/5jzsHR0Z)

EDIT:- I haven't tested any of this in programs like imagemagick(sorry)
**To Reproduce**
Same as above

**Expected behavior**
Normal images, same as they entered 

**Screenshots**
Given above

**Smartphone (please complete the following information):**
 - Device: Redmi note 10 pro max
 - OS: Android 10 (miui 12.5)
 - EDIT 2 :- Device doesn't have hardware acceleration for avif and jxl

**Comment by kremzli** [comment]
Can reproduce with jxl on version 2.7.1-beta01-foss(128). Images are encoded properly but decoding shows wrong colors, the quality is the same

Cannot reproduce with avif

What version are you on?

**Comment by T8RIN** [comment]
Maybe it's fixed in jxl coder 2.1.6

**Comment by kremzli** [comment]
i think this is the fix https://github.com/awxkee/jxl-coder/releases/tag/2.1.8

**Comment by T8RIN** [comment]
Maybe, btw i updated to this version now

**Comment by kremzli** [comment]
my first comment is still happening

**Comment by T8RIN** [comment]
Anyways that's not handled by me

**Comment by kremzli** [comment]
Cannot reproduce outside of ImageToolbox https://github.com/awxkee/jxl-coder/issues/16

**Comment by jonnyawsom3** [comment]
May be fixed now by b1d18ba

**Comment by T8RIN** [comment]
Check out the latest build, it should be solved

**Comment by JackDropHammer** [comment]
> Check out the latest build, it should be solved

Does indeed seems to be fixed, thank you very much!

**Comment by OkyDooky** [comment]
I don't quite have the color issue, but the preview in "compare" (on the right siide of the slider) shows what looks like a noticeably lower resolution version with tons of aliasing. I just started using the app, so I can't compare it to before previous fixes to this issue to see if it's the same. I don't want to necro if it's not necessary.
