### ISSUE TITLE
Does not increase to specified dimensions

### ISSUE THREAD

**Issue by edmxn** [T8RIN/ImageToolbox#897]
**Describe the bug**

I want to increase the dimensions of a vertical image to 4500x**** _width_, but the app ends up giving me 4500 _height_

**To Reproduce**

Process an vertical image with the width box at 4500 and the height box either empty or with 4500 as well. And with the "flexible" option.

**Expected behavior**

Should give me a 4500x**** image

**Screenshots**

![Screenshot_20240319_120433_Gallery](https://github.com/T8RIN/ImageToolbox/assets/101371218/ab95c84a-1d15-4eb3-ad3c-9a8a0a85a87a)

**Smartphone (please complete the following information):**
 - Device: Samsung S10+
 - OS: Android 12

**Comment by T8RIN** [comment]
i've added anchor param for flexible resize to select which size will be max for the box
