### ISSUE TITLE
Dont re-encode heic to heif

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#898]
**Is your feature request related to a problem? Please describe.**
Heif is the container, heic is the image format, effectively .heic is heif

**Describe the solution you'd like**
When someone switches them, just apply the file extention change when saving / sharing. No need to re-encode. This would do a couple time and battery savings, efficiency is epic

**Describe alternatives you've considered**
Using jpeg xl

**Comment by T8RIN** [comment]
This is impossible using current implementation

**Comment by T8RIN** [comment]
Nope, only if i use convertion between files
