### ISSUE TITLE
Request for Enhancing Cropping Usability

### ISSUE THREAD

**Issue by nanikore115** [T8RIN/ImageToolbox#912]
I am a loyal user of this app, but I have just one complaint: the cropping operation is difficult to use. Therefore, I would like to request improvements to make cropping more user-friendly.

Request:

1. Set the initial position of the cropping window to match the original size of the image. Currently, the initial position of the cropping window is slightly enlarged from the original image, so it needs to be adjusted.

2. Fix the image by preventing it from moving unintentionally. When the image moves, it becomes difficult to specify the cropping position accurately.

3. Limit the cropping window to the image boundaries to prevent it from extending beyond the image area. When the cropping window is extended beyond the image boundaries, the image automatically enlarges based on the cropping window, causing the cropping position to shift.

If I were to provide an example, something like LLCrop would be ideal.

Also, I'm aware that the existing cropping feature relies on external libraries. Therefore, I would like to request the addition of a new feature focused solely on pure cropping. How about something like "Quick Crop"? The name is up to you. I would like the new feature to prioritize ease of use, leaving aspects like aspect ratio and crop mask changes to the existing cropping tool. I understand that this request may seem ambitious, but I genuinely appreciate your consideration.

**Comment by T8RIN** [comment]
I think this could be acieved using this lib 
https://github.com/Yalantis/uCrop
it also have native llcrop, but only for png and jpg

i will add this as second option in crop

**Comment by T8RIN** [comment]
this implemented somewhat, now cropper much more useable
