### ISSUE TITLE
incorrect border

### ISSUE THREAD

**Issue by sineptic** [T8RIN/ImageToolbox#917]
**Describe the bug**
border does not match ui element. (vertically flipped)

**To Reproduce**
install 2.7.0 app version
enable 0.1 border size

**Expected behavior**
...

**Screenshots**
![Screenshot_20240324_133511_Image Toolbox.jpg](https://github.com/T8RIN/ImageToolbox/assets/98404983/bbab3add-b575-454a-bdf7-098eb3637a2b)

**Smartphone (please complete the following information):**
 - Device: Samsung a32
 - OS: android 13

**Comment by T8RIN** [comment]
Fixed :)
