### ISSUE TITLE
Filter is not applied all time.

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#918]
I have made a strange observation. For some images, actually most of those I take with my camera, Image Toolbox does not apply filters in the preview but in the saved images. Here's a comparison between an image taken by the camera and one image directly taken from the website.
On the left you see the image from the home page and on the right there's a photograph of the home page image. Below you see the application of the live preview filters that work for the stored image from the home page but not from the photo taken by the camera.

![Homepages ](https://i.imgur.com/mGe5NIA.jpeg)

![Photo by camera](https://i.imgur.com/wb2xUNX.jpeg)

![Comparison ](https://i.imgur.com/cLh8Qll.jpeg)

**Comment by T8RIN** [comment]
fixed
