### ISSUE TITLE
XYB Jpegli

### ISSUE THREAD

**Issue by kremzli** [T8RIN/ImageToolbox#920]
**Is your feature request related to a problem? Please describe.**
XYB is a color space that aims to include just the colors we can see, very good for compression and fidelity at the same time. I tested it yesterday (with cjpegli --xyb) and it shaved off another 4% without any quality loss (other than a little bit you wont ever notice without pixel peeping)

**Describe the solution you'd like**
Add on option to convert to the XYB color space with the Jpegli encoder
Also making Jpegli the default for jpeg would probably be another good idea

**Describe alternatives you've considered**
Obviously sometimes you want to keep the same color space (or it messes up), so it should only be an option that is off by default

**Comment by T8RIN** [comment]
As I am just using the aire library for this, i think this request is more related to that library👀

**Comment by kremzli** [comment]
Jpegli is from jxl-coder though? Shouldnt i request there if it isnt already a feature?

**Comment by T8RIN** [comment]
It's from aire 👀

**Comment by kremzli** [comment]
Well that closed cuz of android skill issue and how the color conversion works so you can close this too if you want, maybe re-open if that feature is eventually added

**Comment by T8RIN** [comment]
Okay!
