### ISSUE TITLE
[Bug] App Crash: Exception

### ISSUE THREAD

**Issue by jonnyawsom3** [T8RIN/ImageToolbox#927]
Device: BLA-L09 (HUAWEI - HWBLA), SDK: 29 (10), App: 2.7.1-beta02 (129)java.lang.Exception: Currently support encoding only RGBA_8888, RGBA_F16, RGBA_1010102, RBR_565 images pixel formatat com.awxkee.aire.pipeline.ScalePipelinesImpl.scaleImpl(Native Method)at com.awxkee.aire.pipeline.ScalePipelinesImpl.a(SourceFile:18)at com.awxkee.aire.Aire.scale(SourceFile:18)at h9.v.y(SourceFile:134)at h9.v.o(SourceFile:13)at K3.w.n0(SourceFile:5)at K3.w.r0(SourceFile:74)at h9.C.c(SourceFile:18)at h9.A.y(SourceFile:116)at h9.A.o(SourceFile:13)at K3.w.n0(SourceFile:5)at K3.w.r0(SourceFile:74)at h9.C.b(SourceFile:18)at K3.J2.D(SourceFile:22)at h9.B.y(SourceFile:89)at Q6.a.n(SourceFile:9)at s8.I.run(SourceFile:97)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)at java.lang.Thread.run(Thread.java:929)Suppressed: x8.g: [t0{Cancelling}@7b8d5a6, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
try latest actions build, i suppose this to be fixed

**Comment by jonnyawsom3** [comment]
No crash, but it displays as a broken image icon and then crashes when changing conversion type. Selecting the 'telegram' preset at 512x512 did load the image, but still crashed when changing conversion type

**Comment by jonnyawsom3** [comment]
[Bug] App Crash: Exception

Device: BLA-L09 (HUAWEI - HWBLA), SDK: 29 (10), App: 2.7.1-beta03 (130)

java.lang.Exception: Currently support encoding only RGBA_8888, RGBA_F16, RGBA_1010102, RBR_565 images pixel format
	at com.awxkee.aire.pipeline.BasePipelinesImpl.toJPEGImpl(Native Method)
	at com.awxkee.aire.pipeline.BasePipelinesImpl.k(SourceFile:1)
	at com.awxkee.aire.Aire.mozjpeg(Unknown Source:7)
	at i9.l.a(SourceFile:12)
	at h9.d.y(SourceFile:227)
	at h9.d.n(SourceFile:13)
	at K3.z.c0(SourceFile:5)
	at K3.z.g0(SourceFile:74)
	at h9.e.y(SourceFile:292)
	at Q6.a.p(SourceFile:9)
	at s8.I.run(SourceFile:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
	Suppressed: x8.g: [t0{Cancelling}@6f11585, Dispatchers.Main.immediate]

**Comment by jonnyawsom3** [comment]
The Embedded Picker also fails to load any images if that helps diagnose

**Comment by T8RIN** [comment]
try new :0

**Comment by T8RIN** [comment]
i pushed some extra commits

**Comment by jonnyawsom3** [comment]
Ah, you made another commit. I'll try once actions are done

**Comment by T8RIN** [comment]
Also i will send debuggable apk now, could you check on it?
At least i will see references to place where it happens

**Comment by T8RIN** [comment]
https://drive.google.com/file/d/1CTGIRoguOvPc3Ajd6tOiv9Lho1Z81Vhl/view?usp=sharing

**Comment by jonnyawsom3** [comment]
Sure. I can also contact on Telegram if it helps. This is the first time a developer responds so quickly that Github's delay actually gets in the way

**Comment by T8RIN** [comment]
You can, that's would be helpful :)

**Comment by jonnyawsom3** [comment]
No longer crashes thanks to the commits
