### ISSUE TITLE
 Background remover as mask for filter

### ISSUE THREAD

**Issue by devSJR** [T8RIN/ImageToolbox#930]
I was wondering if it is possible to use the background remover (play store version) to automatically define a mask  in particular of a person for the masked filter tool. I guess this issue was already raised somewhere but I couldn't find it. If this was the case, sorry for that.

**Comment by T8RIN** [comment]
i think no, beacuse i need paths to do that, background remover gives only bitmap, so i can't extract a path from it

**Comment by devSJR** [comment]
OK. Thanks anyway.
