### ISSUE TITLE
Free rotation crop

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#936]
I'm not sure what exactly is it called. But in my stock gallery i can choose a aspect ratio and use the slider to rotate image and crop it for respective aspect ratio.
![Screenshot_2024-03-31-12-51-07-761_com miui mediaeditor](https://github.com/T8RIN/ImageToolbox/assets/99175083/dc40cbfd-6604-4030-b7ec-eaeaa9ccc3a9)

**Comment by NikunjKhangwal** [comment]
I know there's a similar issue but i don't think it also works with aspect ratio

**Comment by Virtualffg** [comment]
This should absolutely be added along with an option to go out of bounds, and choosing what to fill the empty parts of the picture with, transparency or a color, maybe sometime later an image, that would be perfect, especially when changing perspective and you don't care about a full image or want to make some sort of sticker

**Comment by T8RIN** [comment]
It's possible with the crop resize mode, but not rotation
