### ISSUE TITLE
Perspective functionality

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#937]
This is what I'm talking about:
![Screenshot_2024-03-31-09-35-32-301_com miui mediaeditor](https://github.com/T8RIN/ImageToolbox/assets/99175083/ae213dc0-8467-46ef-8022-6937d23047f2)

I think the image provides enough information

**Comment by T8RIN** [comment]
This Was requested a long time ago, but this is hard to add right now

**Comment by NikunjKhangwal** [comment]
That's fine. Should i keep the issue opened?

**Comment by T8RIN** [comment]
Yes, maybe i will add someday👀

**Comment by devSJR** [comment]
@NikunjKhangwal in the meantime https://github.com/danopdev/Perspective might help.

**Comment by NikunjKhangwal** [comment]
@devSJR My gallery has the feature as shown in screenshot. It was just a suggestion. But anyways thanks for the mention.

**Comment by T8RIN** [comment]
Added this

**Comment by T8RIN** [comment]
I will also provide parameter to not stick for image boundaries, so it'll be as shown in picture  
(Added as a crop option only now)

**Comment by T8RIN** [comment]
![Screenshot_20240926-051408.png](https://github.com/user-attachments/assets/761a9386-cf27-4f58-957c-20dca7eeb12f)

**Comment by NikunjKhangwal** [comment]
Awesome. Thank you
