### ISSUE TITLE
Mosaic filters

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#940]
Add mosaic functionality. This could be added in blur filters or just filters, that's up to you to decide.

![Screenshot_2024-03-31-16-40-03-376_com miui mediaeditor](https://github.com/T8RIN/ImageToolbox/assets/99175083/7319ee57-b206-41ef-a068-ffb76778d4e7)

**Comment by NikunjKhangwal** [comment]
Pixelation exists already, my bad. Maybe the triangle shape could be added?

**Comment by T8RIN** [comment]
I don't know such library now, but i will research

**Comment by T8RIN** [comment]
I added low poly filter now, kinda looks similar or better
