### ISSUE TITLE
Slider dissappears

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#942]
**Describe the bug**
Sometimes the slider to compare before and after changes just disappear when I'm switching between filters.

**To Reproduce**
Switching between filters

**Expected behavior**
The slider shouldn't disappear

**Screenshots**
As you can a filter is applied but slider isn't showing up:-
![IMG_20240331_180223](https://github.com/T8RIN/ImageToolbox/assets/99175083/586869c2-a17d-4dc0-b947-6f83280a5302)

**Smartphone (please complete the following information):**
 - Device: Redmi 9
 - OS: Android 12

**Comment by T8RIN** [comment]
it's just on left or right side, but progress clearing on sheet clouse could be helpful

**Comment by T8RIN** [comment]
should be normal now

**Comment by NikunjKhangwal** [comment]
Yup, that was it. I think the behavior should be changed the slider should reset to default in new filter
