### ISSUE TITLE
Magnifier in Draw options

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#947]
Make it so we can quickly turn magnifier on/off from here instead of going to settings. I like to have it on for drawn lines but not for shapes
![IMG_20240402_120129](https://github.com/T8RIN/ImageToolbox/assets/99175083/dfbeb43a-4c21-4f3a-97d7-eca101a3f53a)

**Comment by T8RIN** [comment]
Okay

**Comment by T8RIN** [comment]
added

**Comment by NikunjKhangwal** [comment]
Damn! That was quick. 🚀
