### ISSUE TITLE
Noise generator

### ISSUE THREAD

**Issue by nexus226** [T8RIN/ImageToolbox#948]
Add a mode where the user is capable of generating an image with random noise. Something like this: https://robson.plus/white-noise-image-generator

**Comment by T8RIN** [comment]
Pass black image to noise filter

**Comment by T8RIN** [comment]
https://t.me/t8rin_imagetoolbox/1/4934

**Comment by nexus226** [comment]
Thank you. Found out I can also use luminance treshold to make it 1-bit. It would still be more convenient to add some options to adjust the noise color mode (color, B&W or mono) and cell size.

**Comment by T8RIN** [comment]
Not sure about cell size, but another could be added maybe
