### ISSUE TITLE
Spot Healing Tool

### ISSUE THREAD

**Issue by GhoulBoii** [T8RIN/ImageToolbox#950]
**Is your feature request related to a problem? Please describe.**
I want a feature to "heal" a specific area with this app. Right now, i have to use snapseed for this feature.

**Describe the solution you'd like**
A healing/spot healing feature be added which removes any unwanted blemishes or spots in the background or the face. It is basically like a brush tool but it can hide blemishes when painted over it. Many editors have it like google's snapseed on android or [adobe photoshop](https://www.adobe.com/sg/products/photoshop/spot-heal.html).

**Describe alternatives you've considered**
Using the snapseed app but it is proprietary and would rather have all my image needs done in this one app.

**Comment by T8RIN** [comment]
I think this gonna be added soon :)

**Comment by maninthemiddle01** [comment]
Thank you very much for the implementation. Unfortunately if I want to heal something I only get a half transparent red area where i want things to be "healed". Am I doing something wrong?

**Comment by T8RIN** [comment]
That's a bug, if you tap on the image again it will appear, this issue is fixed in the latest betas

**Comment by maninthemiddle01** [comment]
True, than you very much :)
