### ISSUE TITLE
Undo & Redo buttons

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#952]
Let say I'm editing an image in single edit mode. I've performed a bunch of operations one by one and saved. But if i changed my mind and want to revert the recent change i can't do it and have to completely reset the image and all operations. In that case a undo and redo button will be helpful

**Comment by T8RIN** [comment]
It's not possible to undo redo, but you can reset the image to the original, this button is at the screen bottom

**Comment by NikunjKhangwal** [comment]
Yup, i mentioned the reset button. Is it not possible to implement undo & redo?

**Comment by T8RIN** [comment]
I think no, it's just overcomplicated to do this, and the only thing that's possible, is size, rotation, preset format and image scale mode undo-redo, filters cannot be saved as action that can be performed again

**Comment by T8RIN** [comment]
At least in my implementation 🐸

**Comment by T8RIN** [comment]
But redo the other params sounds like a possible feature

**Comment by NikunjKhangwal** [comment]
Well then try to implement it for things other than filters. Something is better than nothing ig

**Comment by T8RIN** [comment]
Okay, after some attempts its seems to be not possible for current implementation
