### ISSUE TITLE
Directly jump to filter list in single edit mode

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#953]
Make the user directy choose a filter from filters list
![Screenshot_2024-04-03-20-37-28-850_ru tech imageresizershrinker](https://github.com/T8RIN/ImageToolbox/assets/99175083/449d46ef-f2a3-4035-81b3-a23c701d6cab)

Instead of this window. You can't do anything here and it's just a extra step. Make it appear when user actually choosed a filter.
![Screenshot_2024-04-03-20-37-26-891_ru tech imageresizershrinker](https://github.com/T8RIN/ImageToolbox/assets/99175083/cefcb832-8ceb-4265-8c9f-836d93567577)

**Comment by T8RIN** [comment]
Btw thx for so many ideas, i appreciate it

**Comment by NikunjKhangwal** [comment]
No problem. These changes are making mine (and other users) experience with app better as well.
