### ISSUE TITLE
Magnifier in color picker

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#954]
Enable Magnifier for color picker as well. It'll be helpful when you're trying to move cursor to a very small area of specific color or pixel. Also if you do add it to the swipe up menu like #947

**Comment by T8RIN** [comment]
added

**Comment by NikunjKhangwal** [comment]
Hello! I noticed magnifier doesn't appear in swipe menu from color picker. So you need to go back to settings to turn it on/off. Can you add it in menu like draw options?

**Comment by T8RIN** [comment]
It's added, tap on the zoom button at the top app bar

**Comment by NikunjKhangwal** [comment]
Ah! You're right. My bad
