### ISSUE TITLE
Bitwise overlay modes in image watermarking

### ISSUE THREAD

**Issue by nexus226** [T8RIN/ImageToolbox#963]
Bitwise blending, also called binary blending by Krita, basically blends 2 values together by applying a binary bitwise operation to each pixel in the two images. More info at https://docs.krita.org/en/reference_manual/blending_modes/binary.html

**Comment by T8RIN** [comment]
Okay, seems to be possible from Android 10

**Comment by nexus226** [comment]
In the new updates, bitwise overlays are still not available. Why is so?

**Comment by T8RIN** [comment]
Because there are no more overlay modes in android
