### ISSUE TITLE
PDF to Image converting tool generates images without original filename

### ISSUE THREAD

**Issue by CloneWith** [T8RIN/ImageToolbox#973]
**Describe the bug**
I set the `Filename` preferences as follows:

- Prefix: empty
- Suffix: empty
- Add original filename: True
- Replace sequence number: True

And I didn't see original filename in the images.

**To Reproduce**
1. Use `PDF Tools` -> `PDF to Images` tool
2. Open a random file (`test.pdf`)
3. Set to output JPG images
4. Names of images: `1.jpg`

**Expected behavior**
Should generate images with the source file name as a part of filename, like `test_1.jpg`

**Smartphone**
 - Device: Redmi Note 12T Pro
 - OS: MIUI 14.0.10 @ Android 13
 - Version: 2.7.0-foss(124)

**Comment by T8RIN** [comment]
It's intended behavior

**Comment by T8RIN** [comment]
Maybe it should be helpful to add this but idk

**Comment by CloneWith** [comment]
It is, especially when we have the need to convert multiple PDF files continuously.
I tried this earlier and now I have files marked by numbers `(n)`, which is hard to point out from which file they were converted.
btw is it possible to select multiple PDFs at one time (in the future)?

**Comment by T8RIN** [comment]
> btw is it possible to select multiple PDFs at one time (in the future)?

Maybe, but there will be no preview then

**Comment by T8RIN** [comment]
Oringinal name should be added now
