### ISSUE TITLE
Loseless Compression

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#989]
There's this open source [app](https://github.com/YangDai2003/ImageCraft-Android) that can compress images losslessly doesn't matter which format. Is it possible to import this feature in ImageToolbox?

**Comment by NikunjKhangwal** [comment]
As a side note it also has rotation crop mentioned in #936

**Comment by T8RIN** [comment]
This app is just clone of mine👀

**Comment by T8RIN** [comment]
I looked through the code, there's no lossless compression, because it is recording image first, however my app does the same

**Comment by T8RIN** [comment]
Lol, it's not even compress, it's just converting to webp

**Comment by T8RIN** [comment]
Also it have rotation crop because of using uCrop library, i tried it and get some bad results, but this is planned to add anyway

**Comment by NikunjKhangwal** [comment]
It doesn't convert all images to webp but some of them in my experience, i thought it was a bug.
Anyway learned something today.
