### ISSUE TITLE
[Feature request] Resizing with fitting width and height

### ISSUE THREAD

**Issue by nthtimes** [T8RIN/ImageToolbox#99]
I suggest that let users specify a range instead of a fixed size for resizing by WidthLimit or HeightLimit depending on the image aspect ratio.

if the image width or height is greater than the limit, and...
-  the image aspect ratio >= WidthLimit/HeightLimit
  then resize by WidthLimit.
-  the image aspect ratio <= WidthLimit/HeightLimit
  then resize by HeighthLimit.

For example WidthLimit=800, HeightLimit=800
- image1: 4000x3000 -> 800x600
- image2: 3000x4000 -> 600x800
- image3: 400x300 -> do nothing
- image4: 300x400 -> do nothing

**Comment by T8RIN** [comment]
Great idea, will implement this in the future

**Comment by T8RIN** [comment]
started doing this

**Comment by T8RIN** [comment]
added :)
