### ISSUE TITLE
AMOLED mode not totally black since v 2.8

### ISSUE THREAD

**Issue by Richard38907** [T8RIN/ImageToolbox#991]
**Describe the bug**
Try to enable dark AMOLED mode
The background is darker but not totally black (like before)

**To Reproduce**

**Expected behavior**

**Screenshots**
V2.7:

![Screenshot_20240424-174009_Image Toolbox.png](https://github.com/T8RIN/ImageToolbox/assets/148692265/df2ddc3e-7351-450d-ad92-8510e972e032)

V2.8:

![Screenshot_20240424-173714_Image Toolbox.png](https://github.com/T8RIN/ImageToolbox/assets/148692265/6d8ec197-ccad-4b5c-a3ae-4336248d824d)

**Smartphone (please complete the following information):**
 - Device: 
 - OS:

**Comment by T8RIN** [comment]
Thanks! Suppose to be fixed
