### ISSUE TITLE
Why does the app uses internet

### ISSUE THREAD

**Issue by Gamer750** [T8RIN/ImageToolbox#996]
Can you make it fully offline

**Comment by NikunjKhangwal** [comment]
Loading image from internet and downloading OCR data

**Comment by Gamer750** [comment]
> Loading image from internet and downloading OCR data

Is it impo. It would be good if  the app is offline

**Comment by T8RIN** [comment]
> > Loading image from internet and downloading OCR data
> 
> Is it important. It would be good if  the app is offline

Turn off internet if you don't need that features 👀
