### ISSUE TITLE
android.permission.ACCESS_MEDIA_LOCATION

### ISSUE THREAD

**Issue by IzzySoft** [T8RIN/ImageToolbox#997]
My scanner today just reported your app having added `android.permission.ACCESS_MEDIA_LOCATION`. I assume the Exif editor functionality includes location edit (or display), am I correct?

While searching for that in the description of your Readme I noticed there's no link to your app in my repo, though you wanted to keep your app here (stated in #3). Maybe you want to add a badge for that, too?

Thanks in advance!

**Comment by T8RIN** [comment]
Yes, that's for exif👀

**Comment by IzzySoft** [comment]
Thanks, thought so – just wanted to make sure before writing that:

![image](https://github.com/T8RIN/ImageToolbox/assets/6781438/1928f047-d2b6-4707-a84c-d7cca3247cb0)

**Comment by T8RIN** [comment]
Thanks!

**Comment by IzzySoft** [comment]
Umpf, now also `CAMERA` is requested. Intended, or an "accident"?

**Comment by T8RIN** [comment]
Nope, it's needed for new document scanner and qr code scanner features

**Comment by IzzySoft** [comment]
Wow, that was fast! Thanks! Will add it to the green list then.
