### ISSUE TITLE
Severe Performance Decrease Upgrading From 2.70 - 2.80

### ISSUE THREAD

**Issue by lowerclasswarfare** [T8RIN/ImageToolbox#998]
**Describe the bug**
When opening the app there is a noticeable lag when using the menus or tools. Trying to crop an image is basically unusable as the screen updates are extremely slow.

EDIT: After playing with the settings a bit I turned off drawing shadows beneath containers and got a noticeable performance increase.

**To Reproduce**
Literally just upgraded the app and used it.

**Expected behavior**
Smooth operation and fast editing in 2.70
Menus and screen does not lag.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: LG V30 model LG-H931
 - OS: Android 9

Let me know what I can do to help figure out what is happening. I know I'm running an older phone but the last version worked flawlessly.

**Comment by NikunjKhangwal** [comment]
Also when you search something in settings and press back button to clear out, it lags a bit. This doesn't happen in others apps.

**Comment by T8RIN** [comment]
Okay, maybe shadows could be changed a bit

**Comment by NikunjKhangwal** [comment]
Is it actually happing because of shadows tho? Shadows existed in previous stable version as well but app was working fine. Did the new version changed something regarding visuals?

**Comment by T8RIN** [comment]
Yes, some shadows drawing on render script now instead of soft layer, that was a mistake

**Comment by NikunjKhangwal** [comment]
I see. I think a quick fix release is needed. Lag and crashes are two major problem in new release.

**Comment by T8RIN** [comment]
Will be today i hope

**Comment by T8RIN** [comment]
How it's going on alpha 2.8.2 ?

**Comment by nexus226** [comment]
> How it's going on alpha 2.8.2 ?

I can say I'm having the same issue. When the preview loads on any of the modes, scrolling lags horribly. Shadows are disabled. Latest version.

**Comment by T8RIN** [comment]
that's compose related thing i think, maybe that's will be better in alpha 02

**Comment by nexus226** [comment]
It still isn't fixed but something weird I noticed is that the app doesn't lag when turned to the horizontal orientation

**Comment by T8RIN** [comment]
Because there are less objects in the lazy list, compose issue
