### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by Menorah** [T8RIN/ImageToolbox#999]
When I try to modify the position of two filters on an image, the app closes.

**Log:**

`Device: ZTE 8046 (ZTE - P616F01), SDK: 31 (12), App: 2.8.0 (134)java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.833397E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)at androidx.compose.ui.graphics.a.F(SourceFile:3)at androidx.compose.ui.graphics.a.b(SourceFile:484)at s0.u.c(SourceFile:17)at u0.c.a(SourceFile:18)at u0.c.L(SourceFile:44)at J0.J.L(SourceFile:16)at u0.g.j(SourceFile:60)at u.r.a(SourceFile:582)at u.r.n(SourceFile:54)at p0.e.a(SourceFile:3)at J0.J.b(SourceFile:50)at J0.h0.I0(SourceFile:55)at J0.h0.G0(SourceFile:30)at J0.D.Y0(SourceFile:6)at J0.h0.I0(SourceFile:9)at J0.h0.G0(SourceFile:30)at androidx.compose.ui.node.a.i(SourceFile:5)at J0.y.Y0(SourceFile:28)at J0.h0.I0(SourceFile:9)at J0.h0.G0(SourceFile:30)at J0.D.Y0(SourceFile:6)at J0.h0.I0(SourceFile:9)at J0.h0.G0(SourceFile:30)at androidx.compose.ui.node.a.i(SourceFile:5)at J0.y.Y0(SourceFile:28)at J0.h0.I0(SourceFile:9)at J0.h0.G0(SourceFile:30)at androidx.compose.ui.node.a.i(SourceFile:5)at J0.y.Y0(SourceFile:28)at J0.h0.I0(SourceFile:9)at J0.h0.G0(SourceFile:30)at J0.D.Y0(SourceFile:6)at J0.h0.I0(SourceFile:9)at J0.h0.G0(SourceFile:30)at androidx.compose.ui.node.a.i(SourceFile:5)at J0.y.Y0(SourceFile:28)at J0.h0.I0(SourceFile:9)at u.Y.b(SourceFile:257)at u.Y.d(SourceFile:166)at Z.n.n(SourceFile:114)at j0.w.a(SourceFile:52)at j0.x.c(SourceFile:140)at J0.u0.a(SourceFile:3)at Z.K0.n(SourceFile:395)at K0.X0.B(SourceFile:22)at K0.Z0.i(SourceFile:40)at K0.Z0.b(SourceFile:14)at J0.h0.G0(SourceFile:5)at androidx.compose.ui.node.a.i(SourceFile:5)at J0.y.Y0(SourceFile:28)at J0.h0.I0(SourceFile:9)at J0.h0.G0(SourceFile:30)at androidx.compose.ui.node.a.i(SourceFile:5)at K0.z.dispatchDraw(SourceFile:69)at android.view.View.draw(View.java:22863)at android.view.View.updateDisplayListIfDirty(View.java:21714)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4601)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4574)at android.view.View.updateDisplayListIfDirty(View.java:21663)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4601)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4574)at android.view.View.updateDisplayListIfDirty(View.java:21663)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4642)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4370)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3500)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2249)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8930)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1038)at android.view.Choreographer.doCallbacks(Choreographer.java:846)at android.view.Choreographer.doFrame(Choreographer.java:781)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1023)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:235)at android.os.Looper.loop(Looper.java:349)at android.app.ActivityThread.main(ActivityThread.java:8422)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by T8RIN** [comment]
Oh, definitely Library bug, i think i can just lower it, for normal stable version

**Comment by T8RIN** [comment]
https://issuetracker.google.com/issues/336815323 fixed in next lib release, for now i'll rollback to use it normally
